# CZSO shortlist – head() + základní charakteristiky

Notebook používá `czso_shortlist_profiles.py`, `pyczso.py` a `pyczso_lkod_bridge.py`.
Pro každý dataset ze shortlistu zobrazí:

- `head()`
- počet řádků a sloupců
- detekované časové sloupce
- roky obsažené v datasetu
- frekvenci a časový rozsah z katalogu
- základní projektová metadata (priorita, skupina, územní úroveň)

In [3]:
from pathlib import Path
import pandas as pd

from czso_shortlist_profiles import display_shortlist_profiles

# Uprav si jen tuto část podle své lokální složky
BASE_DIR = Path.cwd()
CATALOG_XLSX = BASE_DIR / 'czso_katalog_trideny.xlsx'
OUTPUT_DIR = BASE_DIR / 'czso_dataset_profiles'

HEAD_ROWS = 5
MAX_DATASETS = None   # např. 10 pro rychlý test, None = celý shortlist
PRIORITY = None       # např. ['A'] nebo ['A', 'B']; None = vše
PAUSE_SECONDS = 0.0
FORCE_REDOWNLOAD = False

print('Base dir:', BASE_DIR)
print('Catalog :', CATALOG_XLSX)
print('Output  :', OUTPUT_DIR)

Base dir: C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_preview
Catalog : C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_preview\czso_katalog_trideny.xlsx
Output  : C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_preview\czso_dataset_profiles

In [4]:
profiles_df = display_shortlist_profiles(
    catalog_xlsx=CATALOG_XLSX,
    output_dir=OUTPUT_DIR,
    head_rows=HEAD_ROWS,
    max_datasets=MAX_DATASETS,
    priority=PRIORITY,
    pause_seconds=PAUSE_SECONDS,
    force_redownload=FORCE_REDOWNLOAD,
)

print('Hotovo. Výstupní manifest:', OUTPUT_DIR / 'dataset_profiles_manifest.csv')
print('Markdown report       :', OUTPUT_DIR / 'dataset_profiles_report.md')
print('CSV head previews     :', OUTPUT_DIR / 'heads_csv')

## 001. [A] Dokončené byty v obcích

                                                             hodnota
dataset_id                                                    200068
dataset_title                                Dokončené byty v obcích
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title           {'cs': 'Data do roku 2024 - revidovaná data'}
selected_file                          OD_STA01_2025090509313708.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     509671
column_count                                                      13
time_columns                   stapro_kod, rok, casref_od, casref_do
years_min                                                       1997
years_max                                                       2024
years_count                                                       28
years_sample       1997, 1998, 1999, 2000, 2001, 2002 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             1997-01-01
end_catalog                                               2024-12-31
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                      bytová výstavba a stavebnictví
uzemni_uroven                                                   obec
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/b8162c4b-9666-e...
preview_csv         heads_csv\001_200068_Dokoncene_byty_v_obcich.csv
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,tb_cis,tb_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,stapro_txt,tb_txt,vuzemi_txt
0,765513729,0,3103,NaN,NaN,43,539783,2001,2001-01-01,2001-12-31,Počet dokončených bytů,NaN,Oplot
1,765499689,0,3103,NaN,NaN,43,532479,2001,2001-01-01,2001-12-31,Počet dokončených bytů,NaN,Kmetiněves
2,765532709,0,3103,NaN,NaN,43,551821,2001,2001-01-01,2001-12-31,Počet dokončených bytů,NaN,Tvrdkov
3,765543549,0,3103,NaN,NaN,43,559806,2001,2001-01-01,2001-12-31,Počet dokončených bytů,NaN,Hlohovice
4,765571469,8,3103,NaN,NaN,43,574911,2001,2001-01-01,2001-12-31,Počet dokončených bytů,NaN,Dolní Roveň

## 002. [A] Obyvatelstvo a domy v obcích podle výsledků sčítání od roku

                                                             hodnota
dataset_id                                                 170240-17
dataset_title      Obyvatelstvo a domy v obcích podle výsledků sč...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo a domy v obcích podle výs...
selected_file                                      OD_SLDB_HD_at.csv
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     175081
column_count                                                      15
time_columns                                  stapro_kod, rok, datum
years_min                                                       1869
years_max                                                       2011
years_count                                                       14
years_sample       1869, 1880, 1890, 1900, 1910, 1921 ... 1961, 1...
years_source                                            data_columns
frequency_catalog                       desetileté / census [R/P10Y]
start_catalog                                                   None
end_catalog                                               2011-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina         základní lokální přehled obyvatel a bydlení
uzemni_uroven                                                   obec
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107516/9378b376-1a8c-a...
preview_csv        heads_csv\002_170240-17_Obyvatelstvo_a_domy_v_...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,"﻿""idhod""",hodnota,stapro_kod,stapro_txt,rok,datum,vuzemi_cis,vuzemi_kod,vuzemi_txt,so_orp,so_orp_text,okres,okres_text,kraj,kraj_text
0,808433980,1148,2406,Počet obyvatel s trvalým nebo dlouhodobým pobytem,2011,2011-03-26,43,594881,Šatov,6220,Znojmo,40762,Znojmo,3115,Jihomoravský kraj
1,808433981,659,2406,Počet obyvatel s trvalým nebo dlouhodobým pobytem,2011,2011-03-26,43,594890,Štítary,6220,Znojmo,40762,Znojmo,3115,Jihomoravský kraj
2,808433982,621,2406,Počet obyvatel s trvalým nebo dlouhodobým pobytem,2011,2011-03-26,43,594911,Šumná,6220,Znojmo,40762,Znojmo,3115,Jihomoravský kraj
3,808433983,1340,2406,Počet obyvatel s trvalým nebo dlouhodobým pobytem,2011,2011-03-26,43,594920,Tasovice,6220,Znojmo,40762,Znojmo,3115,Jihomoravský kraj
4,808433985,533,2406,Počet obyvatel s trvalým nebo dlouhodobým pobytem,2011,2011-03-26,43,594946,Těšetice,6220,Znojmo,40762,Znojmo,3115,Jihomoravský kraj

## 003. [A] Obyvatelstvo v základních sídelních jednotkách podle výsledků sčítání

                                                             hodnota
dataset_id                                                 170241-17
dataset_title      Obyvatelstvo v základních sídelních jednotkách...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo v základních sídelních je...
selected_file                                        OD_SLD_ZSJD.csv
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                      21743
column_count                                                       9
time_columns                                       stapro_kod, datum
years_min                                                       2011
years_max                                                       2011
years_count                                                        1
years_sample                                                    2011
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2011-03-26
end_catalog                                               2011-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                             základní populační stav
uzemni_uroven                       podobecní úroveň (část obce/ZSJ)
zdroj_typ                             SLDB 2011 / historické sčítání
page               https://csu.gov.cz/docs/107516/5de62523-0188-3...
preview_csv        heads_csv\003_170241-17_Obyvatelstvo_v_zakladn...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,stapro_txt,datum,zsjd_kod,zsjd_txt,obec_kod,obec_txt
0,759033373,1157,3162,PoДҚet obyvatel s obvyklГҪm pobytem,2011-03-26,190,Abertamy,554979,Abertamy (okres Karlovy Vary)
1,759033374,56,3162,PoДҚet obyvatel s obvyklГҪm pobytem,2011-03-26,270,HЕҷebeДҚnГЎ,554979,Abertamy (okres Karlovy Vary)
2,759033376,1746,3162,PoДҚet obyvatel s obvyklГҪm pobytem,2011-03-26,430,Adamov-stЕҷed,581291,Adamov (okres Blansko)
3,759053743,6,3162,PoДҚet obyvatel s obvyklГҪm pobytem,2011-03-26,3130090,K ГҡtДӣchovu,581291,Adamov (okres Blansko)
4,759053741,317,3162,PoДҚet obyvatel s obvyklГҪm pobytem,2011-03-26,3129830,Kolonie,581291,Adamov (okres Blansko)

## 004. [A] Sčítání 2021 - Počet obyvatel a počet obydlených bytů za části obce, části obce - díl, ZSJ, ZDJ - díl,

                                                             hodnota
dataset_id                                 sldb2021_obyv_byt_cob_zsj
dataset_title      Sčítání 2021 - Počet obyvatel a počet obydlený...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Počet obyvatel a počet obydlených bytů...
selected_file                       ds_sldb2021_obyv_byt_cob_zsj.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     156388
column_count                                                      10
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina         základní lokální přehled obyvatel a bydlení
uzemni_uroven                       podobecní úroveň (část obce/ZSJ)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\004_sldb2021_obyv_byt_cob_zsj_Scitan...
error                                                           None

,idhod,hodnota,ukaz_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,uzemi_txt,uzemi_typ
0,1000356176,355,2607,42,19,2021,2021-03-26,Počet bytů,Abertamy,část obce
1,1000372657,21,2607,42,27,2021,2021-03-26,Počet bytů,Hřebečná,část obce
2,1000344922,349,2607,42,35,2021,2021-03-26,Počet bytů,Adamov,část obce
3,1000374146,63,2607,42,51,2021,2021-03-26,Počet bytů,Dolní Adršpach,část obce
4,1000316913,140,2607,42,60,2021,2021-03-26,Počet bytů,Horní Adršpach,část obce

## 005. [A] Počty ekonomických subjektů podle odvětví převažující činnosti za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části

                                                             hodnota
dataset_id                                                 140133q25
dataset_title      Počty ekonomických subjektů podle odvětví přev...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                           {'cs': 'Čtvrtletí roku 2025'}
selected_file                         OD_ORG02q_2025041409194587.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     179313
column_count                                                      13
time_columns                                      stapro_kod, casref
years_min                                                       2025
years_max                                                       2025
years_count                                                        1
years_sample                                                    2025
years_source                                            data_columns
frequency_catalog                                 čtvrtletní [R/P3M]
start_catalog                                             2025-01-01
end_catalog                                               2025-03-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                                   obec
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/a4b3e19f-9153-f...
preview_csv        heads_csv\005_140133q25_Pocty_ekonomickych_sub...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,odvetvi_cis,odvetvi_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,odvetvi_txt,vuzemi_txt
0,1437671882,62,4958,NaN,NaN,NaN,NaN,43,539783,2025-03-31,NaN,NaN,Oplot
1,1437821660,75,4958,NaN,NaN,NaN,NaN,43,532479,2025-03-31,NaN,NaN,Kmetiněves
2,1437817745,51,4958,NaN,NaN,NaN,NaN,43,551821,2025-03-31,NaN,NaN,Tvrdkov
3,1438033018,80,4958,NaN,NaN,NaN,NaN,43,559806,2025-03-31,NaN,NaN,Hlohovice
4,1437579150,449,4958,NaN,NaN,NaN,NaN,43,574911,2025-03-31,NaN,NaN,Dolní Roveň

## 006. [A] Počty ekonomických subjektů podle vybraných právních forem za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části

                                                             hodnota
dataset_id                                                 140131q25
dataset_title      Počty ekonomických subjektů podle vybraných pr...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                           {'cs': 'Čtvrtletí roku 2025'}
selected_file                         OD_ORG01q_2025041409242722.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                      93649
column_count                                                      13
time_columns                                      stapro_kod, casref
years_min                                                       2025
years_max                                                       2025
years_count                                                        1
years_sample                                                    2025
years_source                                            data_columns
frequency_catalog                                 čtvrtletní [R/P3M]
start_catalog                                             2025-01-01
end_catalog                                               2025-03-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                                   obec
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/e9e70029-f638-b...
preview_csv        heads_csv\006_140131q25_Pocty_ekonomickych_sub...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,forma_cis,forma_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,forma_txt,vuzemi_txt
0,1437671882,62,4958,NaN,NaN,NaN,NaN,43,539783,2025-03-31,NaN,NaN,Oplot
1,1437821660,75,4958,NaN,NaN,NaN,NaN,43,532479,2025-03-31,NaN,NaN,Kmetiněves
2,1437817745,51,4958,NaN,NaN,NaN,NaN,43,551821,2025-03-31,NaN,NaN,Tvrdkov
3,1438033018,80,4958,NaN,NaN,NaN,NaN,43,559806,2025-03-31,NaN,NaN,Hlohovice
4,1437579150,449,4958,NaN,NaN,NaN,NaN,43,574911,2025-03-31,NaN,NaN,Dolní Roveň

## 007. [A] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí

                                                             hodnota
dataset_id                                                 250169r24
dataset_title      Uchazeči o zaměstnání dosažitelní a podíl neza...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2024'}
selected_file                          OD_NEZ01_2025011310375706.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     375480
column_count                                                      10
time_columns                                      obdobi, rok, mesic
years_min                                                       2024
years_max                                                       2024
years_count                                                        1
years_sample                                                    2024
years_source                                            data_columns
frequency_catalog            měsíční; jednorázové / snapshot [R/P1M]
start_catalog                                             2024-01-01
end_catalog                                               2024-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                      nezaměstnanost
uzemni_uroven                                                   obec
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/e64e2c95-d6b2-8...
preview_csv        heads_csv\007_250169r24_Uchazeci_o_zamestnani_...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,vuk,vuk_text,obdobi,rok,mesic,uzemi_cis,uzemi_kod,uzemi_txt
0,1285998842,29,NEZ0007,Uchazeči o zaměstnání,20240430,2024,4,43,500011,Želechovice nad Dřevnicí
1,1354646498,26,NEZ0007,Uchazeči o zaměstnání,20241130,2024,11,43,500011,Želechovice nad Dřevnicí
2,1307690694,25,NEZ0007,Uchazeči o zaměstnání,20240731,2024,7,43,500011,Želechovice nad Dřevnicí
3,1335857939,26,NEZ0007,Uchazeči o zaměstnání,20240930,2024,9,43,500011,Želechovice nad Dřevnicí
4,1270041170,24,NEZ0007,Uchazeči o zaměstnání,20240331,2024,3,43,500011,Želechovice nad Dřevnicí

## 008. [A] Statistická data pro územně analytické podklady

                                                             hodnota
dataset_id                                                 340129r25
dataset_title      Statistická data pro územně analytické podklad...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Data do roku 2024 - definitivní data z...
selected_file                  OD_UAP01_KOMPLET_2025092909424565.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     278158
column_count                                                      10
time_columns                                                     rok
years_min                                                       2024
years_max                                                       2024
years_count                                                        1
years_sample                                                    2024
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2024-01-01
end_catalog                                               2024-12-31
hlavni_skupina                               Průřezové datové balíky
detailni_skupina                          územně analytické podklady
uzemni_uroven                                                   obec
zdroj_typ                           databanka ČSÚ / agregovaný balík
page               https://csu.gov.cz/docs/107508/0c2dbf3c-6830-b...
preview_csv        heads_csv\008_340129r25_Statisticka_data_pro_u...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,vuk_id,rok,uzemi_cis,uzemi_kod,uzemi_txt,prislorp_kod,prislorp_txt,vuk_txt
0,1446565628,14,DEM0008,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Zemřelí
1,1446592380,56,DEM0009,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Přistěhovalí
2,1446584407,74,DEM0010,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Vystěhovalí
3,1446574143,4,DEM0011,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Přirozený přírůstek
4,1446579244,-14,DEM0012,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Celkový přírůstek

## 009. [A] Zařízení sociálních služeb podle obcí

                                                             hodnota
dataset_id                                                    190037
dataset_title                  Zařízení sociálních služeb podle obcí
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data k 31.12.2024'}
selected_file                                          ds_190037.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       2207
column_count                                                      11
time_columns                                         stapro_kod, rok
years_min                                                       2024
years_max                                                       2024
years_count                                                        1
years_sample                                                    2024
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2018-12-31
end_catalog                                               2024-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                          kapacity sociálních služeb
uzemni_uroven                                                   obec
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/4b842027-3f33-1...
preview_csv        heads_csv\009_190037_Zarizeni_socialnich_sluze...
error                                                           None

,idhod,hodnota,stapro_kod,dsz_cis,dsz_kod,rok,obec_kod,obec_txt,okres_kod,okres_txt,dsz_txt
0,1493415753,1,6098,2910,130,2024,529303,Benešov,40169,Benešov,Domovy pro seniory
1,1493415756,1,6098,2910,131,2024,529303,Benešov,40169,Benešov,Azylové domy
2,1493415757,1,6098,2910,132,2024,529303,Benešov,40169,Benešov,Domy na půl cesty
3,1493415759,1,6098,2910,114,2024,529303,Benešov,40169,Benešov,Nízkoprahová denní centra
4,1493415760,1,6098,2910,115,2024,529303,Benešov,40169,Benešov,Nízkoprahová zařízení pro děti a mládež

## 010. [B] Sčítání 2021 - Byty podle obydlenosti

                                                             hodnota
dataset_id                                  sldb2021_byty_obydlenost
dataset_title                  Sčítání 2021 - Byty podle obydlenosti
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                        {'cs': 'Byty podle obydlenosti'}
selected_file                        ds_sldb2021_byty_obydlenost.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      20175
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\010_sldb2021_byty_obydlenost_Scitani...
error                                                           None

,idhod,hodnota,ukaz_kod,obydlenost_cis,obydlenost_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,obydlenost_txt,uzemi_txt
0,988459561,859,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet bytů,NaN,Želechovice nad Dřevnicí
1,988445854,669,2607,3316.0,1.0,43,500011,2021,2021-03-26,Počet bytů,obvykle obydlen,Želechovice nad Dřevnicí
2,988445855,190,2607,3244.0,52.0,43,500011,2021,2021-03-26,Počet bytů,obvykle neobydlen,Želechovice nad Dřevnicí
3,988456154,552,2607,NaN,NaN,43,500020,2021,2021-03-26,Počet bytů,NaN,Petrov nad Desnou
4,988445856,469,2607,3316.0,1.0,43,500020,2021,2021-03-26,Počet bytů,obvykle obydlen,Petrov nad Desnou

## 011. [B] Sčítání 2021 - Byty podle obydlenosti a druhu domu

                                                             hodnota
dataset_id                         sldb2021_byty_obydlenost_druhdomu
dataset_title      Sčítání 2021 - Byty podle obydlenosti a druhu ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title           {'cs': 'Byty podle obydlenosti a druhu domu'}
selected_file               ds_sldb2021_byty_obydlenost_druhdomu.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     759734
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\011_sldb2021_byty_obydlenost_druhdom...
error                                                           None

,idhod,hodnota,ukaz_kod,obydlenost_cis,obydlenost_kod,druhdomu_cis,druhdomu_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,obydlenost_txt,druhdomu_txt,uzemi_txt,uzemi_typ
0,1055289407,537,2607,NaN,NaN,NaN,NaN,42,19,2021,2021-03-26,Počet bytů,NaN,NaN,Abertamy,část obce
1,1055535272,258,2607,NaN,NaN,3041.0,4.0,42,19,2021,2021-03-26,Počet bytů,NaN,Bytové domy,Abertamy,část obce
2,1055395569,274,2607,NaN,NaN,3240.0,51.0,42,19,2021,2021-03-26,Počet bytů,NaN,Rodinné domy,Abertamy,část obce
3,1054836674,5,2607,NaN,NaN,3240.0,55.0,42,19,2021,2021-03-26,Počet bytů,NaN,Ostatní budovy (bez rodinných a bytových domů),Abertamy,část obce
4,1000356176,355,2607,3316.0,1.0,NaN,NaN,42,19,2021,2021-03-26,Počet bytů,Obydlen,NaN,Abertamy,část obce

## 012. [B] Sčítání 2021 - Domy podle obydlenosti a druhu domu

                                                             hodnota
dataset_id                                sldb2021_domy_obydlen_druh
dataset_title      Sčítání 2021 - Domy podle obydlenosti a druhu ...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv                                                     None
error              LKOD/VDB selhalo: Response ended prematurely |...

## 013. [B] Sčítání 2021 - Obydlené byty podle celkové plochy bytu

                                                             hodnota
dataset_id                                      sldb2021_byty_plocha
dataset_title      Sčítání 2021 - Obydlené byty podle celkové plo...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle celkové plochy bytu'}
selected_file                            ds_sldb2021_byty_plocha.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      60517
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\013_sldb2021_byty_plocha_Scitani_202...
error                                                           None

,idhod,hodnota,ukaz_kod,plocha_cis,plocha_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,plocha_txt,uzemi_txt
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí
1,988552787,35,2607,5768.0,9.000000e+00,43,500011,2021,2021-03-26,Počet obydlených bytů,nezjištěno,Želechovice nad Dřevnicí
2,988758513,21,2607,7700.0,3.999996e+14,43,500011,2021,2021-03-26,Počet obydlených bytů,"do 39,9 m2",Želechovice nad Dřevnicí
3,988905538,38,2607,7700.0,4.100406e+14,43,500011,2021,2021-03-26,Počet obydlených bytů,"40,0-59,9 m2",Želechovice nad Dřevnicí
4,988905640,115,2607,7700.0,4.100606e+14,43,500011,2021,2021-03-26,Počet obydlených bytů,"60,0-79,9 m2",Želechovice nad Dřevnicí

## 014. [B] Sčítání 2021 - Obydlené byty podle hlavního zdroje energie používaného k vytápění

                                                             hodnota
dataset_id                                     sldb2021_byty_energie
dataset_title      Sčítání 2021 - Obydlené byty podle hlavního zd...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle hlavního zdroje en...
selected_file                           ds_sldb2021_byty_energie.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      87413
column_count                                                      13
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\014_sldb2021_byty_energie_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,energie_cis,energie_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,energie_txt,uzemi_txt,uzemi_typ
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí,obec
1,1025234117,2,2607,3063.0,1.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Z kotelny mimo dům,Želechovice nad Dřevnicí,obec
2,1025246019,54,2607,3063.0,2.0,43,500011,2021,2021-03-26,Počet obydlených bytů,"Uhlí, koks, uhelné brikety",Želechovice nad Dřevnicí,obec
3,1025200775,139,2607,3063.0,3.0,43,500011,2021,2021-03-26,Počet obydlených bytů,"Dřevo, dřevěné brikety",Želechovice nad Dřevnicí,obec
4,1025200780,1,2607,3063.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,"Topné oleje, nafta",Želechovice nad Dřevnicí,obec

## 015. [B] Sčítání 2021 - Obydlené byty podle materiálu nosných zdí a druhu domu

                                                             hodnota
dataset_id                        sldb2021_obybyty_material_druhdomu
dataset_title      Sčítání 2021 - Obydlené byty podle materiálu n...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle materiálu nosných ...
selected_file              ds_sldb2021_obybyty_material_druhdomu.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     161376
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\015_sldb2021_obybyty_material_druhdo...
error                                                           None

,idhod,hodnota,ukaz_kod,material_cis,material_kod,druhdomu_cis,druhdomu_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,material_txt,druhdomu_txt,uzemi_txt,uzemi_typ
0,1056378243,9,2607,3043,6,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,Dřevo,NaN,Želechovice nad Dřevnicí,obec
1,1056306090,0,2607,3043,6,3041.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Dřevo,Bytové domy,Želechovice nad Dřevnicí,obec
2,1056208834,9,2607,3043,6,3240.0,51.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Dřevo,Rodinné domy,Želechovice nad Dřevnicí,obec
3,1055992104,0,2607,3043,6,3240.0,55.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Dřevo,Ostatní budovy (bez rodinných a bytových domů),Želechovice nad Dřevnicí,obec
4,1056022162,566,2607,3337,10,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,"Kámen, cihly, tvárnice",NaN,Želechovice nad Dřevnicí,obec

## 016. [B] Sčítání 2021 - Obydlené byty podle období výstavby nebo rekonstrukce domu a druhu domu

                                                             hodnota
dataset_id                          sldb2021_obybyty_obdobi_druhdomu
dataset_title      Sčítání 2021 - Obydlené byty podle období výst...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle období výstavby ne...
selected_file                ds_sldb2021_obybyty_obdobi_druhdomu.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     268960
column_count                                                      16
time_columns       obdobi_cis, obdobi_kod, sldb_rok, sldb_datum, ...
years_min                                                       1919
years_max                                                       2021
years_count                                                       17
years_sample       1919, 1920, 1945, 1946, 1970, 1971 ... 2001, 2...
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\016_sldb2021_obybyty_obdobi_druhdomu...
error                                                           None

,idhod,hodnota,ukaz_kod,obdobi_cis,obdobi_kod,druhdomu_cis,druhdomu_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,obdobi_txt,druhdomu_txt,uzemi_txt,uzemi_typ
0,1056373039,32,2607,3044,10,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,1919 a dříve,NaN,Želechovice nad Dřevnicí,obec
1,1056405421,0,2607,3044,10,3041.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,1919 a dříve,Bytové domy,Želechovice nad Dřevnicí,obec
2,1056162140,30,2607,3044,10,3240.0,51.0,43,500011,2021,2021-03-26,Počet obydlených bytů,1919 a dříve,Rodinné domy,Želechovice nad Dřevnicí,obec
3,1055960326,2,2607,3044,10,3240.0,55.0,43,500011,2021,2021-03-26,Počet obydlených bytů,1919 a dříve,Ostatní budovy (bez rodinných a bytových domů),Želechovice nad Dřevnicí,obec
4,1056551034,84,2607,3044,3,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,1920-1945,NaN,Želechovice nad Dřevnicí,obec

## 017. [B] Sčítání 2021 - Obydlené byty podle polohy bytu v domě a druhu domu

                                                             hodnota
dataset_id                          sldb2021_obybyty_poloha_druhdomu
dataset_title      Sčítání 2021 - Obydlené byty podle polohy bytu...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle polohy bytu v domě...
selected_file                ds_sldb2021_obybyty_poloha_druhdomu.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     295856
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\017_sldb2021_obybyty_poloha_druhdomu...
error                                                           None

,idhod,hodnota,ukaz_kod,poloha_cis,poloha_kod,druhdomu_cis,druhdomu_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,poloha_txt,druhdomu_txt,uzemi_txt,uzemi_typ
0,1056838985,5,2607,3058,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,"Suterén, sklep",NaN,Želechovice nad Dřevnicí,obec
1,1056662139,0,2607,3058,1,3041.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,"Suterén, sklep",Bytové domy,Želechovice nad Dřevnicí,obec
2,1056738670,5,2607,3058,1,3240.0,51.0,43,500011,2021,2021-03-26,Počet obydlených bytů,"Suterén, sklep",Rodinné domy,Želechovice nad Dřevnicí,obec
3,1056738671,0,2607,3058,1,3240.0,55.0,43,500011,2021,2021-03-26,Počet obydlených bytů,"Suterén, sklep",Ostatní budovy (bez rodinných a bytových domů),Želechovice nad Dřevnicí,obec
4,1056877256,426,2607,3058,2,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,Přízemí,NaN,Želechovice nad Dřevnicí,obec

## 018. [B] Sčítání 2021 - Obydlené byty podle počtu obytných místností

                                                             hodnota
dataset_id                                   sldb2021_byty_mistnosti
dataset_title      Sčítání 2021 - Obydlené byty podle počtu obytn...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle počtu obytných mís...
selected_file                         ds_sldb2021_byty_mistnosti.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      53793
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\018_sldb2021_byty_mistnosti_Scitani_...
error                                                           None

,idhod,hodnota,ukaz_kod,mistnosti_cis,mistnosti_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,mistnosti_txt,uzemi_txt
0,988481225,3.99,2416,NaN,NaN,43,500011,2021,2021-03-26,Průměrný počet obytných místností na 1 byt,NaN,Želechovice nad Dřevnicí
1,988481226,3.54,2416,NaN,NaN,43,500020,2021,2021-03-26,Průměrný počet obytných místností na 1 byt,NaN,Petrov nad Desnou
2,988492658,3.95,2416,NaN,NaN,43,500046,2021,2021-03-26,Průměrný počet obytných místností na 1 byt,NaN,Libhošť
3,988503734,3.79,2416,NaN,NaN,43,500062,2021,2021-03-26,Průměrný počet obytných místností na 1 byt,NaN,Krhová
4,988481227,3.75,2416,NaN,NaN,43,500071,2021,2021-03-26,Průměrný počet obytných místností na 1 byt,NaN,Poličná

## 019. [B] Sčítání 2021 - Obydlené byty podle počtu obytných místností včetně kuchyně

                                                             hodnota
dataset_id                           sldb2021_byty_mistnosti_kuchyne
dataset_title      Sčítání 2021 - Obydlené byty podle počtu obytn...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle počtu obytných mís...
selected_file                 ds_sldb2021_byty_mistnosti_kuchyne.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      53793
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\019_sldb2021_byty_mistnosti_kuchyne_...
error                                                           None

,idhod,hodnota,ukaz_kod,mistnosti_cis,mistnosti_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,mistnosti_txt,uzemi_txt
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí
1,988445856,469,2607,NaN,NaN,43,500020,2021,2021-03-26,Počet obydlených bytů,NaN,Petrov nad Desnou
2,988445858,627,2607,NaN,NaN,43,500046,2021,2021-03-26,Počet obydlených bytů,NaN,Libhošť
3,988445860,782,2607,NaN,NaN,43,500062,2021,2021-03-26,Počet obydlených bytů,NaN,Krhová
4,988445862,652,2607,NaN,NaN,43,500071,2021,2021-03-26,Počet obydlených bytů,NaN,Poličná

## 020. [B] Sčítání 2021 - Obydlené byty podle počtu osob v bytě

                                                             hodnota
dataset_id                                       sldb2021_byty_osoby
dataset_title      Sčítání 2021 - Obydlené byty podle počtu osob ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title         {'cs': 'Obydlené byty podle počtu osob v bytě'}
selected_file                             ds_sldb2021_byty_osoby.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      22141
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\020_sldb2021_byty_osoby_Scitani_2021...
error                                                           None

,idhod,hodnota,ukaz_kod,osob_cis,osob_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,osob_txt,uzemi_txt
0,987843452,2.65,2419,NaN,NaN,43,500011,2021,2021-03-26,Průměrný počet osob na 1 obydlený byt,NaN,Želechovice nad Dřevnicí
1,987848944,2.47,2419,NaN,NaN,43,500020,2021,2021-03-26,Průměrný počet osob na 1 obydlený byt,NaN,Petrov nad Desnou
2,987844341,2.68,2419,NaN,NaN,43,500046,2021,2021-03-26,Průměrný počet osob na 1 obydlený byt,NaN,Libhošť
3,987848529,2.57,2419,NaN,NaN,43,500062,2021,2021-03-26,Průměrný počet osob na 1 obydlený byt,NaN,Krhová
4,987843555,2.61,2419,NaN,NaN,43,500071,2021,2021-03-26,Průměrný počet osob na 1 obydlený byt,NaN,Poličná

## 021. [B] Sčítání 2021 - Obydlené byty podle právního důvodu užívání bytu

                                                             hodnota
dataset_id                                     sldb2021_byty_uzivani
dataset_title      Sčítání 2021 - Obydlené byty podle právního dů...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle právního důvodu už...
selected_file                           ds_sldb2021_byty_uzivani.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      53793
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\021_sldb2021_byty_uzivani_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,uzivani_cis,uzivani_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,uzivani_txt,uzemi_txt
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí
1,988991446,493,2607,3055.0,1.0,43,500011,2021,2021-03-26,Počet obydlených bytů,ve vlastním domě,Želechovice nad Dřevnicí
2,988697662,47,2607,3055.0,2.0,43,500011,2021,2021-03-26,Počet obydlených bytů,v osobním vlastnictví,Želechovice nad Dřevnicí
3,988918189,50,2607,3055.0,3.0,43,500011,2021,2021-03-26,Počet obydlených bytů,jiné bezplatné užívání,Želechovice nad Dřevnicí
4,988844224,30,2607,3055.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,nájemní/pronajatý,Želechovice nad Dřevnicí

## 022. [B] Sčítání 2021 - Obydlené byty podle převažujícího způsobu vytápění

                                                             hodnota
dataset_id                                    sldb2021_byty_vytapeni
dataset_title      Sčítání 2021 - Obydlené byty podle převažující...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle převažujícího způs...
selected_file                          ds_sldb2021_byty_vytapeni.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      47069
column_count                                                      13
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\022_sldb2021_byty_vytapeni_Scitani_2...
error                                                           None

,idhod,hodnota,ukaz_kod,vytapeni_cis,vytapeni_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vytapeni_txt,uzemi_txt,uzemi_typ
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí,obec
1,1025149181,2,2607,3062.0,1.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Ústřední dálkové,Želechovice nad Dřevnicí,obec
2,1025149180,250,2607,3261.0,54.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Ústřední domovní,Želechovice nad Dřevnicí,obec
3,1025149182,321,2607,3062.0,3.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Ústřední s vlastním zdrojem (v bytě),Želechovice nad Dřevnicí,obec
4,1025149183,52,2607,3062.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Lokální topidla (kamna),Želechovice nad Dřevnicí,obec

## 023. [B] Sčítání 2021 - Obydlené byty podle připojení na plyn

                                                             hodnota
dataset_id                                        sldb2021_byty_plyn
dataset_title      Sčítání 2021 - Obydlené byty podle připojení n...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title         {'cs': 'Obydlené byty podle připojení na plyn'}
selected_file                              ds_sldb2021_byty_plyn.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      40345
column_count                                                      13
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\023_sldb2021_byty_plyn_Scitani_2021_...
error                                                           None

,idhod,hodnota,ukaz_kod,plyn_cis,plyn_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,plyn_txt,uzemi_txt,uzemi_typ
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí,obec
1,1025272432,429,2607,3056.0,3.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Z veřejné sítě,Želechovice nad Dřevnicí,obec
2,1025272436,1,2607,3056.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Z domovního (lokálního) zásobníku,Želechovice nad Dřevnicí,obec
3,1025272435,10,2607,3056.0,5.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Pouze plynové tlakové lahve,Želechovice nad Dřevnicí,obec
4,1025272433,225,2607,3056.0,2.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Bez plynu,Želechovice nad Dřevnicí,obec

## 024. [B] Sčítání 2021 - Obydlené byty podle připojení na vodovod

                                                             hodnota
dataset_id                                     sldb2021_byty_vodovod
dataset_title      Sčítání 2021 - Obydlené byty podle připojení n...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle připojení na vodov...
selected_file                           ds_sldb2021_byty_vodovod.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      47069
column_count                                                      13
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\024_sldb2021_byty_vodovod_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,vodovod_cis,vodovod_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vodovod_txt,uzemi_txt,uzemi_typ
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí,obec
1,1025125229,300,2607,3061.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,V bytě - pouze z veřejné sítě,Želechovice nad Dřevnicí,obec
2,1025113300,241,2607,3061.0,5.0,43,500011,2021,2021-03-26,Počet obydlených bytů,V bytě - pouze ze soukromého zdroje,Želechovice nad Dřevnicí,obec
3,1025125020,95,2607,3061.0,6.0,43,500011,2021,2021-03-26,Počet obydlených bytů,V bytě - z veřejné sítě i ze soukromého zdroje,Želechovice nad Dřevnicí,obec
4,1025090470,2,2607,3061.0,2.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Mimo byt v domě,Želechovice nad Dřevnicí,obec

## 025. [B] Sčítání 2021 - Obydlené byty podle vlastníka a druhu domu

                                                             hodnota
dataset_id                        sldb2021_obybyty_vlastnik_druhdomu
dataset_title      Sčítání 2021 - Obydlené byty podle vlastníka a...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle vlastníka a druhu ...
selected_file              ds_sldb2021_obybyty_vlastnik_druhdomu.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     188272
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\025_sldb2021_obybyty_vlastnik_druhdo...
error                                                           None

,idhod,hodnota,ukaz_kod,vlastnik_cis,vlastnik_kod,druhdomu_cis,druhdomu_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vlastnik_txt,druhdomu_txt,uzemi_txt,uzemi_typ
0,1056455826,590,2607,3049,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,Fyzická osoba,NaN,Želechovice nad Dřevnicí,obec
1,1056047151,5,2607,3049,1,3041.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Fyzická osoba,Bytové domy,Želechovice nad Dřevnicí,obec
2,1056241247,584,2607,3049,1,3240.0,51.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Fyzická osoba,Rodinné domy,Želechovice nad Dřevnicí,obec
3,1056565629,1,2607,3049,1,3240.0,55.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Fyzická osoba,Ostatní budovy (bez rodinných a bytových domů),Želechovice nad Dřevnicí,obec
4,1055921627,1,2607,3049,10,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,Bytové družstvo,NaN,Želechovice nad Dřevnicí,obec

## 026. [B] Sčítání 2021 - Obydlené byty podle vybavení domu výtahem a druhu domu

                                                             hodnota
dataset_id                           sldb2021_obybyty_vytah_druhdomu
dataset_title      Sčítání 2021 - Obydlené byty podle vybavení do...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle vybavení domu výta...
selected_file                 ds_sldb2021_obybyty_vytah_druhdomu.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      80688
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\026_sldb2021_obybyty_vytah_druhdomu_...
error                                                           None

,idhod,hodnota,ukaz_kod,vytah_cis,vytah_kod,druhdomu_cis,druhdomu_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vytah_txt,druhdomu_txt,uzemi_txt,uzemi_typ
0,1055714597,0,2607,3206,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,S výtahem,NaN,Želechovice nad Dřevnicí,obec
1,1055754312,0,2607,3206,1,3041.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,S výtahem,Bytové domy,Želechovice nad Dřevnicí,obec
2,1055754189,0,2607,3206,1,3240.0,51.0,43,500011,2021,2021-03-26,Počet obydlených bytů,S výtahem,Rodinné domy,Želechovice nad Dřevnicí,obec
3,1055810234,0,2607,3206,1,3240.0,55.0,43,500011,2021,2021-03-26,Počet obydlených bytů,S výtahem,Ostatní budovy (bez rodinných a bytových domů),Želechovice nad Dřevnicí,obec
4,1055686827,666,2607,3206,2,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,Bez výtahu,NaN,Želechovice nad Dřevnicí,obec

## 027. [B] Sčítání 2021 - Obydlené byty podle vybavení kuchyní

                                                             hodnota
dataset_id                                     sldb2021_byty_kuchyne
dataset_title      Sčítání 2021 - Obydlené byty podle vybavení ku...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title          {'cs': 'Obydlené byty podle vybavení kuchyní'}
selected_file                           ds_sldb2021_byty_kuchyne.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      33621
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\027_sldb2021_byty_kuchyne_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,kuchyne_cis,kuchyne_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,kuchyne_txt,uzemi_txt
0,988445854,669,2607,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,NaN,Želechovice nad Dřevnicí
1,999576287,523,2607,3223.0,10.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Kuchyň,Želechovice nad Dřevnicí
2,999576286,119,2607,3223.0,11.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Kuchyňský kout,Želechovice nad Dřevnicí
3,999576289,3,2607,3223.0,12.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Bez kuchyně a bez kuchyňského koutu,Želechovice nad Dřevnicí
4,999576288,24,2607,3223.0,9.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Nezjištěno,Želechovice nad Dřevnicí

## 028. [B] Sčítání 2021 - Obydlené byty podle způsobu odvádění odpadních vod a druhu domu

                                                             hodnota
dataset_id                           sldb2021_obybyty_odpad_druhdomu
dataset_title      Sčítání 2021 - Obydlené byty podle způsobu odv...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené byty podle způsobu odvádění o...
selected_file                 ds_sldb2021_obybyty_odpad_druhdomu.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     134480
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\028_sldb2021_obybyty_odpad_druhdomu_...
error                                                           None

,idhod,hodnota,ukaz_kod,odpad_cis,odpad_kod,druhdomu_cis,druhdomu_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,odpad_txt,druhdomu_txt,uzemi_txt,uzemi_typ
0,1055879666,239,2607,2335,10,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,Kanalizační síť,NaN,Želechovice nad Dřevnicí,obec
1,1055791123,27,2607,2335,10,3041.0,4.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Kanalizační síť,Bytové domy,Želechovice nad Dřevnicí,obec
2,1055763204,208,2607,2335,10,3240.0,51.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Kanalizační síť,Rodinné domy,Želechovice nad Dřevnicí,obec
3,1055902781,4,2607,2335,10,3240.0,55.0,43,500011,2021,2021-03-26,Počet obydlených bytů,Kanalizační síť,Ostatní budovy (bez rodinných a bytových domů),Želechovice nad Dřevnicí,obec
4,1055879665,350,2607,2335,20,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených bytů,Žumpa,NaN,Želechovice nad Dřevnicí,obec

## 029. [B] Sčítání 2021 - Obydlené domy podle materiálu nosných zdí a druhu domu

                                                             hodnota
dataset_id                                 sldb2021_obydomy_druh_zdi
dataset_title      Sčítání 2021 - Obydlené domy podle materiálu n...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle materiálu nosných ...
selected_file                       ds_sldb2021_obydomy_druh_zdi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     134480
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\029_sldb2021_obydomy_druh_zdi_Scitan...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,zdi_cis,zdi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,zdi_txt,uzemi_txt,uzemi_typ
0,1046559733,7,2409,NaN,NaN,3043,6,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Dřevo,Želechovice nad Dřevnicí,obec
1,1048068757,37,2409,NaN,NaN,3043,7,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Jiné materiály a kombinace,Želechovice nad Dřevnicí,obec
2,1042786910,29,2409,NaN,NaN,5768,9,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Nezjištěno,Želechovice nad Dřevnicí,obec
3,1045051804,433,2409,NaN,NaN,3337,10,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,"Kámen, cihly, tvárnice",Želechovice nad Dřevnicí,obec
4,1042786912,0,2409,NaN,NaN,3043,20,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Monolit (monolitická betonová tyčová),Želechovice nad Dřevnicí,obec

## 030. [B] Sčítání 2021 - Obydlené domy podle napojení na kanalizaci a druhu domu

                                                             hodnota
dataset_id                               sldb2021_obydomy_druh_odpad
dataset_title      Sčítání 2021 - Obydlené domy podle napojení na...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle napojení na kanali...
selected_file                     ds_sldb2021_obydomy_druh_odpad.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     134480
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\030_sldb2021_obydomy_druh_odpad_Scit...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,odpad_cis,odpad_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,odpad_txt,uzemi_txt,uzemi_typ
0,1046553698,181,2409,NaN,NaN,2335,10,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Kanalizační síť,Želechovice nad Dřevnicí,obec
1,1046553699,274,2409,NaN,NaN,2335,20,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Žumpa,Želechovice nad Dřevnicí,obec
2,1043533247,51,2409,NaN,NaN,2335,30,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Vlastní čistírna odpadních vod,Želechovice nad Dřevnicí,obec
3,1042779133,6,2409,NaN,NaN,2335,40,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,bez připojení,Želechovice nad Dřevnicí,obec
4,1043534988,18,2409,NaN,NaN,5768,9,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Nezjištěno,Želechovice nad Dřevnicí,obec

## 031. [B] Sčítání 2021 - Obydlené domy podle napojení na plyn a druhu domu

                                                             hodnota
dataset_id                                sldb2021_obydomy_druh_plyn
dataset_title      Sčítání 2021 - Obydlené domy podle napojení na...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle napojení na plyn a...
selected_file                      ds_sldb2021_obydomy_druh_plyn.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     134480
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\031_sldb2021_obydomy_druh_plyn_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,plyn_cis,plyn_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,plyn_txt,uzemi_txt,uzemi_typ
0,1048700824,5,2409,NaN,NaN,2663,20,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Lokální zásobník plynu pro dokončenou stavbu,Želechovice nad Dřevnicí,obec
1,1048415233,181,2409,NaN,NaN,2663,40,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Bez přívodu plynu,Želechovice nad Dřevnicí,obec
2,1048944668,345,2409,NaN,NaN,3247,51,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Plyn v domě,Želechovice nad Dřevnicí,obec
3,1048700823,340,2409,NaN,NaN,2663,52,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Plyn z veřejné sítě,Želechovice nad Dřevnicí,obec
4,1049272398,4,2409,NaN,NaN,5768,9,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Nezjištěno,Želechovice nad Dřevnicí,obec

## 032. [B] Sčítání 2021 - Obydlené domy podle napojení na vodovod a druhu domu

                                                             hodnota
dataset_id                             sldb2021_obydomy_druh_vodovod
dataset_title      Sčítání 2021 - Obydlené domy podle napojení na...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle napojení na vodovo...
selected_file                   ds_sldb2021_obydomy_druh_vodovod.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     161376
column_count                                                      17
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\032_sldb2021_obydomy_druh_vodovod_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,vodovod_cis,vodovod_kod,vodovod_cleneni,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,vodovod_txt,uzemi_txt,uzemi_typ
0,1048271171,5,2409,NaN,NaN,3050,4,1,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Bez vodovodu,Želechovice nad Dřevnicí,obec
1,1048786530,516,2409,NaN,NaN,3248,51,1,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Vodovod v domě,Želechovice nad Dřevnicí,obec
2,1049129361,9,2409,NaN,NaN,3050,9,1,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Nezjištěno,Želechovice nad Dřevnicí,obec
3,1048557732,229,2409,NaN,NaN,3050,1,2,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Vodovod v domě - z veřejné sítě,Želechovice nad Dřevnicí,obec
4,1049272001,196,2409,NaN,NaN,3050,2,2,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Vodovod v domě - domácí,Želechovice nad Dřevnicí,obec

## 033. [B] Sčítání 2021 - Obydlené domy podle období výstavby a druhu domu

                                                             hodnota
dataset_id                              sldb2021_obydomy_druh_obdobi
dataset_title      Sčítání 2021 - Obydlené domy podle období výst...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle období výstavby a ...
selected_file                    ds_sldb2021_obydomy_druh_obdobi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     269000
column_count                                                      16
time_columns       obdobi_cis, obdobi_kod, sldb_rok, sldb_datum, ...
years_min                                                       1919
years_max                                                       2021
years_count                                                       17
years_sample       1919, 1920, 1945, 1946, 1970, 1971 ... 2001, 2...
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\033_sldb2021_obydomy_druh_obdobi_Sci...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,obdobi_cis,obdobi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,obdobi_txt,uzemi_txt,uzemi_typ
0,1034549372,25,2409,NaN,NaN,3044,10,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,1919 a dříve,Želechovice nad Dřevnicí,obec
1,1035597835,70,2409,NaN,NaN,3044,3,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,1920-1945,Želechovice nad Dřevnicí,obec
2,1035597836,118,2409,NaN,NaN,3265,55,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,1946-1970,Želechovice nad Dřevnicí,obec
3,1035948202,105,2409,NaN,NaN,3044,6,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,1971-1980,Želechovice nad Dřevnicí,obec
4,1033849946,57,2409,NaN,NaN,3044,7,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,1981-1990,Želechovice nad Dřevnicí,obec

## 034. [B] Sčítání 2021 - Obydlené domy podle počtu bytů v domě a druhu domu

                                                             hodnota
dataset_id                                sldb2021_obydomy_druh_byty
dataset_title      Sčítání 2021 - Obydlené domy podle počtu bytů ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle počtu bytů v domě ...
selected_file                      ds_sldb2021_obydomy_druh_byty.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     181548
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\034_sldb2021_obydomy_druh_byty_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,byty_cis,byty_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,byty_txt,uzemi_txt,uzemi_typ
0,1029484583,11,2409,3041,4,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,NaN,Želechovice nad Dřevnicí,obec
1,1029316250,0,2409,3041,4,7600.0,1.0,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,1.0,Želechovice nad Dřevnicí,obec
2,1029595244,0,2409,3041,4,7600.0,2.0,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,2.0,Želechovice nad Dřevnicí,obec
3,1029651080,0,2409,3041,4,7600.0,3.0,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,3.0,Želechovice nad Dřevnicí,obec
4,1029483725,2,2409,3041,4,7600.0,4.0,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,4.0,Želechovice nad Dřevnicí,obec

## 035. [B] Sčítání 2021 - Obydlené domy podle počtu nadzemních podlaží a druhu domu

                                                             hodnota
dataset_id                             sldb2021_obydomy_podlazi_druh
dataset_title      Sčítání 2021 - Obydlené domy podle počtu nadze...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle počtu nadzemních p...
selected_file                   ds_sldb2021_obydomy_podlazi_druh.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     269000
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\035_sldb2021_obydomy_podlazi_druh_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,podlazi_cis,podlazi_kod,druh_cis,druh_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,podlazi_txt,druh_txt,uzemi_txt,uzemi_typ
0,1054075472,157,2409,7600,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených domů,1,NaN,Želechovice nad Dřevnicí,obec
1,1054127702,0,2409,7600,1,3041.0,4.0,43,500011,2021,2021-03-26,Počet obydlených domů,1,Bytové domy,Želechovice nad Dřevnicí,obec
2,1054057891,156,2409,7600,1,3240.0,51.0,43,500011,2021,2021-03-26,Počet obydlených domů,1,Rodinné domy,Želechovice nad Dřevnicí,obec
3,1054127703,1,2409,7600,1,3240.0,55.0,43,500011,2021,2021-03-26,Počet obydlených domů,1,Ostatní budovy (bez rodinných a bytových domů),Želechovice nad Dřevnicí,obec
4,1054075355,323,2409,7600,2,NaN,NaN,43,500011,2021,2021-03-26,Počet obydlených domů,2,NaN,Želechovice nad Dřevnicí,obec

## 036. [B] Sčítání 2021 - Obydlené domy podle vlastnictví a druhu domu

                                                             hodnota
dataset_id                            sldb2021_obydomy_druh_vlastnik
dataset_title      Sčítání 2021 - Obydlené domy podle vlastnictví...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle vlastnictví a druh...
selected_file                  ds_sldb2021_obydomy_druh_vlastnik.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     188300
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\036_sldb2021_obydomy_druh_vlastnik_S...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,vlastnik_cis,vlastnik_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,vlastnik_txt,uzemi_txt,uzemi_typ
0,1034547151,505,2409,NaN,NaN,3049,1,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Fyzická osoba,Želechovice nad Dřevnicí,obec
1,1033847536,1,2409,NaN,NaN,3049,10,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Bytové družstvo,Želechovice nad Dřevnicí,obec
2,1034896246,13,2409,NaN,NaN,3049,11,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Spoluvlastnictví vlastníků bytů (jednotek),Želechovice nad Dřevnicí,obec
3,1033497194,3,2409,NaN,NaN,3049,2,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,"Obec, stát",Želechovice nad Dřevnicí,obec
4,1034197187,3,2409,NaN,NaN,3049,6,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Jiná právnická osoba,Želechovice nad Dřevnicí,obec

## 037. [B] Sčítání 2021 - Obydlené domy podle vybavení výtahem a druhu domu

                                                             hodnota
dataset_id                               sldb2021_obydomy_druh_vytah
dataset_title      Sčítání 2021 - Obydlené domy podle vybavení vý...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy podle vybavení výtahem a...
selected_file                     ds_sldb2021_obydomy_druh_vytah.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      80688
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\037_sldb2021_obydomy_druh_vytah_Scit...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,vytah_cis,vytah_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,vytah_txt,uzemi_txt,uzemi_typ
0,1048066184,0,2409,NaN,NaN,3206,1,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,s výtahem,Želechovice nad Dřevnicí,obec
1,1048066183,527,2409,NaN,NaN,3206,2,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,bez výtahu,Želechovice nad Dřevnicí,obec
2,1042784327,3,2409,NaN,NaN,5768,9,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Nezjištěno,Želechovice nad Dřevnicí,obec
3,1042967618,0,2409,3041.0,4.0,3206,1,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,s výtahem,Želechovice nad Dřevnicí,obec
4,1046741299,11,2409,3041.0,4.0,3206,2,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,bez výtahu,Želechovice nad Dřevnicí,obec

## 038. [B] Sčítání 2021 - Obydlené domy způsobu vytápění a druhu domu

                                                             hodnota
dataset_id                            sldb2021_obydomy_druh_vytapeni
dataset_title      Sčítání 2021 - Obydlené domy způsobu vytápění ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obydlené domy způsobu vytápění a druhu...
selected_file                  ds_sldb2021_obydomy_druh_vytapeni.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     107584
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                           domy a technické vybavení
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\038_sldb2021_obydomy_druh_vytapeni_S...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_cis,druh_kod,vytapeni_cis,vytapeni_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_txt,vytapeni_txt,uzemi_txt,uzemi_typ
0,1049501186,409,2409,NaN,NaN,3242,52,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Kotelna v domě,Želechovice nad Dřevnicí,obec
1,1049416753,116,2409,NaN,NaN,3048,8,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Bez ústředního topení,Želechovice nad Dřevnicí,obec
2,1049416754,2,2409,NaN,NaN,3048,9,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Kotelna mimo dům,Želechovice nad Dřevnicí,obec
3,1049416755,3,2409,NaN,NaN,3048,99,43,500011,2021,2021-03-26,Počet obydlených domů,NaN,Nezjištěno,Želechovice nad Dřevnicí,obec
4,1049443022,9,2409,3041.0,4.0,3242,52,43,500011,2021,2021-03-26,Počet obydlených domů,Bytové domy,Kotelna v domě,Želechovice nad Dřevnicí,obec

## 039. [B] Výběr údajů ze SLDB 2011 za domy a byty

                                                             hodnota
dataset_id                                                  sldbdomy
dataset_title                Výběr údajů ze SLDB 2011 za domy a byty
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                   {'cs': 'Domy a byty'}
selected_file                                      SLDB_DOMYBYTY.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                       6712
column_count                                                      92
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                       desetileté / census [R/P10Y]
start_catalog                                             2011-03-26
end_catalog                                               2011-03-26
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                              byty a kvalita bydlení
uzemni_uroven                       více úrovní (ČR–kraj–okres–obec)
zdroj_typ                             SLDB 2011 / historické sčítání
page               https://csu.gov.cz/docs/107516/67827fbf-a0d5-2...
preview_csv        heads_csv\039_sldbdomy_Vyber_udaju_ze_SLDB_201...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,typuz_naz,nazev,uzcis,uzkod,vse7111,vse7112,vse7113,vse7114,vse7121,vse7122,...,vse8183,vse8184,vse8191,vse8192,vse8193,vse8194,vse81101,vse81102,vse81103,vse81104
0,kraj,Hlavní město Praha,100,3018,99949.0,63610.0,32986.0,3353.0,92927.0,57354.0,...,116581.0,777.0,134535.0,16496.0,117572.0,467.0,61204.0,30322.0,30490.0,392.0
1,kraj,Středočeský kraj,100,3026,353037.0,327239.0,19892.0,5906.0,286780.0,262703.0,...,57181.0,1048.0,123515.0,73273.0,49481.0,761.0,134041.0,123550.0,9866.0,625.0
2,kraj,Jihočeský kraj,100,3034,163889.0,148153.0,12694.0,3042.0,123048.0,108358.0,...,34405.0,526.0,72151.0,34042.0,37604.0,505.0,58590.0,48512.0,9780.0,298.0
3,kraj,Plzeňský kraj,100,3042,131052.0,115381.0,12814.0,2857.0,105835.0,90894.0,...,36457.0,471.0,65350.0,29958.0,35071.0,321.0,48279.0,39797.0,8258.0,224.0
4,kraj,Karlovarský kraj,100,3051,44979.0,33753.0,9616.0,1610.0,39845.0,29092.0,...,29304.0,292.0,28258.0,8654.0,19388.0,216.0,19304.0,13765.0,5393.0,146.0

## 040. [B] Obyvatelstvo podle jednotek věku a pohlaví ve správních obvodech obcí s rozšířenou působností

                                                             hodnota
dataset_id                                                 130181r22
dataset_title      Obyvatelstvo podle jednotek věku a pohlaví ve ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                {'cs': 'Data roku 2021'}
selected_file                                       ds_130181r22.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      41612
column_count                                                      13
time_columns                                   stapro_kod, casref_do
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2021-01-01
end_catalog                                               2021-12-31
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                                    ORP
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/1d21dfbf-4642-d...
preview_csv        heads_csv\040_130181r22_Obyvatelstvo_podle_jed...
error                                                           None

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_do,pohlavi_txt,vek_txt,vuzemi_txt
0,975483566,125,2406,102,2,7700,410034610035000,65,3114,2021-12-31,žena,34 až 35 (více nebo rovno 34 a méně než 35),Třeboň
1,975535800,209,2406,102,2,7700,410034610035000,65,8102,2021-12-31,žena,34 až 35 (více nebo rovno 34 a méně než 35),Bohumín
2,975477457,948,2406,102,2,7700,410034610035000,65,5105,2021-12-31,žena,34 až 35 (více nebo rovno 34 a méně než 35),Liberec
3,975518625,184,2406,102,2,7700,410034610035000,65,6214,2021-12-31,žena,34 až 35 (více nebo rovno 34 a méně než 35),Rosice
4,975500537,95,2406,102,2,7700,410034610035000,65,4215,2021-12-31,žena,34 až 35 (více nebo rovno 34 a méně než 35),Varnsdorf

## 041. [B] Obyvatelstvo podle pohlaví a základních věkových skupin

                                                             hodnota
dataset_id                                                    130149
dataset_title      Obyvatelstvo podle pohlaví a základních věkový...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2000-01-01
end_catalog                                               2024-12-31
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                   více úrovní (ČR–kraj–okres–ORP–obec)
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/3de428e4-62ea-3...
preview_csv                                                     None
error              LKOD/VDB selhalo: ('Connection broken: Incompl...

## 042. [B] Pohyb obyvatel

                                                             hodnota
dataset_id                                                 130141r25
dataset_title                              Pohyb obyvatel - rok 2024
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                {'cs': 'Data roku 2024'}
selected_file                                       ds_130141r25.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      78744
column_count                                                      11
time_columns                   stapro_kod, rok, casref_od, casref_do
years_min                                                       2024
years_max                                                       2024
years_count                                                        1
years_sample                                                    2024
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2024-01-01
end_catalog                                               2024-12-31
hlavni_skupina                                 Demografie a populace
detailni_skupina                            přirozená měna a migrace
uzemni_uroven                   více úrovní (ČR–kraj–okres–ORP–obec)
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/e40b9b8d-ff26-8...
preview_csv        heads_csv\042_130141r25_Pohyb_obyvatel_-_rok_2...
error                                                           None

,idhod,hodnota,vuk,vuk_text,stapro_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,vuzemi_txt
0,1446607887,8,DEM0008,Zemřelí,5393,43,578231,2024,2024-01-01,2024-12-31,Koclířov
1,1446607050,7,DEM0008,Zemřelí,5393,43,575534,2024,2024-01-01,2024-12-31,Ráby
2,1446607855,2,DEM0008,Zemřelí,5393,43,597473,2024,2024-01-01,2024-12-31,Karlova Studánka
3,1446607865,3,DEM0008,Zemřelí,5393,43,557374,2024,2024-01-01,2024-12-31,Velké Hydčice
4,1446607870,3,DEM0008,Zemřelí,5393,43,594831,2024,2024-01-01,2024-12-31,Střelice

## 043. [B] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce

                                                             hodnota
dataset_id                                                 130141r22
dataset_title      Pohyb obyvatel za ČR, kraje, okresy, SO ORP a ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                {'cs': 'Data roku 2021'}
selected_file                                       ds_130141r22.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      52432
column_count                                                      11
time_columns                   stapro_kod, rok, casref_od, casref_do
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2021-01-01
end_catalog                                               2021-12-31
hlavni_skupina                                 Demografie a populace
detailni_skupina                            přirozená měna a migrace
uzemni_uroven                   více úrovní (ČR–kraj–okres–ORP–obec)
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107516/60a4ae8d-62d9-b...
preview_csv        heads_csv\043_130141r22_Pohyb_obyvatel_za_CR_k...
error                                                           None

,idhod,hodnota,vuk,vuk_text,stapro_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,vuzemi_txt
0,967561553,0,DEM0008,Zemřelí,5393,43,581526,2021,2021-01-01,2021-12-31,Dlouhá Lhota
1,967558929,1,DEM0008,Zemřelí,5393,43,571814,2021,2021-01-01,2021-12-31,Zdětín
2,967558946,5,DEM0008,Zemřelí,5393,43,571881,2021,2021-01-01,2021-12-31,Strážiště
3,967559924,8,DEM0008,Zemřelí,5393,43,575089,2021,2021-01-01,2021-12-31,Chvojenec
4,967561518,170,DEM0008,Zemřelí,5393,43,581372,2021,2021-01-01,2021-12-31,Boskovice

## 044. [B] Sčítání 2021 - Obyvatelstvo podle bydliště matky v době narození a pohlaví

                                                             hodnota
dataset_id                                sldb2021_bydlnaroz_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle bydliště mat...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle bydliště matky v do...
selected_file                      ds_sldb2021_bydlnaroz_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     391140
column_count                                                      17
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\044_sldb2021_bydlnaroz_pohlavi_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,bydl_narozeni_cis,bydl_narozeni_kod,bydl_cleneni_typ,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,bydl_narozeni_txt,bydl_cleneni_txt,pohlavi_txt,uzemi_txt
0,1009668978,872,3162,3239,1,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V obci obvyklého pobytu,základní,NaN,Želechovice nad Dřevnicí
1,1009668979,631,3162,3239,2,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V jiné obci okresu obvyklého pobytu,základní,NaN,Želechovice nad Dřevnicí
2,1009651437,88,3162,3239,3,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V jiném okrese kraje obvyklého pobytu,základní,NaN,Želechovice nad Dřevnicí
3,1009668977,130,3162,3334,51,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V jiném kraji,základní,NaN,Želechovice nad Dřevnicí
4,1009651436,50,3162,3239,7,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,"V ČR, místo nezjištěno",základní,NaN,Želechovice nad Dřevnicí

## 045. [B] Sčítání 2021 - Obyvatelstvo podle bydliště rok před sčítáním a pohlaví

                                                             hodnota
dataset_id                                 sldb2021_bydl1rok_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle bydliště rok...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle bydliště rok před s...
selected_file                       ds_sldb2021_bydl1rok_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     391140
column_count                                                      17
time_columns       bydl_1rok_cis, bydl_1rok_kod, sldb_rok, sldb_d...
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\045_sldb2021_bydl1rok_pohlavi_Scitan...
error                                                           None

,idhod,hodnota,ukaz_kod,bydl_1rok_cis,bydl_1rok_kod,bydl_cleneni_typ,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,bydl_1rok_txt,bydl_cleneni_txt,pohlavi_txt,uzemi_txt
0,1010088181,1713,3162,3239,1,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V obci obvyklého pobytu,základní,NaN,Želechovice nad Dřevnicí
1,1010043149,51,3162,3239,2,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V jiné obci okresu obvyklého pobytu,základní,NaN,Želechovice nad Dřevnicí
2,1010043150,7,3162,3239,3,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V jiném okrese kraje obvyklého pobytu,základní,NaN,Želechovice nad Dřevnicí
3,1010088182,15,3162,3334,51,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,V jiném kraji,základní,NaN,Želechovice nad Dřevnicí
4,1010043151,0,3162,3239,7,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,"V ČR, místo nezjištěno",základní,NaN,Želechovice nad Dřevnicí

## 046. [B] Sčítání 2021 - Obyvatelstvo podle desetiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                                    sldb2021_vek10_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle desetiletých...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle desetiletých věkový...
selected_file                          ds_sldb2021_vek10_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     242064
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\046_sldb2021_vek10_pohlavi_Scitani_2...
error                                                           None

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,pohlavi_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Želechovice nad Dřevnicí
1,947084833,909,3162,NaN,NaN,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,muž,Želechovice nad Dřevnicí
2,947119976,908,3162,NaN,NaN,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,žena,Želechovice nad Dřevnicí
3,964971449,162,3162,1035.0,1.100000e+09,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 9 let,NaN,Želechovice nad Dřevnicí
4,964954808,94,3162,1035.0,1.100000e+09,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 9 let,muž,Želechovice nad Dřevnicí

## 047. [B] Sčítání 2021 - Obyvatelstvo podle druhu registrovaného pobytu a pohlaví

                                                             hodnota
dataset_id                             sldb2021_druhregpobyt_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle druhu regist...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle druhu registrovanéh...
selected_file                   ds_sldb2021_druhregpobyt_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      36900
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\047_sldb2021_druhregpobyt_pohlavi_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,druh_regpobytu_cis,druh_regpobytu_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,druh_regpobytu_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1016844711,1794,3162,3260,59,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,Trvalý pobyt občana ČR,NaN,Želechovice nad Dřevnicí,obec
1,1016862576,11,3162,3260,60,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,Trvalý pobyt cizince (bez rozlišení státu),NaN,Želechovice nad Dřevnicí,obec
2,1016844712,8,3162,3260,61,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,Dlouhodobý pobyt cizince,NaN,Želechovice nad Dřevnicí,obec
3,1016844713,4,3162,5616,88,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,Bez registrovaného pobytu,NaN,Želechovice nad Dřevnicí,obec
4,1016857945,0,3162,5768,9,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,Nezjištěno,NaN,Želechovice nad Dřevnicí,obec

## 048. [B] Sčítání 2021 - Obyvatelstvo podle jednotek věku a pohlaví

                                                             hodnota
dataset_id                                     sldb2021_vek1_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle jednotek věk...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle jednotek věku a poh...
selected_file                           ds_sldb2021_vek1_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     589968
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\048_sldb2021_vek1_pohlavi_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,pohlavi_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Želechovice nad Dřevnicí
1,947084833,909,3162,NaN,NaN,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,muž,Želechovice nad Dřevnicí
2,947119976,908,3162,NaN,NaN,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,žena,Želechovice nad Dřevnicí
3,971997841,18,3162,1035.0,1.000000e+09,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 let,NaN,Želechovice nad Dřevnicí
4,971969567,11,3162,1035.0,1.000000e+09,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 let,muž,Želechovice nad Dřevnicí

## 049. [B] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka (1 mateřský jazyk)

                                                             hodnota
dataset_id                                           sldb2021_jazyk1
dataset_title      Sčítání 2021 - Obyvatelstvo podle mateřského j...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle mateřského jazyka (...
selected_file                                 ds_sldb2021_jazyk1.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     101872
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\049_sldb2021_jazyk1_Scitani_2021_-_O...
error                                                           None

,idhod,hodnota,ukaz_kod,jazyk_cis,jazyk_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,jazyk_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Želechovice nad Dřevnicí
1,967371033,1662,3162,5750.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český jazyk,Želechovice nad Dřevnicí
2,967371034,16,3162,5750.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Slovenský jazyk,Želechovice nad Dřevnicí
3,967415048,2,3162,5750.0,3.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Anglický jazyk,Želechovice nad Dřevnicí
4,967371735,0,3162,5750.0,5.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Německý jazyk,Želechovice nad Dřevnicí

## 050. [B] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka (1 nebo 2 mateřské jazyky)

                                                             hodnota
dataset_id                                            sldb2021_jazyk
dataset_title      Sčítání 2021 - Obyvatelstvo podle mateřského j...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title          {'cs': 'Obyvatelstvo podle mateřského jazyka'}
selected_file                                  ds_sldb2021_jazyk.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     101849
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\050_sldb2021_jazyk_Scitani_2021_-_Ob...
error                                                           None

,idhod,hodnota,ukaz_kod,jazyk_cis,jazyk_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,jazyk_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Želechovice nad Dřevnicí
1,968161229,1696,3162,3295.0,201.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český celkem,Želechovice nad Dřevnicí
2,968169634,34,3162,3295.0,202.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Slovenský celkem,Želechovice nad Dřevnicí
3,968214176,0,3162,3295.0,203.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Romský celkem,Želechovice nad Dřevnicí
4,968158867,0,3162,3295.0,204.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Polský celkem,Želechovice nad Dřevnicí

## 051. [B] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka a pohlaví (1 mateřský jazyk)

                                                             hodnota
dataset_id                                   sldb2021_jazyk1_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle mateřského j...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle mateřského jazyka a...
selected_file                         ds_sldb2021_jazyk1_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       2691
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\051_sldb2021_jazyk1_pohlavi_Scitani_...
error                                                           None

,idhod,hodnota,ukaz_kod,jazyk_cis,jazyk_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,jazyk_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Česká republika
1,967320076,4365187,3162,5750.0,1.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český jazyk,muž,Česká republika
2,967320310,4631288,3162,5750.0,1.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český jazyk,žena,Česká republika
3,967320315,68822,3162,5750.0,2.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Slovenský jazyk,muž,Česká republika
4,967320316,81916,3162,5750.0,2.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Slovenský jazyk,žena,Česká republika

## 052. [B] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka a pohlaví (1 nebo 2 mateřské jazyky)

                                                             hodnota
dataset_id                                    sldb2021_jazyk_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle mateřského j...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle mateřského jazyka a...
selected_file                          ds_sldb2021_jazyk_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       2645
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\052_sldb2021_jazyk_pohlavi_Scitani_2...
error                                                           None

,idhod,hodnota,ukaz_kod,jazyk_cis,jazyk_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,jazyk_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Česká republika
1,968137568,4476299,3162,3295.0,201.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český celkem,muž,Česká republika
2,968137569,4737688,3162,3295.0,201.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český celkem,žena,Česká republika
3,968137570,105621,3162,3295.0,202.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Slovenský celkem,muž,Česká republika
4,968137571,119625,3162,3295.0,202.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Slovenský celkem,žena,Česká republika

## 053. [B] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka, věku a pohlaví (1 mateřský jazyk)

                                                             hodnota
dataset_id                               sldb2021_jazyk1_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle mateřského j...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle mateřského jazyka, ...
selected_file                     ds_sldb2021_jazyk1_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      36675
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\053_sldb2021_jazyk1_vek_pohlavi_Scit...
error                                                           None

,idhod,hodnota,ukaz_kod,jazyk_cis,jazyk_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,jazyk_txt,vek_txt,pohlavi_txt,uzemi_txt
0,987347049,85782,3162,5750,1,1035,1000000000,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český,0 let,NaN,Česká republika
1,987335928,43886,3162,5750,1,1035,1000000000,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český,0 let,muž,Česká republika
2,987336800,41896,3162,5750,1,1035,1000000000,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český,0 let,žena,Česká republika
3,987339037,89054,3162,5750,1,1035,1000010001,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český,1 rok,NaN,Česká republika
4,987338541,45559,3162,5750,1,1035,1000010001,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Český,1 rok,muž,Česká republika

## 054. [B] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka, věku a pohlaví (1 nebo 2 mateřské jazyky)

                                                             hodnota
dataset_id                                sldb2021_jazyk_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle mateřského j...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle mateřského jazyka, ...
selected_file                      ds_sldb2021_jazyk_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      34986
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\054_sldb2021_jazyk_vek_pohlavi_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,jazyk_cis,jazyk_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,jazyk_txt,vek_txt,pohlavi_txt,uzemi_txt
0,987395721,89108,3162,3295,201,1035,1000000000,NaN,NaN,97,19,2021,2021-03-26,PoДЌet obyvatel s obvyklГЅm pobytem,ДЊeskГЅ celkem,0 let,NaN,ДЊeskГЎ republika
1,987395198,45612,3162,3295,201,1035,1000000000,102.0,1.0,97,19,2021,2021-03-26,PoДЌet obyvatel s obvyklГЅm pobytem,ДЊeskГЅ celkem,0 let,muЕѕ,ДЊeskГЎ republika
2,987395199,43496,3162,3295,201,1035,1000000000,102.0,2.0,97,19,2021,2021-03-26,PoДЌet obyvatel s obvyklГЅm pobytem,ДЊeskГЅ celkem,0 let,Еѕena,ДЊeskГЎ republika
3,987395722,92636,3162,3295,201,1035,1000010001,NaN,NaN,97,19,2021,2021-03-26,PoДЌet obyvatel s obvyklГЅm pobytem,ДЊeskГЅ celkem,1 rok,NaN,ДЊeskГЎ republika
4,987396080,47412,3162,3295,201,1035,1000010001,102.0,1.0,97,19,2021,2021-03-26,PoДЌet obyvatel s obvyklГЅm pobytem,ДЊeskГЅ celkem,1 rok,muЕѕ,ДЊeskГЎ republika

## 055. [B] Sčítání 2021 - Obyvatelstvo podle místa registrovaného pobytu a pohlaví

                                                             hodnota
dataset_id                            sldb2021_mistoregpobyt_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle místa regist...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle místa registrovanéh...
selected_file                  ds_sldb2021_mistoregpobyt_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      36900
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\055_sldb2021_mistoregpobyt_pohlavi_S...
error                                                           None

,idhod,hodnota,ukaz_kod,misto_regpobytu_cis,misto_regpobytu_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,misto_regpobytu_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1016806271,1670,3162,3320,2,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,Ve stejné obci,NaN,Želechovice nad Dřevnicí,obec
1,1016806272,113,3162,3320,3,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,V jiné obci stejného okresu,NaN,Želechovice nad Dřevnicí,obec
2,1016806273,18,3162,3320,4,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,V jiném okrese kraje,NaN,Želechovice nad Dřevnicí,obec
3,1016825361,12,3162,3342,50,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,V jiném kraji oblasti a v jiné oblasti,NaN,Želechovice nad Dřevnicí,obec
4,1016806274,4,3162,5616,88,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obyklým pobytem,Bez registrovaného pobytu,NaN,Želechovice nad Dřevnicí,obec

## 056. [B] Sčítání 2021 - Obyvatelstvo podle náboženské víry

                                                             hodnota
dataset_id                                             sldb2021_vira
dataset_title      Sčítání 2021 - Obyvatelstvo podle náboženské víry
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title            {'cs': 'Obyvatelstvo podle náboženské víry'}
selected_file                                   ds_sldb2021_vira.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     531196
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\056_sldb2021_vira_Scitani_2021_-_Oby...
error                                                           None

,idhod,hodnota,ukaz_kod,vira_cis,vira_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vira_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Želechovice nad Dřevnicí
1,946276585,567,3162,3078.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,Želechovice nad Dřevnicí
2,946276732,0,3162,3078.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Apoštolská církev,Želechovice nad Dřevnicí
3,946746866,1,3162,3078.0,3.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bratrská jednota baptistů,Želechovice nad Dřevnicí
4,946545251,0,3162,3078.0,4.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Církev adventistů sedmého dne,Želechovice nad Dřevnicí

## 057. [B] Sčítání 2021 - Obyvatelstvo podle náboženské víry a pohlaví

                                                             hodnota
dataset_id                                     sldb2021_vira_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle náboženské v...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle náboženské víry a p...
selected_file                           ds_sldb2021_vira_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       3611
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\057_sldb2021_vira_pohlavi_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,vira_cis,vira_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vira_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Česká republika
1,946963121,2548297,3162,3078.0,1.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,muž,Česká republika
2,946963122,2478844,3162,3078.0,1.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,žena,Česká republika
3,946963833,2287,3162,3078.0,2.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Apoštolská církev,muž,Česká republika
4,946963834,2671,3162,3078.0,2.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Apoštolská církev,žena,Česká republika

## 058. [B] Sčítání 2021 - Obyvatelstvo podle náboženské víry, věku a pohlaví

                                                             hodnota
dataset_id                                 sldb2021_vira_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle náboženské v...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle náboženské víry, vě...
selected_file                       ds_sldb2021_vira_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      58890
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\058_sldb2021_vira_vek_pohlavi_Scitan...
error                                                           None

,idhod,hodnota,ukaz_kod,vira_cis,vira_kod,vira_cleneni,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vira_txt,vek_txt,pohlavi_txt,uzemi_txt
0,989095533,51397,3162,3078,1,1,1035,1000000000,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,0 let,NaN,Česká republika
1,989113507,26279,3162,3078,1,1,1035,1000000000,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,0 let,muž,Česká republika
2,989113508,25118,3162,3078,1,1,1035,1000000000,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,0 let,žena,Česká republika
3,989096570,52693,3162,3078,1,1,1035,1000010001,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,1 rok,NaN,Česká republika
4,989112602,26922,3162,3078,1,1,1035,1000010001,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez náboženské víry,1 rok,muž,Česká republika

## 059. [B] Sčítání 2021 - Obyvatelstvo podle národnosti

                                                             hodnota
dataset_id                                        sldb2021_narodnost
dataset_title           Sčítání 2021 - Obyvatelstvo podle národnosti
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle národnosti (osoby s...
selected_file                              ds_sldb2021_narodnost.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     537920
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\059_sldb2021_narodnost_Scitani_2021_...
error                                                           None

,idhod,hodnota,ukaz_kod,narodnost_cis,narodnost_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,narodnost_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Želechovice nad Dřevnicí
1,959308279,0,3162,3267.0,201.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Afghánská celkem,Želechovice nad Dřevnicí
2,959201672,0,3162,3267.0,202.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Albánská celkem,Želechovice nad Dřevnicí
3,959307772,0,3162,3267.0,203.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Americká (USA) celkem,Želechovice nad Dřevnicí
4,959455676,0,3162,3267.0,204.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Anglická celkem,Želechovice nad Dřevnicí

## 060. [B] Sčítání 2021 - Obyvatelstvo podle národnosti, věku a pohlaví

                                                             hodnota
dataset_id                            sldb2021_narodnost_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle národnosti, ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle národnosti, věku a ...
selected_file                  ds_sldb2021_narodnost_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      97263
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\060_sldb2021_narodnost_vek_pohlavi_S...
error                                                           None

,idhod,hodnota,ukaz_kod,narodnost_cis,narodnost_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,narodnost_txt,vek_txt,pohlavi_txt,uzemi_txt
0,987569350,1,3162,3267,201,1035,1000000000,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,afghánská celkem,0 let,NaN,Česká republika
1,987580198,1,3162,3267,201,1035,1000000000,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,afghánská celkem,0 let,muž,Česká republika
2,987592433,0,3162,3267,201,1035,1000000000,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,afghánská celkem,0 let,žena,Česká republika
3,987630662,2,3162,3267,201,1035,1000010001,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,afghánská celkem,1 rok,NaN,Česká republika
4,987616862,1,3162,3267,201,1035,1000010001,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,afghánská celkem,1 rok,muž,Česká republika

## 061. [B] Sčítání 2021 - Obyvatelstvo podle pohlaví

                                                             hodnota
dataset_id                                          sldb2021_pohlavi
dataset_title              Sčítání 2021 - Obyvatelstvo podle pohlaví
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                    {'cs': 'Obyvatelstvo podle pohlaví'}
selected_file                                ds_sldb2021_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      20172
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\061_sldb2021_pohlavi_Scitani_2021_-_...
error                                                           None

,idhod,hodnota,ukaz_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,pohlavi_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Želechovice nad Dřevnicí
1,947084833,909,3162,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,muž,Želechovice nad Dřevnicí
2,947119976,908,3162,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,žena,Želechovice nad Dřevnicí
3,947108884,1195,3162,NaN,NaN,43,500020,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Petrov nad Desnou
4,947108254,592,3162,102.0,1.0,43,500020,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,muž,Petrov nad Desnou

## 062. [B] Sčítání 2021 - Obyvatelstvo podle pětiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                                     sldb2021_vek5_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle pětiletých v...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle pětiletých věkových...
selected_file                           ds_sldb2021_vek5_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     443784
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\062_sldb2021_vek5_pohlavi_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,pohlavi_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Želechovice nad Dřevnicí
1,947084833,909,3162,NaN,NaN,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,muž,Želechovice nad Dřevnicí
2,947119976,908,3162,NaN,NaN,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,žena,Želechovice nad Dřevnicí
3,964961283,93,3162,1035.0,1.100000e+09,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 4 roky,NaN,Želechovice nad Dřevnicí
4,964734134,60,3162,1035.0,1.100000e+09,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 4 roky,muž,Želechovice nad Dřevnicí

## 063. [B] Sčítání 2021 - Obyvatelstvo podle rodinného stavu

                                                             hodnota
dataset_id                                             sldb2021_stav
dataset_title      Sčítání 2021 - Obyvatelstvo podle rodinného stavu
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title            {'cs': 'Obyvatelstvo podle rodinného stavu'}
selected_file                                   ds_sldb2021_stav.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      60516
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                          rodinná struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\063_sldb2021_stav_Scitani_2021_-_Oby...
error                                                           None

,idhod,hodnota,ukaz_kod,stav_cis,stav_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,stav_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Želechovice nad Dřevnicí
1,947122957,671,3162,5788.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,Želechovice nad Dřevnicí
2,947076021,823,3162,5788.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Ženatý/vdaná,Želechovice nad Dřevnicí
3,947111359,171,3162,5788.0,3.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Rozvedený/rozvedená,Želechovice nad Dřevnicí
4,947076022,142,3162,5788.0,4.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Vdovec/vdova,Želechovice nad Dřevnicí

## 064. [B] Sčítání 2021 - Obyvatelstvo podle rodinného stavu a pohlaví

                                                             hodnota
dataset_id                                     sldb2021_stav_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle rodinného st...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle rodinného stavu a p...
selected_file                           ds_sldb2021_stav_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                        391
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                          rodinná struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\064_sldb2021_stav_pohlavi_Scitani_20...
error                                                           None

,idhod,hodnota,ukaz_kod,stav_cis,stav_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,stav_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Česká republika
1,936990231,2477037,3162,5788.0,1.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,muž,Česká republika
2,936990255,2031554,3162,5788.0,1.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,žena,Česká republika
3,936990230,2009738,3162,5788.0,2.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Ženatý/vdaná,muž,Česká republika
4,936990254,1997604,3162,5788.0,2.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Ženatý/vdaná,žena,Česká republika

## 065. [B] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, desetiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                               sldb2021_stav_vek10_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle rodinného st...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle rodinného stavu, de...
selected_file                     ds_sldb2021_stav_vek10_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       6072
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                          rodinná struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\065_sldb2021_stav_vek10_pohlavi_Scit...
error                                                           None

,idhod,hodnota,ukaz_kod,stav_cis,stav_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,stav_txt,vek_txt,pohlavi_txt,uzemi_txt
0,980446664,1110656,3162,5788,1,1035,1100000009,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 - 9 let,NaN,Česká republika
1,980383293,568961,3162,5788,1,1035,1100000009,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 - 9 let,muž,Česká republika
2,980445569,541695,3162,5788,1,1035,1100000009,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 - 9 let,žena,Česká republika
3,980385529,1069246,3162,5788,1,1035,1300100019,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,10 - 19 let,NaN,Česká republika
4,980447123,548129,3162,5788,1,1035,1300100019,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,10 - 19 let,muž,Česká republika

## 066. [B] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, jednoletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                                sldb2021_stav_vek1_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle rodinného st...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle rodinného stavu, je...
selected_file                      ds_sldb2021_stav_vek1_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      55752
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                          rodinná struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\066_sldb2021_stav_vek1_pohlavi_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,stav_cis,stav_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,stav_txt,vek_txt,pohlavi_txt,uzemi_txt
0,980415301,109186,3162,5788,1,1035,1000000000,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 let,NaN,Česká republika
1,980436823,55778,3162,5788,1,1035,1000000000,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 let,muž,Česká republika
2,980426747,53408,3162,5788,1,1035,1000000000,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 let,žena,Česká republika
3,980435653,110951,3162,5788,1,1035,1000010001,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,1 rok,NaN,Česká republika
4,980415090,56820,3162,5788,1,1035,1000010001,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,1 rok,muž,Česká republika

## 067. [B] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, pětiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                                sldb2021_stav_vek5_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle rodinného st...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle rodinného stavu, pě...
selected_file                      ds_sldb2021_stav_vek5_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      11592
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                          rodinná struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\067_sldb2021_stav_vek5_pohlavi_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,stav_cis,stav_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,stav_txt,vek_txt,pohlavi_txt,uzemi_txt
0,980395735,560632,3162,5788,1,1035,1100000004,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 - 4 roky,NaN,Česká republika
1,980405143,286889,3162,5788,1,1035,1100000004,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 - 4 roky,muž,Česká republika
2,980383501,273743,3162,5788,1,1035,1100000004,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,0 - 4 roky,žena,Česká republika
3,980426005,550024,3162,5788,1,1035,1300050009,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,5 - 9 let,NaN,Česká republika
4,980383298,282072,3162,5788,1,1035,1300050009,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,5 - 9 let,muž,Česká republika

## 068. [B] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, velikostních skupin obcí a pohlaví

                                                             hodnota
dataset_id                        sldb2021_stav_velikostobce_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle rodinného st...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle rodinného stavu, ve...
selected_file              ds_sldb2021_stav_velikostobce_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       5543
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                          rodinná struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\068_sldb2021_stav_velikostobce_pohla...
error                                                           None

,idhod,hodnota,ukaz_kod,stav_cis,stav_kod,velikostobce_cis,velikostobce_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,stav_txt,velikostobce_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,NaN,Česká republika
1,980415191,71690,3162,5788.0,1.0,1234.0,98.0,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,do 199 obyvatel,NaN,Česká republika
2,980436915,41011,3162,5788.0,1.0,1234.0,98.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,do 199 obyvatel,muž,Česká republika
3,980447096,30679,3162,5788.0,1.0,1234.0,98.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,do 199 obyvatel,žena,Česká republika
4,980383452,268817,3162,5788.0,1.0,1234.0,99.0,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Svobodný/svobodná,200 - 499 obyvatel,NaN,Česká republika

## 069. [B] Sčítání 2021 - Obyvatelstvo podle státního občanství

                                                             hodnota
dataset_id                                        sldb2021_obcanstvi
dataset_title      Sčítání 2021 - Obyvatelstvo podle státního obč...
status                                              ERROR_SELECTIONS
source_kind                                                     None
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv                                                     None
error              LKOD/VDB selhalo: Response ended prematurely |...

## 070. [B] Sčítání 2021 - Obyvatelstvo podle státního občanství a pohlaví

                                                             hodnota
dataset_id                                sldb2021_obcanstvi_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle státního obč...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle státního občanství ...
selected_file                      ds_sldb2021_obcanstvi_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       8303
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\070_sldb2021_obcanstvi_pohlavi_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,obcanstvi_cis,obcanstvi_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,obcanstvi_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Česká republika
1,957681860,21893,3162,3181.0,5.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Dvojí občanství,muž,Česká republika
2,957681863,23483,3162,3181.0,5.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Dvojí občanství,žena,Česká republika
3,954943279,145,3162,3228.0,4.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Islámská republika Afghánistán,muž,Česká republika
4,954943753,104,3162,3228.0,4.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Islámská republika Afghánistán,žena,Česká republika

## 071. [B] Sčítání 2021 - Obyvatelstvo podle státního občanství, věku a pohlaví

                                                             hodnota
dataset_id                                sldb2021_obcan_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle státního obč...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle státního občanství,...
selected_file                      ds_sldb2021_obcan_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     206058
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\071_sldb2021_obcan_vek_pohlavi_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,obcan_cis,obcan_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,obcan_txt,vek_txt,pohlavi_txt,uzemi_txt
0,1009172017,455,3162,3228,9999,1035,1000000000,102,1,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Nezjištěno,0 let,muž,Česká republika
1,1008947722,486,3162,3228,9999,1035,1000000000,102,2,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Nezjištěno,0 let,žena,Česká republika
2,1009025193,260,3162,3228,9999,1035,1000010001,102,1,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Nezjištěno,1 rok,muž,Česká republika
3,1008654019,236,3162,3228,9999,1035,1000010001,102,2,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Nezjištěno,1 rok,žena,Česká republika
4,1008951351,182,3162,3228,9999,1035,1000020002,102,1,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Nezjištěno,2 roky,muž,Česká republika

## 072. [B] Sčítání 2021 - Obyvatelstvo podle velikostních skupin obcí a pohlaví

                                                             hodnota
dataset_id                             sldb2021_velikostobce_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle velikostních...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle velikostních skupin...
selected_file                   ds_sldb2021_velikostobce_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                        713
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\072_sldb2021_velikostobce_pohlavi_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,velikostobce_cis,velikostobce_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,velikostobce_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Česká republika
1,978399248,178213,3162,1234.0,98.0,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,do 199 obyvatel,NaN,Česká republika
2,978179816,91305,3162,1234.0,98.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,do 199 obyvatel,muž,Česká republika
3,978070391,86908,3162,1234.0,98.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,do 199 obyvatel,žena,Česká republika
4,978124969,654469,3162,1234.0,99.0,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,200 - 499 obyvatel,NaN,Česká republika

## 073. [B] Sčítání 2021 - Obyvatelstvo podle věkových skupin

                                                             hodnota
dataset_id                                              sldb2021_vek
dataset_title      Sčítání 2021 - Obyvatelstvo podle věkových skupin
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle věkových skupin (zá...
selected_file                                    ds_sldb2021_vek.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      26896
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\073_sldb2021_vek_Scitani_2021_-_Obyv...
error                                                           None

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,uzemi_txt
0,947108883,1817,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Želechovice nad Dřevnicí
1,947149795,240,3162,1035.0,1.100000e+09,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 14 let,Želechovice nad Dřevnicí
2,947091150,1158,3162,1035.0,1.300150e+09,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,15 - 64 let,Želechovice nad Dřevnicí
3,947138048,419,3162,1035.0,1.200660e+09,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,65 a více let,Želechovice nad Dřevnicí
4,947108884,1195,3162,NaN,NaN,43,500020,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,Petrov nad Desnou

## 074. [B] Sčítání 2021 - Obyvatelstvo podle věkových skupin a pohlaví

                                                             hodnota
dataset_id                                      sldb2021_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle věkových sku...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle věkových skupin a p...
selected_file                            ds_sldb2021_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                        161
column_count                                                      15
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\074_sldb2021_vek_pohlavi_Scitani_202...
error                                                           None

,idhod,hodnota,ukaz_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vek_txt,pohlavi_txt,uzemi_txt
0,947072940,10524167,3162,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,NaN,NaN,Česká republika
1,936989583,866322,3162,1035.0,1.100000e+09,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 14 let,muž,Česká republika
2,936989586,825438,3162,1035.0,1.100000e+09,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,0 - 14 let,žena,Česká republika
3,936989584,903375,3162,1035.0,1.200660e+09,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,65 a více let,muž,Česká republika
4,936989587,1244673,3162,1035.0,1.200660e+09,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,65 a více let,žena,Česká republika

## 075. [B] Sčítání 2021 - Obyvatelstvo podle způsobu bydlení a pohlaví

                                                             hodnota
dataset_id                                  sldb2021_bydleni_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle způsobu bydl...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle způsobu bydlení a p...
selected_file                        ds_sldb2021_bydleni_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     100860
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\075_sldb2021_bydleni_pohlavi_Scitani...
error                                                           None

,idhod,hodnota,ukaz_kod,bydleni_cis,bydleni_kod,bydleni_cleneni,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,bydleni_txt,pohlavi_txt,uzemi_txt
0,989167155,1817,3162,3335,56,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,NaN,Želechovice nad Dřevnicí
1,989187098,909,3162,3335,56,1,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,muž,Želechovice nad Dřevnicí
2,989169784,908,3162,3335,56,1,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,žena,Želechovice nad Dřevnicí
3,989148017,0,3162,3321,7,1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bezdomovci,NaN,Želechovice nad Dřevnicí
4,989247974,0,3162,3321,7,1,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bezdomovci,muž,Želechovice nad Dřevnicí

## 076. [B] Sčítání 2021 - Obyvatelstvo podle způsobu bydlení, velikostních skupin obcí a pohlaví

                                                             hodnota
dataset_id                     sldb2021_bydleni_velikostobce_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle způsobu bydl...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle způsobu bydlení, ve...
selected_file           ds_sldb2021_bydleni_velikostobce_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       3450
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\076_sldb2021_bydleni_velikostobce_po...
error                                                           None

,idhod,hodnota,ukaz_kod,bydleni_cis,bydleni_kod,bydleni_cleneni,velikostobce_cis,velikostobce_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,bydleni_txt,velikostobce_txt,pohlavi_txt,uzemi_txt
0,989231321,178204,3162,3335,56,1,1234,98,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,do 199 obyvatel,NaN,Česká republika
1,989232817,91298,3162,3335,56,1,1234,98,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,do 199 obyvatel,muž,Česká republika
2,989250187,86906,3162,3335,56,1,1234,98,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,do 199 obyvatel,žena,Česká republika
3,989248848,654432,3162,3335,56,1,1234,99,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,200 - 499 obyvatel,NaN,Česká republika
4,989215560,332373,3162,3335,56,1,1234,99,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,200 - 499 obyvatel,muž,Česká republika

## 077. [B] Sčítání 2021 - Obyvatelstvo podle způsobu bydlení, věku a pohlaví

                                                             hodnota
dataset_id                              sldb2021_bydleni_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle způsobu bydl...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle způsobu bydlení, vě...
selected_file                    ds_sldb2021_bydleni_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      34845
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\077_sldb2021_bydleni_vek_pohlavi_Sci...
error                                                           None

,idhod,hodnota,ukaz_kod,bydleni_cis,bydleni_kod,bydleni_cleneni,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,bydleni_txt,vek_txt,pohlavi_txt,uzemi_txt
0,989214475,109185,3162,3335,56,1,1035,1000000000,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,0 let,NaN,Česká republika
1,989145591,55778,3162,3335,56,1,1035,1000000000,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,0 let,muž,Česká republika
2,989214804,53407,3162,3335,56,1,1035,1000000000,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,0 let,žena,Česká republika
3,989179221,110950,3162,3335,56,1,1035,1000010001,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,1 rok,NaN,Česká republika
4,989127848,56820,3162,3335,56,1,1035,1000010001,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Obyvatelstvo podle způsobu bydlení celkem (kro...,1 rok,muž,Česká republika

## 078. [B] Sčítání 2021 - Obyvatelstvo s registrovaným pobytem podle pohlaví

                                                             hodnota
dataset_id                                 sldb2021_regpobyt_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo s registrovaným po...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo s registrovaným pobytem p...
selected_file                       ds_sldb2021_regpobyt_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     111143
column_count                                                      13
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\078_sldb2021_regpobyt_pohlavi_Scitan...
error                                                           None

,idhod,hodnota,ukaz_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1016738842,842,2406,NaN,NaN,42,19,2021,2021-03-26,Počet obyvatel s registrovaným pobytem,NaN,Abertamy,část obce
1,1016795275,50,2406,NaN,NaN,42,27,2021,2021-03-26,Počet obyvatel s registrovaným pobytem,NaN,Hřebečná,část obce
2,1016792454,984,2406,NaN,NaN,42,35,2021,2021-03-26,Počet obyvatel s registrovaným pobytem,NaN,Adamov,část obce
3,1016741551,132,2406,NaN,NaN,42,51,2021,2021-03-26,Počet obyvatel s registrovaným pobytem,NaN,Dolní Adršpach,část obce
4,1016766939,353,2406,NaN,NaN,42,60,2021,2021-03-26,Počet obyvatel s registrovaným pobytem,NaN,Horní Adršpach,část obce

## 079. [B] Sčítání 2021 - Plodnost žen

                                                             hodnota
dataset_id                                         sldb2021_plodnost
dataset_title                            Sčítání 2021 - Plodnost žen
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                  {'cs': 'Plodnost žen'}
selected_file                               ds_sldb2021_plodnost.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      53792
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                                            plodnost
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\079_sldb2021_plodnost_Scitani_2021_-...
error                                                           None

,idhod,hodnota,ukaz_kod,pocetdeti_cis,pocetdeti_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,pocetdeti_txt,uzemi_txt
0,975026246,795,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet žen ve věku 15 a více let,NaN,Želechovice nad Dřevnicí
1,971890990,155,3162,7600.0,0.0,43,500011,2021,2021-03-26,Počet žen ve věku 15 a více let,0.0,Želechovice nad Dřevnicí
2,971890991,114,3162,7600.0,1.0,43,500011,2021,2021-03-26,Počet žen ve věku 15 a více let,1.0,Želechovice nad Dřevnicí
3,971890989,388,3162,7600.0,2.0,43,500011,2021,2021-03-26,Počet žen ve věku 15 a více let,2.0,Želechovice nad Dřevnicí
4,971893829,109,3162,7600.0,3.0,43,500011,2021,2021-03-26,Počet žen ve věku 15 a více let,3.0,Želechovice nad Dřevnicí

## 080. [B] Sčítání 2021 - Průměrný věk obyvatel podle pohlaví

                                                             hodnota
dataset_id                                  sldb2021_prumvek_pohlavi
dataset_title      Sčítání 2021 - Průměrný věk obyvatel podle poh...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title           {'cs': 'Průměrný věk obyvatel podle pohlaví'}
selected_file                        ds_sldb2021_prumvek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      20172
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\080_sldb2021_prumvek_pohlavi_Scitani...
error                                                           None

,idhod,hodnota,ukaz_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,pohlavi_txt,uzemi_txt
0,957097509,45.4,2407,NaN,NaN,43,500011,2021,2021-03-26,Průměrný věk obyvatel (roky),NaN,Želechovice nad Dřevnicí
1,957094144,43.4,2407,102.0,1.0,43,500011,2021,2021-03-26,Průměrný věk obyvatel (roky),muž,Želechovice nad Dřevnicí
2,957082718,47.4,2407,102.0,2.0,43,500011,2021,2021-03-26,Průměrný věk obyvatel (roky),žena,Želechovice nad Dřevnicí
3,957097510,44.7,2407,NaN,NaN,43,500020,2021,2021-03-26,Průměrný věk obyvatel (roky),NaN,Petrov nad Desnou
4,957089067,43.7,2407,102.0,1.0,43,500020,2021,2021-03-26,Průměrný věk obyvatel (roky),muž,Petrov nad Desnou

## 081. [B] Výběr údajů ze SLDB 2011 za obyvatelstvo

                                                             hodnota
dataset_id                                                SLDB-VYBER
dataset_title               Výběr údajů ze SLDB 2011 za obyvatelstvo
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                  {'cs': 'Obyvatelstvo'}
selected_file                                  SLDB_OBYVATELSTVO.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                       6712
column_count                                                     175
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                       desetileté / census [R/P10Y]
start_catalog                                             2011-03-26
end_catalog                                               2011-03-26
hlavni_skupina                                 Demografie a populace
detailni_skupina                             základní populační stav
uzemni_uroven                       více úrovní (ČR–kraj–okres–obec)
zdroj_typ                             SLDB 2011 / historické sčítání
page               https://csu.gov.cz/docs/107516/55859845-7a0c-3...
preview_csv        heads_csv\081_SLDB-VYBER_Vyber_udaju_ze_SLDB_2...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,typuz_naz,nazev,uzcis,uzkod,vse1111,vse1112,vse1113,vse1121,vse1122,vse1123,...,vse6193,vse61101,vse61102,vse61103,vse61111,vse61112,vse61113,vse61121,vse61122,vse61123
0,kraj,Hlavní město Praha,100,3018,1268796.0,613738.0,655058.0,535604.0,285543.0,250061.0,...,294698.0,231135.0,83326.0,147809.0,147461.0,73622.0,73839.0,123182.0,72214.0,50968.0
1,kraj,Středočeský kraj,100,3026,1289211.0,637252.0,651959.0,507375.0,280621.0,226754.0,...,334656.0,266140.0,102500.0,163640.0,174154.0,87125.0,87029.0,66595.0,40072.0,26523.0
2,kraj,Jihočeský kraj,100,3034,628336.0,308296.0,320040.0,245650.0,135702.0,109948.0,...,169649.0,142858.0,55375.0,87483.0,90905.0,45122.0,45783.0,26619.0,15605.0,11014.0
3,kraj,Plzeňský kraj,100,3042,570401.0,282137.0,288264.0,222189.0,124170.0,98019.0,...,149000.0,130064.0,51112.0,78952.0,74891.0,37205.0,37686.0,31752.0,19261.0,12491.0
4,kraj,Karlovarský kraj,100,3051,295595.0,145483.0,150112.0,121610.0,67238.0,54372.0,...,74334.0,62774.0,23914.0,38860.0,38270.0,19367.0,18903.0,24405.0,13850.0,10555.0

## 082. [B] Sčítání 2021 - Dojížďka mezi obcemi, včetně denní dojížďky

                                                             hodnota
dataset_id                                    sldb2021_dojizdka_obce
dataset_title      Sčítání 2021 - Dojížďka mezi obcemi, včetně de...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Dojížďka mezi obcemi, včetně denní doj...
selected_file                          ds_sldb2021_dojizdka_obce.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     275699
column_count                                                      17
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                              dojížďka do zaměstnání
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\082_sldb2021_dojizdka_obce_Scitani_2...
error                                                           None

,lokalizace,op_lau1_kod,op_okres,op_orp_kod,op_orp,op_obec_kod,op_obec,doj_lau1_kod,doj_okres,doj_orp_kod,doj_orp,doj_obec_kod,doj_obec,dojizdka_prace,dojizdka_skola,dojizdka_celkova,dojizdka_celkova_denni
0,0_na_adrese_OP,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,141946,96,142042,0
1,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0641,BLANSKO,6202,BOSKOVICE,582018,LYSICE,0,1,1,0
2,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0641,BLANSKO,6202,BOSKOVICE,582409,SUCHÝ,1,0,1,0
3,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0641,BLANSKO,6202,BOSKOVICE,582646,VELKÉ OPATOVICE,1,0,1,0
4,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0642,BRNO-MĚSTO,6203,BRNO,582786,BRNO,482,338,820,0

## 083. [B] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle frekvence vyjížďky

                                                             hodnota
dataset_id               sldb2021_vyjizdka_vsichni_frekvence_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání a ško...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání a školy podl...
selected_file      ds_sldb2021_vyjizdka_vsichni_frekvence_pohlavi...
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      51004
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                           dojížďka do práce a školy
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\083_sldb2021_vyjizdka_vsichni_frekve...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,frekvence_cis,frekvence_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,frekvence_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1099813543,659,2623,3249,58,3073,20,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",5x týdně a častěji,NaN,Želechovice nad Dřevnicí,obec
1,1100116197,101,2623,3249,58,3073,21,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",1x - 4x týdně,NaN,Želechovice nad Dřevnicí,obec
2,1099987893,4,2623,3249,58,3073,22,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti","pravidelně, ale méně než 1x týdně",NaN,Želechovice nad Dřevnicí,obec
3,1099726240,36,2623,3249,58,3073,23,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",nepravidelně,NaN,Želechovice nad Dřevnicí,obec
4,1100116198,5,2623,3249,58,3073,24,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",z jiného místa než z obvyklého bydliště,NaN,Želechovice nad Dřevnicí,obec

## 084. [B] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle hlavního dopravního prostředku

                                                             hodnota
dataset_id              sldb2021_vyjizdka_vsichni_prostredek_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání a ško...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání a školy podl...
selected_file      ds_sldb2021_vyjizdka_vsichni_prostredek_pohlav...
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      80524
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                    dopravní prostředek při dojížďce
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\084_sldb2021_vyjizdka_vsichni_prostr...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,prostredek_cis,prostredek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,prostredek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1099335760,903,2623,3249,58,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",NaN,NaN,Želechovice nad Dřevnicí,obec
1,1099718094,101,2623,3249,58,3090.0,1.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Autobus (kromě MHD),NaN,Želechovice nad Dřevnicí,obec
2,1099805321,44,2623,3249,58,3090.0,2.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Vlak,NaN,Želechovice nad Dřevnicí,obec
3,1099805320,78,2623,3249,58,3090.0,3.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Městská hromadná doprava,NaN,Želechovice nad Dřevnicí,obec
4,1099932766,409,2623,3249,58,3090.0,4.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Automobil - řidič,NaN,Želechovice nad Dřevnicí,obec

## 085. [B] Sčítání 2021 - Vyjíždějící do zaměstnání podle frekvence vyjížďky

                                                             hodnota
dataset_id            sldb2021_vyjizdka_pracoviste_frekvence_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání podle...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání podle frekve...
selected_file      ds_sldb2021_vyjizdka_pracoviste_frekvence_pohl...
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      51004
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                              dojížďka do zaměstnání
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\085_sldb2021_vyjizdka_pracoviste_fre...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,frekvence_cis,frekvence_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,frekvence_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1100095272,542,2623,3249,51,3073,20,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,5x týdně a častěji,NaN,Želechovice nad Dřevnicí,obec
1,1099658728,82,2623,3249,51,3073,21,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,1x - 4x týdně,NaN,Želechovice nad Dřevnicí,obec
2,1099658627,3,2623,3249,51,3073,22,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,"pravidelně, ale méně než 1x týdně",NaN,Želechovice nad Dřevnicí,obec
3,1099858559,31,2623,3249,51,3073,23,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,nepravidelně,NaN,Želechovice nad Dřevnicí,obec
4,1099858560,4,2623,3249,51,3073,24,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,z jiného místa než z obvyklého bydliště,NaN,Želechovice nad Dřevnicí,obec

## 086. [B] Sčítání 2021 - Vyjíždějící do zaměstnání podle hlavního dopravního prostředku

                                                             hodnota
dataset_id           sldb2021_vyjizdka_pracoviste_prostredek_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání podle...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání podle hlavní...
selected_file      ds_sldb2021_vyjizdka_pracoviste_prostredek_poh...
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      80524
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                    dopravní prostředek při dojížďce
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\086_sldb2021_vyjizdka_pracoviste_pro...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,prostredek_cis,prostredek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,prostredek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1098784826,699,2623,3249,51,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,NaN,NaN,Želechovice nad Dřevnicí,obec
1,1099850415,53,2623,3249,51,3090.0,1.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Autobus (kromě MHD),NaN,Želechovice nad Dřevnicí,obec
2,1099850307,24,2623,3249,51,3090.0,2.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Vlak,NaN,Želechovice nad Dřevnicí,obec
3,1099756573,51,2623,3249,51,3090.0,3.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Městská hromadná doprava,NaN,Želechovice nad Dřevnicí,obec
4,1099756574,408,2623,3249,51,3090.0,4.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Automobil - řidič,NaN,Želechovice nad Dřevnicí,obec

## 087. [B] Sčítání 2021 - Vyjíždějící do školy podle frekvence vyjížďky

                                                             hodnota
dataset_id                 sldb2021_vyjizdka_skola_frekvence_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do školy podle frek...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do školy podle frekvence v...
selected_file       ds_sldb2021_vyjizdka_skola_frekvence_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      50955
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                                   dojížďka do školy
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\087_sldb2021_vyjizdka_skola_frekvenc...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,frekvence_cis,frekvence_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,frekvence_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1099796904,117,2623,3072,8,3073,20,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",5x týdně a častěji,NaN,Želechovice nad Dřevnicí,obec
1,1099924377,19,2623,3072,8,3073,21,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",1x - 4x týdně,NaN,Želechovice nad Dřevnicí,obec
2,1099924378,1,2623,3072,8,3073,22,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti","pravidelně, ale méně než 1x týdně",NaN,Želechovice nad Dřevnicí,obec
3,1099769128,5,2623,3072,8,3073,23,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",nepravidelně,NaN,Želechovice nad Dřevnicí,obec
4,1099769127,1,2623,3072,8,3073,24,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",z jiného místa než z obvyklého bydliště,NaN,Želechovice nad Dřevnicí,obec

## 088. [B] Sčítání 2021 - Vyjíždějící do školy podle hlavního dopravního prostředku

                                                             hodnota
dataset_id                sldb2021_vyjizdka_skola_prostredek_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do školy podle hlav...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do školy podle hlavního do...
selected_file      ds_sldb2021_vyjizdka_skola_prostredek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      80447
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                    dopravní prostředek při dojížďce
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\088_sldb2021_vyjizdka_skola_prostred...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,prostredek_cis,prostredek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,prostredek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1098535036,204,2623,3072,8,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",NaN,NaN,Želechovice nad Dřevnicí,obec
1,1100091199,48,2623,3072,8,3090.0,1.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Autobus (kromě MHD),NaN,Želechovice nad Dřevnicí,obec
2,1099654563,20,2623,3072,8,3090.0,2.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Vlak,NaN,Želechovice nad Dřevnicí,obec
3,1100016129,27,2623,3072,8,3090.0,3.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Městská hromadná doprava,NaN,Želechovice nad Dřevnicí,obec
4,1100016238,1,2623,3072,8,3090.0,4.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Automobil - řidič,NaN,Želechovice nad Dřevnicí,obec

## 089. [B] Výběr údajů ze SLDB 2011 za vyjížďku

                                                             hodnota
dataset_id                                              sldbvyjizdka
dataset_title                   Výběr údajů ze SLDB 2011 za vyjížďku
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                      {'cs': 'Vyjížďka'}
selected_file                                      SLDB_VYJIZDKA.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                       6712
column_count                                                      14
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                       desetileté / census [R/P10Y]
start_catalog                                             2011-03-26
end_catalog                                               2011-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                              dojížďka do zaměstnání
uzemni_uroven                       více úrovní (ČR–kraj–okres–obec)
zdroj_typ                             SLDB 2011 / historické sčítání
page               https://csu.gov.cz/docs/107516/ea9ce708-a0f1-8...
preview_csv        heads_csv\089_sldbvyjizdka_Vyber_udaju_ze_SLDB...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,typuz_naz,nazev,uzcis,uzkod,vse9111,vse9121,vse9131,vse9141,vse9151,vse9161,vse9171,vse9181,vse9191,vse91101
0,kraj,Hlavní město Praha,100,3018,363057.0,274568.0,250277.0,0.0,0.0,19615.0,4676.0,88489.0,82806.0,5683.0
1,kraj,Středočeský kraj,100,3026,367980.0,271378.0,57680.0,78688.0,25861.0,106645.0,2504.0,96602.0,26416.0,70186.0
2,kraj,Jihočeský kraj,100,3034,172169.0,122918.0,48181.0,48648.0,13561.0,8829.0,3699.0,49251.0,17074.0,32177.0
3,kraj,Plzeňský kraj,100,3042,157987.0,116786.0,47851.0,30368.0,27693.0,7691.0,3183.0,41201.0,17441.0,23760.0
4,kraj,Karlovarský kraj,100,3051,64822.0,47793.0,18276.0,18720.0,5490.0,3331.0,1976.0,17029.0,6191.0,10838.0

## 090. [B] Ekonomické subjekty podle odvětví převažující činnosti za správní obvody Prahy a obcí s rozšířenou působností

                                                             hodnota
dataset_id                                                    140133
dataset_title      Ekonomické subjekty podle odvětví převažující ...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2010-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina       ekonomické subjekty a podnikatelská struktura
uzemni_uroven                                                    ORP
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/a4b3e19f-9153-f...
preview_csv                                                     None
error              LKOD/VDB selhalo: ('Connection broken: Incompl...

## 091. [B] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity a pohlaví

                                                             hodnota
dataset_id                                 sldb2021_aktivita_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle ekonomické a...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle ekonomické aktivity...
selected_file                       ds_sldb2021_aktivita_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     282408
column_count                                                      17
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\091_sldb2021_aktivita_pohlavi_Scitan...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,aktivita_struktura,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,ekonaktiv_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1059667763,997,3162,3249,53,1.0,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,NaN,Želechovice nad Dřevnicí,obec
1,1059748058,555,3162,3249,53,1.0,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,muž,Želechovice nad Dřevnicí,obec
2,1059669618,442,3162,3249,53,1.0,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,žena,Želechovice nad Dřevnicí,obec
3,1059743292,973,3162,3249,51,1.1,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Zaměstnaní,NaN,Želechovice nad Dřevnicí,obec
4,1059711624,542,3162,3249,51,1.1,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Zaměstnaní,muž,Želechovice nad Dřevnicí,obec

## 092. [B] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, desetiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                           sldb2021_aktivita_vek10_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle ekonomické a...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv                                                     None
error              LKOD/VDB selhalo: Response ended prematurely |...

## 093. [B] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, jednoletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                            sldb2021_aktivita_vek1_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle ekonomické a...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle ekonomické aktivity...
selected_file                  ds_sldb2021_aktivita_vek1_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      96531
column_count                                                      20
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\093_sldb2021_aktivita_vek1_pohlavi_S...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,aktivita_struktura,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,vek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1080013679,0,3162,3249,53,1,1035,1000000000,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 let,NaN,Česká republika,stát
1,1079741836,0,3162,3249,53,1,1035,1000000000,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 let,muž,Česká republika,stát
2,1080642190,0,3162,3249,53,1,1035,1000000000,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 let,žena,Česká republika,stát
3,1080159644,0,3162,3249,53,1,1035,1000010001,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,1 rok,NaN,Česká republika,stát
4,1080401675,0,3162,3249,53,1,1035,1000010001,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,1 rok,muž,Česká republika,stát

## 094. [B] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, pětiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                            sldb2021_aktivita_vek5_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle ekonomické a...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle ekonomické aktivity...
selected_file                  ds_sldb2021_aktivita_vek5_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     286344
column_count                                                      20
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\094_sldb2021_aktivita_vek5_pohlavi_S...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,aktivita_struktura,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,vek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1081591850,0,3162,3249,53,1,1035,1100000004,NaN,NaN,65,1000,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 - 4 roky,NaN,Praha,správní obvod obce s rozšířenou působností
1,1079844191,0,3162,3249,53,1,1035,1100000004,102.0,1.0,65,1000,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 - 4 roky,muž,Praha,správní obvod obce s rozšířenou působností
2,1081358900,0,3162,3249,53,1,1035,1100000004,102.0,2.0,65,1000,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 - 4 roky,žena,Praha,správní obvod obce s rozšířenou působností
3,1080627018,0,3162,3249,53,1,1035,1300050009,NaN,NaN,65,1000,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,5 - 9 let,NaN,Praha,správní obvod obce s rozšířenou působností
4,1080394665,0,3162,3249,53,1,1035,1300050009,102.0,1.0,65,1000,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,5 - 9 let,muž,Praha,správní obvod obce s rozšířenou působností

## 095. [B] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, základních věkových skupin a pohlaví

                                                             hodnota
dataset_id                             sldb2021_aktivita_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle ekonomické a...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle ekonomické aktivity...
selected_file                   ds_sldb2021_aktivita_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     847224
column_count                                                      20
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\095_sldb2021_aktivita_vek_pohlavi_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,aktivita_struktura,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,vek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1064711789,0,3162,3249,53,1,1035,1100000014,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 - 14 let,NaN,Želechovice nad Dřevnicí,obec
1,1064699480,0,3162,3249,53,1,1035,1100000014,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 - 14 let,muž,Želechovice nad Dřevnicí,obec
2,1064196364,0,3162,3249,53,1,1035,1100000014,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,0 - 14 let,žena,Želechovice nad Dřevnicí,obec
3,1064825248,941,3162,3249,53,1,1035,1300150064,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,15 - 64 let,NaN,Želechovice nad Dřevnicí,obec
4,1064585697,519,3162,3249,53,1,1035,1300150064,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Pracovní síla,15 - 64 let,muž,Želechovice nad Dřevnicí,obec

## 096. [B] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle cílového území a pohlaví

                                                             hodnota
dataset_id                     sldb2021_vyjizdka_vsichni_cil_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání a ško...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání a školy podl...
selected_file           ds_sldb2021_vyjizdka_vsichni_cil_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     300448
column_count                                                      20
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                      školy a školská infrastruktura
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\096_sldb2021_vyjizdka_vsichni_cil_po...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,bydliste_cis,bydliste_kod,cil_dojizdky_cis,cil_dojizdky_kod,pohlavi_cis,pohlavi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,bydliste_txt,bydliste_typ,cil_dojizdky_txt,cil_dojizdky_typ,pohlavi_txt
0,1098782501,660139,2623,3249,58,65,1000,NaN,NaN,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Praha,správní obvod obce s rozšířenou působností,NaN,NaN,NaN
1,1104581004,603462,2623,3249,58,65,1000,65.0,1000.0,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,NaN
2,1104014690,292212,2623,3249,58,65,1000,65.0,1000.0,102.0,1.0,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,muž
3,1104015289,311250,2623,3249,58,65,1000,65.0,1000.0,102.0,2.0,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,žena
4,1104283076,720,2623,3249,58,65,1000,65.0,2101.0,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Benešov,správní obvod obce s rozšířenou působností,NaN

## 097. [B] Sčítání 2021 - Vyjíždějící do zaměstnání podle cílového území a pohlaví

                                                             hodnota
dataset_id                  sldb2021_vyjizdka_pracoviste_cil_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání podle...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání podle cílové...
selected_file        ds_sldb2021_vyjizdka_pracoviste_cil_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     300448
column_count                                                      20
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\097_sldb2021_vyjizdka_pracoviste_cil...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,bydliste_cis,bydliste_kod,cil_dojizdky_cis,cil_dojizdky_kod,pohlavi_cis,pohlavi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,bydliste_txt,bydliste_typ,cil_dojizdky_txt,cil_dojizdky_typ,pohlavi_txt
0,1098927893,496421,2623,3249,51,65,1000,NaN,NaN,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Praha,správní obvod obce s rozšířenou působností,NaN,NaN,NaN
1,1104555327,447273,2623,3249,51,65,1000,65.0,1000.0,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,NaN
2,1104102007,213527,2623,3249,51,65,1000,65.0,1000.0,102.0,1.0,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,muž
3,1103939340,233746,2623,3249,51,65,1000,65.0,1000.0,102.0,2.0,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,žena
4,1103936035,585,2623,3249,51,65,1000,65.0,2101.0,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Praha,správní obvod obce s rozšířenou působností,Benešov,správní obvod obce s rozšířenou působností,NaN

## 098. [B] Sčítání 2021 - Zaměstnaní podle hlavních tříd zaměstnání a pohlaví

                                                             hodnota
dataset_id                                   sldb2021_klasif_pohlavi
dataset_title      Sčítání 2021 - Zaměstnaní podle hlavních tříd ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Zaměstnaní podle hlavních tříd zaměstn...
selected_file                         ds_sldb2021_klasif_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     221892
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\098_sldb2021_klasif_pohlavi_Scitani_...
error                                                           None

,idhod,hodnota,ukaz_kod,klasif_cis,klasif_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,klasif_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1060662276,1,3162,5705,0,NaN,NaN,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnanci v ozbrojených silách,NaN,Želechovice nad Dřevnicí,obec
1,1060551490,1,3162,5705,0,102.0,1.0,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnanci v ozbrojených silách,muž,Želechovice nad Dřevnicí,obec
2,1060580214,0,3162,5705,0,102.0,2.0,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnanci v ozbrojených silách,žena,Želechovice nad Dřevnicí,obec
3,1060690932,50,3162,5705,1,NaN,NaN,43,500011,2021,2021-03-26,Zaměstnaní,Zákonodárci a řídící pracovníci,NaN,Želechovice nad Dřevnicí,obec
4,1060666332,35,3162,5705,1,102.0,1.0,43,500011,2021,2021-03-26,Zaměstnaní,Zákonodárci a řídící pracovníci,muž,Želechovice nad Dřevnicí,obec

## 099. [B] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti a pohlaví

                                                             hodnota
dataset_id                                  sldb2021_odvetvi_pohlavi
dataset_title      Sčítání 2021 - Zaměstnaní podle odvětví ekonom...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Zaměstnaní podle odvětví ekonomické či...
selected_file                        ds_sldb2021_odvetvi_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     443784
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\099_sldb2021_odvetvi_pohlavi_Scitani...
error                                                           None

,idhod,hodnota,ukaz_kod,odvetvi_cis,odvetvi_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,odvetvi_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1060289087,35,3162,5103,A,NaN,NaN,43,500011,2021,2021-03-26,Zaměstnaní,"Zemědělství, lesnictví, rybářství",NaN,Želechovice nad Dřevnicí,obec
1,1059840196,24,3162,5103,A,102.0,1.0,43,500011,2021,2021-03-26,Zaměstnaní,"Zemědělství, lesnictví, rybářství",muž,Želechovice nad Dřevnicí,obec
2,1059930458,11,3162,5103,A,102.0,2.0,43,500011,2021,2021-03-26,Zaměstnaní,"Zemědělství, lesnictví, rybářství",žena,Želechovice nad Dřevnicí,obec
3,1060236677,2,3162,5103,B,NaN,NaN,43,500011,2021,2021-03-26,Zaměstnaní,Těžba a dobývání,NaN,Želechovice nad Dřevnicí,obec
4,1060381104,2,3162,5103,B,102.0,1.0,43,500011,2021,2021-03-26,Zaměstnaní,Těžba a dobývání,muž,Želechovice nad Dřevnicí,obec

## 100. [B] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti, desetiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                            sldb2021_odvetvi_vek10_pohlavi
dataset_title      Sčítání 2021 - Zaměstnaní podle odvětví ekonom...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Zaměstnaní podle odvětví ekonomické či...
selected_file                  ds_sldb2021_odvetvi_vek10_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     238128
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\100_sldb2021_odvetvi_vek10_pohlavi_S...
error                                                           None

,idhod,hodnota,ukaz_kod,odvetvi_cis,odvetvi_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,odvetvi_txt,vek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1093928886,5098,3162,5103,A,1035,1200159999,NaN,NaN,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,NaN,Praha,správní obvod obce s rozšířenou působností
1,1094378013,3482,3162,5103,A,1035,1200159999,102.0,1.0,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,muž,Praha,správní obvod obce s rozšířenou působností
2,1093972562,1616,3162,5103,A,1035,1200159999,102.0,2.0,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,žena,Praha,správní obvod obce s rozšířenou působností
3,1094324702,70,3162,5103,A,1035,1300100019,NaN,NaN,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",10 - 19 let,NaN,Praha,správní obvod obce s rozšířenou působností
4,1094474740,48,3162,5103,A,1035,1300100019,102.0,1.0,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",10 - 19 let,muž,Praha,správní obvod obce s rozšířenou působností

## 101. [B] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti, jednoletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                             sldb2021_odvetvi_vek1_pohlavi
dataset_title      Sčítání 2021 - Zaměstnaní podle odvětví ekonom...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Zaměstnaní podle odvětví ekonomické či...
selected_file                   ds_sldb2021_odvetvi_vek1_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     132066
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\101_sldb2021_odvetvi_vek1_pohlavi_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,odvetvi_cis,odvetvi_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,odvetvi_txt,vek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1093547828,167161,3162,5103,A,1035,1200159999,NaN,NaN,97,19,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,NaN,Česká republika,stát
1,1093549544,120787,3162,5103,A,1035,1200159999,102.0,1.0,97,19,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,muž,Česká republika,stát
2,1094149390,46374,3162,5103,A,1035,1200159999,102.0,2.0,97,19,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,žena,Česká republika,stát
3,1093617536,61,3162,5103,A,1035,1000150015,NaN,NaN,97,19,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 let,NaN,Česká republika,stát
4,1094267937,48,3162,5103,A,1035,1000150015,102.0,1.0,97,19,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 let,muž,Česká republika,stát

## 102. [B] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti, pětiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                             sldb2021_odvetvi_vek5_pohlavi
dataset_title      Sčítání 2021 - Zaměstnaní podle odvětví ekonom...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Zaměstnaní podle odvětví ekonomické či...
selected_file                   ds_sldb2021_odvetvi_vek5_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     411312
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\102_sldb2021_odvetvi_vek5_pohlavi_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,odvetvi_cis,odvetvi_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,odvetvi_txt,vek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1093928886,5098,3162,5103,A,1035,1200159999,NaN,NaN,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,NaN,Praha,správní obvod obce s rozšířenou působností
1,1094378013,3482,3162,5103,A,1035,1200159999,102.0,1.0,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,muž,Praha,správní obvod obce s rozšířenou působností
2,1093972562,1616,3162,5103,A,1035,1200159999,102.0,2.0,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 a více let,žena,Praha,správní obvod obce s rozšířenou působností
3,1093870940,70,3162,5103,A,1035,1300150019,NaN,NaN,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 - 19 let,NaN,Praha,správní obvod obce s rozšířenou působností
4,1094463156,48,3162,5103,A,1035,1300150019,102.0,1.0,65,1000,2021,2021-03-26,Počet zaměstnaných,"Zemědělství, lesnictví, rybářství",15 - 19 let,muž,Praha,správní obvod obce s rozšířenou působností

## 103. [B] Sčítání 2021 - Zaměstnaní podle postavení v zaměstnání a pohlaví

                                                             hodnota
dataset_id                                sldb2021_postaveni_pohlavi
dataset_title      Sčítání 2021 - Zaměstnaní podle postavení v za...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Zaměstnaní podle postavení v zaměstnán...
selected_file                      ds_sldb2021_postaveni_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      80688
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\103_sldb2021_postaveni_pohlavi_Scita...
error                                                           None

,idhod,hodnota,ukaz_kod,postaveni_cis,postaveni_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,postaveni_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1060504297,732,3162,5661,1,NaN,NaN,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnanci,NaN,Želechovice nad Dřevnicí,obec
1,1059916947,372,3162,5661,1,102.0,1.0,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnanci,muž,Želechovice nad Dřevnicí,obec
2,1060403404,360,3162,5661,1,102.0,2.0,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnanci,žena,Želechovice nad Dřevnicí,obec
3,1060143758,21,3162,5661,2,NaN,NaN,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnavatelé,NaN,Želechovice nad Dřevnicí,obec
4,1060044764,17,3162,5661,2,102.0,1.0,43,500011,2021,2021-03-26,Zaměstnaní,Zaměstnavatelé,muž,Želechovice nad Dřevnicí,obec

## 104. [B] Základní výsledky Sčítání lidu, domů a bytů

                                                             hodnota
dataset_id                                         sldb2011_zakladni
dataset_title       Základní výsledky Sčítání lidu, domů a bytů 2011
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                {'cs': 'Základní výsledky - CSV soubor'}
selected_file                               ds_sldb2011_zakladni.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       6712
column_count                                                      15
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                       desetileté / census [R/P10Y]
start_catalog                                             2011-03-26
end_catalog                                               2011-03-26
hlavni_skupina                               Průřezové datové balíky
detailni_skupina                             základní census přehled
uzemni_uroven                       více úrovní (ČR–kraj–okres–obec)
zdroj_typ                             SLDB 2011 / historické sčítání
page               https://www.czso.cz/csu/czso/otevrena_data_pro...
preview_csv        heads_csv\104_sldb2011_zakladni_Zakladni_vysle...
error                                                           None

,typuz_naz,nazev,uzcis,uzkod,u01,u02,u03,u04,u05,u06,u07,u08,u09,u10,u11
0,kraj,Hlavní město Praha,100,3018,1268796.0,613738.0,655058.0,153622.0,908321.0,201029.0,644643.0,600730.0,92927.0,542168.0,579509.0
1,kraj,Středočeský kraj,100,3026,1289211.0,637252.0,651959.0,199300.0,895024.0,190911.0,639851.0,587539.0,286780.0,482860.0,523045.0
2,kraj,Jihočeský kraj,100,3034,628336.0,308296.0,320040.0,91119.0,435187.0,100000.0,307130.0,280844.0,123048.0,247608.0,262692.0
3,kraj,Plzeňský kraj,100,3042,570401.0,282137.0,288264.0,79469.0,396468.0,92734.0,278674.0,255278.0,105835.0,226298.0,242397.0
4,kraj,Karlovarský kraj,100,3051,295595.0,145483.0,150112.0,42159.0,207480.0,44538.0,139871.0,123100.0,39845.0,119403.0,128904.0

## 105. [B] Sčítání 2021 - Děti podle rodinného stavu, vzdělání a věku matky

                                                             hodnota
dataset_id                     sldb2021_deti_stav_vzdelani_vek_matky
dataset_title      Sčítání 2021 - Děti podle rodinného stavu, vzd...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Děti podle rodinného stavu, vzdělání a...
selected_file           ds_sldb2021_deti_stav_vzdelani_vek_matky.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      47120
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\105_sldb2021_deti_stav_vzdelani_vek_...
error                                                           None

,idhod,hodnota,ukaz_kod,stav_zeny_cis,stav_zeny_kod,vzdelani_zeny_cis,vzdelani_zeny_kod,vek_zeny_cis,vek_zeny_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,stav_zeny_txt,vzdelani_zeny_txt,vek_zeny_txt,uzemi_txt
0,983446234,580783,2501,5788,1,NaN,NaN,1035,1200159999,97,19,2021,2021-03-26,Počet živě narozených dětí,Svobodná,NaN,15 a více let,Česká republika
1,983443618,3096,2501,5788,1,NaN,NaN,1035,1300150019,97,19,2021,2021-03-26,Počet živě narozených dětí,Svobodná,NaN,15 - 19 let,Česká republika
2,983482131,28284,2501,5788,1,NaN,NaN,1035,1300200024,97,19,2021,2021-03-26,Počet živě narozených dětí,Svobodná,NaN,20 - 24 let,Česká republika
3,983475445,81582,2501,5788,1,NaN,NaN,1035,1300250029,97,19,2021,2021-03-26,Počet živě narozených dětí,Svobodná,NaN,25 - 29 let,Česká republika
4,983441931,123395,2501,5788,1,NaN,NaN,1035,1300300034,97,19,2021,2021-03-26,Počet živě narozených dětí,Svobodná,NaN,30 - 34 let,Česká republika

## 106. [B] Sčítání 2021 - Hospodařící domácnosti podle velikosti a typu domácnosti

                                                             hodnota
dataset_id                             sldb2021_domacnosti_clenu_typ
dataset_title      Sčítání 2021 - Hospodařící domácnosti podle ve...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Hospodařící domácnosti podle velikosti...
selected_file                   ds_sldb2021_domacnosti_clenu_typ.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     177448
column_count                                                      17
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                struktura domácností
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\106_sldb2021_domacnosti_clenu_typ_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,clenu_cis,clenu_kod,typ_cis,typ_kod,typ_struktura,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,clenu_txt,typ_txt,uzemi_txt,uzemi_typ
0,1061994271,759,2423,NaN,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet hospodařících domácností,NaN,NaN,Želechovice nad Dřevnicí,obec
1,1062015492,528,2423,NaN,NaN,3303.0,12.0,1,43,500011,2021,2021-03-26,Počet hospodařících domácností,NaN,Rodinné domácnosti,Želechovice nad Dřevnicí,obec
2,1061948848,505,2423,NaN,NaN,3303.0,13.0,1.1,43,500011,2021,2021-03-26,Počet hospodařících domácností,NaN,Domácnost - 1 rodina,Želechovice nad Dřevnicí,obec
3,1062520654,429,2423,NaN,NaN,3303.0,14.0,1.1.1.,43,500011,2021,2021-03-26,Počet hospodařících domácností,NaN,Domácnost - 1 úplná rodina,Želechovice nad Dřevnicí,obec
4,1062466884,356,2423,NaN,NaN,3303.0,4.0,1.1.1.1,43,500011,2021,2021-03-26,Počet hospodařících domácností,NaN,Domácnost - 1 rodina - úplná rodina - manželsk...,Želechovice nad Dřevnicí,obec

## 107. [B] Sčítání 2021 - Obyvatelstvo podle vzdělání

                                                             hodnota
dataset_id                                         sldb2021_vzdelani
dataset_title             Sčítání 2021 - Obyvatelstvo podle vzdělání
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                   {'cs': 'Obyvatelstvo podle vzdělání'}
selected_file                               ds_sldb2021_vzdelani.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      53792
column_count                                                      12
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\107_sldb2021_vzdelani_Scitani_2021_-...
error                                                           None

,idhod,hodnota,ukaz_kod,vzdelani_cis,vzdelani_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vzdelani_txt,uzemi_txt
0,944997548,1577,3162,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,NaN,Želechovice nad Dřevnicí
1,945010849,9,3162,1294.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,Želechovice nad Dřevnicí
2,944984326,59,3162,1294.0,900.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Nezjištěno,Želechovice nad Dřevnicí
3,944984325,489,3162,5181.0,35450001.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,"Úplné střední (s maturitou), vč. nástavbového...",Želechovice nad Dřevnicí
4,944984323,540,3162,5784.0,105.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Střední vč. vyučení (bez maturity),Želechovice nad Dřevnicí

## 108. [B] Sčítání 2021 - Obyvatelstvo podle vzdělání a pohlaví

                                                             hodnota
dataset_id                                 sldb2021_vzdelani_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle vzdělání a p...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title         {'cs': 'Obyvatelstvo podle vzdělání a pohlaví'}
selected_file                       ds_sldb2021_vzdelani_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                        713
column_count                                                      16
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\108_sldb2021_vzdelani_pohlavi_Scitan...
error                                                           None

,idhod,hodnota,ukaz_kod,vzdelani_cis,vzdelani_kod,vzdelani_cleneni,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vzdelani_txt,pohlavi_txt,uzemi_txt
0,978179474,8832407,3162,NaN,NaN,0,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,NaN,NaN,Česká republika
1,944998080,56100,3162,1294.0,1.0,1,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,NaN,Česká republika
2,936989751,28660,3162,1294.0,1.0,1,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,muž,Česká republika
3,936989758,27440,3162,1294.0,1.0,1,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,žena,Česká republika
4,944985497,1107860,3162,5784.0,117.0,1,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Základní vč. neukončeného,NaN,Česká republika

## 109. [B] Sčítání 2021 - Obyvatelstvo podle vzdělání, velikostních skupin obcí a pohlaví

                                                             hodnota
dataset_id                    sldb2021_vzdelani_velikostobce_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle vzdělání, ve...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle vzdělání, velikostn...
selected_file          ds_sldb2021_vzdelani_velikostobce_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       6923
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\109_sldb2021_vzdelani_velikostobce_p...
error                                                           None

,idhod,hodnota,ukaz_kod,vzdelani_cis,vzdelani_kod,vzdelani_cleneni,velikostobce_cis,velikostobce_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vzdelani_txt,velikostobce_txt,pohlavi_txt,uzemi_txt
0,978179474,8832407,3162,NaN,NaN,0,NaN,NaN,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,NaN,NaN,NaN,Česká republika
1,980448207,916,3162,1294.0,1.0,1,1234.0,98.0,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,do 199 obyvatel,NaN,Česká republika
2,980447782,463,3162,1294.0,1.0,1,1234.0,98.0,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,do 199 obyvatel,muž,Česká republika
3,980448231,453,3162,1294.0,1.0,1,1234.0,98.0,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,do 199 obyvatel,žena,Česká republika
4,980448205,3610,3162,1294.0,1.0,1,1234.0,99.0,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,200 - 499 obyvatel,NaN,Česká republika

## 110. [B] Sčítání 2021 - Obyvatelstvo podle vzdělání, věku a pohlaví

                                                             hodnota
dataset_id                             sldb2021_vzdelani_vek_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle vzdělání, vě...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle vzdělání, věku a po...
selected_file                   ds_sldb2021_vzdelani_vek_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      83076
column_count                                                      18
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\110_sldb2021_vzdelani_vek_pohlavi_Sc...
error                                                           None

,idhod,hodnota,ukaz_kod,vzdelani_cis,vzdelani_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vzdelani_txt,vek_txt,pohlavi_txt,uzemi_txt
0,987497214,6136,3162,1294,1,1035,1000150015,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,bez vzdělání,15 let,NaN,Česká republika
1,987516921,3517,3162,1294,1,1035,1000150015,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,bez vzdělání,15 let,muž,Česká republika
2,987445083,2619,3162,1294,1,1035,1000150015,102.0,2.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,bez vzdělání,15 let,žena,Česká republika
3,987465226,1227,3162,1294,1,1035,1000160016,NaN,NaN,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,bez vzdělání,16 let,NaN,Česká republika
4,987446375,733,3162,1294,1,1035,1000160016,102.0,1.0,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,bez vzdělání,16 let,muž,Česká republika

## 111. [B] Sčítání 2021 - Obyvatelstvo podle vzdělání, věku, velikostních skupin obcí a pohlaví

                                                             hodnota
dataset_id                sldb2021_vzdelani_vek_velikostobce_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle vzdělání, vě...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle vzdělání, věku, vel...
selected_file      ds_sldb2021_vzdelani_vek_velikostobce_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      45080
column_count                                                      22
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\111_sldb2021_vzdelani_vek_velikostob...
error                                                           None

,idhod,hodnota,ukaz_kod,vzdelani_cis,vzdelani_kod,vzdelani_cleneni,vek_cis,vek_kod,velikostobce_cis,velikostobce_kod,...,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vzdelani_txt,vek_txt,velikostobce_txt,pohlavi_txt,uzemi_txt
0,982793118,96,3162,1294,1,1,1035,1300150019,1234,98,...,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez vzdělání,15 - 19 let,do 199 obyvatel,muž,Česká republika
1,982747858,58,3162,1294,1,1,1035,1300150019,1234,98,...,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez vzdělání,15 - 19 let,do 199 obyvatel,žena,Česká republika
2,982749936,25,3162,1294,1,1,1035,1300200024,1234,98,...,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez vzdělání,20 - 24 let,do 199 obyvatel,muž,Česká republika
3,982753537,17,3162,1294,1,1,1035,1300200024,1234,98,...,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez vzdělání,20 - 24 let,do 199 obyvatel,žena,Česká republika
4,982751979,30,3162,1294,1,1,1035,1300250029,1234,98,...,97,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,Bez vzdělání,25 - 29 let,do 199 obyvatel,muž,Česká republika

## 112. [B] Sčítání 2021 - Obyvatelstvo podle vzdělání, základních věkových skupin a pohlaví

                                                             hodnota
dataset_id                            sldb2021_vzdelani_vek2_pohlavi
dataset_title      Sčítání 2021 - Obyvatelstvo podle vzdělání, zá...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Obyvatelstvo podle vzdělání, základníc...
selected_file                  ds_sldb2021_vzdelani_vek2_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     564816
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\112_sldb2021_vzdelani_vek2_pohlavi_S...
error                                                           None

,idhod,hodnota,ukaz_kod,vzdelani_cis,vzdelani_kod,vek_cis,vek_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,vzdelani_txt,vek_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1065348324,6,3162,1294,1,1035,1300150064,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,15 - 64 let,NaN,Želechovice nad Dřevnicí,obec
1,1065987611,4,3162,1294,1,1035,1300150064,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,15 - 64 let,muž,Želechovice nad Dřevnicí,obec
2,1065439653,2,3162,1294,1,1035,1300150064,102.0,2.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,15 - 64 let,žena,Želechovice nad Dřevnicí,obec
3,1066034432,3,3162,1294,1,1035,1200659999,NaN,NaN,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,65 a více let,NaN,Želechovice nad Dřevnicí,obec
4,1065233243,2,3162,1294,1,1035,1200659999,102.0,1.0,43,500011,2021,2021-03-26,Počet obyvatel s obvyklým pobytem ve věku 15 a...,Bez vzdělání,65 a více let,muž,Želechovice nad Dřevnicí,obec

## 113. [B] Sčítání 2021 - Počet členů hospodařících domácností podle velikosti a typu domácnosti

                                                             hodnota
dataset_id                                  sldb2021_pocty_clenu_typ
dataset_title      Sčítání 2021 - Počet členů hospodařících domác...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Počet členů hospodařících domácností p...
selected_file                        ds_sldb2021_pocty_clenu_typ.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     240096
column_count                                                      17
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                struktura domácností
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\113_sldb2021_pocty_clenu_typ_Scitani...
error                                                           None

,idhod,hodnota,ukaz_kod,clenu_cis,clenu_kod,typ_cis,typ_kod,typ_struktura,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,clenu_txt,typ_txt,uzemi_txt,uzemi_typ
0,1061894925,1817,3337,NaN,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet členů hospodařící domácnosti,NaN,NaN,Želechovice nad Dřevnicí,obec
1,1062027264,1578,3337,NaN,NaN,3303.0,12.0,1,43,500011,2021,2021-03-26,Počet členů hospodařící domácnosti,NaN,Rodinné domácnosti,Želechovice nad Dřevnicí,obec
2,1061861681,1457,3337,NaN,NaN,3303.0,13.0,1.1,43,500011,2021,2021-03-26,Počet členů hospodařící domácnosti,NaN,Domácnost - 1 rodina,Želechovice nad Dřevnicí,obec
3,1062471958,1272,3337,NaN,NaN,3303.0,14.0,1.1.1.,43,500011,2021,2021-03-26,Počet členů hospodařící domácnosti,NaN,Domácnost - 1 úplná rodina,Želechovice nad Dřevnicí,obec
4,1062463710,1052,3337,NaN,NaN,3303.0,4.0,1.1.1.1,43,500011,2021,2021-03-26,Počet členů hospodařící domácnosti,NaN,Domácnost - 1 rodina - úplná rodina - manželsk...,Želechovice nad Dřevnicí,obec

## 114. [B] Sčítání 2021 - Vyjíždějící do školy podle cílového území a pohlaví

                                                             hodnota
dataset_id                       sldb2021_vyjizdka_skola_cil_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do školy podle cílo...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do školy podle cílového úz...
selected_file             ds_sldb2021_vyjizdka_skola_cil_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     300448
column_count                                                      20
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                      školy a školská infrastruktura
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\114_sldb2021_vyjizdka_skola_cil_pohl...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,bydliste_cis,bydliste_kod,cil_dojizdky_cis,cil_dojizdky_kod,pohlavi_cis,pohlavi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,bydliste_txt,bydliste_typ,cil_dojizdky_txt,cil_dojizdky_typ,pohlavi_txt
0,1099263671,163718,2623,3072,8,65,1000,NaN,NaN,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Praha,správní obvod obce s rozšířenou působností,NaN,NaN,NaN
1,1104565200,156189,2623,3072,8,65,1000,65.0,1000.0,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,NaN
2,1104575761,78685,2623,3072,8,65,1000,65.0,1000.0,102.0,1.0,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,muž
3,1104684397,77504,2623,3072,8,65,1000,65.0,1000.0,102.0,2.0,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Praha,správní obvod obce s rozšířenou působností,žena
4,1104106317,135,2623,3072,8,65,1000,65.0,2101.0,NaN,NaN,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Praha,správní obvod obce s rozšířenou působností,Benešov,správní obvod obce s rozšířenou působností,NaN

## 115. [B] Sčítání 2021 - Ženy ve věku 15 a více let podle rodinného stavu, vzdělání, věku a počtu dětí

                                                             hodnota
dataset_id                      sldb2021_zeny_stav_vzdelani_vek_deti
dataset_title      Sčítání 2021 - Ženy ve věku 15 a více let podl...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Ženy ve věku 15 a více let podle rodin...
selected_file            ds_sldb2021_zeny_stav_vzdelani_vek_deti.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     235313
column_count                                                      24
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                 vzdělanost obyvatel
uzemni_uroven                                   více úrovní (census)
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\115_sldb2021_zeny_stav_vzdelani_vek_...
error                                                           None

,idhod,hodnota,ukaz_kod,pohlavi_cis,pohlavi_kod,stav_cis,stav_kod,vzdelani_cis,vzdelani_kod,vek_cis,...,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,pohlavi_txt,stav_txt,vzdelani_txt,vek_txt,pocet_deti_txt,uzemi_txt
0,983095156,238290,3162,102,2,NaN,NaN,NaN,NaN,1035,...,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,žena,NaN,NaN,15 - 19 let,NaN,Česká republika
1,982844265,234041,3162,102,2,NaN,NaN,NaN,NaN,1035,...,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,žena,NaN,NaN,15 - 19 let,0.0,Česká republika
2,982844369,2400,3162,102,2,NaN,NaN,NaN,NaN,1035,...,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,žena,NaN,NaN,15 - 19 let,1.0,Česká republika
3,982879802,322,3162,102,2,NaN,NaN,NaN,NaN,1035,...,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,žena,NaN,NaN,15 - 19 let,2.0,Česká republika
4,983057787,53,3162,102,2,NaN,NaN,NaN,NaN,1035,...,19,2021,2021-03-26,Počet obyvatel s obvyklým pobytem,žena,NaN,NaN,15 - 19 let,3.0,Česká republika

## 116. [B] Výběr údajů ze SLDB 2011 za domácnosti

                                                             hodnota
dataset_id                                                 sldbdomac
dataset_title                 Výběr údajů ze SLDB 2011 za domácnosti
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                    {'cs': 'Domácnosti'}
selected_file                                    SLDB_DOMACNOSTI.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                       6712
column_count                                                      13
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                       desetileté / census [R/P10Y]
start_catalog                                             2011-03-26
end_catalog                                               2011-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                struktura domácností
uzemni_uroven                       více úrovní (ČR–kraj–okres–obec)
zdroj_typ                             SLDB 2011 / historické sčítání
page               https://csu.gov.cz/docs/107516/3151dee8-4277-1...
preview_csv        heads_csv\116_sldbdomac_Vyber_udaju_ze_SLDB_20...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,typuz_naz,nazev,uzcis,uzkod,vse10111,vse10121,vse10131,vse10141,vse10151,vse10161,vse10171,vse10181,vse10191
0,kraj,Hlavní město Praha,100,3018,579509.0,300262.0,138255.0,85440.0,36987.0,39580.0,5034.0,225802.0,48411.0
1,kraj,Středočeský kraj,100,3026,523045.0,329829.0,150431.0,112184.0,32229.0,34985.0,10207.0,158918.0,24091.0
2,kraj,Jihočeský kraj,100,3034,262692.0,163840.0,76508.0,53696.0,15649.0,17987.0,4332.0,84195.0,10325.0
3,kraj,Plzeňský kraj,100,3042,242397.0,147651.0,71475.0,46581.0,14052.0,15543.0,3555.0,79334.0,11857.0
4,kraj,Karlovarský kraj,100,3051,128904.0,73917.0,34015.0,21078.0,8252.0,10572.0,1610.0,45345.0,8032.0

## 117. [B] Naděje dožití v okresech a správních obvodech ORP

                                                             hodnota
dataset_id                                                 130140r17
dataset_title      Naděje dožití v okresech a správních obvodech ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                              {'cs': 'Data za rok 2017'}
selected_file                                       ds_130140r17.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       1698
column_count                                                      15
time_columns                        stapro_kod, casref_od, casref_do
years_min                                                       2013
years_max                                                       2017
years_count                                                        2
years_sample                                              2013, 2017
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2013-01-01
end_catalog                                               2017-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                                    ORP
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/2ee86c60-4118-3...
preview_csv        heads_csv\117_130140r17_Nadeje_doziti_v_okrese...
error                                                           None

,"﻿""idhod""",hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
0,783054936,"33,9719809011",5411,7700,410045610046000,102,1,65,1000,2013-01-01,2017-12-31,Naděje dožití,45 až 46 (více nebo rovno 45 a méně než 46),muž,Praha
1,783054937,"17,017342219",5411,7700,410065610066000,102,1,65,1000,2013-01-01,2017-12-31,Naděje dožití,65 až 66 (více nebo rovno 65 a méně než 66),muž,Praha
2,783054938,"82,5376340206",5411,7700,400000600001000,102,2,65,1000,2013-01-01,2017-12-31,Naděje dožití,0 až 1 (více nebo rovno 0 a méně než 1),žena,Praha
3,783054935,"77,7078891119",5411,7700,400000600001000,102,1,65,1000,2013-01-01,2017-12-31,Naděje dožití,0 až 1 (více nebo rovno 0 a méně než 1),muž,Praha
4,783054940,"20,0997475018",5411,7700,410065610066000,102,2,65,1000,2013-01-01,2017-12-31,Naděje dožití,65 až 66 (více nebo rovno 65 a méně než 66),žena,Praha

## 118. [B] Naděje dožití v okresech a správních obvodech ORP - časová řada

                                                             hodnota
dataset_id                                                    130140
dataset_title      Naděje dožití v okresech a správních obvodech ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2021'}
selected_file                                          ds_130140.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      15848
column_count                                                      15
time_columns                        stapro_kod, casref_od, casref_do
years_min                                                       2011
years_max                                                       2021
years_count                                                       11
years_sample       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2011-01-01
end_catalog                                               2021-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                                    ORP
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/2ee86c60-4118-3...
preview_csv        heads_csv\118_130140_Nadeje_doziti_v_okresech_...
error                                                           None

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
0,794233212,19.569515,5411,102,2,7700,410065610066000,101,40720,2011-01-01,2015-12-31,Naděje dožití,žena,65 až 66 (více nebo rovno 65 a méně než 66),Brno-venkov
1,794232070,19.386517,5411,102,2,7700,410065610066000,101,40673,2011-01-01,2015-12-31,Naděje dožití,žena,65 až 66 (více nebo rovno 65 a méně než 66),Pelhřimov
2,794226369,6.578681,5411,102,1,7700,410080610081000,101,40444,2011-01-01,2015-12-31,Naděje dožití,muž,80 až 81 (více nebo rovno 80 a méně než 81),Sokolov
3,794224039,81.843185,5411,102,2,7700,400000600001000,101,40347,2011-01-01,2015-12-31,Naděje dožití,žena,0 až 1 (více nebo rovno 0 a méně než 1),Tábor
4,794227125,79.660277,5411,102,2,7700,400000600001000,101,40479,2011-01-01,2015-12-31,Naděje dožití,žena,0 až 1 (více nebo rovno 0 a méně než 1),Litoměřice

## 119. [C] Stavební povolení

                                                             hodnota
dataset_id                                                    200077
dataset_title                                      Stavební povolení
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2025'}
selected_file                          OD_STA02_2026020416094438.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                      88554
column_count                                                      20
time_columns                       stapro_kod, mesicod, mesicdo, rok
years_min                                                       2005
years_max                                                       2025
years_count                                                       21
years_sample       2005, 2006, 2007, 2008, 2009, 2010 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2005-01-01
end_catalog                                               2025-12-31
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                      bytová výstavba a stavebnictví
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/130319fd-bc2c-2...
preview_csv               heads_csv\119_200077_Stavebni_povoleni.csv
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,duvernost,stapro_kod,mj_cis,mj_kod,typstavby_cis,typstavby_kod,smer_cis,smer_kod,mesicod,mesicdo,rok,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,mj_txt,typstavby_txt,smer_txt
0,758356430,105743,verejny,3030,78,99998,NaN,NaN,NaN,NaN,1,12,2010,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,NaN,NaN
1,758351902,15553,verejny,3030,78,99998,5632.0,11.0,2323.0,20.0,1,12,2010,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Budovy bytové,nová výstavba
2,758352389,7279,verejny,3030,78,99998,5632.0,12.0,2323.0,20.0,1,12,2010,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Budovy nebytové,nová výstavba
3,758355907,31000,verejny,3030,78,99998,5714.0,20.0,NaN,NaN,1,12,2010,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Stavby - ostatní (kromě bytových a nebytových ...,NaN
4,758354418,39158,verejny,3030,78,99998,5632.0,11.0,NaN,NaN,1,12,2010,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Budovy bytové,NaN

## 120. [C] Stavební zakázky

                                                             hodnota
dataset_id                                                    200076
dataset_title                                       Stavební zakázky
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                     {'cs': 'Data do 4. čtvrtletí 2025'}
selected_file                                          ds_200076.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                        972
column_count                                                      19
time_columns          stapro_kod, obdobiod, obdobido, ctvrtleti, rok
years_min                                                       1999
years_max                                                       2025
years_count                                                       27
years_sample       1999, 2000, 2001, 2002, 2003, 2004 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             1999-01-01
end_catalog                                               2025-12-31
hlavni_skupina                    Bydlení a technická infrastruktura
detailni_skupina                      bytová výstavba a stavebnictví
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/61aaa546-1188-3...
preview_csv                heads_csv\120_200076_Stavebni_zakazky.csv
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,misto_cis,misto_kod,stavprace_cis,stavprace_kod,obdobiod,obdobido,ctvrtleti,rok,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,misto_txt,stavprace_txt
0,814439405,14971,278,78,206,2478.0,10.0,NaN,NaN,2012-12-31 00:00:00,2012-12-31 00:00:00,4,2012,97,19,Hodnota stavebních zakázek,mil. Kč,zahraničí,NaN
1,814439402,140373,278,78,206,NaN,NaN,NaN,NaN,2012-12-31 00:00:00,2012-12-31 00:00:00,4,2012,97,19,Hodnota stavebních zakázek,mil. Kč,NaN,NaN
2,814439360,11430,278,78,206,2478.0,10.0,NaN,NaN,2011-12-31 00:00:00,2011-12-31 00:00:00,4,2011,97,19,Hodnota stavebních zakázek,mil. Kč,zahraničí,NaN
3,814439357,143078,278,78,206,NaN,NaN,NaN,NaN,2011-12-31 00:00:00,2011-12-31 00:00:00,4,2011,97,19,Hodnota stavebních zakázek,mil. Kč,NaN,NaN
4,814439225,11794,278,78,206,2478.0,10.0,NaN,NaN,2008-12-31 00:00:00,2008-12-31 00:00:00,4,2008,97,19,Hodnota stavebních zakázek,mil. Kč,zahraničí,NaN

## 121. [C] Cizinci podle státního občanství, věku a pohlaví

                                                             hodnota
dataset_id                                                 290038r25
dataset_title      Cizinci podle státního občanství, věku a pohla...
status                                              ERROR_SELECTIONS
source_kind                                                     None
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2024-01-01
end_catalog                                               2024-12-31
hlavni_skupina                                 Demografie a populace
detailni_skupina                      struktura populace a diverzita
uzemni_uroven                                                  okres
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/4711685d-93fa-8...
preview_csv                                                     None
error              LKOD/VDB selhalo: HTTP 404 for https://csu.gov...

## 122. [C] Obyvatelstvo podle jednotek věku a pohlaví

                                                             hodnota
dataset_id                                                 130181r25
dataset_title      Obyvatelstvo podle jednotek věku a pohlaví - r...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                {'cs': 'Data roku 2024'}
selected_file                                       ds_130181r25.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      93024
column_count                                                      14
time_columns                                      stapro_kod, obdobi
years_min                                                       2024
years_max                                                       2024
years_count                                                        1
years_sample                                                    2024
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2024-01-01
end_catalog                                               2024-12-31
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                            více úrovní (ČR–kraj–okres)
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/bc0dbd59-0cf0-7...
preview_csv        heads_csv\122_130181r25_Obyvatelstvo_podle_jed...
error                                                           None

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,obdobi,pohlavi_txt,vek_txt,uzemi_txt,uzemi_typ
0,1446328288,1397880,2406,NaN,NaN,NaN,NaN,100,3018,2024-12-31,NaN,NaN,Hlavní město Praha,kraj
1,1446020251,12083,2406,NaN,NaN,7700.0,4.000006e+14,100,3018,2024-12-31,NaN,0.0,Hlavní město Praha,kraj
2,1446058963,12716,2406,NaN,NaN,7700.0,4.000016e+14,100,3018,2024-12-31,NaN,1.0,Hlavní město Praha,kraj
3,1445962976,13675,2406,NaN,NaN,7700.0,4.000026e+14,100,3018,2024-12-31,NaN,2.0,Hlavní město Praha,kraj
4,1446063539,15577,2406,NaN,NaN,7700.0,4.000036e+14,100,3018,2024-12-31,NaN,3.0,Hlavní město Praha,kraj

## 123. [C] Obyvatelstvo podle pětiletých věkových skupin a pohlaví

                                                             hodnota
dataset_id                                                    130142
dataset_title      Obyvatelstvo podle pětiletých věkových skupin ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                      OD_DEM02_vse_2025051510021868.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     462855
column_count                                                      14
time_columns                                   stapro_kod, casref_do
years_min                                                       2000
years_max                                                       2024
years_count                                                       25
years_sample       2000, 2001, 2002, 2003, 2004, 2005 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2010-01-01
end_catalog                                               2024-12-31
hlavni_skupina                                 Demografie a populace
detailni_skupina                věková a pohlavní struktura populace
uzemni_uroven                            více úrovní (ČR–kraj–okres)
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/419cb3ed-65d3-e...
preview_csv        heads_csv\123_130142_Obyvatelstvo_podle_petile...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_do,pohlavi_txt,vek_txt,vuzemi_txt,uzemi_typ
0,884752318,1181126,2406,NaN,NaN,NaN,NaN,100,3018,2000-12-31,NaN,NaN,Hlavní město Praha,kraj
1,758059807,9392,2406,NaN,NaN,7700.0,4.000006e+14,100,3018,2000-12-31,NaN,0 až 1 (více nebo rovno 0 a méně než 1),Hlavní město Praha,kraj
2,1132562079,34676,2406,NaN,NaN,7700.0,4.000016e+14,100,3018,2000-12-31,NaN,1 až 5 (více nebo rovno 1 a méně než 5),Hlavní město Praha,kraj
3,902936995,53319,2406,NaN,NaN,7700.0,4.000056e+14,100,3018,2000-12-31,NaN,5 až 10 (více nebo rovno 5 a méně než 10),Hlavní město Praha,kraj
4,902936996,62338,2406,NaN,NaN,7700.0,4.100106e+14,100,3018,2000-12-31,NaN,10 až 15 (více nebo rovno 10 a méně než 15),Hlavní město Praha,kraj

## 124. [C] Bilance meziokresní vyjížďky do zaměstnání podle výsledků sčítání

                                                             hodnota
dataset_id                                                    170242
dataset_title      Bilance meziokresní vyjížďky do zaměstnání pod...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Bilance meziokresní vyjížďky do zaměst...
selected_file                                          ds_170242.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       5929
column_count                                                      12
time_columns                                       stapro_kod, datum
years_min                                                       2011
years_max                                                       2011
years_count                                                        1
years_sample                                                    2011
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2011-03-26
end_catalog                                               2011-03-26
hlavni_skupina                                 Mobilita a dostupnost
detailni_skupina                              dojížďka do zaměstnání
uzemni_uroven                                                  okres
zdroj_typ                             SLDB 2011 / historické sčítání
page               https://csu.gov.cz/docs/107516/f4224f10-d886-7...
preview_csv        heads_csv\124_170242_Bilance_meziokresni_vyjiz...
error                                                           None

,"﻿""idhod""",hodnota,stapro_kod,ekonaktiv_cis,ekonaktiv_kod,uzemiz_cis,uzemiz_kod,uzemido_cis,uzemido_kod,datum,uzemiz_txt,uzemido_txt
0,150005966,269,2623,3249,57,101,40592,101,40622,2011-03-26,Rychnov nad Kněžnou,Pardubice
1,150005973,48,2623,3249,57,101,40169,101,40657,2011-03-26,Benešov,Havlíčkův Brod
2,150005974,0,2623,3249,57,101,40177,101,40657,2011-03-26,Beroun,Havlíčkův Brod
3,150005982,3,2623,3249,57,101,40258,101,40657,2011-03-26,Praha-západ,Havlíčkův Brod
4,150006003,0,2623,3249,57,101,40525,101,40703,2011-03-26,Česká Lípa,Blansko

## 125. [C] Ekonomické subjekty podle vybraných právních forem za správní obvody Prahy a obcí s rozšířenou působností

                                                             hodnota
dataset_id                                                    140131
dataset_title      Ekonomické subjekty podle vybraných právních f...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                           {'cs': 'Čtvrtletí roku 2025'}
selected_file                         OD_ORG01q_2026011319304025.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     374711
column_count                                                      13
time_columns                                      stapro_kod, casref
years_min                                                       2025
years_max                                                       2025
years_count                                                        1
years_sample                                                    2025
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2010-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina       ekonomické subjekty a podnikatelská struktura
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/e9e70029-f638-b...
preview_csv        heads_csv\125_140131_Ekonomicke_subjekty_podle...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,forma_cis,forma_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,forma_txt,vuzemi_txt
0,1499835858,62,4958,NaN,NaN,NaN,NaN,43,539783,2025-12-31,NaN,NaN,Oplot
1,1498698714,74,4958,NaN,NaN,NaN,NaN,43,532479,2025-12-31,NaN,NaN,Kmetiněves
2,1498490635,49,4958,NaN,NaN,NaN,NaN,43,551821,2025-12-31,NaN,NaN,Tvrdkov
3,1498452543,80,4958,NaN,NaN,NaN,NaN,43,559806,2025-12-31,NaN,NaN,Hlohovice
4,1499305200,450,4958,NaN,NaN,NaN,NaN,43,574911,2025-12-31,NaN,NaN,Dolní Roveň

## 126. [C] Index průmyslové produkce

                                                             hodnota
dataset_id                                                    150196
dataset_title                              Index průmyslové produkce
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2025'}
selected_file                                          ds_150196.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      18972
column_count                                                      14
time_columns       stapro_kod, casz_cis, casz_kod, mesic, rok, me...
years_min                                                       2000
years_max                                                       2025
years_count                                                       26
years_sample       2000, 2001, 2002, 2003, 2004, 2005 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2000-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina              makroekonomické a odvětvové indikátory
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/7dfe803b-d9bf-e...
preview_csv        heads_csv\126_150196_Index_prumyslove_produkce...
error                                                           None

,idhod,hodnota,stapro_kod,casz_cis,casz_kod,cznace_cis,cznace_kod,mesic,rok,mesicz,rokz,stapro_txt,casz_txt,cznace_txt
0,1266016685,92.7,5249,7626,C,5104,5,4,2010,4,2009,Index průmyslové produkce,stejné období předchozího roku,Těžba a úprava černého a hnědého uhlí
1,1265237719,108.2,5249,7626,C,5104,22,4,2010,4,2009,Index průmyslové produkce,stejné období předchozího roku,Výroba pryžových a plastových výrobků
2,1265822167,90.5,5249,7626,C,5104,33,4,2010,4,2009,Index průmyslové produkce,stejné období předchozího roku,Opravy a instalace strojů a zařízení
3,1265432400,120.2,5249,7626,C,5104,26,4,2010,4,2009,Index průmyslové produkce,stejné období předchozího roku,"Výroba počítačů, elektronických a optických př..."
4,1266211493,122.2,5249,7626,C,5104,27,4,2010,4,2009,Index průmyslové produkce,stejné období předchozího roku,Výroba elektrických zařízení

## 127. [C] Index stavební produkce

                                                             hodnota
dataset_id                                                    200075
dataset_title                                Index stavební produkce
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2025'}
selected_file                                          ds_200075.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       1728
column_count                                                      20
time_columns       stapro_kod, casz_cis, casz_kod, mesic, rok, me...
years_min                                                       2019
years_max                                                       2025
years_count                                                        7
years_sample                2019, 2020, 2021, 2022, 2023, 2024, 2025
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2000-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina              makroekonomické a odvětvové indikátory
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/e89c424a-e3df-b...
preview_csv         heads_csv\127_200075_Index_stavebni_produkce.csv
error                                                           None

,idhod,hodnota,stapro_kod,casz_cis,casz_kod,stavprace_cis,stavprace_kod,oceneni_cis,oceneni_kod,ocisteni_cis,ocisteni_kod,mesic,rok,mesicz,rokz,stapro_txt,casz_txt,stavprace_txt,oceneni_txt,ocisteni_txt
0,1267033748,109.2,5939,7626,C,NaN,NaN,NaN,NaN,NaN,NaN,1,2020,1,2019,Index stavební produkce,stejné období předchozího roku,Stavební práce celkem,běžné ceny,neočištěno
1,1267027132,123.5,5939,7626,C,175.0,24.0,NaN,NaN,NaN,NaN,1,2020,1,2019,Index stavební produkce,stejné období předchozího roku,Inženýrské stavitelství,běžné ceny,neočištěno
2,1267060344,104.7,5939,7626,C,175.0,23.0,NaN,NaN,NaN,NaN,1,2020,1,2019,Index stavební produkce,stejné období předchozího roku,Pozemní stavitelství,běžné ceny,neočištěno
3,1421929520,114.6,5939,7626,C,175.0,24.0,7603.0,P,7604.0,O,1,2020,1,2019,Index stavební produkce,stejné období předchozího roku,Inženýrské stavitelství,stálé (průměrné) ceny roku,"sezónně očištěno, včetně očištění o kalendářní..."
4,1267062631,104.8,5939,7626,C,NaN,NaN,7603.0,P,NaN,NaN,1,2020,1,2019,Index stavební produkce,stejné období předchozího roku,Stavební práce celkem,stálé (průměrné) ceny roku,neočištěno

## 128. [C] Indexy spotřebitelských cen

                                                             hodnota
dataset_id                                                     10022
dataset_title                            Indexy spotřebitelských cen
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             1995-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                              ceny a životní náklady
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/5bc19b9e-1d32-5...
preview_csv                                                     None
error              LKOD/VDB selhalo: JSON parsing failed. Respons...

## 129. [C] Indexy tržeb v odvětví dopravy, maloobchodu a služeb

                                                             hodnota
dataset_id                                                     30030
dataset_title      Indexy tržeb v odvětví dopravy, maloobchodu a ...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2000-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina              makroekonomické a odvětvové indikátory
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/c7d72e2f-fd33-c...
preview_csv                                                     None
error              LKOD/VDB selhalo: JSON parsing failed. Respons...

## 130. [C] Konjunkturální průzkumy

                                                             hodnota
dataset_id                                                     70013
dataset_title                                Konjunkturální průzkumy
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2000-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina              makroekonomické a odvětvové indikátory
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/82607324-dd20-3...
preview_csv                                                     None
error              LKOD/VDB selhalo: JSON parsing failed. Respons...

## 131. [C] Pohyb zboží přes hranice podle vybraných zemí

                                                             hodnota
dataset_id                                                    241048
dataset_title          Pohyb zboží přes hranice podle vybraných zemí
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2025'}
selected_file                                          ds_241048.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      67967
column_count                                                      13
time_columns                                  stapro_kod, rok, mesic
years_min                                                       2000
years_max                                                       2025
years_count                                                       26
years_sample       2000, 2001, 2002, 2003, 2004, 2005 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2000-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                   zahraniční obchod
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/1b5cd267-8e4a-d...
preview_csv        heads_csv\131_241048_Pohyb_zbozi_pres_hranice_...
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,czem_cis,czem_kod,vuzemi_cis,vuzemi_kod,rok,mesic,stapro_txt,czem_txt
0,739504535,14215,5757,78,206,NaN,NaN,97,19,2007,3,Bilance pohybu zboží přes hranice,NaN
1,739504871,5705,5757,78,206,5584.0,GB,97,19,2007,3,Bilance pohybu zboží přes hranice,Spojené království
2,739504773,10164,5757,78,206,5584.0,DE,97,19,2007,3,Bilance pohybu zboží přes hranice,Německo
3,739504633,294,5757,78,206,5584.0,FR,97,19,2007,3,Bilance pohybu zboží přes hranice,Francie
4,739504878,397,5757,78,206,5584.0,US,97,19,2007,3,Bilance pohybu zboží přes hranice,Spojené státy

## 132. [C] Průměrná hrubá měsíční mzda a medián mezd v krajích

                                                             hodnota
dataset_id                                                    110080
dataset_title      Průměrná hrubá měsíční mzda a medián mezd v kr...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                                          ds_110080.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       1260
column_count                                                      14
time_columns                                         stapro_kod, rok
years_min                                                       2011
years_max                                                       2024
years_count                                                       14
years_sample       2011, 2012, 2013, 2014, 2015, 2016 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2011-01-01
end_catalog                                               2024-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                                mzdy
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/159084c6-c6c7-d...
preview_csv        heads_csv\132_110080_Prumerna_hruba_mesicni_mz...
error                                                           None

,idhod,hodnota,stapro_kod,SPKVANTIL_cis,SPKVANTIL_kod,POHLAVI_cis,POHLAVI_kod,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,SPKVANTIL_txt,POHLAVI_txt
0,736622362,25625,5958,NaN,NaN,NaN,NaN,2011,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,NaN,NaN
1,736622363,28431,5958,NaN,NaN,102.0,1.0,2011,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,NaN,muž
2,736622364,22133,5958,NaN,NaN,102.0,2.0,2011,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,NaN,žena
3,736622365,21782,5958,7636.0,Q5,NaN,NaN,2011,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,medián,NaN
4,736622366,23533,5958,7636.0,Q5,102.0,1.0,2011,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,medián,muž

## 133. [C] Průměrné spotřebitelské ceny pohonných hmot - týdenní šetření

                                                             hodnota
dataset_id                                                 phm_tydny
dataset_title      Průměrné spotřebitelské ceny pohonných hmot - ...
status                                            UNSUPPORTED_FORMAT
source_kind                                                     LKOD
source_code                                               resource#1
source_title                                    {'cs': 'Data v CSV'}
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                    týdenní [R/P1W]
start_catalog                                             2016-01-01
end_catalog                                               2024-12-22
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                              ceny a životní náklady
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page                https://vdb.czso.cz/pll/eweb/cenyphm.dokumentace
preview_csv                                                     None
error              Stažený formát `data` není zatím podporovaný p...

## 134. [C] Průměrné spotřebitelské ceny vybraných výrobků - potravinářské výrobky

                                                             hodnota
dataset_id                                                     12052
dataset_title      Průměrné spotřebitelské ceny vybraných výrobků...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2006-01-01
end_catalog                                               2018-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                              ceny a životní náklady
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/31c4adf6-208b-6...
preview_csv                                                     None
error              LKOD/VDB selhalo: JSON parsing failed. Respons...

## 135. [C] Příjmy domácností zaměstnanců a důchodců

                                                             hodnota
dataset_id                                                    160061
dataset_title               Příjmy domácností zaměstnanců a důchodců
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2023'}
selected_file                                          ds_160061.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       1149
column_count                                                      13
time_columns                                         stapro_kod, rok
years_min                                                       2010
years_max                                                       2023
years_count                                                       14
years_sample       2010, 2011, 2012, 2013, 2014, 2015 ... 2018, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2010-01-01
end_catalog                                               2023-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                   příjmy domácností
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/2ea186fb-2a16-0...
preview_csv        heads_csv\135_160061_Prijmy_domacnosti_zamestn...
error                                                           None

,idhod,hodnota,stapro_kod,ekakocd_cis,ekakocd_kod,pvdom_cis,pvdom_kod,rok,uzemi_cis,uzemi_kod,stapro_txt,ekakocd_txt,pvdom_txt
0,1433379011,144597,6010,NaN,NaN,NaN,NaN,2010,97,19,Průměrné čisté peněžní příjmy domácností,Domácnosti celkem,NaN
1,1433369055,150246,6010,221.0,6.0,NaN,NaN,2010,97,19,Průměrné čisté peněžní příjmy domácností,Zaměstnanci,NaN
2,1433371722,161300,6010,221.0,5.0,NaN,NaN,2010,97,19,Průměrné čisté peněžní příjmy domácností,Samostatně činní,NaN
3,1433381169,15703,6010,220.0,14.0,213.0,14.0,2010,97,19,Průměrné čisté peněžní příjmy domácností,Důchodci,Příjmy ze závislé činnosti (hlavní zaměstnání)
4,1433381144,78411,6010,NaN,NaN,213.0,14.0,2010,97,19,Průměrné čisté peněžní příjmy domácností,Domácnosti celkem,Příjmy ze závislé činnosti (hlavní zaměstnání)

## 136. [C] Regionální účty za regiony soudržnosti a kraje

                                                             hodnota
dataset_id                                                     50101
dataset_title         Regionální účty za regiony soudržnosti a kraje
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             1995-01-01
end_catalog                                               2024-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                           národní a regionální účty
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/2a1d572e-aeaa-8...
preview_csv                                                     None
error              LKOD/VDB selhalo: JSON parsing failed. Respons...

## 137. [C] Registr ekonomických subjektů - seznam právních forem a ekonomických činností

                                                             hodnota
dataset_id                                               res_pf_nace
dataset_title      Registr ekonomických subjektů - seznam právníc...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Seznam právních forem a činností ekono...
selected_file                                     ds_res_pf_nace.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                   21715245
column_count                                                       7
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                               2x měsíčně [R/P0.5M]
start_catalog                                                   None
end_catalog                                                     None
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina       ekonomické subjekty a podnikatelská struktura
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://www.czso.cz/csu/czso/registr-ekonomick...
preview_csv        heads_csv\137_res_pf_nace_Registr_ekonomickych...
error                                                           None

   ICO  ZDRUD  KODCIS   HODN     DATPLAT    DDATPAKT  PRIZNAK
0   78    450   80004   2100  2026-03-15  2026-01-15      NaN
1   78    450   80004  49410  2026-03-15  2026-01-15      NaN
2   78    450   80143   2100  2026-03-15  2026-01-15      NaN
3   78    450   80143  49410  2026-03-15  2026-01-15      NaN
4  175    450   80004   6820  2026-03-15  2026-01-15      NaN

## 138. [C] Registr ekonomických subjektů - seznam subjektů

                                                             hodnota
dataset_id                                                  res_data
dataset_title        Registr ekonomických subjektů - seznam subjektů
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title            {'cs': 'Seznam ekonomických subjektů v CSV'}
selected_file                                        ds_res_data.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                    3492349
column_count                                                      25
time_columns                                       DDATVZN, DDATPAKT
years_min                                                       1918
years_max                                                       2026
years_count                                                       93
years_sample       1918, 1919, 1920, 1921, 1923, 1924 ... 2021, 2...
years_source                                            data_columns
frequency_catalog                               2x měsíčně [R/P0.5M]
start_catalog                                                   None
end_catalog                                                     None
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina       ekonomické subjekty a podnikatelská struktura
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://www.czso.cz/csu/czso/registr-ekonomick...
preview_csv        heads_csv\138_res_data_Registr_ekonomickych_su...
error                                                           None

,ICO,OKRESLAU,DDATVZN,DDATZAN,ZPZAN,DDATPAKT,FORMA,ROSFORMA,KATPO,NACE,...,TEXTADR,PSC,OBEC_TEXT,COBCE_TEXT,ULICE_TEXT,TYPCDOM,CDOM,COR,DATPLAT,PRIZNAK
0,78,CZ0203,1974-01-01,NaN,NaN,2026-01-15,332,332,240,2100,...,NaN,27061.0,Lány,Lány,Lesní,1.0,140.0,NaN,2026-03-15,NaN
1,175,CZ0100,1972-01-01,NaN,NaN,2026-01-15,332,332,320,6820,...,NaN,11000.0,Praha,Nové Město (Praha 1),Václavské náměstí,1.0,816.0,49.0,2026-03-15,NaN
2,205,CZ0100,1972-01-01,NaN,NaN,2026-01-15,301,301,440,2,...,NaN,16000.0,Praha,Dejvice,Pod Juliskou,1.0,1621.0,5.0,2026-03-15,NaN
3,337,CZ0100,1972-01-01,2022-08-18,1.0,2022-09-01,301,301,0,74,...,"Praha 8 - Libeň, V Mezihoří 1082/2, PSČ 18000",NaN,Praha,NaN,NaN,NaN,NaN,NaN,2026-03-15,NaN
4,345,CZ0100,1981-01-01,NaN,NaN,2026-01-15,301,301,0,18110,...,NaN,16100.0,Praha,Ruzyně,Vlastina,1.0,889.0,23.0,2026-03-15,NaN

## 139. [C] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle kraje místa pracoviště/školy

                                                             hodnota
dataset_id                    sldb2021_vyjizdka_vsichni_kraj_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání a ško...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání a školy podl...
selected_file          ds_sldb2021_vyjizdka_vsichni_kraj_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     282080
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                      školy a školská infrastruktura
uzemni_uroven                                                   kraj
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\139_sldb2021_vyjizdka_vsichni_kraj_p...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,kraj_dojizdky_cis,kraj_dojizdky_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,kraj_dojizdky_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1099335760,903,2623,3249,58,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",NaN,NaN,Želechovice nad Dřevnicí,obec
1,1099004757,9,2623,3249,58,100.0,3018.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Hlavní město Praha,NaN,Želechovice nad Dřevnicí,obec
2,1098777122,3,2623,3249,58,100.0,3018.0,102.0,1.0,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Hlavní město Praha,muž,Želechovice nad Dřevnicí,obec
3,1098778331,6,2623,3249,58,100.0,3018.0,102.0,2.0,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Hlavní město Praha,žena,Želechovice nad Dřevnicí,obec
4,1098671307,2,2623,3249,58,100.0,3026.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Zaměstnaní a žáci, studenti",Středočeský kraj,NaN,Želechovice nad Dřevnicí,obec

## 140. [C] Sčítání 2021 - Vyjíždějící do zaměstnání podle kraje místa pracoviště

                                                             hodnota
dataset_id                 sldb2021_vyjizdka_pracoviste_kraj_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do zaměstnání podle...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do zaměstnání podle kraje ...
selected_file       ds_sldb2021_vyjizdka_pracoviste_kraj_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     282080
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                                   kraj
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\140_sldb2021_vyjizdka_pracoviste_kra...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,kraj_dojizdky_cis,kraj_dojizdky_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,kraj_dojizdky_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1098784826,699,2623,3249,51,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,NaN,NaN,Želechovice nad Dřevnicí,obec
1,1099050715,8,2623,3249,51,100.0,3018.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Hlavní město Praha,NaN,Želechovice nad Dřevnicí,obec
2,1098846461,2,2623,3249,51,100.0,3018.0,102.0,1.0,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Hlavní město Praha,muž,Želechovice nad Dřevnicí,obec
3,1098624340,6,2623,3249,51,100.0,3018.0,102.0,2.0,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Hlavní město Praha,žena,Želechovice nad Dřevnicí,obec
4,1099273104,2,2623,3249,51,100.0,3026.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,Zaměstnaní,Středočeský kraj,NaN,Želechovice nad Dřevnicí,obec

## 141. [C] Ukazatele výzkumu a vývoje podle krajů

                                                             hodnota
dataset_id                                                    210014
dataset_title                 Ukazatele výzkumu a vývoje podle krajů
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                                          ds_210014.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       3300
column_count                                                      13
time_columns                                         stapro_kod, rok
years_min                                                       2005
years_max                                                       2024
years_count                                                       20
years_sample       2005, 2006, 2007, 2008, 2009, 2010 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2005-01-01
end_catalog                                               2024-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                      výzkum a vývoj
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/c435fe23-0578-c...
preview_csv        heads_csv\141_210014_Ukazatele_vyzkumu_a_vyvoj...
error                                                           None

,idhod,hodnota,duvernost,stapro_kod,elpro_id,mj_cis,mj_kod,rok,uzemi_cis,uzemi_kod,ukazatel_txt,mj_txt,uzemi_txt
0,1409293474,18789,verejny,322,1336103,78,80400,2012,100,3018,Výzkumní pracovníci (fyzické osoby k 31.12.),osoba,Hlavní město Praha
1,1409292773,1730,verejny,322,1345880,78,80400,2012,100,3069,Zaměstnanci VaV (fyzické osoby k 31.12),osoba,Ústecký kraj
2,1409293742,454,verejny,322,1336103,78,80400,2012,100,3107,Výzkumní pracovníci (fyzické osoby k 31.12.),osoba,Kraj Vysočina
3,1409293751,9326,verejny,322,1336103,78,80400,2012,100,3115,Výzkumní pracovníci (fyzické osoby k 31.12.),osoba,Jihomoravský kraj
4,1409293025,4057,verejny,322,1345880,78,80400,2012,100,3123,Zaměstnanci VaV (fyzické osoby k 31.12),osoba,Olomoucký kraj

## 142. [C] Zahraniční obchod se zbožím podle vybraných zemí

                                                             hodnota
dataset_id                                                    242010
dataset_title       Zahraniční obchod se zbožím podle vybraných zemí
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2025'}
selected_file                                          ds_242010.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      47567
column_count                                                      13
time_columns                                  stapro_kod, rok, mesic
years_min                                                       2005
years_max                                                       2025
years_count                                                       21
years_sample       2005, 2006, 2007, 2008, 2009, 2010 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2005-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                   zahraniční obchod
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/3cdd6b74-7a4d-6...
preview_csv        heads_csv\142_242010_Zahranicni_obchod_se_zboz...
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,czem_cis,czem_kod,vuzemi_cis,vuzemi_kod,rok,mesic,stapro_txt,czem_txt
0,1495165536,391723.412883,8476,78,206,NaN,NaN,97,19,2025,4,Hodnota dovozu zboží,NaN
1,831736203,3877.000000,8476,78,206,5584.0,ES,97,19,2011,5,Hodnota dovozu zboží,Španělsko
2,831736209,1771.000000,8476,78,206,5584.0,TH,97,19,2011,5,Hodnota dovozu zboží,Thajsko
3,831736211,1931.000000,8476,78,206,5584.0,TR,97,19,2011,5,Hodnota dovozu zboží,Turecko
4,831736215,447.000000,8476,78,206,5584.0,BG,97,19,2011,5,Hodnota dovozu zboží,Bulharsko

## 143. [C] Zaměstnanci a průměrné hrubé měsíční mzdy podle odvětví

                                                             hodnota
dataset_id                                                    110079
dataset_title      Zaměstnanci a průměrné hrubé měsíční mzdy podl...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                     {'cs': 'Data do 4. čtvrtletí 2025'}
selected_file                                          ds_110079.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       8320
column_count                                                      16
time_columns                              stapro_kod, rok, ctvrtleti
years_min                                                       2000
years_max                                                       2025
years_count                                                       26
years_sample       2000, 2001, 2002, 2003, 2004, 2005 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                 čtvrtletní [R/P3M]
start_catalog                                             2000-01-01
end_catalog                                               2025-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                             ostatní
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/a7309d97-c5be-4...
preview_csv        heads_csv\143_110079_Zamestnanci_a_prumerne_hr...
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,typosoby_kod,odvetvi_cis,odvetvi_kod,rok,ctvrtleti,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,typosoby_txt,odvetvi_txt
0,741373605,269.6,316,78,80403,100,5103,Q,2008,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),fyzický,Zdravotní a sociální péče
1,741372615,276.6,316,78,80403,100,5103,H,2008,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),fyzický,Doprava a skladování
2,741381699,255.3,316,78,80403,200,5103,Q,2008,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),přepočtený,Zdravotní a sociální péče
3,741372725,123.4,316,78,80403,100,5103,I,2008,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),fyzický,"Ubytování, stravování a pohostinství"
4,741380819,118.1,316,78,80403,200,5103,I,2008,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),přepočtený,"Ubytování, stravování a pohostinství"

## 144. [C] Zaměstnaní a nezaměstnaní podle výsledků výběrového šetření pracovních sil za kraje

                                                             hodnota
dataset_id                                                    250180
dataset_title      Zaměstnaní a nezaměstnaní podle výsledků výběr...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                     {'cs': 'Data do 3. čtvrtletí 2025'}
selected_file                                          ds_250180.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      58491
column_count                                                      17
time_columns                              stapro_kod, rok, ctvrtleti
years_min                                                       1993
years_max                                                       2025
years_count                                                       33
years_sample       1993, 1994, 1995, 1996, 1997, 1998 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                 čtvrtletní [R/P3M]
start_catalog                                             1993-01-01
end_catalog                                               2025-09-30
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                                      nezaměstnanost
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/6b88a085-ac3f-0...
preview_csv        heads_csv\144_250180_Zamestnani_a_nezamestnani...
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,ekak_cis,ekak_kod,pohlavi_cis,pohlavi_kod,rok,ctvrtleti,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,mj_txt,pohlavi_txt
0,758799743,4574.7,3162,78,80403,NaN,NaN,102.0,2.0,2016,4,97,19,Česká republika,Obyvatelstvo ve věku 15 a více let,tisíc osob,žena
1,758799713,8929.4,3162,78,80403,NaN,NaN,NaN,NaN,2016,4,97,19,Česká republika,Obyvatelstvo ve věku 15 a více let,tisíc osob,NaN
2,758799728,4354.7,3162,78,80403,NaN,NaN,102.0,1.0,2016,4,97,19,Česká republika,Obyvatelstvo ve věku 15 a více let,tisíc osob,muž
3,758799758,5379.2,3162,78,80403,221.0,1.0,NaN,NaN,2016,4,97,19,Česká republika,Pracovní síla (ekonomicky aktivní),tisíc osob,NaN
4,758799773,5187.4,3162,78,80403,221.0,3.0,NaN,NaN,2016,4,97,19,Česká republika,Zaměstnaní,tisíc osob,NaN

## 145. [C] Základní ukazatele národních účtů

                                                             hodnota
dataset_id                                                     50111
dataset_title                      Základní ukazatele národních účtů
status                                              ERROR_SELECTIONS
source_kind                                                     None
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             1990-01-01
end_catalog                                               2024-12-31
hlavni_skupina                             Práce, příjmy a ekonomika
detailni_skupina                           národní a regionální účty
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/e83f3f8f-9ce5-0...
preview_csv                                                     None
error              LKOD/VDB selhalo: JSON parsing failed. Respons...

## 146. [C] Sčítání 2021 - Vyjíždějící do školy podle kraje místa školy

                                                             hodnota
dataset_id                      sldb2021_vyjizdka_skola_kraj_pohlavi
dataset_title      Sčítání 2021 - Vyjíždějící do školy podle kraj...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title       {'cs': 'Vyjíždějící do školy podle kraje místa...
selected_file            ds_sldb2021_vyjizdka_skola_kraj_pohlavi.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                     281779
column_count                                                      19
time_columns                                    sldb_rok, sldb_datum
years_min                                                       2021
years_max                                                       2021
years_count                                                        1
years_sample                                                    2021
years_source                                            data_columns
frequency_catalog                     jednorázové / snapshot [NEVER]
start_catalog                                             2021-03-26
end_catalog                                               2021-03-26
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                      školy a školská infrastruktura
uzemni_uroven                                                   kraj
zdroj_typ                                               Sčítání 2021
page               https://www.czso.cz/csu/czso/vysledky-scitani-...
preview_csv        heads_csv\146_sldb2021_vyjizdka_skola_kraj_poh...
error                                                           None

,idhod,hodnota,ukaz_kod,aktivita_cis,aktivita_kod,kraj_dojizdky_cis,kraj_dojizdky_kod,pohlavi_cis,pohlavi_kod,uzemi_cis,uzemi_kod,sldb_rok,sldb_datum,ukaz_txt,aktivita_txt,kraj_dojizdky_txt,pohlavi_txt,uzemi_txt,uzemi_typ
0,1098535036,204,2623,3072,8,NaN,NaN,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",NaN,NaN,Želechovice nad Dřevnicí,obec
1,1098637799,1,2623,3072,8,100.0,3018.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Hlavní město Praha,NaN,Želechovice nad Dřevnicí,obec
2,1098649744,1,2623,3072,8,100.0,3018.0,102.0,1.0,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Hlavní město Praha,muž,Želechovice nad Dřevnicí,obec
3,1098739594,0,2623,3072,8,100.0,3018.0,102.0,2.0,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Hlavní město Praha,žena,Želechovice nad Dřevnicí,obec
4,1098538143,0,2623,3072,8,100.0,3026.0,NaN,NaN,43,500011,2021,2021-03-26,Počet vyjíždějících osob,"Žáci, studenti",Středočeský kraj,NaN,Želechovice nad Dřevnicí,obec

## 147. [C] Vybavenost domácností informačními a komunikačními technologiemi

                                                             hodnota
dataset_id                                                     60003
dataset_title      Vybavenost domácností informačními a komunikač...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2007-01-01
end_catalog                                               2025-12-31
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                                struktura domácností
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/4f247a99-efac-1...
preview_csv                                                     None
error              LKOD/VDB selhalo: JSON parsing failed. Respons...

## 148. [C] Školy a školská zařízení

                                                             hodnota
dataset_id                                                    230057
dataset_title                               Školy a školská zařízení
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title               {'cs': 'Data do školního roku 2024/2025'}
selected_file                                          ds_230057.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       3420
column_count                                                      18
time_columns                   stapro_kod, rok, casref_od, casref_do
years_min                                                       2006
years_max                                                       2025
years_count                                                       20
years_sample       2006, 2007, 2008, 2009, 2010, 2011 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2006-09-01
end_catalog                                               2025-08-31
hlavni_skupina         Vzdělávání, domácnosti a digitální vybavenost
detailni_skupina                      školy a školská infrastruktura
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/f7249bd5-9284-1...
preview_csv        heads_csv\148_230057_Skoly_a_skolska_zarizeni.csv
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,ds_cis,ds_kod,fs_cis,fs_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,stapro_txt,ds_txt,fs_txt,vuzemi_txt
0,1463590840,4815,6043,78,99998,340,1,NaN,NaN,97,19,2007,2006-09-01,2007-08-31,Počet školských zařízení,Mateřská škola,NaN,Česká republika
1,1463590902,12494,6053,78,99998,340,1,NaN,NaN,97,19,2007,2006-09-01,2007-08-31,Počet tříd,Mateřská škola,NaN,Česká republika
2,1463590903,285419,6059,78,80400,340,1,NaN,NaN,97,19,2007,2006-09-01,2007-08-31,Počet dětí v předškolních zařízeních,Mateřská škola,NaN,Česká republika
3,1463594208,4199,6043,78,99998,340,2,NaN,NaN,97,19,2007,2006-09-01,2007-08-31,Počet školských zařízení,Základní škola,NaN,Česká republika
4,1474738572,44527,6053,78,99998,340,2,NaN,NaN,97,19,2007,2006-09-01,2007-08-31,Počet tříd,Základní škola,NaN,Česká republika

## 149. [C] Pracovní neschopnost pro nemoc a úraz podle okresů a krajů

                                                             hodnota
dataset_id                                                    260017
dataset_title      Pracovní neschopnost pro nemoc a úraz podle ok...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                      {'cs': 'Data do 1. pololetí 2025'}
selected_file                                          ds_260017.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      12036
column_count                                                      13
time_columns                                  stapro_kod, rok, mesic
years_min                                                       2006
years_max                                                       2025
years_count                                                       20
years_sample       2006, 2007, 2008, 2009, 2010, 2011 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2006-01-01
end_catalog                                               2025-06-30
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                                pracovní neschopnost
uzemni_uroven                            více úrovní (ČR–kraj–okres)
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/fc146a4a-7550-9...
preview_csv        heads_csv\149_260017_Pracovni_neschopnost_pro_...
error                                                           None

,idhod,hodnota,duvernost,stapro_kod,spjmen_cis,spjmen_kod,rok,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,spjmen_txt,mesic
0,758468173,22594,verejny,3126,NaN,NaN,2016,101,40312,Písek,Průměrný počet nemocensky pojištěných osob,NaN,12
1,758468008,28351,verejny,3126,NaN,NaN,2016,101,40193,Kolín,Průměrný počet nemocensky pojištěných osob,NaN,12
2,758468010,33542,verejny,3126,NaN,NaN,2016,101,40606,Trutnov,Průměrný počet nemocensky pojištěných osob,NaN,12
3,758468027,30216,verejny,3126,NaN,NaN,2016,101,40703,Blansko,Průměrný počet nemocensky pojištěných osob,NaN,12
4,758468029,25123,verejny,3126,NaN,NaN,2016,101,40428,Cheb,Průměrný počet nemocensky pojištěných osob,NaN,12

## 150. [C] Zemřelí podle měsíců a věkových skupin v České republice

                                                             hodnota
dataset_id                                                    130285
dataset_title      Zemřelí podle měsíců a věkových skupin v České...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2025'}
selected_file                                          ds_130285.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       1260
column_count                                                      12
time_columns                 hodnota, stapro_kod, obdobi, rok, mesic
years_min                                                       1801
years_max                                                       2097
years_count                                                       91
years_sample       1801, 1807, 1808, 1810, 1814, 1819 ... 2079, 2...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2011-01-01
end_catalog                                               2025-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/6c8a873d-2d06-2...
preview_csv        heads_csv\150_130285_Zemreli_podle_mesicu_a_ve...
error                                                           None

,idhod,hodnota,stapro_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,obdobi,rok,mesic,vek_txt,priznak
0,1326287322,46,5393,7700,400000610015000,97,19,2011-01,2011,1,0-14,NaN
1,1326287654,304,5393,7700,410015610045000,97,19,2011-01,2011,1,15-44,NaN
2,1326784494,1837,5393,7700,410045610065000,97,19,2011-01,2011,1,45-64,NaN
3,1326442322,1927,5393,7700,410065610075000,97,19,2011-01,2011,1,65-74,NaN
4,1326442930,2999,5393,7700,410075610085000,97,19,2011-01,2011,1,75-84,NaN

## 151. [C] Zemřelí podle příčin smrti a pohlaví v ČR, krajích a okresech

                                                             hodnota
dataset_id                                                    130143
dataset_title      Zemřelí podle příčin smrti a pohlaví v ČR, kra...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2006-01-01
end_catalog                                               2024-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                            více úrovní (ČR–kraj–okres)
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/578696cc-beb1-4...
preview_csv                                                     None
error              LKOD/VDB selhalo: ('Connection broken: Incompl...

## 152. [C] Zemřelí podle týdnů a věkových skupin v České republice

                                                             hodnota
dataset_id                                                    130185
dataset_title      Zemřelí podle týdnů a věkových skupin v České ...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                        {'cs': 'Data do 52. týdne 2025'}
selected_file                                          ds_130185.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       5474
column_count                                                      14
time_columns       stapro_kod, rok, tyden, roktyden, casref_od, c...
years_min                                                       2011
years_max                                                       2025
years_count                                                       15
years_sample       2011, 2012, 2013, 2014, 2015, 2016 ... 2020, 2...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2011-01-01
end_catalog                                               2025-12-28
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/6c8a873d-2d06-2...
preview_csv        heads_csv\152_130185_Zemreli_podle_tydnu_a_vek...
error                                                           None

,idhod,hodnota,stapro_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,rok,tyden,roktyden,casref_od,casref_do,vek_txt,priznak
0,1326495435,9,5393,7700,400000610015000,97,19,2011,1,2011-W01,2011-01-03,2011-01-09,0-14,NaN
1,1326644592,68,5393,7700,410015610045000,97,19,2011,1,2011-W01,2011-01-03,2011-01-09,15-44,NaN
2,1326227274,444,5393,7700,410045610065000,97,19,2011,1,2011-W01,2011-01-03,2011-01-09,45-64,NaN
3,1326401990,469,5393,7700,410065610075000,97,19,2011,1,2011-W01,2011-01-03,2011-01-09,65-74,NaN
4,1326485348,682,5393,7700,410075610085000,97,19,2011,1,2011-W01,2011-01-03,2011-01-09,75-84,NaN

## 153. [C] Úmrtnostní tabulky pro kraje

                                                             hodnota
dataset_id                                                  130140kr
dataset_title                           Úmrtnostní tabulky pro kraje
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2001-01-01
end_catalog                                               2024-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/05b78c1d-27e9-c...
preview_csv                                                     None
error              LKOD/VDB selhalo: ('Connection broken: Incompl...

## 154. [C] Úmrtnostní tabulky pro okresy

                                                             hodnota
dataset_id                                                  130140ok
dataset_title                          Úmrtnostní tabulky pro okresy
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2001-01-01
end_catalog                                               2024-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                                  okres
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/05b78c1d-27e9-c...
preview_csv                                                     None
error              LKOD/VDB selhalo: ('Connection broken: Incompl...

## 155. [C] Úmrtnostní tabulky pro regiony soudržnosti

                                                             hodnota
dataset_id                                                  130140rs
dataset_title             Úmrtnostní tabulky pro regiony soudržnosti
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                    OD_DEM04_UT_RS_2025052908483691.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     365184
column_count                                                      15
time_columns                        stapro_kod, casref_od, casref_do
years_min                                                       2001
years_max                                                       2024
years_count                                                       24
years_sample       2001, 2002, 2003, 2004, 2005, 2006 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2001-01-01
end_catalog                                               2024-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/05b78c1d-27e9-c...
preview_csv        heads_csv\155_130140rs_Umrtnostni_tabulky_pro_...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
0,889016950,0.004444,8817,102,1,7700,400000600001000,99,213,2001-01-01,2001-12-31,Míra úmrtnosti (mx),muž,0,Praha
1,889093172,0.001258,8817,102,1,7700,400001600002000,99,213,2001-01-01,2001-12-31,Míra úmrtnosti (mx),muž,1,Praha
2,889093174,0.000455,8817,102,1,7700,400002600003000,99,213,2001-01-01,2001-12-31,Míra úmrtnosti (mx),muž,2,Praha
3,889093175,0.000206,8817,102,1,7700,400003600004000,99,213,2001-01-01,2001-12-31,Míra úmrtnosti (mx),muž,3,Praha
4,888941046,0.000121,8817,102,1,7700,400004600005000,99,213,2001-01-01,2001-12-31,Míra úmrtnosti (mx),muž,4,Praha

## 156. [C] Úmrtnostní tabulky pro správní obvody obcí s rozšířenou působností

                                                             hodnota
dataset_id                                                  130140or
dataset_title      Úmrtnostní tabulky pro správní obvody obcí s r...
status                                                  NO_SELECTION
source_kind                                                 DATASTAT
source_code                                                     None
source_title                                                    None
selected_file                                                   None
selected_sheet                                                  None
selected_format                                                 None
row_count                                                       None
column_count                                                    None
time_columns                                                    None
years_min                                                       None
years_max                                                       None
years_count                                                     None
years_sample                                                    None
years_source                                                    None
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2001-01-01
end_catalog                                               2024-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/05b78c1d-27e9-c...
preview_csv                                                     None
error              LKOD/VDB selhalo: ('Connection broken: Incompl...

## 157. [C] Úmrtnostní tabulky pro ČR

                                                             hodnota
dataset_id                                                  130140cr
dataset_title                              Úmrtnostní tabulky pro ČR
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                    OD_DEM04_UT_CR_2025052908205138.CSV
selected_sheet                                                  None
selected_format                                             zip->csv
row_count                                                     198136
column_count                                                      15
time_columns                        stapro_kod, casref_od, casref_do
years_min                                                       1920
years_max                                                       2024
years_count                                                      105
years_sample       1920, 1921, 1922, 1923, 1924, 1925 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             1920-01-01
end_catalog                                               2024-12-31
hlavni_skupina                              Zdraví a sociální služby
detailni_skupina                             úmrtnost a délka života
uzemni_uroven                                  nespecifikováno / mix
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/05b78c1d-27e9-c...
preview_csv        heads_csv\157_130140cr_Umrtnostni_tabulky_pro_...
error              Archiv obsahuje 1 čitelných souborů; profilová...

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
0,796014148,0.197956,8817,102,1,7700,400000600001000,97,19,1920-01-01,1920-12-31,Míra úmrtnosti (mx),muž,0,Česká republika
1,796014152,0.023426,8817,102,1,7700,400001600002000,97,19,1920-01-01,1920-12-31,Míra úmrtnosti (mx),muž,1,Česká republika
2,796154522,0.012121,8817,102,1,7700,400002600003000,97,19,1920-01-01,1920-12-31,Míra úmrtnosti (mx),muž,2,Česká republika
3,796060706,0.010351,8817,102,1,7700,400003600004000,97,19,1920-01-01,1920-12-31,Míra úmrtnosti (mx),muž,3,Česká republika
4,796014159,0.007865,8817,102,1,7700,400004600005000,97,19,1920-01-01,1920-12-31,Míra úmrtnosti (mx),muž,4,Česká republika

## 158. [C] Hospodářská zvířata podle krajů

                                                             hodnota
dataset_id                                                    270230
dataset_title                        Hospodářská zvířata podle krajů
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                                          ds_270230.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       2869
column_count                                                      12
time_columns                              stapro_kod, refobdobi, rok
years_min                                                       2002
years_max                                                       2024
years_count                                                       23
years_sample       2002, 2003, 2004, 2005, 2006, 2007 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2002-01-01
end_catalog                                               2024-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                             zemědělství a lesnictví
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/4793eb3e-331e-6...
preview_csv        heads_csv\158_270230_Hospodarska_zvirata_podle...
error                                                           None

,idhod,hodnota,stapro_kod,DRUHZVIRE_cis,DRUHZVIRE_kod,refobdobi,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,DRUHZVIRE_txt
0,736615562,176454,5560,132,1,20020301,2002,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Skot
1,736615564,525919,5560,132,30,20020301,2002,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Prasata
2,736615565,43683,5560,132,33,20020301,2002,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Prasnice chovné
3,736615566,7606,5560,132,50,20020301,2002,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Ovce
4,736615584,915,5560,132,60,20020301,2002,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Kozy

## 159. [C] Náklady na ochranu životního prostředí a ekonomický přínos těchto aktivit

                                                             hodnota
dataset_id                                                    280041
dataset_title      Náklady na ochranu životního prostředí a ekono...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                                          ds_280041.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      21005
column_count                                                      17
time_columns                                         stapro_kod, rok
years_min                                                       2006
years_max                                                       2024
years_count                                                       19
years_sample       2006, 2007, 2008, 2009, 2010, 2011 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2006-01-01
end_catalog                                               2024-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                         ochrana životního prostředí
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/4917179e-229c-a...
preview_csv        heads_csv\159_280041_Naklady_na_ochranu_zivotn...
error                                                           None

,idhod,hodnota,duvernost,stapro_kod,dnn_cis,dnn_kod,sektor_cis,sektor_kod,ozp_cis,ozp_kod,rok,uzemi_cis,uzemi_kod,ukazatel_txt,ozp_txt,uzemi_txt,typ_uzemi
0,704872646,3404636,verejny,726,NaN,NaN,NaN,NaN,2307,140,2006,97,19,Investice na ochranu životního prostředí,Ekologické nakládání s odpady,Česká republika,NaN
1,704872650,1190118,verejny,726,NaN,NaN,NaN,NaN,2307,113,2006,97,19,Investice na ochranu životního prostředí,Omezování hluku a vibrací (kromě ochrany praco...,Česká republika,NaN
2,704872642,4561770,verejny,726,NaN,NaN,NaN,NaN,2307,130,2006,97,19,Investice na ochranu životního prostředí,Ochrana ovzduší a klimatu,Česká republika,NaN
3,704872654,166382,verejny,726,NaN,NaN,NaN,NaN,2307,115,2006,97,19,Investice na ochranu životního prostředí,Ochrana proti záření,Česká republika,NaN
4,704872652,1084489,verejny,726,NaN,NaN,NaN,NaN,2307,114,2006,97,19,Investice na ochranu životního prostředí,Ochrana krajiny a biodiverzity (druhová rozman...,Česká republika,NaN

## 160. [C] Osevní plochy zemědělských plodin podle krajů

                                                             hodnota
dataset_id                                                    270228
dataset_title          Osevní plochy zemědělských plodin podle krajů
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2025'}
selected_file                                          ds_270228.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      14039
column_count                                                      12
time_columns                                         stapro_kod, rok
years_min                                                       2014
years_max                                                       2025
years_count                                                       12
years_sample       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2014-01-01
end_catalog                                               2025-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                             zemědělství a lesnictví
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/dc16980f-c030-9...
preview_csv        heads_csv\160_270228_Osevni_plochy_zemedelskyc...
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzplod_cis,druhzplod_kod,rok,uzemi_cis,uzemi_kod,uzemi_txt,druhzplod_txt
0,813030909,932,5898,78,11104,208,20300,2018,97,19,Česká republika,Bob polní (na zrno)
1,835551325,757,5898,78,11104,208,20300,2019,97,19,Česká republika,Bob polní (na zrno)
2,889882525,826,5898,78,11104,208,20300,2020,97,19,Česká republika,Bob polní (na zrno)
3,983640346,991,5898,78,11104,208,20300,2021,97,19,Česká republika,Bob polní (na zrno)
4,1128582717,1426,5898,78,11104,208,20300,2022,97,19,Česká republika,Bob polní (na zrno)

## 161. [C] Produkce podnikových a komunálních odpadů podle krajů

                                                             hodnota
dataset_id                                                    280040
dataset_title      Produkce podnikových a komunálních odpadů podl...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2018'}
selected_file                                          ds_280040.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       1485
column_count                                                      12
time_columns                                         stapro_kod, rok
years_min                                                       2008
years_max                                                       2018
years_count                                                       11
years_sample       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2008-01-01
end_catalog                                               2018-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                                              odpady
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/3b160fbc-2258-1...
preview_csv        heads_csv\161_280040_Produkce_podnikovych_a_ko...
error                                                           None

,idhod,hodnota,duvernost,stapro_kod,cznace_cis,cznace_kod,rok,uzemi_cis,uzemi_kod,stapro_txt,cznace_txt,uzemi_txt
0,745245377,136904,verejny,5319,NaN,NaN,2010,100,3042,Celková produkce komunálního odpadu,NaN,Plzeňský kraj
1,745245701,155268,verejny,5319,NaN,NaN,2010,100,3107,Celková produkce komunálního odpadu,NaN,Kraj Vysočina
2,745245431,92661,verejny,5319,NaN,NaN,2010,100,3051,Celková produkce komunálního odpadu,NaN,Karlovarský kraj
3,745245386,137205,verejny,5319,NaN,NaN,2011,100,3042,Celková produkce komunálního odpadu,NaN,Plzeňský kraj
4,745245656,140780,verejny,5319,NaN,NaN,2011,100,3093,Celková produkce komunálního odpadu,NaN,Pardubický kraj

## 162. [C] Sklizeň zemědělských plodin podle krajů

                                                             hodnota
dataset_id                                                    270229
dataset_title                Sklizeň zemědělských plodin podle krajů
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                                          ds_270229.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       7561
column_count                                                      13
time_columns                                         stapro_kod, rok
years_min                                                       2002
years_max                                                       2024
years_count                                                       23
years_sample       2002, 2003, 2004, 2005, 2006, 2007 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2002-01-01
end_catalog                                               2024-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                             zemědělství a lesnictví
uzemni_uroven                                                   kraj
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/6cb85f4c-fc17-8...
preview_csv        heads_csv\162_270229_Sklizen_zemedelskych_plod...
error                                                           None

,idhod,hodnota,stapro_kod,MJ_CIS,MJ_KOD,DRUHZPLOD_cis,DRUHZPLOD_kod,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,DRUHZPLOD_txt
0,697231786,2471666,5906,78,20103,209,806,2002,97,19,Sklizeň zemědělských plodin,Česká republika,Trvalé travní porosty
1,697231787,7082516,5906,78,20103,209,502,2002,97,19,Sklizeň zemědělských plodin,Česká republika,Kukuřice na zeleno
2,697231788,3274437,5906,78,20103,209,505,2002,97,19,Sklizeň zemědělských plodin,Česká republika,Pícniny na orné půdě
3,697231789,709533,5906,78,20103,209,401,2002,97,19,Sklizeň zemědělských plodin,Česká republika,Řepka
4,697231790,3832466,5906,78,20103,208,30200,2002,97,19,Sklizeň zemědělských plodin,Česká republika,Řepa cukrová

## 163. [C] Stavy turů a prasat

                                                             hodnota
dataset_id                                                    270248
dataset_title                                    Stavy turů a prasat
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                                          ds_270248.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                       2997
column_count                                                      21
time_columns                                       stapro_kod, datum
years_min                                                       2016
years_max                                                       2024
years_count                                                        9
years_sample       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2016-01-01
end_catalog                                               2024-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                             zemědělství a lesnictví
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/21f93fd8-f5d1-7...
preview_csv             heads_csv\163_270248_Stavy_turu_a_prasat.csv
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzvire_cis,druhzvire_kod,vek_cis,vek_kod,vekmes_cis,...,hmotkg_cis,hmotkg_kod,datum,uzemi_cis,uzemi_kod,uzemi_txt,mj_txt,key,alttext_cz,alttext_en
0,862705155,1546.020,5560,78,80203,132,30,NaN,NaN,NaN,...,NaN,NaN,2020-12-31,97,19,Česká republika,tisíc kusů,3,Prasata,Pigs
1,821213578,1531.689,5560,78,80203,132,30,NaN,NaN,NaN,...,NaN,NaN,2017-12-31,97,19,Česká republika,tisíc kusů,3,Prasata,Pigs
2,825597517,1508.913,5560,78,80203,132,30,NaN,NaN,NaN,...,NaN,NaN,2019-12-31,97,19,Česká republika,tisíc kusů,3,Prasata,Pigs
3,821214635,1479.283,5560,78,80203,132,30,NaN,NaN,NaN,...,NaN,NaN,2016-12-31,97,19,Česká republika,tisíc kusů,3,Prasata,Pigs
4,825596949,1507.582,5560,78,80203,132,30,NaN,NaN,NaN,...,NaN,NaN,2018-12-31,97,19,Česká republika,tisíc kusů,3,Prasata,Pigs

## 164. [C] Těžba dřeva podle druhů dřevin a typu nahodilé těžby

                                                             hodnota
dataset_id                                                    100013
dataset_title      Těžba dřeva podle druhů dřevin a typu nahodilé...
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                             {'cs': 'Data do roku 2024'}
selected_file                                          ds_100013.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                        525
column_count                                                      16
time_columns                                         stapro_kod, rok
years_min                                                       2000
years_max                                                       2024
years_count                                                       25
years_sample       2000, 2001, 2002, 2003, 2004, 2005 ... 2019, 2...
years_source                                            data_columns
frequency_catalog                                      roční [R/P1Y]
start_catalog                                             2000-01-01
end_catalog                                               2024-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                             zemědělství a lesnictví
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/20da0b5a-c23b-c...
preview_csv        heads_csv\164_100013_Tezba_dreva_podle_druhu_d...
error                                                           None

,idhod,hodnota,stapro_kod,dd_cis,dd_kod,druhtez_cis,druhtez_kod,prictez_cis,prictez_kod,rok,uzemi_cis,uzemi_kod,dd_txt,druhtez_txt,prictez_txt,ELPRO_ID
0,701338287,397847,5966,203,21,NaN,NaN,NaN,NaN,2001,97,19,Dub,NaN,NaN,1845096
1,701338301,768131,5966,202,14,NaN,NaN,NaN,NaN,2001,97,19,Buk,NaN,NaN,1845097
2,701338315,69804,5966,202,17,NaN,NaN,NaN,NaN,2001,97,19,Jasan,NaN,NaN,1845098
3,701338329,29660,5966,202,16,NaN,NaN,NaN,NaN,2001,97,19,Javor,NaN,NaN,1845155
4,701338049,60441,5966,202,22,NaN,NaN,NaN,NaN,2001,97,19,Lípa,NaN,NaN,1845110

## 165. [C] Výroba masa na jatkách

                                                             hodnota
dataset_id                                                    270243
dataset_title                                 Výroba masa na jatkách
status                                                       OK_LKOD
source_kind                                                     LKOD
source_code                                               resource#1
source_title                         {'cs': 'Data do prosince 2025'}
selected_file                                          ds_270243.csv
selected_sheet                                                  None
selected_format                                                  csv
row_count                                                      24722
column_count                                                      17
time_columns                                  stapro_kod, mesic, rok
years_min                                                       2014
years_max                                                       2025
years_count                                                       12
years_sample       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021...
years_source                                            data_columns
frequency_catalog                                    měsíční [R/P1M]
start_catalog                                             2014-01-01
end_catalog                                               2025-12-31
hlavni_skupina               Životní prostředí, zemědělství a odpady
detailni_skupina                             zemědělství a lesnictví
uzemni_uroven                                                     ČR
zdroj_typ                                       běžná statistika ČSÚ
page               https://csu.gov.cz/docs/107508/c305b798-c84c-6...
preview_csv          heads_csv\165_270243_Vyroba_masa_na_jatkach.csv
error                                                           None

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzvire_cis,druhzvire_kod,mesic,rok,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,uzemi_txt,zviremaso_txt,status_kod,status_txt
0,802928356,26.000,5660,78,80200,131,22,1,2014,97,19,Poražená hospodářská zvířata,kus,Česká republika,Skot - voli,NaN,NaN
1,802930431,7.446,5660,78,93503,131,22,1,2014,97,19,Poražená hospodářská zvířata,tuna jatečné hmotnosti,Česká republika,hovězí maso z volů,NaN,NaN
2,802927782,108.000,5660,78,80200,131,50,1,2014,93,1,Poražená hospodářská zvířata,kus,Hlavní město Praha + Středočeský kraj,Jehňata,NaN,NaN
3,802935658,1.372,5660,78,93503,131,50,1,2014,93,1,Poražená hospodářská zvířata,tuna jatečné hmotnosti,Hlavní město Praha + Středočeský kraj,jehněčí maso,NaN,NaN
4,802927882,658.000,5660,78,80200,131,50,1,2014,97,19,Poražená hospodářská zvířata,kus,Česká republika,Jehňata,NaN,NaN

Hotovo. Výstupní manifest: C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_preview\czso_dataset_profiles\dataset_profiles_manifest.csv
Markdown report       : C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_preview\czso_dataset_profiles\dataset_profiles_report.md
CSV head previews     : C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_preview\czso_dataset_profiles\heads_csv

In [5]:
# Souhrnný pohled na výsledný manifest
profiles_df.head()

,order,priority,rodina_datasetu,dataset_id,dataset_title,source_kind,source_code,source_title,selected_file,selected_sheet,...,frequency_catalog,start_catalog,end_catalog,hlavni_skupina,detailni_skupina,uzemni_uroven,zdroj_typ,page,preview_csv,error
0,1,A,Dokončené byty v obcích,200068,Dokončené byty v obcích,LKOD,resource#1,{'cs': 'Data do roku 2024 - revidovaná data'},OD_STA01_2025090509313708.CSV,None,...,roční [R/P1Y],1997-01-01,2024-12-31,Bydlení a technická infrastruktura,bytová výstavba a stavebnictví,obec,běžná statistika ČSÚ,https://csu.gov.cz/docs/107508/b8162c4b-9666-e...,heads_csv\001_200068_Dokoncene_byty_v_obcich.csv,Archiv obsahuje 1 čitelných souborů; profilová...
1,2,A,Obyvatelstvo a domy v obcích podle výsledků sč...,170240-17,Obyvatelstvo a domy v obcích podle výsledků sč...,LKOD,resource#1,{'cs': 'Obyvatelstvo a domy v obcích podle výs...,OD_SLDB_HD_at.csv,None,...,desetileté / census [R/P10Y],None,2011-03-26,Demografie a populace,základní lokální přehled obyvatel a bydlení,obec,běžná statistika ČSÚ,https://csu.gov.cz/docs/107516/9378b376-1a8c-a...,heads_csv\002_170240-17_Obyvatelstvo_a_domy_v_...,Archiv obsahuje 1 čitelných souborů; profilová...
2,3,A,Obyvatelstvo v základních sídelních jednotkách...,170241-17,Obyvatelstvo v základních sídelních jednotkách...,LKOD,resource#1,{'cs': 'Obyvatelstvo v základních sídelních je...,OD_SLD_ZSJD.csv,None,...,jednorázové / snapshot [NEVER],2011-03-26,2011-03-26,Demografie a populace,základní populační stav,podobecní úroveň (část obce/ZSJ),SLDB 2011 / historické sčítání,https://csu.gov.cz/docs/107516/5de62523-0188-3...,heads_csv\003_170241-17_Obyvatelstvo_v_zakladn...,Archiv obsahuje 1 čitelných souborů; profilová...
3,4,A,Sčítání 2021 - Počet obyvatel a počet obydlený...,sldb2021_obyv_byt_cob_zsj,Sčítání 2021 - Počet obyvatel a počet obydlený...,LKOD,resource#1,{'cs': 'Počet obyvatel a počet obydlených bytů...,ds_sldb2021_obyv_byt_cob_zsj.csv,None,...,jednorázové / snapshot [NEVER],2021-03-26,2021-03-26,Demografie a populace,základní lokální přehled obyvatel a bydlení,podobecní úroveň (část obce/ZSJ),Sčítání 2021,https://www.czso.cz/csu/czso/vysledky-scitani-...,heads_csv\004_sldb2021_obyv_byt_cob_zsj_Scitan...,None
4,5,A,Počty ekonomických subjektů podle odvětví přev...,140133q25,Počty ekonomických subjektů podle odvětví přev...,LKOD,resource#1,{'cs': 'Čtvrtletí roku 2025'},OD_ORG02q_2025041409194587.CSV,None,...,čtvrtletní [R/P3M],2025-01-01,2025-03-31,"Práce, příjmy a ekonomika",ostatní,obec,běžná statistika ČSÚ,https://csu.gov.cz/docs/107508/a4b3e19f-9153-f...,heads_csv\005_140133q25_Pocty_ekonomickych_sub...,Archiv obsahuje 1 čitelných souborů; profilová...

In [6]:
# Rychlý přehled stavů a pokrytí let
summary = (
    profiles_df
    .groupby(['priority', 'status'], dropna=False)
    .size()
    .reset_index(name='count')
    .sort_values(['priority', 'count'], ascending=[True, False])
)
summary

  priority              status  count
0        A             OK_LKOD      9
3        B             OK_LKOD    104
2        B        NO_SELECTION      4
1        B    ERROR_SELECTIONS      1
6        C             OK_LKOD     34
5        C        NO_SELECTION     10
4        C    ERROR_SELECTIONS      2
7        C  UNSUPPORTED_FORMAT      1