
# CZSO IKZ – workflow od A do Z (v5: přesnější roky + filtrované previewe)

Notebook dělá celý pipeline v jednom místě:

1. načte `Katalog_trideny`,
2. vybere všechny relevantní datasety (vše kromě `referenční / technická`),
3. stáhne / profiluje každý dataset,
4. zařadí ho do kategorií **A–D**,
5. uloží `head()` + `tail()` previewe a manifest,
6. umožní výstupy zobrazit interaktivně po kategoriích.

## Co je v této verzi opravené

- **přesnější detekce roků** – už se nechytají falešné roky ze sloupce `hodnota`
- **priorita skutečného časového sloupce** – `rok`, `year`, `datum`, `casref`, `obdobi` mají přednost
- **heuristika unikátnosti / podílu zásahů** – sloupec s časem musí mít omezený počet unikátních roků a silný časový signál
- **previewe jsou filtrované ještě před `head()` a `tail()`** – pokud je nalezen řádkový časový sloupec, `head` i `tail` se tvoří už jen z `target years`
- **stažené zdrojové soubory se po preview ve výchozím stavu mažou**

> Výchozí cílové roky jsou **2023 a 2024**.
> Výchozí logika je **přísná**: dataset musí obsahovat **oba roky**.
> Výchozí chování je, že `HEAD` a `TAIL` jsou filtrovány jen na `target years`.

In [1]:

from pathlib import Path
import pandas as pd

from czso_ikz_a_to_z_v5 import (
    read_catalogue,
    select_relevant_datasets,
    process_relevant_catalogue,
    build_summary_tables,
    display_category_results,
)

BASE_DIR = Path.cwd()
CATALOG_XLSX = BASE_DIR / 'czso_katalog_trideny.xlsx'
OUTPUT_DIR = BASE_DIR / 'czso_ikz_a_to_z_output'

TARGET_YEARS = [2023, 2024]
REQUIRE_ALL_TARGET_YEARS = True   # False = stačí libovolný překryv s oknem 2023–2024
FILTER_PREVIEW_TO_TARGET_YEARS = True
HEAD_ROWS = 5
TAIL_ROWS = 5
MAX_DATASETS = None               # např. 20 pro rychlý test
FORCE_REDOWNLOAD = False
DELETE_DOWNLOADED_FILES_AFTER_PREVIEW = True
PAUSE_SECONDS = 0.0

DISPLAY_CATEGORIES = None         # např. ['A'] nebo ['A', 'B']
DISPLAY_LIMIT = None              # např. 10 pro rychlý náhled

print('Base dir :', BASE_DIR)
print('Catalog  :', CATALOG_XLSX)
print('Output   :', OUTPUT_DIR)
print('Years    :', TARGET_YEARS)
print('Strict   :', REQUIRE_ALL_TARGET_YEARS)
print('Filter preview rows to target years :', FILTER_PREVIEW_TO_TARGET_YEARS)

Base dir : C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_ikz_a_to_z_bundle_v5_year_filter
Catalog  : C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_ikz_a_to_z_bundle_v5_year_filter\czso_katalog_trideny.xlsx
Output   : C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_ikz_a_to_z_bundle_v5_year_filter\czso_ikz_a_to_z_output
Years    : [2023, 2024]
Strict   : True
Filter preview rows to target years : True

In [2]:

catalogue_df = read_catalogue(CATALOG_XLSX)
relevant_df = select_relevant_datasets(catalogue_df)

print('Celkem řádků v katalogu:', len(catalogue_df))
print('Relevantních datasetů po odfiltrování technických:', len(relevant_df))

summary_relevance = (
    relevant_df.groupby('relevance_pro_IKZ', dropna=False)
    .size()
    .reset_index(name='pocet_datasetu')
    .sort_values('pocet_datasetu', ascending=False)
    .reset_index(drop=True)
)
summary_relevance

Celkem řádků v katalogu: 1030
Relevantních datasetů po odfiltrování technických: 656

            relevance_pro_IKZ  pocet_datasetu
0  volitelná / specializovaná             390
1             jádrová pro IKŽ             197
2       podpůrná / kontextová              69

In [3]:

relevant_df[['dataset_id', 'dataset_title', 'relevance_pro_IKZ', 'hlavni_skupina', 'detailni_skupina']].head(20)

,dataset_id,dataset_title,relevance_pro_IKZ,hlavni_skupina,detailni_skupina
0,200068,Dokončené byty v obcích,jádrová pro IKŽ,Bydlení a technická infrastruktura,bytová výstavba a stavebnictví
1,sldb2021_byty_obydlenost,Sčítání 2021 - Byty podle obydlenosti,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
2,sldb2021_byty_obydlenost_druhdomu,Sčítání 2021 - Byty podle obydlenosti a druhu ...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
3,sldb2021_byty_plocha,Sčítání 2021 - Obydlené byty podle celkové plo...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
4,sldb2021_byty_energie,Sčítání 2021 - Obydlené byty podle hlavního zd...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
5,sldb2021_obybyty_material_druhdomu,Sčítání 2021 - Obydlené byty podle materiálu n...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
6,sldb2021_obybyty_obdobi_druhdomu,Sčítání 2021 - Obydlené byty podle období výst...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
7,sldb2021_obybyty_poloha_druhdomu,Sčítání 2021 - Obydlené byty podle polohy bytu...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
8,sldb2021_byty_mistnosti,Sčítání 2021 - Obydlené byty podle počtu obytn...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
9,sldb2021_byty_mistnosti_kuchyne,Sčítání 2021 - Obydlené byty podle počtu obytn...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
10,sldb2021_byty_osoby,Sčítání 2021 - Obydlené byty podle počtu osob ...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
11,sldb2021_byty_uzivani,Sčítání 2021 - Obydlené byty podle právního dů...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
12,sldb2021_byty_vytapeni,Sčítání 2021 - Obydlené byty podle převažující...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
13,sldb2021_byty_plyn,Sčítání 2021 - Obydlené byty podle připojení n...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
14,sldb2021_byty_vodovod,Sčítání 2021 - Obydlené byty podle připojení n...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
15,sldb2021_obybyty_vlastnik_druhdomu,Sčítání 2021 - Obydlené byty podle vlastníka a...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
16,sldb2021_obybyty_vytah_druhdomu,Sčítání 2021 - Obydlené byty podle vybavení do...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
17,sldb2021_byty_kuchyne,Sčítání 2021 - Obydlené byty podle vybavení ku...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
18,sldb2021_obybyty_odpad_druhdomu,Sčítání 2021 - Obydlené byty podle způsobu odv...,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení
19,sldbdomy,Výběr údajů ze SLDB 2011 za domy a byty,jádrová pro IKŽ,Bydlení a technická infrastruktura,byty a kvalita bydlení

In [4]:

manifest_df, results = process_relevant_catalogue(
    CATALOG_XLSX,
    output_dir=OUTPUT_DIR,
    target_years=TARGET_YEARS,
    require_all_target_years=REQUIRE_ALL_TARGET_YEARS,
    head_rows=HEAD_ROWS,
    tail_rows=TAIL_ROWS,
    max_datasets=MAX_DATASETS,
    force_redownload=FORCE_REDOWNLOAD,
    cleanup_downloaded_files=DELETE_DOWNLOADED_FILES_AFTER_PREVIEW,
    pause_seconds=PAUSE_SECONDS,
    display_in_notebook=False,
    filter_preview_to_target_years=FILTER_PREVIEW_TO_TARGET_YEARS,
)

print('Počet zpracovaných datasetů:', len(manifest_df))
manifest_df.head()

====================================================================================================
Dataset: 200068 :: Dokončené byty v obcích
status   : OK_LKOD
category : A (obsahuje cílové roky (data) a má primary key)
pk       : True | vuzemi_cis | equivalent
years    : [2023, 2024] missing []
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=28635 | Archiv obsahuje 1 čitelných souborů; použit byl vybraný soubor `OD_STA01_2025090509313708.CSV`.
====================================================================================================
Dataset: sldb2021_byty_obydlenost :: Sčítání 2021 - Byty podle obydlenosti
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_obydlenost_druhdomu :: Sčítání 2021 - Byty podle obydlenosti a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_plocha :: Sčítání 2021 - Obydlené byty podle celkové plochy bytu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_energie :: Sčítání 2021 - Obydlené byty podle hlavního zdroje energie používaného k vytápění
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obybyty_material_druhdomu :: Sčítání 2021 - Obydlené byty podle materiálu nosných zdí a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obybyty_obdobi_druhdomu :: Sčítání 2021 - Obydlené byty podle období výstavby nebo rekonstrukce domu a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obybyty_poloha_druhdomu :: Sčítání 2021 - Obydlené byty podle polohy bytu v domě a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_mistnosti :: Sčítání 2021 - Obydlené byty podle počtu obytných místností
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_mistnosti_kuchyne :: Sčítání 2021 - Obydlené byty podle počtu obytných místností včetně kuchyně
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_osoby :: Sčítání 2021 - Obydlené byty podle počtu osob v bytě
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_uzivani :: Sčítání 2021 - Obydlené byty podle právního důvodu užívání bytu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_vytapeni :: Sčítání 2021 - Obydlené byty podle převažujícího způsobu vytápění
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | uzemi_cis | equivalent
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_plyn :: Sčítání 2021 - Obydlené byty podle připojení na plyn
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_vodovod :: Sčítání 2021 - Obydlené byty podle připojení na vodovod
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obybyty_vlastnik_druhdomu :: Sčítání 2021 - Obydlené byty podle vlastníka a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obybyty_vytah_druhdomu :: Sčítání 2021 - Obydlené byty podle vybavení domu výtahem a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_byty_kuchyne :: Sčítání 2021 - Obydlené byty podle vybavení kuchyní
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obybyty_odpad_druhdomu :: Sčítání 2021 - Obydlené byty podle způsobu odvádění odpadních vod a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldbdomy :: Výběr údajů ze SLDB 2011 za domy a byty
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | None | None
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail zůstaly nefiltrované: nebyl nalezen spolehlivý řádkový časový sloupec | Archiv obsahuje 1 čitelných souborů; použit byl vybraný soubor `SLDB_DOMYBYTY.CSV`.
====================================================================================================
Dataset: sldb2021_domy_obydlen_druh :: Sčítání 2021 - Domy podle obydlenosti a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_zdi :: Sčítání 2021 - Obydlené domy podle materiálu nosných zdí a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_odpad :: Sčítání 2021 - Obydlené domy podle napojení na kanalizaci a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_plyn :: Sčítání 2021 - Obydlené domy podle napojení na plyn a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_vodovod :: Sčítání 2021 - Obydlené domy podle napojení na vodovod a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_obdobi :: Sčítání 2021 - Obydlené domy podle období výstavby a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_byty :: Sčítání 2021 - Obydlené domy podle počtu bytů v domě a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_podlazi_druh :: Sčítání 2021 - Obydlené domy podle počtu nadzemních podlaží a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_vlastnik :: Sčítání 2021 - Obydlené domy podle vlastnictví a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_vytah :: Sčítání 2021 - Obydlené domy podle vybavení výtahem a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_obydomy_druh_vytapeni :: Sčítání 2021 - Obydlené domy způsobu vytápění a druhu domu
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_prumvek_pohlavi :: Sčítání 2021 - Průměrný věk obyvatel podle pohlaví
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: sldb2021_plodnost :: Sčítání 2021 - Plodnost žen
status   : OK_LKOD
category : D (nesplňuje podmínky A/B/C)
pk       : False | uzemi_cis | territorial_non_municipal
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `sldb_rok`; matching_rows=0
====================================================================================================
Dataset: 130141r23 :: Pohyb obyvatel - rok 2022
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | vuzemi_cis | equivalent
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=0
====================================================================================================
Dataset: 130141r24 :: Pohyb obyvatel - rok 2023
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | vuzemi_cis | equivalent
years    : [2023] missing [2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=85306
====================================================================================================
Dataset: 130141r25 :: Pohyb obyvatel - rok 2024
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | vuzemi_cis | equivalent
years    : [2024] missing [2023]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=78744
====================================================================================================
Dataset: 130141r14 :: Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2014
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | vuzemi_cis | equivalent
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=0
====================================================================================================
Dataset: 130141r15 :: Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2015
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | vuzemi_cis | equivalent
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=0
====================================================================================================
Dataset: 130141r16 :: Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2016
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | vuzemi_cis | equivalent
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=0
====================================================================================================
Dataset: 130141r18 :: Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2017
status   : OK_LKOD
category : C (má primary key, ale neobsahuje cílové roky (data))
pk       : True | vuzemi_cis | equivalent
years    : [] missing [2023, 2024]
error    : roky načteny z celého souboru po chunkách | head/tail filtrovány na target years [2023, 2024] přes sloupec `rok`; matching_rows=0
====================================================================================================

C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_ikz_a_to_z_bundle_v5_year_filter\_czso_ikz_a_to_z_v4_base.py:1333: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  manifest_df["_has_pk_sort"] = manifest_df["has_primary_key"].fillna(False).astype(int) * -1
C:\Users\jakub.sekanina\projekt_index_kvality_cr\Datamining-2026\czso_ikz_a_to_z_bundle_v5_year_filter\_czso_ikz_a_to_z_v4_base.py:1334: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  manifest_df["_has_years_sort"] = manifest_df["has_target_years"].fillna(False).astype(int) * -1

Počet zpracovaných datasetů: 656

,order,category,category_reason,relevance_pro_ikz,relevance_rank,dataset_id,dataset_title,rodina_datasetu,hlavni_skupina,detailni_skupina,...,primary_key_kind,primary_key_note,start_catalog,end_catalog,periodicita_text,head_csv,tail_csv,metadata_json,page,error
0,1,A,obsahuje cílové roky (data) a má primary key,jádrová pro IKŽ,0,200068,Dokončené byty v obcích,Dokončené byty v obcích,Bydlení a technická infrastruktura,bytová výstavba a stavebnictví,...,equivalent,územní kód použitelný jako obecní ekvivalent (...,1997-01-01 00:00:00,2024-12-31 00:00:00,roční,previews\A_200068_Dokoncene_byty_v_obcich_head...,previews\A_200068_Dokoncene_byty_v_obcich_tail...,previews\A_200068_Dokoncene_byty_v_obcich_meta...,https://csu.gov.cz/docs/107508/b8162c4b-9666-e...,roky načteny z celého souboru po chunkách | he...
1,2,A,obsahuje cílové roky (data) a má primary key,jádrová pro IKŽ,0,130149,Obyvatelstvo podle pohlaví a základních věkový...,Obyvatelstvo podle pohlaví a základních věkový...,Demografie a populace,věková a pohlavní struktura populace,...,equivalent,územní kód použitelný jako obecní ekvivalent (...,2000-01-01 00:00:00,2024-12-31 00:00:00,roční,previews\A_130149_Obyvatelstvo_podle_pohlavi_a...,previews\A_130149_Obyvatelstvo_podle_pohlavi_a...,previews\A_130149_Obyvatelstvo_podle_pohlavi_a...,https://csu.gov.cz/docs/107508/3de428e4-62ea-3...,roky načteny z celého souboru po chunkách | he...
2,3,A,obsahuje cílové roky (data) a má primary key,podpůrná / kontextová,1,270228,Osevní plochy zemědělských plodin podle krajů,Osevní plochy zemědělských plodin podle krajů,"Životní prostředí, zemědělství a odpady",zemědělství a lesnictví,...,equivalent,územní kód použitelný jako obecní ekvivalent (...,2014-01-01 00:00:00,2025-12-31 00:00:00,roční,previews\A_270228_Osevni_plochy_zemedelskych_p...,previews\A_270228_Osevni_plochy_zemedelskych_p...,previews\A_270228_Osevni_plochy_zemedelskych_p...,https://csu.gov.cz/docs/107508/dc16980f-c030-9...,roky načteny z celého souboru po chunkách | he...
3,4,A,obsahuje cílové roky (data) a má primary key,podpůrná / kontextová,1,260017,Pracovní neschopnost pro nemoc a úraz podle ok...,Pracovní neschopnost pro nemoc a úraz podle ok...,Zdraví a sociální služby,pracovní neschopnost,...,equivalent,územní kód použitelný jako obecní ekvivalent (...,2006-01-01 00:00:00,2025-06-30 00:00:00,roční,previews\A_260017_Pracovni_neschopnost_pro_nem...,previews\A_260017_Pracovni_neschopnost_pro_nem...,previews\A_260017_Pracovni_neschopnost_pro_nem...,https://csu.gov.cz/docs/107508/fc146a4a-7550-9...,roky načteny z celého souboru po chunkách | he...
4,5,A,obsahuje cílové roky (data) a má primary key,podpůrná / kontextová,1,200077,Stavební povolení,Stavební povolení,Bydlení a technická infrastruktura,bytová výstavba a stavebnictví,...,equivalent,územní kód použitelný jako obecní ekvivalent (...,2005-01-01 00:00:00,2025-12-31 00:00:00,měsíční,previews\A_200077_Stavebni_povoleni_head.csv,previews\A_200077_Stavebni_povoleni_tail.csv,previews\A_200077_Stavebni_povoleni_meta.json,https://csu.gov.cz/docs/107508/130319fd-bc2c-2...,roky načteny z celého souboru po chunkách | he...

In [5]:

summary_tables = build_summary_tables(manifest_df)
summary_tables['datasets_by_category']

  category           relevance_pro_ikz  pocet_datasetu
0        A       podpůrná / kontextová              16
1        A             jádrová pro IKŽ               2
2        B       podpůrná / kontextová              12
3        B  volitelná / specializovaná               9
4        C             jádrová pro IKŽ              46
5        C       podpůrná / kontextová               3
6        D  volitelná / specializovaná             381
7        D             jádrová pro IKŽ             149
8        D       podpůrná / kontextová              38

In [6]:

summary_tables['datasets_by_pk_and_years']

  has_primary_key has_target_years  pocet_datasetu
0            True             True              18
1            True            False              49
2           False             True              21
3           False            False             269
4             NaN             True              14
5             NaN            False             282
6             NaN              NaN               3

In [7]:

summary_tables['datasets_by_status']

               status  pocet_datasetu
0             OK_LKOD             363
1  UNSUPPORTED_FORMAT             256
2        NO_SELECTION              37

In [8]:

manifest_df[['order', 'category', 'dataset_id', 'dataset_title', 'relevance_pro_ikz', 'has_primary_key', 'primary_key_column', 'has_target_years', 'target_years_present', 'years_sample', 'status']].head(40)

,order,category,dataset_id,dataset_title,relevance_pro_ikz,has_primary_key,primary_key_column,has_target_years,target_years_present,years_sample,status
0,1,A,200068,Dokončené byty v obcích,jádrová pro IKŽ,True,vuzemi_cis,True,"2023, 2024","1997, 1998, 1999, 2000, 2001, 2002 ... 2019, 2...",OK_LKOD
1,2,A,130149,Obyvatelstvo podle pohlaví a základních věkový...,jádrová pro IKŽ,True,uzemi_cis,True,"2023, 2024","2000, 2001, 2002, 2003, 2004, 2005 ... 2019, 2...",OK_LKOD
2,3,A,270228,Osevní plochy zemědělských plodin podle krajů,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021...",OK_LKOD
3,4,A,260017,Pracovní neschopnost pro nemoc a úraz podle ok...,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2006, 2007, 2008, 2009, 2010, 2011 ... 2020, 2...",OK_LKOD
4,5,A,200077,Stavební povolení,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2005, 2006, 2007, 2008, 2009, 2010 ... 2020, 2...",OK_LKOD
5,6,A,270243,Výroba masa na jatkách,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021...",OK_LKOD
6,7,A,250180,Zaměstnaní a nezaměstnaní podle výsledků výběr...,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","1993, 1994, 1995, 1996, 1997, 1998 ... 2020, 2...",OK_LKOD
7,8,A,230057,Školy a školská zařízení,podpůrná / kontextová,True,vuzemi_cis,True,"2023, 2024","2006, 2007, 2008, 2009, 2010, 2011 ... 2020, 2...",OK_LKOD
8,9,A,270230,Hospodářská zvířata podle krajů,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2002, 2003, 2004, 2005, 2006, 2007 ... 2019, 2...",OK_LKOD
9,10,A,280041,Náklady na ochranu životního prostředí a ekono...,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2006, 2007, 2008, 2009, 2010, 2011 ... 2019, 2...",OK_LKOD
10,11,A,130142,Obyvatelstvo podle pětiletých věkových skupin ...,podpůrná / kontextová,True,vuzemi_cis,True,"2023, 2024","2000, 2001, 2002, 2003, 2004, 2005 ... 2019, 2...",OK_LKOD
11,12,A,110080,Průměrná hrubá měsíční mzda a medián mezd v kr...,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2011, 2012, 2013, 2014, 2015, 2016 ... 2019, 2...",OK_LKOD
12,13,A,270229,Sklizeň zemědělských plodin podle krajů,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2002, 2003, 2004, 2005, 2006, 2007 ... 2019, 2...",OK_LKOD
13,14,A,270248,Stavy turů a prasat,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023...",OK_LKOD
14,15,A,210014,Ukazatele výzkumu a vývoje podle krajů,podpůrná / kontextová,True,uzemi_cis,True,"2023, 2024","2005, 2006, 2007, 2008, 2009, 2010 ... 2019, 2...",OK_LKOD
15,16,A,130143,"Zemřelí podle příčin smrti a pohlaví v ČR, kra...",podpůrná / kontextová,True,vuzemi_cis,True,"2023, 2024","2006, 2007, 2008, 2009, 2010, 2011 ... 2019, 2...",OK_LKOD
16,17,A,130140kr,Úmrtnostní tabulky pro kraje,podpůrná / kontextová,True,vuzemi_cis,True,"2023, 2024","2001, 2002, 2003, 2004, 2005, 2006 ... 2019, 2...",OK_LKOD
17,18,A,130140cr,Úmrtnostní tabulky pro ČR,podpůrná / kontextová,True,vuzemi_cis,True,"2023, 2024","1920, 1921, 1922, 1923, 1924, 1925 ... 2019, 2...",OK_LKOD
18,19,B,241048,Pohyb zboží přes hranice podle vybraných zemí,podpůrná / kontextová,False,vuzemi_cis,True,"2023, 2024","2000, 2001, 2002, 2003, 2004, 2005 ... 2020, 2...",OK_LKOD
19,20,B,200076,Stavební zakázky,podpůrná / kontextová,False,uzemi_cis,True,"2023, 2024","1999, 2000, 2001, 2002, 2003, 2004 ... 2020, 2...",OK_LKOD
20,21,B,242010,Zahraniční obchod se zbožím podle vybraných zemí,podpůrná / kontextová,False,vuzemi_cis,True,"2023, 2024","2005, 2006, 2007, 2008, 2009, 2010 ... 2020, 2...",OK_LKOD
21,22,B,110079,Zaměstnanci a průměrné hrubé měsíční mzdy podl...,podpůrná / kontextová,False,uzemi_cis,True,"2023, 2024","2000, 2001, 2002, 2003, 2004, 2005 ... 2020, 2...",OK_LKOD
22,23,B,130285,Zemřelí podle měsíců a věkových skupin v České...,podpůrná / kontextová,False,vuzemi_cis,True,"2023, 2024","2011, 2012, 2013, 2014, 2015, 2016 ... 2020, 2...",OK_LKOD
23,24,B,130185,Zemřelí podle týdnů a věkových skupin v České ...,podpůrná / kontextová,False,vuzemi_cis,True,"2023, 2024","2011, 2012, 2013, 2014, 2015, 2016 ... 2020, 2...",OK_LKOD
24,25,B,100013,Těžba dřeva podle druhů dřevin a typu nahodilé...,podpůrná / kontextová,False,uzemi_cis,True,"2023, 2024","2000, 2001, 2002, 2003, 2004, 2005 ... 2019, 2...",OK_LKOD
25,26,B,130140ok,Úmrtnostní tabulky pro okresy,podpůrná / kontextová,False,vuzemi_cis,True,"2023, 2024","2001, 2002, 2003, 2004, 2005, 2006 ... 2019, 2...",OK_LKOD
26,27,B,res_pf_nace,Registr ekonomických subjektů - seznam právníc...,podpůrná / kontextová,False,None,True,"2023, 2024","2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025...",OK_LKOD
27,28,B,res_data,Registr ekonomických subjektů - seznam subjektů,podpůrná / kontextová,False,None,True,"2023, 2024","1918, 1919, 1920, 1921, 1923, 1924 ... 2021, 2...",OK_LKOD
28,29,B,150196,Index průmyslové produkce,podpůrná / kontextová,False,None,True,"2023, 2024","2000, 2001, 2002, 2003, 2004, 2005 ... 2020, 2...",OK_LKOD
29,30,B,200075,Index stavební produkce,podpůrná / kontextová,False,None,True,"2023, 2024","2019, 2020, 2021, 2022, 2023, 2024, 2025",OK_LKOD
30,31,B,kv2022kvrk,Volby do zastupitelstev obcí 2022 - registr ka...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
31,32,B,kv2022kvrk,Volby do zastupitelstev obcí 2022 - registr ka...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
32,33,B,kv2022kvros,Volby do zastupitelstev obcí 2022 - registr vo...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
33,34,B,kv2022kvros,Volby do zastupitelstev obcí 2022 - registr vo...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
34,35,B,kv2022kvrzcoco,Volby do zastupitelstev obcí 2022 - registr vo...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
35,36,B,kv2022kvrzcoco,Volby do zastupitelstev obcí 2022 - registr vo...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
36,37,B,kv2022kvt3,Volby do zastupitelstev obcí 2022 - tiskopisy ...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
37,38,B,kv2022kvhl,Volby do zastupitelstev obcí 2022 - výsledky z...,volitelná / specializovaná,False,None,True,"2023, 2024","2022, 2023, 2024, 2025, 2026",OK_LKOD
38,39,B,kz2024cns,Volby do zastupitelstev krajů 2024 - číselník ...,volitelná / specializovaná,False,None,True,"2023, 2024",None,OK_LKOD
39,40,C,190037,Zařízení sociálních služeb podle obcí,jádrová pro IKŽ,True,obec_kod,False,2024,2024,OK_LKOD

In [9]:

display_category_results(
    results,
    categories=DISPLAY_CATEGORIES,
    max_items=DISPLAY_LIMIT,
)

## 001. [A] Dokončené byty v obcích

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,tb_cis,tb_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,stapro_txt,tb_txt,vuzemi_txt
0,1457433181,2,3103,NaN,NaN,43,539783,2024,2024-01-01,2024-12-31,Počet dokončených bytů,NaN,Oplot
1,1457432328,2,3103,NaN,NaN,43,532479,2024,2024-01-01,2024-12-31,Počet dokončených bytů,NaN,Kmetiněves
2,1457433488,1,3103,NaN,NaN,43,551821,2024,2024-01-01,2024-12-31,Počet dokončených bytů,NaN,Tvrdkov
3,1457431105,0,3103,NaN,NaN,43,559806,2024,2024-01-01,2024-12-31,Počet dokončených bytů,NaN,Hlohovice
4,1457433090,3,3103,NaN,NaN,43,574911,2024,2024-01-01,2024-12-31,Počet dokončených bytů,NaN,Dolní Roveň

**TAIL**

,idhod,hodnota,stapro_kod,tb_cis,tb_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,stapro_txt,tb_txt,vuzemi_txt
0,1290507562,0,3103,5711.0,10.0,43,506753,2023,2023-01-01,2023-12-31,Počet dokončených bytů,Bytový dům,Háj ve Slezsku
1,1290510176,0,3103,5711.0,10.0,43,549169,2023,2023-01-01,2023-12-31,Počet dokončených bytů,Bytový dům,Kbelnice
2,1290507434,0,3103,5711.0,10.0,43,500062,2023,2023-01-01,2023-12-31,Počet dokončených bytů,Bytový dům,Krhová
3,1290507436,0,3103,5711.0,10.0,43,500071,2023,2023-01-01,2023-12-31,Počet dokončených bytů,Bytový dům,Poličná
4,1290507438,0,3103,5711.0,10.0,43,500194,2023,2023-01-01,2023-12-31,Počet dokončených bytů,Bytový dům,Polná na Šumavě

## 002. [A] Obyvatelstvo podle pohlaví a základních věkových skupin

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,obdobi,pohlavi_txt,vek_txt,uzemi_txt,uzemi_typ
23,1286408928,1384732,2406,NaN,NaN,NaN,NaN,100,3018,2023-12-31,NaN,NaN,Hlavní město Praha,kraj
24,1446328288,1397880,2406,NaN,NaN,NaN,NaN,100,3018,2024-12-31,NaN,NaN,Hlavní město Praha,kraj
48,1284353798,218647,2406,NaN,NaN,7700.0,4.000006e+14,100,3018,2023-12-31,NaN,0 až 14,Hlavní město Praha,kraj
49,1446176432,215285,2406,NaN,NaN,7700.0,4.000006e+14,100,3018,2024-12-31,NaN,0 až 14,Hlavní město Praha,kraj
73,1284201313,909437,2406,NaN,NaN,7700.0,4.100156e+14,100,3018,2023-12-31,NaN,15 až 64,Hlavní město Praha,kraj

**TAIL**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,obdobi,pohlavi_txt,vek_txt,uzemi_txt,uzemi_typ
1380,1446113233,824554,2406,102.0,2.0,7700.0,4.000006e+14,97,19,2024-12-31,žena,0 až 14,Česká republika,stát
1381,1284208372,3420347,2406,102.0,2.0,7700.0,4.100156e+14,97,19,2023-12-31,žena,15 až 64,Česká republika,stát
1382,1446056827,3426641,2406,102.0,2.0,7700.0,4.100156e+14,97,19,2024-12-31,žena,15 až 64,Česká republika,stát
1383,1284336948,1294312,2406,102.0,2.0,7700.0,4.100658e+14,97,19,2023-12-31,žena,65 a více,Česká republika,stát
1384,1446121230,1303726,2406,102.0,2.0,7700.0,4.100658e+14,97,19,2024-12-31,žena,65 a více,Česká republika,stát

## 003. [A] Osevní plochy zemědělských plodin podle krajů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzplod_cis,druhzplod_kod,rok,uzemi_cis,uzemi_kod,uzemi_txt,druhzplod_txt
5,1306615018,1890.0,5898,78,11104,208.0,20300.0,2023,97,19,Česká republika,Bob polní (na zrno)
6,1461161934,2135.0,5898,78,11104,208.0,20300.0,2024,97,19,Česká republika,Bob polní (na zrno)
17,1306614961,20947.0,5898,78,11104,209.0,306.0,2023,97,19,Česká republika,Brambory
18,1461162245,22747.0,5898,78,11104,209.0,306.0,2024,97,19,Česká republika,Brambory
29,1306613460,17334.0,5898,78,11104,209.0,301.0,2023,97,19,Česká republika,Brambory (mimo rané a sadbové)

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzplod_cis,druhzplod_kod,rok,uzemi_cis,uzemi_kod,uzemi_txt,druhzplod_txt
14013,1306613672,NaN,5898,78,11104,208.0,60506.0,2024,100,3140,Moravskoslezský kraj,Špenát
14024,1263383734,758.0,5898,78,11104,208.0,10200.0,2023,100,3140,Moravskoslezský kraj,Žito
14025,1393172412,686.0,5898,78,11104,208.0,10200.0,2024,100,3140,Moravskoslezský kraj,Žito
14036,1128582903,119438.0,5898,78,11104,NaN,NaN,2023,100,3140,Moravskoslezský kraj,NaN
14037,1306613759,119336.0,5898,78,11104,NaN,NaN,2024,100,3140,Moravskoslezský kraj,NaN

## 004. [A] Pracovní neschopnost pro nemoc a úraz podle okresů a krajů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,duvernost,stapro_kod,spjmen_cis,spjmen_kod,rok,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,spjmen_txt,mesic
1723,1179401782,4751976.00,verejny,3126,NaN,NaN,2023,97,19,Česká republika,Průměrný počet nemocensky pojištěných osob,NaN,6
1912,1286663462,4766867.00,verejny,3126,NaN,NaN,2023,97,19,Česká republika,Průměrný počet nemocensky pojištěných osob,NaN,12
1913,1457982861,4764802.00,verejny,3126,NaN,NaN,2024,97,19,Česká republika,Průměrný počet nemocensky pojištěných osob,NaN,12
5464,1179416638,1327877.00,verejny,3136,NaN,NaN,2023,97,19,Česká republika,Počet nově hlášených případů pracovní neschopn...,NaN,6
5465,1179385250,27.94,verejny,3136,7605.0,HAX,2023,97,19,Česká republika,Počet nově hlášených případů pracovní neschopn...,průměrný počet nemocensky pojištěných osob (10...,6

**TAIL**

,idhod,hodnota,duvernost,stapro_kod,spjmen_cis,spjmen_kod,rok,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,spjmen_txt,mesic
9844,1457982904,7.848212e+07,verejny,3605,NaN,NaN,2024,97,19,Česká republika,Doba pracovní neschopnosti - celkem,NaN,12
9845,1457981566,3.170000e+01,verejny,3605,7605.0,HNX,2024,97,19,Česká republika,Doba pracovní neschopnosti - celkem,nově hlášený případ pracovní neschopnosti,12
11759,1179377050,4.931000e+00,verejny,6049,7605.0,HAX,2023,97,19,Česká republika,Průměrné procento pracovní neschopnosti,průměrný počet nemocensky pojištěných osob (10...,6
11942,1286652142,4.573000e+00,verejny,6049,7605.0,HAX,2023,97,19,Česká republika,Průměrné procento pracovní neschopnosti,průměrný počet nemocensky pojištěných osob (10...,12
11943,1457928320,4.500000e+00,verejny,6049,7605.0,HAX,2024,97,19,Česká republika,Průměrné procento pracovní neschopnosti,průměrný počet nemocensky pojištěných osob (10...,12

## 005. [A] Stavební povolení

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,duvernost,stapro_kod,mj_cis,mj_kod,typstavby_cis,typstavby_kod,smer_cis,smer_kod,mesicod,mesicdo,rok,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,mj_txt,typstavby_txt,smer_txt
2106,1456743179,72066.0,verejny,3030,78,99998,NaN,NaN,NaN,NaN,1,12,2024,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,NaN,NaN
2107,1456738537,11060.0,verejny,3030,78,99998,5632.0,11.0,2323.0,20.0,1,12,2024,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Budovy bytové,nová výstavba
2108,1456736278,8263.0,verejny,3030,78,99998,5632.0,12.0,2323.0,20.0,1,12,2024,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Budovy nebytové,nová výstavba
2109,1456736275,42118.0,verejny,3030,78,99998,5631.0,1.0,NaN,NaN,1,12,2024,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Budovy,NaN
2110,1456741482,24260.0,verejny,3030,78,99998,5632.0,11.0,NaN,NaN,1,12,2024,97,19,Česká republika,Počet vydaných stavebních ohlášení a povolení,četnostní jednotka,Budovy bytové,NaN

**TAIL**

,idhod,hodnota,duvernost,stapro_kod,mj_cis,mj_kod,typstavby_cis,typstavby_kod,smer_cis,smer_kod,mesicod,mesicdo,rok,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,mj_txt,typstavby_txt,smer_txt
3493,1456733739,8572.0,verejny,3037,78,206,5632.0,12.0,5747.0,20.0,1,11,2024,100,3140,Moravskoslezský kraj,Orientační hodnota stavby se stavebním ohlášen...,mil. Kč,Budovy nebytové,"Změny dokončených staveb (nástavby, přístavby ..."
3494,1456739671,12878.0,verejny,3037,78,206,5632.0,11.0,NaN,NaN,1,11,2024,100,3140,Moravskoslezský kraj,Orientační hodnota stavby se stavebním ohlášen...,mil. Kč,Budovy bytové,NaN
3495,1456740765,47455.0,verejny,3037,78,206,NaN,NaN,NaN,NaN,1,11,2024,100,3140,Moravskoslezský kraj,Orientační hodnota stavby se stavebním ohlášen...,mil. Kč,NaN,NaN
3496,1456738984,21206.0,verejny,3037,78,206,5632.0,12.0,NaN,NaN,1,11,2024,100,3140,Moravskoslezský kraj,Orientační hodnota stavby se stavebním ohlášen...,mil. Kč,Budovy nebytové,NaN
3497,1456735185,13371.0,verejny,3037,78,206,5631.0,2.0,NaN,NaN,1,11,2024,100,3140,Moravskoslezský kraj,Orientační hodnota stavby se stavebním ohlášen...,mil. Kč,Inženýrská díla,NaN

## 006. [A] Výroba masa na jatkách

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzvire_cis,druhzvire_kod,mesic,rok,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,uzemi_txt,zviremaso_txt,status_kod,status_txt
18217,1069202458,47.000,5660,78,80200,131,22,1,2023,97,19,Poražená hospodářská zvířata,kus,Česká republika,Skot - voli,NaN,NaN
18218,1069202973,16.006,5660,78,93503,131,22,1,2023,97,19,Poražená hospodářská zvířata,tuna jatečné hmotnosti,Česká republika,hovězí maso z volů,NaN,NaN
18219,1069203015,78.000,5660,78,80200,131,50,1,2023,93,1,Poražená hospodářská zvířata,kus,Hlavní město Praha + Středočeský kraj,Jehňata,NaN,NaN
18220,1069202501,1.373,5660,78,93503,131,50,1,2023,93,1,Poražená hospodářská zvířata,tuna jatečné hmotnosti,Hlavní město Praha + Středočeský kraj,jehněčí maso,NaN,NaN
18221,1069202427,289.000,5660,78,80200,131,50,1,2023,97,19,Poražená hospodářská zvířata,kus,Česká republika,Jehňata,NaN,NaN

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzvire_cis,druhzvire_kod,mesic,rok,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,uzemi_txt,zviremaso_txt,status_kod,status_txt
22448,1380991946,NaN,5660,78,80200,132,7,12,2024,100,3131,Poražená hospodářská zvířata,kus,Zlínský kraj,Skot - krávy,C,Důvěrná hodnota
22449,1380992298,188.000,5660,78,80200,132,7,12,2024,100,3140,Poražená hospodářská zvířata,kus,Moravskoslezský kraj,Skot - krávy,NaN,NaN
22450,1380992191,1.000,5660,78,80200,132,70,12,2024,97,19,Poražená hospodářská zvířata,kus,Česká republika,Koně,NaN,NaN
22451,1380992025,0.307,5660,78,93503,132,70,12,2024,97,19,Poražená hospodářská zvířata,tuna jatečné hmotnosti,Česká republika,koňské maso,NaN,NaN
22452,1380991379,13535.994,5660,78,93503,132,91,12,2024,97,19,Poražená hospodářská zvířata,tuna jatečné hmotnosti,Česká republika,drůbeží maso (drůbež a pštrosi),NaN,NaN

## 007. [A] Zaměstnaní a nezaměstnaní podle výsledků výběrového šetření pracovních sil za kraje

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,ekak_cis,ekak_kod,pohlavi_cis,pohlavi_kod,rok,ctvrtleti,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,mj_txt,pohlavi_txt
2248,1170310791,67.9,3162,78,80403,221.0,4.0,102.0,2.0,2023,2.0,97,19,Česká republika,Nezaměstnaní,tisíc osob,žena
2249,1170310806,2141.8,3162,78,80403,221.0,2.0,102.0,2.0,2023,2.0,97,19,Česká republika,Ekonomicky neaktivní,tisíc osob,žena
2250,1170308320,8666.9,3162,78,80403,NaN,NaN,NaN,NaN,2023,1.0,97,19,Česká republika,Obyvatelstvo ve věku 15 a více let,tisíc osob,NaN
2251,1170308335,4232.2,3162,78,80403,NaN,NaN,102.0,1.0,2023,1.0,97,19,Česká republika,Obyvatelstvo ve věku 15 a více let,tisíc osob,muž
2252,1170308350,4434.6,3162,78,80403,NaN,NaN,102.0,2.0,2023,1.0,97,19,Česká republika,Obyvatelstvo ve věku 15 a více let,tisíc osob,žena

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,ekak_cis,ekak_kod,pohlavi_cis,pohlavi_kod,rok,ctvrtleti,uzemi_cis,uzemi_kod,uzemi_txt,stapro_txt,mj_txt,pohlavi_txt
528,1296595080,4.9,6290,78,83798,NaN,NaN,102.0,2.0,2024,1.0,100,3140,Moravskoslezský kraj,Obecná míra nezaměstnanosti,procento,žena
529,1296576632,3.2,6290,78,83798,NaN,NaN,102.0,1.0,2024,1.0,100,3140,Moravskoslezský kraj,Obecná míra nezaměstnanosti,procento,muž
530,1332566691,3.4,6290,78,83798,NaN,NaN,102.0,1.0,2024,2.0,100,3140,Moravskoslezský kraj,Obecná míra nezaměstnanosti,procento,muž
531,1332566722,3.4,6290,78,83798,NaN,NaN,102.0,2.0,2024,2.0,100,3140,Moravskoslezský kraj,Obecná míra nezaměstnanosti,procento,žena
532,1332566660,3.4,6290,78,83798,NaN,NaN,NaN,NaN,2024,2.0,100,3140,Moravskoslezský kraj,Obecná míra nezaměstnanosti,procento,NaN

## 008. [A] Školy a školská zařízení

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,ds_cis,ds_kod,fs_cis,fs_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,stapro_txt,ds_txt,fs_txt,vuzemi_txt
192,1463590852,5374,6043,78,99998,340,1,NaN,NaN,97,19,2023,2022-09-01,2023-08-31,Počet školských zařízení,Mateřská škola,NaN,Česká republika
193,1463590853,17120,6053,78,99998,340,1,NaN,NaN,97,19,2023,2022-09-01,2023-08-31,Počet tříd,Mateřská škola,NaN,Česká republika
194,1463590854,369205,6059,78,80400,340,1,NaN,NaN,97,19,2023,2022-09-01,2023-08-31,Počet dětí v předškolních zařízeních,Mateřská škola,NaN,Česká republika
195,1463593411,4261,6043,78,99998,340,2,NaN,NaN,97,19,2023,2022-09-01,2023-08-31,Počet školských zařízení,Základní škola,NaN,Česká republika
196,1474737402,51190,6053,78,99998,340,2,NaN,NaN,97,19,2023,2022-09-01,2023-08-31,Počet tříd,Základní škola,NaN,Česká republika

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,ds_cis,ds_kod,fs_cis,fs_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,stapro_txt,ds_txt,fs_txt,vuzemi_txt
3403,1349579249,2266,6053,78,99998,340,3,NaN,NaN,100,3140,2024,2023-09-01,2024-08-31,Počet tříd,Střední škola,NaN,Moravskoslezský kraj
3404,1349579250,52353,6057,78,80400,340,3,NaN,NaN,100,3140,2024,2023-09-01,2024-08-31,Počet žáků,Střední škola,NaN,Moravskoslezský kraj
3405,1463602212,13,6043,78,99998,340,5,NaN,NaN,100,3140,2024,2023-09-01,2024-08-31,Počet školských zařízení,Vyšší odborná škola,NaN,Moravskoslezský kraj
3406,1463600850,106,6053,78,99998,340,5,NaN,NaN,100,3140,2024,2023-09-01,2024-08-31,Počet tříd,Vyšší odborná škola,NaN,Moravskoslezský kraj
3407,1463600851,3485,6058,78,80400,340,5,NaN,NaN,100,3140,2024,2023-09-01,2024-08-31,Počet studentů,Vyšší odborná škola,NaN,Moravskoslezský kraj

## 009. [A] Hospodářská zvířata podle krajů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,DRUHZVIRE_cis,DRUHZVIRE_kod,refobdobi,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,DRUHZVIRE_txt
2645,1248155766,153643,5560,132,1,20231231,2023,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Skot
2646,1247675815,313557,5560,132,30,20231231,2023,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Prasata
2647,1247674869,18255,5560,132,33,20231231,2023,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Prasnice chovné
2648,1284170295,21568,5560,132,50,20231231,2023,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Ovce
2649,1271554560,21568,5560,132,50,20231231,2023,93,1,Počet hospodářských zvířat,Hlavní město Praha + Středočeský kraj,Ovce

**TAIL**

,idhod,hodnota,stapro_kod,DRUHZVIRE_cis,DRUHZVIRE_kod,refobdobi,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,DRUHZVIRE_txt
2864,1388195087,26125,5560,132,30,20241231,2024,100,3140,Počet hospodářských zvířat,Moravskoslezský kraj,Prasata
2865,1388195620,1686,5560,132,33,20241231,2024,100,3140,Počet hospodářských zvířat,Moravskoslezský kraj,Prasnice chovné
2866,1388129647,39064,5560,132,7,20241231,2024,100,3140,Počet hospodářských zvířat,Moravskoslezský kraj,Skot - krávy
2867,1388189433,315347,5560,132,81,20241231,2024,100,3140,Počet hospodářských zvířat,Moravskoslezský kraj,Slepice
2868,1388189264,926290,5560,132,91,20241231,2024,100,3140,Počet hospodářských zvířat,Moravskoslezský kraj,Drůbež a pštrosi

## 010. [A] Náklady na ochranu životního prostředí a ekonomický přínos těchto aktivit

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,duvernost,stapro_kod,dnn_cis,dnn_kod,sektor_cis,sektor_kod,ozp_cis,ozp_kod,rok,uzemi_cis,uzemi_kod,ukazatel_txt,ozp_txt,uzemi_txt,typ_uzemi
1328,1480079433,52105.0,verejny,726,NaN,NaN,NaN,NaN,2307.0,115.0,2024,97,19,Investice na ochranu životního prostředí,Ochrana proti záření,Česká republika,Sídlo investora
1329,1480078691,1538579.0,verejny,726,NaN,NaN,NaN,NaN,2307.0,114.0,2024,97,19,Investice na ochranu životního prostředí,Ochrana krajiny a biodiverzity (druhová rozman...,Česká republika,Sídlo investora
1330,1480079601,11571584.0,verejny,726,NaN,NaN,NaN,NaN,2307.0,111.0,2024,97,19,Investice na ochranu životního prostředí,Ekologické nakládání s odpadními vodami,Česká republika,Sídlo investora
1331,1480079431,207156.0,verejny,726,NaN,NaN,NaN,NaN,2307.0,116.0,2024,97,19,Investice na ochranu životního prostředí,Výzkum a vývoj na ochranu životního prostředí,Česká republika,Sídlo investora
1332,1480079355,2691696.0,verejny,726,NaN,NaN,NaN,NaN,2307.0,112.0,2024,97,19,Investice na ochranu životního prostředí,"Ochrana a sanace půdy, podzemních a povrchovýc...",Česká republika,Sídlo investora

**TAIL**

,idhod,hodnota,duvernost,stapro_kod,dnn_cis,dnn_kod,sektor_cis,sektor_kod,ozp_cis,ozp_kod,rok,uzemi_cis,uzemi_kod,ukazatel_txt,ozp_txt,uzemi_txt,typ_uzemi
20910,1331004674,34492.0,verejny,3932,NaN,NaN,NaN,NaN,2307.0,111.0,2023,100,3140,Tržby z prodeje vedlejších produktů,Ekologické nakládání s odpadními vodami,Moravskoslezský kraj,NaN
20911,1331004758,0.0,verejny,3932,NaN,NaN,NaN,NaN,2307.0,113.0,2023,100,3140,Tržby z prodeje vedlejších produktů,Omezování hluku a vibrací (kromě ochrany praco...,Moravskoslezský kraj,NaN
20912,1331004692,0.0,verejny,3932,NaN,NaN,NaN,NaN,2307.0,115.0,2023,100,3140,Tržby z prodeje vedlejších produktů,Ochrana proti záření,Moravskoslezský kraj,NaN
20913,1331004701,0.0,verejny,3932,NaN,NaN,NaN,NaN,2307.0,116.0,2023,100,3140,Tržby z prodeje vedlejších produktů,Výzkum a vývoj na ochranu životního prostředí,Moravskoslezský kraj,NaN
20914,1331004766,NaN,duverny,3932,NaN,NaN,NaN,NaN,2307.0,180.0,2023,100,3140,Tržby z prodeje vedlejších produktů,Ost.akt.na ochr.živ.pr.,Moravskoslezský kraj,NaN

## 011. [A] Obyvatelstvo podle pětiletých věkových skupin a pohlaví

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_do,pohlavi_txt,vek_txt,vuzemi_txt,uzemi_typ
1518,1286408928,1384732,2406,NaN,NaN,NaN,NaN,100,3018,2023-12-31,NaN,NaN,Hlavní město Praha,kraj
1519,1284319375,12586,2406,NaN,NaN,7700.0,4.000006e+14,100,3018,2023-12-31,NaN,0 až 1 (více nebo rovno 0 a méně než 1),Hlavní město Praha,kraj
1520,1284389234,58005,2406,NaN,NaN,7700.0,4.000016e+14,100,3018,2023-12-31,NaN,1 až 5 (více nebo rovno 1 a méně než 5),Hlavní město Praha,kraj
1521,1284266315,74663,2406,NaN,NaN,7700.0,4.000056e+14,100,3018,2023-12-31,NaN,5 až 10 (více nebo rovno 5 a méně než 10),Hlavní město Praha,kraj
1522,1284276193,73393,2406,NaN,NaN,7700.0,4.100106e+14,100,3018,2023-12-31,NaN,10 až 15 (více nebo rovno 10 a méně než 15),Hlavní město Praha,kraj

**TAIL**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_do,pohlavi_txt,vek_txt,vuzemi_txt,uzemi_typ
1188,1446047508,298814,2406,102.0,2.0,7700.0,4.100756e+14,97,19,2024-12-31,žena,75 až 80 (více nebo rovno 75 a méně než 80),Česká republika,stát
1189,1446092575,192597,2406,102.0,2.0,7700.0,4.100806e+14,97,19,2024-12-31,žena,80 až 85 (více nebo rovno 80 a méně než 85),Česká republika,stát
1190,1446006735,96551,2406,102.0,2.0,7700.0,4.100856e+14,97,19,2024-12-31,žena,85 až 90 (více nebo rovno 85 a méně než 90),Česká republika,stát
1191,1446113914,41311,2406,102.0,2.0,7700.0,4.100906e+14,97,19,2024-12-31,žena,90 až 95 (více nebo rovno 90 a méně než 95),Česká republika,stát
1192,1446026165,9577,2406,102.0,2.0,7700.0,4.100958e+14,97,19,2024-12-31,žena,Od 95 (více nebo rovno 95),Česká republika,stát

## 012. [A] Průměrná hrubá měsíční mzda a medián mezd v krajích

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,SPKVANTIL_cis,SPKVANTIL_kod,POHLAVI_cis,POHLAVI_kod,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,SPKVANTIL_txt,POHLAVI_txt
66,1448846369,48936,5958,NaN,NaN,NaN,NaN,2024,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,NaN,NaN
67,1448846373,41742,5958,7636.0,Q5,NaN,NaN,2024,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,medián,NaN
68,1448846377,53423,5958,NaN,NaN,102.0,1.0,2024,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,NaN,muž
69,1448846381,44740,5958,7636.0,Q5,102.0,1.0,2024,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,medián,muž
70,1448846385,43741,5958,NaN,NaN,102.0,2.0,2024,97,19,Průměrná hrubá mzda na zaměstnance,Česká republika,NaN,žena

**TAIL**

,idhod,hodnota,stapro_kod,SPKVANTIL_cis,SPKVANTIL_kod,POHLAVI_cis,POHLAVI_kod,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,SPKVANTIL_txt,POHLAVI_txt
1249,1286716606,45284,5958,NaN,NaN,102.0,1.0,2023,100,3140,Průměrná hrubá mzda na zaměstnance,Moravskoslezský kraj,NaN,muž
1250,1286716607,37925,5958,NaN,NaN,102.0,2.0,2023,100,3140,Průměrná hrubá mzda na zaměstnance,Moravskoslezský kraj,NaN,žena
1251,1286716608,38073,5958,7636.0,Q5,NaN,NaN,2023,100,3140,Průměrná hrubá mzda na zaměstnance,Moravskoslezský kraj,medián,NaN
1252,1286716609,40741,5958,7636.0,Q5,102.0,1.0,2023,100,3140,Průměrná hrubá mzda na zaměstnance,Moravskoslezský kraj,medián,muž
1253,1286716610,34690,5958,7636.0,Q5,102.0,2.0,2023,100,3140,Průměrná hrubá mzda na zaměstnance,Moravskoslezský kraj,medián,žena

## 013. [A] Sklizeň zemědělských plodin podle krajů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,MJ_CIS,MJ_KOD,DRUHZPLOD_cis,DRUHZPLOD_kod,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,DRUHZPLOD_txt
220,1393173448,4.625367e+06,5906,78,20103,209,103,2024,97,19,Sklizeň zemědělských plodin,Česká republika,Pšenice
221,1393175172,7.130454e+06,5906,78,20103,209,502,2024,97,19,Sklizeň zemědělských plodin,Česká republika,Kukuřice na zeleno
222,1393169642,1.056402e+05,5906,78,20103,208,10200,2024,97,19,Sklizeň zemědělských plodin,Česká republika,Žito
223,1393169723,4.347322e+06,5906,78,20103,209,505,2024,97,19,Sklizeň zemědělských plodin,Česká republika,Pícniny na orné půdě
224,1393177150,9.468908e+05,5906,78,20103,209,401,2024,97,19,Sklizeň zemědělských plodin,Česká republika,Řepka

**TAIL**

,idhod,hodnota,stapro_kod,MJ_CIS,MJ_KOD,DRUHZPLOD_cis,DRUHZPLOD_kod,rok,uzemi_cis,uzemi_kod,STAPRO_TXT,uzemi_txt,DRUHZPLOD_txt
7545,1263381030,65.802558,5908,78,20103,208,30200,2023,100,3140,Hektarový výnos sklizně zemědělských plodin,Moravskoslezský kraj,Řepa cukrová
7546,1263386436,5.132866,5908,78,20103,208,10200,2023,100,3140,Hektarový výnos sklizně zemědělských plodin,Moravskoslezský kraj,Žito
7547,1263383086,5.927721,5908,78,20103,209,112,2023,100,3140,Hektarový výnos sklizně zemědělských plodin,Moravskoslezský kraj,"Obiloviny na zrno (pšenice, žito, ječmen, oves..."
7548,1263385962,3.400415,5908,78,20103,209,806,2023,100,3140,Hektarový výnos sklizně zemědělských plodin,Moravskoslezský kraj,Trvalé travní porosty
7549,1263388608,33.638289,5908,78,20103,209,502,2023,100,3140,Hektarový výnos sklizně zemědělských plodin,Moravskoslezský kraj,Kukuřice na zeleno

## 014. [A] Stavy turů a prasat

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzvire_cis,druhzvire_kod,vek_cis,vek_kod,vekmes_cis,...,hmotkg_cis,hmotkg_kod,datum,uzemi_cis,uzemi_kod,uzemi_txt,mj_txt,key,alttext_cz,alttext_en
7,1247675855,1362.275,5560,78,80203,132,30,NaN,NaN,NaN,...,NaN,NaN,2023-12-31,97,19,Česká republika,tisíc kusů,3,Prasata,Pigs
8,1388196153,1421.823,5560,78,80203,132,30,NaN,NaN,NaN,...,NaN,NaN,2024-12-31,97,19,Česká republika,tisíc kusů,3,Prasata,Pigs
16,1247676187,54.431,5560,78,80203,132,35,NaN,NaN,NaN,...,7700.0,4.201108e+14,2023-12-31,97,19,Česká republika,tisíc kusů,3.3.3,"Prasata ve výkrmu, nad 110 kg","Fattening pigs, over 110 kg"
17,1388195340,67.675,5560,78,80203,132,35,NaN,NaN,NaN,...,7700.0,4.201108e+14,2024-12-31,97,19,Česká republika,tisíc kusů,3.3.3,"Prasata ve výkrmu, nad 110 kg","Fattening pigs, over 110 kg"
25,1247675065,22.331,5560,78,80203,131,41,NaN,NaN,NaN,...,NaN,NaN,2023-12-31,97,19,Česká republika,tisíc kusů,3.4.2.2.1,"Prasničky, nad 50 kg - nezapuštěné","Gilts, over 50 kg - not yet covered"

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,druhzvire_cis,druhzvire_kod,vek_cis,vek_kod,vekmes_cis,...,hmotkg_cis,hmotkg_kod,datum,uzemi_cis,uzemi_kod,uzemi_txt,mj_txt,key,alttext_cz,alttext_en
2978,1388129268,0.000,5560,78,80203,132,207,NaN,NaN,NaN,...,NaN,NaN,2024-12-31,99,281,Moravskoslezsko,tisíc kusů,2.2.1,Buvoli - krávy,Buffaloes - cows
2986,1248154856,15.853,5560,78,80203,132,325,NaN,NaN,7700.0,...,NaN,NaN,2023-12-31,99,281,Moravskoslezsko,tisíc kusů,2.0.2.2.2,"Tuři, do 1 roku - jiní než k porážce - jalovičky","Bovines, up to 1 year - other than for slaught..."
2987,1388131263,16.189,5560,78,80203,132,325,NaN,NaN,7700.0,...,NaN,NaN,2024-12-31,99,281,Moravskoslezsko,tisíc kusů,2.0.2.2.2,"Tuři, do 1 roku - jiní než k porážce - jalovičky","Bovines, up to 1 year - other than for slaught..."
2995,1248157638,38.868,5560,78,80203,132,307,NaN,NaN,NaN,...,NaN,NaN,2023-12-31,99,281,Moravskoslezsko,tisíc kusů,2.0.4.2.2,"Tuři, nad 2 roky - krávy","Bovines, over 2 years - cows"
2996,1388129465,39.064,5560,78,80203,132,307,NaN,NaN,NaN,...,NaN,NaN,2024-12-31,99,281,Moravskoslezsko,tisíc kusů,2.0.4.2.2,"Tuři, nad 2 roky - krávy","Bovines, over 2 years - cows"

## 015. [A] Ukazatele výzkumu a vývoje podle krajů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,duvernost,stapro_kod,elpro_id,mj_cis,mj_kod,rok,uzemi_cis,uzemi_kod,ukazatel_txt,mj_txt,uzemi_txt
540,1338236872,902,verejny,322,1336103,78,80400,2023,100,3069,Výzkumní pracovníci (fyzické osoby k 31.12.),osoba,Ústecký kraj
541,1338236874,4086,verejny,322,1345880,78,80400,2023,100,3034,Zaměstnanci VaV (fyzické osoby k 31.12),osoba,Jihočeský kraj
542,1338236889,1947,verejny,322,1336103,78,80400,2023,100,3085,Výzkumní pracovníci (fyzické osoby k 31.12.),osoba,Královéhradecký kraj
543,1338236890,2078,verejny,322,1336103,78,80400,2023,100,3034,Výzkumní pracovníci (fyzické osoby k 31.12.),osoba,Jihočeský kraj
544,1338236909,828,verejny,322,1336103,78,80400,2023,100,3107,Výzkumní pracovníci (fyzické osoby k 31.12.),osoba,Kraj Vysočina

**TAIL**

,idhod,hodnota,duvernost,stapro_kod,elpro_id,mj_cis,mj_kod,rok,uzemi_cis,uzemi_kod,ukazatel_txt,mj_txt,uzemi_txt
3250,1484913772,17,verejny,2927,10013204,78,206,2024,100,3107,Výdaje na VaV financované z veřejných zdrojů z...,milion korun českých,Kraj Vysočina
3278,1338237122,1427,verejny,2927,10022558,78,206,2023,100,3107,Výdaje na VaV financované z podnikatelských zd...,milion korun českých,Kraj Vysočina
3279,1484913797,1558,verejny,2927,10022558,78,206,2024,100,3107,Výdaje na VaV financované z podnikatelských zd...,milion korun českých,Kraj Vysočina
3289,1338237037,1497,verejny,2927,10022630,78,206,2023,100,3107,Běžné výdaje na výzkum a vědu,milion korun českých,Kraj Vysočina
3290,1484913798,1633,verejny,2927,10022630,78,206,2024,100,3107,Běžné výdaje na výzkum a vědu,milion korun českých,Kraj Vysočina

## 016. [A] Zemřelí podle příčin smrti a pohlaví v ČR, krajích a okresech

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,ps_cis,ps_kod,ps0_cis,ps0_kod,vuzemi_cis,vuzemi_kod,rok,pohlavi_txt,ps_txt,ps0_txt,vuzemi_txt
48,1481729926,1,5393,102.0,1.0,5121,A01,5120,I,97,19,2024,muž,Břišní tyfus a paratyfus,Některé infekční a parazitární nemoci (A00–B99),Česká republika
49,1481726838,1,5393,102.0,1.0,5121,A01,5120,I,100,3093,2024,muž,Břišní tyfus a paratyfus,Některé infekční a parazitární nemoci (A00–B99),Pardubický kraj
50,1481751852,1,5393,102.0,1.0,5121,A01,5120,I,101,40622,2024,muž,Břišní tyfus a paratyfus,Některé infekční a parazitární nemoci (A00–B99),Pardubice
51,1481723918,1,5393,NaN,NaN,5121,A01,5120,I,97,19,2024,NaN,Břišní tyfus a paratyfus,Některé infekční a parazitární nemoci (A00–B99),Česká republika
52,1481739990,1,5393,NaN,NaN,5121,A01,5120,I,100,3093,2024,NaN,Břišní tyfus a paratyfus,Některé infekční a parazitární nemoci (A00–B99),Pardubický kraj

**TAIL**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,ps_cis,ps_kod,ps0_cis,ps0_kod,vuzemi_cis,vuzemi_kod,rok,pohlavi_txt,ps_txt,ps0_txt,vuzemi_txt
3421,1347495990,2366,5393,NaN,NaN,NaN,NaN,NaN,NaN,101,40878,2023,NaN,NaN,NaN,Frýdek-Místek
3422,1347462172,1183,5393,NaN,NaN,NaN,NaN,NaN,NaN,101,40223,2023,NaN,NaN,NaN,Mladá Boleslav
3423,1347460897,1130,5393,NaN,NaN,NaN,NaN,NaN,NaN,101,40525,2023,NaN,NaN,NaN,Česká Lípa
3424,1347436347,1227,5393,NaN,NaN,NaN,NaN,NaN,NaN,101,40690,2023,NaN,NaN,NaN,Žďár nad Sázavou
3425,1347486154,649,5393,NaN,NaN,NaN,NaN,NaN,NaN,101,40274,2023,NaN,NaN,NaN,Rakovník

## 017. [A] Úmrtnostní tabulky pro kraje

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
41832,1455246006,0.001621,8817,102,1,7700,400000600001000,100,3018,2023-01-01,2024-12-31,Míra úmrtnosti (mx),muž,0,Hlavní město Praha
41833,1455388444,0.000263,8817,102,1,7700,400001600002000,100,3018,2023-01-01,2024-12-31,Míra úmrtnosti (mx),muž,1,Hlavní město Praha
41834,1455172546,0.000133,8817,102,1,7700,400002600003000,100,3018,2023-01-01,2024-12-31,Míra úmrtnosti (mx),muž,2,Hlavní město Praha
41835,1455083086,0.000105,8817,102,1,7700,400003600004000,100,3018,2023-01-01,2024-12-31,Míra úmrtnosti (mx),muž,3,Hlavní město Praha
41836,1455083058,0.000083,8817,102,1,7700,400004600005000,100,3018,2023-01-01,2024-12-31,Míra úmrtnosti (mx),muž,4,Hlavní město Praha

**TAIL**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
1908,1454948383,717.0,7193,102,2,7700,420101620102000,100,3140,2023-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,101,Moravskoslezský kraj
1909,1454966357,417.0,7193,102,2,7700,420102620103000,100,3140,2023-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,102,Moravskoslezský kraj
1910,1454941625,233.0,7193,102,2,7700,420103620104000,100,3140,2023-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,103,Moravskoslezský kraj
1911,1454954653,125.0,7193,102,2,7700,420104620105000,100,3140,2023-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,104,Moravskoslezský kraj
1912,1448830916,129.0,7193,102,2,7700,420105620106000,100,3140,2023-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,105,Moravskoslezský kraj

## 018. [A] Úmrtnostní tabulky pro ČR

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
0,1287496751,0.002254,8817,102,1,7700,400000600001000,97,19,2023-01-01,2023-12-31,Míra úmrtnosti (mx),muž,0,Česká republika
1,1287658095,0.000185,8817,102,1,7700,400001600002000,97,19,2023-01-01,2023-12-31,Míra úmrtnosti (mx),muž,1,Česká republika
2,1287486432,0.000110,8817,102,1,7700,400002600003000,97,19,2023-01-01,2023-12-31,Míra úmrtnosti (mx),muž,2,Česká republika
3,1287496379,0.000123,8817,102,1,7700,400003600004000,97,19,2023-01-01,2023-12-31,Míra úmrtnosti (mx),muž,3,Česká republika
4,1287699045,0.000109,8817,102,1,7700,400004600005000,97,19,2023-01-01,2023-12-31,Míra úmrtnosti (mx),muž,4,Česká republika

**TAIL**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,casref_od,casref_do,stapro_txt,pohlavi_txt,vek_txt,vuzemi_txt
3811,1455098397,1276.0,7193,102,2,7700,420101620102000,97,19,2024-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,101,Česká republika
3812,1455248287,796.0,7193,102,2,7700,420102620103000,97,19,2024-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,102,Česká republika
3813,1455247230,478.0,7193,102,2,7700,420103620104000,97,19,2024-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,103,Česká republika
3814,1455393599,277.0,7193,102,2,7700,420104620105000,97,19,2024-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,104,Česká republika
3815,1448830520,339.0,7193,102,2,7700,420105620106000,97,19,2024-01-01,2024-12-31,Tabulkový počet žijících (Lx),žena,105,Česká republika

## 019. [B] Pohyb zboží přes hranice podle vybraných zemí

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,czem_cis,czem_kod,vuzemi_cis,vuzemi_kod,rok,mesic,stapro_txt,czem_txt
15156,1320835559,50365.450565,5757,78,206,NaN,NaN,97,19,2023,3,Bilance pohybu zboží přes hranice,NaN
15157,1320810302,10959.803328,5757,78,206,5584.0,GB,97,19,2023,3,Bilance pohybu zboží přes hranice,Spojené království
15158,1320911598,68358.523779,5757,78,206,5584.0,DE,97,19,2023,3,Bilance pohybu zboží přes hranice,Německo
15159,1320927520,11409.695644,5757,78,206,5584.0,FR,97,19,2023,3,Bilance pohybu zboží přes hranice,Francie
15160,1320944467,-186.638772,5757,78,206,5584.0,US,97,19,2023,3,Bilance pohybu zboží přes hranice,Spojené státy

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,czem_cis,czem_kod,vuzemi_cis,vuzemi_kod,rok,mesic,stapro_txt,czem_txt
1893,1321027792,1538.041300,5756,78,206,5584.0,AU,97,19,2023,6,Obrat pohybu zboží přes hranice,Austrálie
1894,1320571745,2279.863313,5756,78,206,5584.0,AZ,97,19,2023,6,Obrat pohybu zboží přes hranice,Ázerbájdžán
1895,1321122165,3161.474546,5756,78,206,5584.0,IL,97,19,2023,6,Obrat pohybu zboží přes hranice,Izrael
1896,1321219511,4590.012640,5756,78,206,5584.0,SI,97,19,2023,6,Obrat pohybu zboží přes hranice,Slovinsko
1897,1321000811,23562.748682,5756,78,206,5584.0,ES,97,19,2023,6,Obrat pohybu zboží přes hranice,Španělsko

## 020. [B] Stavební zakázky

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,misto_cis,misto_kod,stavprace_cis,stavprace_kod,obdobiod,obdobido,ctvrtleti,rok,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,misto_txt,stavprace_txt
186,1267067570,10758,278,78,206,2478.0,10.0,NaN,NaN,2023-12-31 00:00:00,2023-12-31 00:00:00,4,2023,97,19,Hodnota stavebních zakázek,mil. Kč,zahraničí,NaN
187,1267067536,262150,278,78,206,NaN,NaN,NaN,NaN,2023-12-31 00:00:00,2023-12-31 00:00:00,4,2023,97,19,Hodnota stavebních zakázek,mil. Kč,NaN,NaN
188,1421917798,9702,278,78,206,2478.0,10.0,NaN,NaN,2024-12-31 00:00:00,2024-12-31 00:00:00,4,2024,97,19,Hodnota stavebních zakázek,mil. Kč,zahraničí,NaN
189,1421917663,330009,278,78,206,NaN,NaN,NaN,NaN,2024-12-31 00:00:00,2024-12-31 00:00:00,4,2024,97,19,Hodnota stavebních zakázek,mil. Kč,NaN,NaN
192,1421917660,8363,278,78,206,2478.0,10.0,NaN,NaN,2024-06-30 00:00:00,2024-06-30 00:00:00,2,2024,97,19,Hodnota stavebních zakázek,mil. Kč,zahraničí,NaN

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,misto_cis,misto_kod,stavprace_cis,stavprace_kod,obdobiod,obdobido,ctvrtleti,rok,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,misto_txt,stavprace_txt
964,1421917793,39115,5959,78,206,2478.0,9.0,175.0,23.0,2024-10-01 00:00:00,2024-12-31 00:00:00,4,2024,97,19,Hodnota nových stavebních zakázek,mil. Kč,tuzemsko,Pozemní stavitelství
965,1421917656,60313,5959,78,206,2478.0,9.0,175.0,24.0,2024-10-01 00:00:00,2024-12-31 00:00:00,4,2024,97,19,Hodnota nových stavebních zakázek,mil. Kč,tuzemsko,Inženýrské stavitelství
966,1421917654,100464,5959,78,206,2478.0,9.0,NaN,NaN,2024-07-01 00:00:00,2024-09-30 00:00:00,3,2024,97,19,Hodnota nových stavebních zakázek,mil. Kč,tuzemsko,NaN
967,1421917801,44799,5959,78,206,2478.0,9.0,175.0,23.0,2024-07-01 00:00:00,2024-09-30 00:00:00,3,2024,97,19,Hodnota nových stavebních zakázek,mil. Kč,tuzemsko,Pozemní stavitelství
968,1421917655,55665,5959,78,206,2478.0,9.0,175.0,24.0,2024-07-01 00:00:00,2024-09-30 00:00:00,3,2024,97,19,Hodnota nových stavebních zakázek,mil. Kč,tuzemsko,Inženýrské stavitelství

## 021. [B] Zahraniční obchod se zbožím podle vybraných zemí

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,czem_cis,czem_kod,vuzemi_cis,vuzemi_kod,rok,mesic,stapro_txt,czem_txt
10210,1473731975,294.842766,8476,78,206,5584.0,LV,97,19,2024,7,Hodnota dovozu zboží,Lotyšsko
10211,1473732864,4020.600296,8476,78,206,5584.0,CH,97,19,2024,10,Hodnota dovozu zboží,Švýcarsko
10212,1473733729,1008.724238,8476,78,206,5584.0,GR,97,19,2024,2,Hodnota dovozu zboží,Řecko
10213,1473734662,655.246918,8476,78,206,5584.0,PH,97,19,2024,8,Hodnota dovozu zboží,Filipíny
10214,1473734683,20584.589092,8476,78,206,5584.0,SK,97,19,2024,9,Hodnota dovozu zboží,Slovensko

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,czem_cis,czem_kod,vuzemi_cis,vuzemi_kod,rok,mesic,stapro_txt,czem_txt
47205,1320698219,874.304253,8500,78,206,5584.0,IL,97,19,2023,9,Bilance zboží,Izrael
47206,1320701897,3161.570017,8500,78,206,5584.0,ES,97,19,2023,5,Bilance zboží,Španělsko
47207,1320699576,-2586.767433,8500,78,206,5584.0,TW,97,19,2023,11,Bilance zboží,Tchaj-wan
47208,1320703870,-7425.629783,8500,78,206,5584.0,KR,97,19,2023,4,Bilance zboží,Korejská republika
47209,1320704707,129.192583,8500,78,206,5584.0,SG,97,19,2023,3,Bilance zboží,Singapur

## 022. [B] Zaměstnanci a průměrné hrubé měsíční mzdy podle odvětví

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,typosoby_kod,odvetvi_cis,odvetvi_kod,rok,ctvrtleti,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,typosoby_txt,odvetvi_txt
3640,1457005882,380.9,316,78,80403,100,5103.0,P,2023,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),fyzický,Vzdělávání
3641,1457005886,74.3,316,78,80403,100,5103.0,K,2023,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),fyzický,Peněžnictví a pojišťovnictví
3642,1457005887,223.1,316,78,80403,100,5103.0,F,2023,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),fyzický,Stavebnictví
3643,1457014089,34.8,316,78,80403,200,5103.0,D,2023,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),přepočtený,"Výroba a rozvod elektřiny, plynu, tepla a klim..."
3644,1457006580,18.5,316,78,80403,100,5103.0,B,2023,2,97,19,Průměrný počet zaměstnaných osob,tis. osob (tis. os.),fyzický,Těžba a dobývání

**TAIL**

,idhod,hodnota,stapro_kod,mj_cis,mj_kod,typosoby_kod,odvetvi_cis,odvetvi_kod,rok,ctvrtleti,uzemi_cis,uzemi_kod,stapro_txt,mj_txt,typosoby_txt,odvetvi_txt
8275,1504623066,35980.0,5958,78,200,200,5103.0,A,2024,3,97,19,Průměrná hrubá mzda na zaměstnance,Kč,přepočtený,"Zemědělství, lesnictví, rybářství"
8276,1504628619,32541.0,5958,78,200,200,5103.0,N,2024,3,97,19,Průměrná hrubá mzda na zaměstnance,Kč,přepočtený,Administrativní a podpůrné činnosti
8277,1504618392,67924.0,5958,78,200,100,5103.0,K,2024,3,97,19,Průměrná hrubá mzda na zaměstnance,Kč,fyzický,Peněžnictví a pojišťovnictví
8278,1504618390,29830.0,5958,78,200,100,5103.0,S,2024,3,97,19,Průměrná hrubá mzda na zaměstnance,Kč,fyzický,Ostatní činnosti
8279,1504618976,40906.0,5958,78,200,200,5103.0,E,2024,3,97,19,Průměrná hrubá mzda na zaměstnance,Kč,přepočtený,Zásobování vodou; činnosti související s odpad...

## 023. [B] Zemřelí podle měsíců a věkových skupin v České republice

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,obdobi,rok,mesic,vek_txt,priznak
1008,1289710969,30,5393,7700.0,4.000006e+14,97,19,2023-01,2023,1,0-14,NaN
1009,1289710970,279,5393,7700.0,4.100156e+14,97,19,2023-01,2023,1,15-44,NaN
1010,1289710971,1351,5393,7700.0,4.100456e+14,97,19,2023-01,2023,1,45-64,NaN
1011,1289710972,2501,5393,7700.0,4.100656e+14,97,19,2023-01,2023,1,65-74,NaN
1012,1289710973,3804,5393,7700.0,4.100756e+14,97,19,2023-01,2023,1,75-84,NaN

**TAIL**

,idhod,hodnota,stapro_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,obdobi,rok,mesic,vek_txt,priznak
1171,1457075564,1297,5393,7700.0,4.100456e+14,97,19,2024-12,2024,12,45-64,NaN
1172,1457074178,2118,5393,7700.0,4.100656e+14,97,19,2024-12,2024,12,65-74,NaN
1173,1457074179,3438,5393,7700.0,4.100756e+14,97,19,2024-12,2024,12,75-84,NaN
1174,1457075563,3029,5393,7700.0,4.100858e+14,97,19,2024-12,2024,12,85 a více,NaN
1175,1457090052,10177,5393,NaN,NaN,97,19,2024-12,2024,12,celkem,NaN

## 024. [B] Zemřelí podle týdnů a věkových skupin v České republice

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,rok,tyden,roktyden,casref_od,casref_do,vek_txt,priznak
4382,1289712319,3,5393,7700.0,4.000006e+14,97,19,2023,1,2023-W01,2023-01-02,2023-01-08,0-14,NaN
4383,1289712320,74,5393,7700.0,4.100156e+14,97,19,2023,1,2023-W01,2023-01-02,2023-01-08,15-44,NaN
4384,1289712321,307,5393,7700.0,4.100456e+14,97,19,2023,1,2023-W01,2023-01-02,2023-01-08,45-64,NaN
4385,1289712322,634,5393,7700.0,4.100656e+14,97,19,2023,1,2023-W01,2023-01-02,2023-01-08,65-74,NaN
4386,1289712323,968,5393,7700.0,4.100756e+14,97,19,2023,1,2023-W01,2023-01-02,2023-01-08,75-84,NaN

**TAIL**

,idhod,hodnota,stapro_kod,vek_cis,vek_kod,vuzemi_cis,vuzemi_kod,rok,tyden,roktyden,casref_od,casref_do,vek_txt,priznak
5105,1457033488,284,5393,7700.0,4.100456e+14,97,19,2024,52,2024-W52,2024-12-23,2024-12-29,45-64,NaN
5106,1457045671,451,5393,7700.0,4.100656e+14,97,19,2024,52,2024-W52,2024-12-23,2024-12-29,65-74,NaN
5107,1457033579,813,5393,7700.0,4.100756e+14,97,19,2024,52,2024-W52,2024-12-23,2024-12-29,75-84,NaN
5108,1457033486,720,5393,7700.0,4.100858e+14,97,19,2024,52,2024-W52,2024-12-23,2024-12-29,85 a více,NaN
5109,1457089529,2324,5393,NaN,NaN,97,19,2024,52,2024-W52,2024-12-23,2024-12-29,celkem,NaN

## 025. [B] Těžba dřeva podle druhů dřevin a typu nahodilé těžby

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column     uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,dd_cis,dd_kod,druhtez_cis,druhtez_kod,prictez_cis,prictez_kod,rok,uzemi_cis,uzemi_kod,dd_txt,druhtez_txt,prictez_txt,ELPRO_ID
462,1454501090,353634,5966,202.0,17.0,NaN,NaN,NaN,NaN,2024,97,19,Jasan,NaN,NaN,1845098
463,1454501321,154,5966,202.0,10.0,NaN,NaN,NaN,NaN,2024,97,19,Ostatní jehličnaté dřeviny,NaN,NaN,1845137
464,1454501299,2132670,5966,203.0,2.0,NaN,NaN,NaN,NaN,2024,97,19,Listnaté dřeviny,NaN,NaN,1845106
465,1454501300,58945,5966,202.0,16.0,NaN,NaN,NaN,NaN,2024,97,19,Javor,NaN,NaN,1845155
466,1454501088,15674286,5966,203.0,1.0,NaN,NaN,NaN,NaN,2024,97,19,Jehličnaté dřeviny,NaN,NaN,1845116

**TAIL**

,idhod,hodnota,stapro_kod,dd_cis,dd_kod,druhtez_cis,druhtez_kod,prictez_cis,prictez_kod,rok,uzemi_cis,uzemi_kod,dd_txt,druhtez_txt,prictez_txt,ELPRO_ID
499,1287999222,754180,5966,202.0,14.0,NaN,NaN,NaN,NaN,2023,97,19,Buk,NaN,NaN,1845097
500,1287999223,54251,5966,202.0,22.0,NaN,NaN,NaN,NaN,2023,97,19,Lípa,NaN,NaN,1845110
501,1287999048,414698,5966,203.0,21.0,NaN,NaN,NaN,NaN,2023,97,19,Dub,NaN,NaN,1845096
502,1287999057,4258,5966,NaN,NaN,199.0,22.0,206.0,2.0,2023,97,19,NaN,Nahodilá těžba dřeva,Exhalační příčina,10009764
503,1287999090,2028183,5966,NaN,NaN,199.0,22.0,206.0,9.0,2023,97,19,NaN,Nahodilá těžba dřeva,"Příčina jiná než živelní, exhalační a hmyzová",10009760

## 026. [B] Úmrtnostní tabulky pro okresy

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 027. [B] Registr ekonomických subjektů - seznam právních forem a ekonomických činností

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

Empty DataFrame
Columns: [ICO, ZDRUD, KODCIS, HODN, DATPLAT, DDATPAKT, PRIZNAK]
Index: []

**TAIL**

Empty DataFrame
Columns: [ICO, ZDRUD, KODCIS, HODN, DATPLAT, DDATPAKT, PRIZNAK]
Index: []

## 028. [B] Registr ekonomických subjektů - seznam subjektů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

Empty DataFrame
Columns: [ICO, OKRESLAU, DDATVZN, DDATZAN, ZPZAN, DDATPAKT, FORMA, ROSFORMA, KATPO, NACE, NACE2025, ICZUJ, FIRMA, CISS2010, KODADM, TEXTADR, PSC, OBEC_TEXT, COBCE_TEXT, ULICE_TEXT, TYPCDOM, CDOM, COR, DATPLAT, PRIZNAK]
Index: []

[0 rows x 25 columns]

**TAIL**

Empty DataFrame
Columns: [ICO, OKRESLAU, DDATVZN, DDATZAN, ZPZAN, DDATPAKT, FORMA, ROSFORMA, KATPO, NACE, NACE2025, ICZUJ, FIRMA, CISS2010, KODADM, TEXTADR, PSC, OBEC_TEXT, COBCE_TEXT, ULICE_TEXT, TYPCDOM, CDOM, COR, DATPLAT, PRIZNAK]
Index: []

[0 rows x 25 columns]

## 029. [B] Index průmyslové produkce

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,idhod,hodnota,stapro_kod,casz_cis,casz_kod,cznace_cis,cznace_kod,mesic,rok,mesicz,rokz,stapro_txt,casz_txt,cznace_txt
7936,1289533887,NaN,5249,7626,Z,5104,12,3,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Výroba tabákových výrobků
7937,1289609773,108.7,5249,7626,Z,5104,22,3,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Výroba pryžových a plastových výrobků
7938,1289585532,102.3,5249,7626,Z,5104,32,3,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Ostatní zpracovatelský průmysl
7939,1289533891,127.5,5249,7626,Z,5104,26,3,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,"Výroba počítačů, elektronických a optických př..."
7940,1289533888,106.1,5249,7626,Z,5104,13,3,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Výroba textilií

**TAIL**

,idhod,hodnota,stapro_kod,casz_cis,casz_kod,cznace_cis,cznace_kod,mesic,rok,mesicz,rokz,stapro_txt,casz_txt,cznace_txt
18967,1289564647,146.4,5249,7626,Z,5104,29,10,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,"Výroba motorových vozidel (kromě motocyklů), p..."
18968,1289636701,104.0,5249,7626,Z,5104,9,10,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Podpůrné činnosti při těžbě
18969,1289587759,97.0,5249,7626,Z,5104,31,10,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Výroba nábytku
18970,1289540323,101.3,5249,7626,Z,5104,25,10,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Výroba kovových konstrukcí a kovodělných výrob...
18971,1289658979,135.0,5249,7626,Z,5104,33,10,2023,NaN,2021,Index průmyslové produkce,průměr bazického roku,Opravy a instalace strojů a zařízení

## 030. [B] Index stavební produkce

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,idhod,hodnota,stapro_kod,casz_cis,casz_kod,stavprace_cis,stavprace_kod,oceneni_cis,oceneni_kod,ocisteni_cis,ocisteni_kod,mesic,rok,mesicz,rokz,stapro_txt,casz_txt,stavprace_txt,oceneni_txt,ocisteni_txt
336,1267031514,107.9,5939,7626,Z,NaN,NaN,NaN,NaN,NaN,NaN,3,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Stavební práce celkem,běžné ceny,neočištěno
337,1267045548,84.2,5939,7626,Z,175.0,24.0,NaN,NaN,NaN,NaN,3,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Inženýrské stavitelství,běžné ceny,neočištěno
338,1267060055,120.3,5939,7626,Z,175.0,23.0,NaN,NaN,NaN,NaN,3,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Pozemní stavitelství,běžné ceny,neočištěno
339,1267031517,101.8,5939,7626,Z,175.0,23.0,7603.0,P,NaN,NaN,3,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Pozemní stavitelství,stálé (průměrné) ceny roku,neočištěno
340,1502904526,106.7,5939,7626,Z,175.0,23.0,7603.0,P,7604.0,O,3,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Pozemní stavitelství,stálé (průměrné) ceny roku,"sezónně očištěno, včetně očištění o kalendářní..."

**TAIL**

,idhod,hodnota,stapro_kod,casz_cis,casz_kod,stavprace_cis,stavprace_kod,oceneni_cis,oceneni_kod,ocisteni_cis,ocisteni_kod,mesic,rok,mesicz,rokz,stapro_txt,casz_txt,stavprace_txt,oceneni_txt,ocisteni_txt
1723,1267028275,138.7,5939,7626,Z,175.0,24.0,7603.0,P,NaN,NaN,10,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Inženýrské stavitelství,stálé (průměrné) ceny roku,neočištěno
1724,1267043189,123.6,5939,7626,Z,NaN,NaN,7603.0,P,NaN,NaN,10,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Stavební práce celkem,stálé (průměrné) ceny roku,neočištěno
1725,1502907512,105.3,5939,7626,Z,175.0,24.0,7603.0,P,7604.0,O,10,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Inženýrské stavitelství,stálé (průměrné) ceny roku,"sezónně očištěno, včetně očištění o kalendářní..."
1726,1502904051,122.6,5939,7626,Z,NaN,NaN,7603.0,P,7604.0,P,10,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Stavební práce celkem,stálé (průměrné) ceny roku,"očištěno o kalendářní vlivy, není očištěno o s..."
1727,1502906065,101.9,5939,7626,Z,NaN,NaN,7603.0,P,7604.0,O,10,2023,NaN,2021,Index stavební produkce,průměr bazického roku,Stavební práce celkem,stálé (průměrné) ceny roku,"sezónně očištěno, včetně očištění o kalendářní..."

## 032. [B] Volby do zastupitelstev obcí 2022 - registr kandidátů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,OKRES,KODZASTUP,COBVODU,POR_STR_HL,OSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,...,BYDLISTEN,PSTRANA,NSTRANA,PLATNOST,POCHLASU,PRESKOCENI,POCPROCVSE,MANDAT,PORADIMAND,PORADINAHR
0,20230107,7104,514802,1,1,901,1,Dalibor,Krbílek,NaN,...,Líšná,99.0,80.0,A,94,A,14.57,A,2,0
1,20230107,7104,514802,1,1,901,2,Petra,Maksantová,Bc.,...,Líšná,99.0,80.0,A,80,N,12.40,A,5,0
2,20230107,7104,514802,1,1,901,3,Hana,Petrášová Mrvová,Ing. Mgr.,...,Líšná,99.0,80.0,A,93,A,14.41,A,3,0
3,20230107,7104,514802,1,1,901,4,Markéta,Poláchová Kropáčková,Bc.,...,Líšná,99.0,80.0,A,96,A,14.88,A,1,0
4,20230107,7104,514802,1,1,901,5,Ladislav,Tomčík,NaN,...,Líšná,99.0,80.0,A,83,N,12.86,A,6,0

**TAIL**

,DATUMVOLEB,OKRES,KODZASTUP,COBVODU,POR_STR_HL,OSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,...,BYDLISTEN,PSTRANA,NSTRANA,PLATNOST,POCHLASU,PRESKOCENI,POCPROCVSE,MANDAT,PORADIMAND,PORADINAHR
1767,20241207,3202,578321,1,1,901,2,Vendula,Faistová,NaN,...,Újezd u Plánice,99.0,80.0,A,44,A,19.13,A,4,0
1768,20241207,3202,578321,1,1,901,3,Libuše,Fremundová,NaN,...,Újezd u Plánice,99.0,80.0,A,45,A,19.56,A,3,0
1769,20241207,3202,578321,1,1,901,4,Helena,Bergerová,Mgr.,...,Újezd u Plánice,99.0,80.0,A,41,N,17.82,A,5,0
1770,20241207,3202,578321,1,1,901,5,Martina,Toušová,NaN,...,Újezd u Plánice,99.0,80.0,A,46,A,20.00,A,1,0
1771,20241207,3202,578321,1,1,901,6,Jitka,Dvořáková,Ing.,...,Újezd u Plánice,99.0,80.0,A,9,N,3.91,N,0,1

## 032. [B] Volby do zastupitelstev obcí 2022 - registr kandidátů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,OKRES,KODZASTUP,COBVODU,POR_STR_HL,OSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,...,BYDLISTEN,PSTRANA,NSTRANA,PLATNOST,POCHLASU,PRESKOCENI,POCPROCVSE,MANDAT,PORADIMAND,PORADINAHR
0,20230107,7104,514802,1,1,901,1,Dalibor,Krbílek,NaN,...,Líšná,99.0,80.0,A,94,A,14.57,A,2,0
1,20230107,7104,514802,1,1,901,2,Petra,Maksantová,Bc.,...,Líšná,99.0,80.0,A,80,N,12.40,A,5,0
2,20230107,7104,514802,1,1,901,3,Hana,Petrášová Mrvová,Ing. Mgr.,...,Líšná,99.0,80.0,A,93,A,14.41,A,3,0
3,20230107,7104,514802,1,1,901,4,Markéta,Poláchová Kropáčková,Bc.,...,Líšná,99.0,80.0,A,96,A,14.88,A,1,0
4,20230107,7104,514802,1,1,901,5,Ladislav,Tomčík,NaN,...,Líšná,99.0,80.0,A,83,N,12.86,A,6,0

**TAIL**

,DATUMVOLEB,OKRES,KODZASTUP,COBVODU,POR_STR_HL,OSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,...,BYDLISTEN,PSTRANA,NSTRANA,PLATNOST,POCHLASU,PRESKOCENI,POCPROCVSE,MANDAT,PORADIMAND,PORADINAHR
1767,20241207,3202,578321,1,1,901,2,Vendula,Faistová,NaN,...,Újezd u Plánice,99.0,80.0,A,44,A,19.13,A,4,0
1768,20241207,3202,578321,1,1,901,3,Libuše,Fremundová,NaN,...,Újezd u Plánice,99.0,80.0,A,45,A,19.56,A,3,0
1769,20241207,3202,578321,1,1,901,4,Helena,Bergerová,Mgr.,...,Újezd u Plánice,99.0,80.0,A,41,N,17.82,A,5,0
1770,20241207,3202,578321,1,1,901,5,Martina,Toušová,NaN,...,Újezd u Plánice,99.0,80.0,A,46,A,20.00,A,1,0
1771,20241207,3202,578321,1,1,901,6,Jitka,Dvořáková,Ing.,...,Újezd u Plánice,99.0,80.0,A,9,N,3.91,N,0,1

## 034. [B] Volby do zastupitelstev obcí 2022 - registr volebních stran (ROS)

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,OKRES,KODZASTUP,NAZEVZAST,COBVODU,POR_STR_HL,OSTRANA,VSTRANA,NAZEVCELK,ZKRATKAO30,ZKRATKAO8,POCSTR_SLO,SLOZENI,HLASY_STR,PROCHLSTR,MAND_STR
23276,20230107,7104,514802,Líšná,1,1,901,90,Líšná spolu to zvládneme,Líšná spolu to zvládneme,SNK,1,080,645.0,100.00,7.0
23277,20230107,2106,535397,Želízy,1,1,901,90,Za lepší Želízy,Za lepší Želízy,SNK,1,080,819.0,53.74,4.0
23278,20230107,2106,535397,Želízy,1,2,902,90,Želízy s rozumem,Želízy s rozumem,SNK,1,080,625.0,41.01,3.0
23279,20230107,2106,535397,Želízy,1,3,903,90,Ženy za Želízy,Ženy za Želízy,SNK,1,080,80.0,12.24,0.0
23280,20230107,2111,541451,Třebsko,1,1,807,80,Pavel Šedivý,Pavel Šedivý,NK,1,080,92.0,64.97,1.0

**TAIL**

,DATUMVOLEB,OKRES,KODZASTUP,NAZEVZAST,COBVODU,POR_STR_HL,OSTRANA,VSTRANA,NAZEVCELK,ZKRATKAO30,ZKRATKAO8,POCSTR_SLO,SLOZENI,HLASY_STR,PROCHLSTR,MAND_STR
23598,20241207,3107,563722,Černýšovice,1,3,801,80,Zdeněk Gottwald,Zdeněk Gottwald,NK,1,080,14.0,91.58,1.0
23599,20241207,3107,563722,Černýšovice,1,4,805,80,Josef Karas,Josef Karas,NK,1,080,21.0,137.38,1.0
23600,20241207,3107,563722,Černýšovice,1,5,804,80,Josef Hruška,Josef Hruška,NK,1,080,16.0,104.67,1.0
23601,20241207,3107,563722,Černýšovice,1,6,802,80,Zuzana Blažková,Zuzana Blažková,NK,1,080,17.0,111.21,1.0
23602,20241207,3202,578321,Újezd u Plánice,1,1,901,90,Sdružení nezávislých kandidátů,Sdružení nezávislých kandidátů,SNK,1,080,230.0,100.00,5.0

## 034. [B] Volby do zastupitelstev obcí 2022 - registr volebních stran (ROS)

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,OKRES,KODZASTUP,NAZEVZAST,COBVODU,POR_STR_HL,OSTRANA,VSTRANA,NAZEVCELK,ZKRATKAO30,ZKRATKAO8,POCSTR_SLO,SLOZENI,HLASY_STR,PROCHLSTR,MAND_STR
23276,20230107,7104,514802,Líšná,1,1,901,90,Líšná spolu to zvládneme,Líšná spolu to zvládneme,SNK,1,080,645.0,100.00,7.0
23277,20230107,2106,535397,Želízy,1,1,901,90,Za lepší Želízy,Za lepší Želízy,SNK,1,080,819.0,53.74,4.0
23278,20230107,2106,535397,Želízy,1,2,902,90,Želízy s rozumem,Želízy s rozumem,SNK,1,080,625.0,41.01,3.0
23279,20230107,2106,535397,Želízy,1,3,903,90,Ženy za Želízy,Ženy za Želízy,SNK,1,080,80.0,12.24,0.0
23280,20230107,2111,541451,Třebsko,1,1,807,80,Pavel Šedivý,Pavel Šedivý,NK,1,080,92.0,64.97,1.0

**TAIL**

,DATUMVOLEB,OKRES,KODZASTUP,NAZEVZAST,COBVODU,POR_STR_HL,OSTRANA,VSTRANA,NAZEVCELK,ZKRATKAO30,ZKRATKAO8,POCSTR_SLO,SLOZENI,HLASY_STR,PROCHLSTR,MAND_STR
23598,20241207,3107,563722,Černýšovice,1,3,801,80,Zdeněk Gottwald,Zdeněk Gottwald,NK,1,080,14.0,91.58,1.0
23599,20241207,3107,563722,Černýšovice,1,4,805,80,Josef Karas,Josef Karas,NK,1,080,21.0,137.38,1.0
23600,20241207,3107,563722,Černýšovice,1,5,804,80,Josef Hruška,Josef Hruška,NK,1,080,16.0,104.67,1.0
23601,20241207,3107,563722,Černýšovice,1,6,802,80,Zuzana Blažková,Zuzana Blažková,NK,1,080,17.0,111.21,1.0
23602,20241207,3202,578321,Újezd u Plánice,1,1,901,90,Sdružení nezávislých kandidátů,Sdružení nezávislých kandidátů,SNK,1,080,230.0,100.00,5.0

## 036. [B] Volby do zastupitelstev obcí 2022 - registr volených zastupitelstev (RZCOCO)

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,KRAJ,OKRES,TYPZASTUP,DRUHZASTUP,KODZASTUP,NAZEVZAST,OBEC,NAZEVOBCE,ORP,...,MAXOKRSEK7,MINOKRSEK8,MAXOKRSEK8,MINOKRSEK9,MAXOKRSEK9,MINOKRSE10,MAXOKRSE10,TYPDUVODU,POCET_VS,STAV_OBCE
6533,20230107,7100,7104,1,1,514802,Líšná,514802,Líšná,7109,...,0,0,0,0,0,0,0,2,1,0
6534,20230107,2100,2106,1,1,535397,Želízy,535397,Želízy,2114,...,0,0,0,0,0,0,0,1,3,0
6535,20230107,2100,2111,1,1,541451,Třebsko,541451,Třebsko,2120,...,0,0,0,0,0,0,0,2,9,0
6536,20230107,3200,3204,1,1,546372,Buková,546372,Buková,3210,...,0,0,0,0,0,0,0,2,2,0
6537,20230107,4200,4204,1,1,546895,Brodec,546895,Brodec,4207,...,0,0,0,0,0,0,0,2,0,1

**TAIL**

,DATUMVOLEB,KRAJ,OKRES,TYPZASTUP,DRUHZASTUP,KODZASTUP,NAZEVZAST,OBEC,NAZEVOBCE,ORP,...,MAXOKRSEK7,MINOKRSEK8,MAXOKRSEK8,MINOKRSEK9,MAXOKRSEK9,MINOKRSE10,MAXOKRSE10,TYPDUVODU,POCET_VS,STAV_OBCE
6637,20241207,2100,2109,1,1,536130,Kostelní Hlavno,536130,Kostelní Hlavno,2103,...,0,0,0,0,0,0,0,1,2,0
6638,20241207,4200,4204,1,1,546895,Brodec,546895,Brodec,4207,...,0,0,0,0,0,0,0,2,0,1
6639,20241207,3100,3104,1,1,562254,Paseky,562254,Paseky,3108,...,0,0,0,0,0,0,0,1,6,0
6640,20241207,3100,3107,1,1,563722,Černýšovice,563722,Černýšovice,3112,...,0,0,0,0,0,0,0,1,6,0
6641,20241207,3200,3202,1,1,578321,Újezd u Plánice,578321,Újezd u Plánice,3205,...,0,0,0,0,0,0,0,1,1,0

## 036. [B] Volby do zastupitelstev obcí 2022 - registr volených zastupitelstev (RZCOCO)

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,KRAJ,OKRES,TYPZASTUP,DRUHZASTUP,KODZASTUP,NAZEVZAST,OBEC,NAZEVOBCE,ORP,...,MAXOKRSEK7,MINOKRSEK8,MAXOKRSEK8,MINOKRSEK9,MAXOKRSEK9,MINOKRSE10,MAXOKRSE10,TYPDUVODU,POCET_VS,STAV_OBCE
6533,20230107,7100,7104,1,1,514802,Líšná,514802,Líšná,7109,...,0,0,0,0,0,0,0,2,1,0
6534,20230107,2100,2106,1,1,535397,Želízy,535397,Želízy,2114,...,0,0,0,0,0,0,0,1,3,0
6535,20230107,2100,2111,1,1,541451,Třebsko,541451,Třebsko,2120,...,0,0,0,0,0,0,0,2,9,0
6536,20230107,3200,3204,1,1,546372,Buková,546372,Buková,3210,...,0,0,0,0,0,0,0,2,2,0
6537,20230107,4200,4204,1,1,546895,Brodec,546895,Brodec,4207,...,0,0,0,0,0,0,0,2,0,1

**TAIL**

,DATUMVOLEB,KRAJ,OKRES,TYPZASTUP,DRUHZASTUP,KODZASTUP,NAZEVZAST,OBEC,NAZEVOBCE,ORP,...,MAXOKRSEK7,MINOKRSEK8,MAXOKRSEK8,MINOKRSEK9,MAXOKRSEK9,MINOKRSE10,MAXOKRSE10,TYPDUVODU,POCET_VS,STAV_OBCE
6637,20241207,2100,2109,1,1,536130,Kostelní Hlavno,536130,Kostelní Hlavno,2103,...,0,0,0,0,0,0,0,1,2,0
6638,20241207,4200,4204,1,1,546895,Brodec,546895,Brodec,4207,...,0,0,0,0,0,0,0,2,0,1
6639,20241207,3100,3104,1,1,562254,Paseky,562254,Paseky,3108,...,0,0,0,0,0,0,0,1,6,0
6640,20241207,3100,3107,1,1,563722,Černýšovice,563722,Černýšovice,3112,...,0,0,0,0,0,0,0,1,6,0
6641,20241207,3200,3202,1,1,578321,Újezd u Plánice,578321,Újezd u Plánice,3205,...,0,0,0,0,0,0,0,1,1,0

## 037. [B] Volby do zastupitelstev obcí 2022 - tiskopisy T3 za okrsky

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,ID_OKRSKY,KRAJ,OKRES,OBEC,OKRSEK,TYPZASTUP,COBVODU,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK,POCET_VS,POC_VS_HL,KODZASTUP
16857,20230107,33693,2100,2106,535397,1,1,1,413,248,248,1524,3,3,535397
16858,20230107,33694,2100,2107,571148,1,1,1,126,96,96,341,9,9,571148
16859,20230107,33695,2100,2111,541451,1,1,1,207,159,159,708,9,9,541451
16860,20230107,33696,3100,3104,549657,1,1,1,123,77,77,502,3,3,549657
16861,20230107,33697,3200,3204,546372,1,1,1,197,145,145,991,2,2,546372

**TAIL**

,DATUMVOLEB,ID_OKRSKY,KRAJ,OKRES,OBEC,OKRSEK,TYPZASTUP,COBVODU,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK,POCET_VS,POC_VS_HL,KODZASTUP
16958,20241005,33794,8100,8105,553042,1,1,1,117,86,85,412,2,2,553042
16959,20241207,33795,2100,2109,536130,1,1,1,379,242,242,1572,2,2,536130
16960,20241207,33796,3100,3104,562254,1,1,1,143,87,87,326,6,6,562254
16961,20241207,33797,3100,3107,563722,1,1,1,73,31,31,107,6,6,563722
16962,20241207,33798,3200,3202,578321,1,1,1,97,61,61,230,1,1,578321

## 038. [B] Volby do zastupitelstev obcí 2022 - výsledky za okrsky

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,DATUMVOLEB,ID_OKRSKY,KRAJ,OKRES,OBEC,OKRSEK,TYPZASTUP,POR_STR_HL,POC_HLASU,HLASY_01,...,HLASY_61,HLASY_62,HLASY_63,HLASY_64,HLASY_65,HLASY_66,HLASY_67,HLASY_68,HLASY_69,HLASY_70
0,20230107,33693,2100,2106,535397,1,1,1,819,110,...,0,0,0,0,0,0,0,0,0,0
1,20230107,33693,2100,2106,535397,1,1,2,625,92,...,0,0,0,0,0,0,0,0,0,0
2,20230107,33693,2100,2106,535397,1,1,3,80,31,...,0,0,0,0,0,0,0,0,0,0
3,20230107,33694,2100,2107,571148,1,1,1,68,68,...,0,0,0,0,0,0,0,0,0,0
4,20230107,33694,2100,2107,571148,1,1,2,37,37,...,0,0,0,0,0,0,0,0,0,0

**TAIL**

,DATUMVOLEB,ID_OKRSKY,KRAJ,OKRES,OBEC,OKRSEK,TYPZASTUP,POR_STR_HL,POC_HLASU,HLASY_01,...,HLASY_61,HLASY_62,HLASY_63,HLASY_64,HLASY_65,HLASY_66,HLASY_67,HLASY_68,HLASY_69,HLASY_70
335,20241207,33797,3100,3107,563722,1,1,3,14,14,...,0,0,0,0,0,0,0,0,0,0
336,20241207,33797,3100,3107,563722,1,1,4,21,21,...,0,0,0,0,0,0,0,0,0,0
337,20241207,33797,3100,3107,563722,1,1,5,16,16,...,0,0,0,0,0,0,0,0,0,0
338,20241207,33797,3100,3107,563722,1,1,6,17,17,...,0,0,0,0,0,0,0,0,0,0
339,20241207,33798,3200,3202,578321,1,1,1,230,45,...,0,0,0,0,0,0,0,0,0,0

## 039. [B] Volby do zastupitelstev krajů 2024 - číselník navrhujících stran

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key            False
primary_key_column          None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,24,Konzervativní strana,Konzervativní strana,KONS

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
211,1292,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČMS
212,1293,Nadační občansko-politické hnutí ReMeK,Nadační obč.-pol. hnutí ReMeK,ReMeK
213,1294,Nestraníci pro jižní Moravu-www.nestranici2024.cz,Nestraníci pro jižní Moravu,Nestranici2024
214,9995,Koalice,Koalice,Koalice
215,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 040. [C] Zařízení sociálních služeb podle obcí

                       hodnota
polozka
target_years_present      2024
has_primary_key           True
primary_key_column    obec_kod

**HEAD**

,idhod,hodnota,stapro_kod,dsz_cis,dsz_kod,rok,obec_kod,obec_txt,okres_kod,okres_txt,dsz_txt
0,1493415753,1,6098,2910,130,2024,529303,Benešov,40169,Benešov,Domovy pro seniory
1,1493415756,1,6098,2910,131,2024,529303,Benešov,40169,Benešov,Azylové domy
2,1493415757,1,6098,2910,132,2024,529303,Benešov,40169,Benešov,Domy na půl cesty
3,1493415759,1,6098,2910,114,2024,529303,Benešov,40169,Benešov,Nízkoprahová denní centra
4,1493415760,1,6098,2910,115,2024,529303,Benešov,40169,Benešov,Nízkoprahová zařízení pro děti a mládež

**TAIL**

,idhod,hodnota,stapro_kod,dsz_cis,dsz_kod,rok,obec_kod,obec_txt,okres_kod,okres_txt,dsz_txt
2202,1493459157,8,6098,2910,125,2024,554782,Praha,40924,Praha,Služby následné péče
2203,1493459097,7,6098,2910,121,2024,554782,Praha,40924,Praha,Centra denních služeb
2204,1493459098,27,6098,2910,128,2024,554782,Praha,40924,Praha,Stacionáře denní
2205,1493459099,4,6098,2910,156,2024,554782,Praha,40924,Praha,Stacionáře týdenní
2206,1493459100,11,6098,2910,129,2024,554782,Praha,40924,Praha,Domovy pro osoby se zdravotním postižením

## 041. [C] Obyvatelstvo v základních sídelních jednotkách podle výsledků sčítání 2011

                       hodnota
polozka
target_years_present      None
has_primary_key           True
primary_key_column    obec_kod

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, stapro_txt, datum, zsjd_kod, zsjd_txt, obec_kod, obec_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, stapro_txt, datum, zsjd_kod, zsjd_txt, obec_kod, obec_txt]
Index: []

## 042. [C] Sčítání 2021 - Dojížďka mezi obcemi, včetně denní dojížďky

                          hodnota
polozka
target_years_present         None
has_primary_key              True
primary_key_column    op_obec_kod

**HEAD**

,lokalizace,op_lau1_kod,op_okres,op_orp_kod,op_orp,op_obec_kod,op_obec,doj_lau1_kod,doj_okres,doj_orp_kod,doj_orp,doj_obec_kod,doj_obec,dojizdka_prace,dojizdka_skola,dojizdka_celkova,dojizdka_celkova_denni
0,0_na_adrese_OP,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,141946,96,142042,0
1,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0641,BLANSKO,6202,BOSKOVICE,582018,LYSICE,0,1,1,0
2,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0641,BLANSKO,6202,BOSKOVICE,582409,SUCHÝ,1,0,1,0
3,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0641,BLANSKO,6202,BOSKOVICE,582646,VELKÉ OPATOVICE,1,0,1,0
4,1_meziobecni,CZ0100,PRAHA,1000,PRAHA,554782,PRAHA,CZ0642,BRNO-MĚSTO,6203,BRNO,582786,BRNO,482,338,820,0

**TAIL**

,lokalizace,op_lau1_kod,op_okres,op_orp_kod,op_orp,op_obec_kod,op_obec,doj_lau1_kod,doj_okres,doj_orp_kod,doj_orp,doj_obec_kod,doj_obec,dojizdka_prace,dojizdka_skola,dojizdka_celkova,dojizdka_celkova_denni
25699,1_meziobecni,CZ0806,OSTRAVA-MĚSTO,8119,OSTRAVA,568449,ZBYSLAVICE,CZ0806,OSTRAVA-MĚSTO,8119.0,OSTRAVA,554821,OSTRAVA,159,38,197,162
25700,1_meziobecni,CZ0806,OSTRAVA-MĚSTO,8119,OSTRAVA,568449,ZBYSLAVICE,CZ0100,PRAHA,1000.0,PRAHA,554782,PRAHA,3,2,5,0
25701,1_meziobecni,CZ0806,OSTRAVA-MĚSTO,8119,OSTRAVA,568449,ZBYSLAVICE,CZ0806,OSTRAVA-MĚSTO,8119.0,OSTRAVA,554049,OLBRAMICE,5,4,9,7
25702,1_meziobecni,CZ0806,OSTRAVA-MĚSTO,8119,OSTRAVA,568449,ZBYSLAVICE,CZ0311,ČESKÉ BUDĚJOVICE,3102.0,ČESKÉ BUDĚJOVICE,544256,ČESKÉ BUDĚJOVICE,1,0,1,0
25703,1_meziobecni,CZ0806,OSTRAVA-MĚSTO,8119,OSTRAVA,568449,ZBYSLAVICE,CZ0714,PŘEROV,7101.0,HRANICE,513750,HRANICE,1,0,1,1

## 043. [C] Počty ekonomických subjektů podle odvětví převažující činnosti za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2025

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, odvetvi_cis, odvetvi_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, odvetvi_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, odvetvi_cis, odvetvi_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, odvetvi_txt, vuzemi_txt]
Index: []

## 044. [C] Počty ekonomických subjektů podle vybraných právních forem za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2025

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, forma_cis, forma_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, forma_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, forma_cis, forma_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, forma_txt, vuzemi_txt]
Index: []

## 045. [C] Pohyb obyvatel - rok 2024

                         hodnota
polozka
target_years_present        2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,vuk,vuk_text,stapro_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,vuzemi_txt
0,1446607887,8,DEM0008,Zemřelí,5393,43,578231,2024,2024-01-01,2024-12-31,Koclířov
1,1446607050,7,DEM0008,Zemřelí,5393,43,575534,2024,2024-01-01,2024-12-31,Ráby
2,1446607855,2,DEM0008,Zemřelí,5393,43,597473,2024,2024-01-01,2024-12-31,Karlova Studánka
3,1446607865,3,DEM0008,Zemřelí,5393,43,557374,2024,2024-01-01,2024-12-31,Velké Hydčice
4,1446607870,3,DEM0008,Zemřelí,5393,43,594831,2024,2024-01-01,2024-12-31,Střelice

**TAIL**

,idhod,hodnota,vuk,vuk_text,stapro_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,vuzemi_txt
28744,1446314214,952,DEM0026A,Počet obyvatel k 1.1.,2406,43,534803,2024,2024-01-01,2024-01-01,Hořín
28745,1446314215,369,DEM0026B,Počet obyvatel k 31.12.,2406,43,564443,2024,2024-12-31,2024-12-31,Svijany
28746,1446314218,272,DEM0026A,Počet obyvatel k 1.1.,2406,43,500135,2024,2024-01-01,2024-01-01,Kozlov
28747,1446314222,407,DEM0026A,Počet obyvatel k 1.1.,2406,43,550531,2024,2024-01-01,2024-01-01,Strážný
28748,1446315041,256,DEM0026A,Počet obyvatel k 1.1.,2406,43,535591,2024,2024-01-01,2024-01-01,Zvíkov

## 046. [C] Počty ekonomických subjektů podle odvětví převažující činnosti za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2024

                         hodnota
polozka
target_years_present        2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,odvetvi_cis,odvetvi_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,odvetvi_txt,vuzemi_txt
0,1297578230,62,4958,NaN,NaN,NaN,NaN,43,539783,2024-06-30,NaN,NaN,Oplot
1,1296792131,74,4958,NaN,NaN,NaN,NaN,43,532479,2024-06-30,NaN,NaN,Kmetiněves
2,1297342262,51,4958,NaN,NaN,NaN,NaN,43,551821,2024-06-30,NaN,NaN,Tvrdkov
3,1297179880,80,4958,NaN,NaN,NaN,NaN,43,559806,2024-06-30,NaN,NaN,Hlohovice
4,1296854657,440,4958,NaN,NaN,NaN,NaN,43,574911,2024-06-30,NaN,NaN,Dolní Roveň

**TAIL**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,odvetvi_cis,odvetvi_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,odvetvi_txt,vuzemi_txt
18889,1270694326,31,4958,571.0,1.0,5103.0,H,44,554669,2024-03-31,Zjištěná aktivita,Doprava a skladování,Hrabová
18890,1270257972,19,4958,571.0,1.0,5103.0,H,43,500062,2024-03-31,Zjištěná aktivita,Doprava a skladování,Krhová
18891,1271150894,7,4958,571.0,1.0,5103.0,H,43,500071,2024-03-31,Zjištěná aktivita,Doprava a skladování,Poličná
18892,1270826200,2,4958,571.0,1.0,5103.0,H,43,500135,2024-03-31,Zjištěná aktivita,Doprava a skladování,Kozlov
18893,1271150980,1,4958,571.0,1.0,5103.0,H,43,500194,2024-03-31,Zjištěná aktivita,Doprava a skladování,Polná na Šumavě

## 047. [C] Počty ekonomických subjektů podle vybraných právních forem za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2024

                         hodnota
polozka
target_years_present        2024
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,forma_cis,forma_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,forma_txt,vuzemi_txt
0,1297578230,62,4958,NaN,NaN,NaN,NaN,43,539783,2024-06-30,NaN,NaN,Oplot
1,1296792131,74,4958,NaN,NaN,NaN,NaN,43,532479,2024-06-30,NaN,NaN,Kmetiněves
2,1297342262,51,4958,NaN,NaN,NaN,NaN,43,551821,2024-06-30,NaN,NaN,Tvrdkov
3,1297179880,80,4958,NaN,NaN,NaN,NaN,43,559806,2024-06-30,NaN,NaN,Hlohovice
4,1296854657,440,4958,NaN,NaN,NaN,NaN,43,574911,2024-06-30,NaN,NaN,Dolní Roveň

**TAIL**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,forma_cis,forma_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,forma_txt,vuzemi_txt
43051,1271022714,12,4958,571.0,1.0,NaN,NaN,43,500101,2024-03-31,Zjištěná aktivita,NaN,Bražec
43052,1270291784,44,4958,571.0,1.0,NaN,NaN,43,500160,2024-03-31,Zjištěná aktivita,NaN,Město Libavá
43053,1270693146,17,4958,571.0,1.0,NaN,NaN,43,500127,2024-03-31,Zjištěná aktivita,NaN,Doupovské Hradiště
43054,1271022715,12,4958,571.0,1.0,NaN,NaN,43,500194,2024-03-31,Zjištěná aktivita,NaN,Polná na Šumavě
43055,1270860050,6,4958,571.0,1.0,NaN,NaN,43,500151,2024-03-31,Zjištěná aktivita,NaN,Luboměř pod Strážnou

## 048. [C] Statistická data pro územně analytické podklady - rok 2024

                        hodnota
polozka
target_years_present       2024
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

,idhod,hodnota,vuk_id,rok,uzemi_cis,uzemi_kod,uzemi_txt,prislorp_kod,prislorp_txt,vuk_txt
0,1446565628,14.0,DEM0008,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Zemřelí
1,1446592380,56.0,DEM0009,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Přistěhovalí
2,1446584407,74.0,DEM0010,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Vystěhovalí
3,1446574143,4.0,DEM0011,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Přirozený přírůstek
4,1446579244,-14.0,DEM0012,2024,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Celkový přírůstek

**TAIL**

,idhod,hodnota,vuk_id,rok,uzemi_cis,uzemi_kod,uzemi_txt,prislorp_kod,prislorp_txt,vuk_txt
28158,1375187152,5.82,NEZ0004,2024,100,3140,Moravskoslezský kraj,NaN,NaN,Podíl nezaměstnaných osob (%)
28159,1446323663,1182613.00,DEM0026,2024,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel
28160,1446106728,174283.00,DEM0027,2024,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel ve věku do 15 let
28161,1446117064,753248.00,DEM0028,2024,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel ve věku 15 až 64 let
28162,1446059025,255082.00,DEM0029,2024,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel nad 65 let

## 049. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí

                        hodnota
polozka
target_years_present       2024
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

,idhod,hodnota,vuk,vuk_text,obdobi,rok,mesic,uzemi_cis,uzemi_kod,uzemi_txt
0,1285998842,29.0,NEZ0007,Uchazeči o zaměstnání,20240430,2024,4,43,500011,Želechovice nad Dřevnicí
1,1354646498,26.0,NEZ0007,Uchazeči o zaměstnání,20241130,2024,11,43,500011,Želechovice nad Dřevnicí
2,1307690694,25.0,NEZ0007,Uchazeči o zaměstnání,20240731,2024,7,43,500011,Želechovice nad Dřevnicí
3,1335857939,26.0,NEZ0007,Uchazeči o zaměstnání,20240930,2024,9,43,500011,Želechovice nad Dřevnicí
4,1270041170,24.0,NEZ0007,Uchazeči o zaměstnání,20240331,2024,3,43,500011,Želechovice nad Dřevnicí

**TAIL**

,idhod,hodnota,vuk,vuk_text,obdobi,rok,mesic,uzemi_cis,uzemi_kod,uzemi_txt
25480,1330852734,1.738,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20240831,2024,8,43,599999,Trojanovice
25481,1290447813,1.970,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20240531,2024,5,43,599999,Trojanovice
25482,1301383520,1.854,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20240630,2024,6,43,599999,Trojanovice
25483,1249670750,1.718,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20240131,2024,1,43,599999,Trojanovice
25484,1374939350,2.317,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20241231,2024,12,43,599999,Trojanovice

## 050. [C] Pohyb obyvatel - rok 2023

                         hodnota
polozka
target_years_present        2023
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,vuk,vuk_text,stapro_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,vuzemi_txt
0,1286495326,5,DEM0008,Zemřelí,5393,43,552674,2023,2023-01-01,2023-12-31,Střítež
1,1286494798,2,DEM0008,Zemřelí,5393,43,555835,2023,2023-01-01,2023-12-31,Bolešiny
2,1286494804,0,DEM0008,Zemřelí,5393,43,558010,2023,2023-01-01,2023-12-31,Louňová
3,1286494806,5,DEM0008,Zemřelí,5393,43,550922,2023,2023-01-01,2023-12-31,Čejetice
4,1286495335,3,DEM0008,Zemřelí,5393,43,589128,2023,2023-01-01,2023-12-31,Věžky

**TAIL**

,idhod,hodnota,vuk,vuk_text,stapro_kod,vuzemi_cis,vuzemi_kod,rok,casref_od,casref_do,vuzemi_txt
35306,1284791049,3094,DEM0026A,Počet obyvatel k 1.1.,2406,43,529516,2023,2023-01-01,2023-01-01,Čerčany
35307,1284791050,359,DEM0026A,Počet obyvatel k 1.1.,2406,43,529605,2023,2023-01-01,2023-01-01,Rokytá
35308,1284791051,1609,DEM0026A,Počet obyvatel k 1.1.,2406,43,506737,2023,2023-01-01,2023-01-01,Chvalčov
35309,1284791052,307,DEM0026A,Počet obyvatel k 1.1.,2406,43,550680,2023,2023-01-01,2023-01-01,Záblatí
35310,1284791053,1718,DEM0026A,Počet obyvatel k 1.1.,2406,43,553441,2023,2023-01-01,2023-01-01,Bělá nad Radbuzou

## 051. [C] Počty ekonomických subjektů podle odvětví převažující činnosti za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2023

                         hodnota
polozka
target_years_present        2023
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,odvetvi_cis,odvetvi_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,odvetvi_txt,vuzemi_txt
0,1225403364,65,4958,NaN,NaN,NaN,NaN,43,539783,2023-12-31,NaN,NaN,Oplot
1,1225557557,71,4958,NaN,NaN,NaN,NaN,43,532479,2023-12-31,NaN,NaN,Kmetiněves
2,1225949426,51,4958,NaN,NaN,NaN,NaN,43,551821,2023-12-31,NaN,NaN,Tvrdkov
3,1225720374,83,4958,NaN,NaN,NaN,NaN,43,559806,2023-12-31,NaN,NaN,Hlohovice
4,1224744792,437,4958,NaN,NaN,NaN,NaN,43,574911,2023-12-31,NaN,NaN,Dolní Roveň

**TAIL**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,odvetvi_cis,odvetvi_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,odvetvi_txt,vuzemi_txt
24934,1102192762,6,4958,571.0,1.0,5103.0,H,44,554324,2023-03-31,Zjištěná aktivita,Doprava a skladování,Lhotka
24935,1103342770,29,4958,571.0,1.0,5103.0,H,44,554669,2023-03-31,Zjištěná aktivita,Doprava a skladování,Hrabová
24936,1103091898,19,4958,571.0,1.0,5103.0,H,43,500062,2023-03-31,Zjištěná aktivita,Doprava a skladování,Krhová
24937,1102978232,7,4958,571.0,1.0,5103.0,H,43,500071,2023-03-31,Zjištěná aktivita,Doprava a skladování,Poličná
24938,1102930638,2,4958,571.0,1.0,5103.0,H,43,500135,2023-03-31,Zjištěná aktivita,Doprava a skladování,Kozlov

## 052. [C] Počty ekonomických subjektů podle vybraných právních forem za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2023

                         hodnota
polozka
target_years_present        2023
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,forma_cis,forma_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,forma_txt,vuzemi_txt
0,1225403364,65,4958,NaN,NaN,NaN,NaN,43,539783,2023-12-31,NaN,NaN,Oplot
1,1225557557,71,4958,NaN,NaN,NaN,NaN,43,532479,2023-12-31,NaN,NaN,Kmetiněves
2,1225949426,51,4958,NaN,NaN,NaN,NaN,43,551821,2023-12-31,NaN,NaN,Tvrdkov
3,1225720374,83,4958,NaN,NaN,NaN,NaN,43,559806,2023-12-31,NaN,NaN,Hlohovice
4,1224744792,437,4958,NaN,NaN,NaN,NaN,43,574911,2023-12-31,NaN,NaN,Dolní Roveň

**TAIL**

,idhod,hodnota,stapro_kod,aktivita_cis,aktivita_kod,forma_cis,forma_kod,vuzemi_cis,vuzemi_kod,casref,aktivita_txt,forma_txt,vuzemi_txt
31934,1103181551,3,4958,571.0,1.0,NaN,NaN,43,500101,2023-03-31,Zjištěná aktivita,NaN,Bražec
31935,1103027749,42,4958,571.0,1.0,NaN,NaN,43,500160,2023-03-31,Zjištěná aktivita,NaN,Město Libavá
31936,1102866719,10,4958,571.0,1.0,NaN,NaN,43,500127,2023-03-31,Zjištěná aktivita,NaN,Doupovské Hradiště
31937,1103164049,5,4958,571.0,1.0,NaN,NaN,43,500194,2023-03-31,Zjištěná aktivita,NaN,Polná na Šumavě
31938,1102704986,5,4958,571.0,1.0,NaN,NaN,43,500151,2023-03-31,Zjištěná aktivita,NaN,Luboměř pod Strážnou

## 053. [C] Statistická data pro územně analytické podklady - rok 2023

                        hodnota
polozka
target_years_present       2023
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

,idhod,hodnota,vuk_id,rok,uzemi_cis,uzemi_kod,uzemi_txt,prislorp_kod,prislorp_txt,vuk_txt
0,1286549899,15.0,DEM0008,2023,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Zemřelí
1,1286499958,65.0,DEM0009,2023,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Přistěhovalí
2,1286524284,54.0,DEM0010,2023,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Vystěhovalí
3,1286515410,-5.0,DEM0011,2023,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Přirozený přírůstek
4,1286495957,6.0,DEM0012,2023,43,500011,Želechovice nad Dřevnicí,7213,Zlín,Celkový přírůstek

**TAIL**

,idhod,hodnota,vuk_id,rok,uzemi_cis,uzemi_kod,uzemi_txt,prislorp_kod,prislorp_txt,vuk_txt
28215,1223859100,5.23,NEZ0004,2023,100,3140,Moravskoslezský kraj,NaN,NaN,Podíl nezaměstnaných osob (%)
28216,1286408854,1189204.00,DEM0026,2023,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel
28217,1284304183,179058.00,DEM0027,2023,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel ve věku do 15 let
28218,1284312367,757202.00,DEM0028,2023,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel ve věku 15 až 64 let
28219,1284339745,252944.00,DEM0029,2023,100,3140,Moravskoslezský kraj,NaN,NaN,Počet obyvatel nad 65 let

## 054. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí

                        hodnota
polozka
target_years_present       2023
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

,idhod,hodnota,vuk,vuk_text,obdobi,rok,mesic,uzemi_cis,uzemi_kod,uzemi_txt
0,1067703135,34.0,NEZ0007,Uchazeči o zaměstnání,20230131,2023,1,43,500011,Želechovice nad Dřevnicí
1,1134596392,20.0,NEZ0007,Uchazeči o zaměstnání,20230731,2023,7,43,500011,Želechovice nad Dřevnicí
2,1175844147,19.0,NEZ0007,Uchazeči o zaměstnání,20230930,2023,9,43,500011,Želechovice nad Dřevnicí
3,1210153651,23.0,NEZ0007,Uchazeči o zaměstnání,20231130,2023,11,43,500011,Želechovice nad Dřevnicí
4,1195558594,18.0,NEZ0007,Uchazeči o zaměstnání,20231031,2023,10,43,500011,Želechovice nad Dřevnicí

**TAIL**

,idhod,hodnota,vuk,vuk_text,obdobi,rok,mesic,uzemi_cis,uzemi_kod,uzemi_txt
25480,1223708159,0.000,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20231231,2023,12,43,575917,Urbanice
25481,1223711622,0.000,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20231231,2023,12,43,560430,Zhoř u Tábora
25482,1223715802,6.276,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20231231,2023,12,43,598933,Český Těšín
25483,1223720851,5.512,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20231231,2023,12,43,574155,Jetřichov
25484,1223719509,2.604,NEZ0006,Podíl nezaměstnaných osob - ženy (%),20231231,2023,12,43,554065,Jakubčovice nad Odrou

## 055. [C] Pohyb obyvatel - rok 2022

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 056. [C] Počty ekonomických subjektů podle odvětví převažující činnosti za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2022

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, odvetvi_cis, odvetvi_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, odvetvi_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, odvetvi_cis, odvetvi_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, odvetvi_txt, vuzemi_txt]
Index: []

## 057. [C] Počty ekonomických subjektů podle vybraných právních forem za správní obvody Prahy, obcí s rozšířenou působností, obce a městské obvody a části - 2022

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, forma_cis, forma_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, forma_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, forma_cis, forma_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, forma_txt, vuzemi_txt]
Index: []

## 058. [C] Statistická data pro územně analytické podklady - rok 2022

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

## 059. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 060. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2021

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 061. [C] Statistická data pro územně analytické podklady - rok 2021

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

## 062. [C] Sčítání 2021 - Obydlené byty podle převažujícího způsobu vytápění

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vytapeni_cis, vytapeni_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vytapeni_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vytapeni_cis, vytapeni_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vytapeni_txt, uzemi_txt, uzemi_typ]
Index: []

## 063. [C] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, velikostních skupin obcí a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

## 064. [C] Sčítání 2021 - Obyvatelstvo podle velikostních skupin obcí a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

## 065. [C] Sčítání 2021 - Obyvatelstvo podle vzdělání, velikostních skupin obcí a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vzdelani_cleneni, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vzdelani_cleneni, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

## 066. [C] Sčítání 2021 - Obyvatelstvo podle vzdělání, věku, velikostních skupin obcí a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vzdelani_cleneni, vek_cis, vek_kod, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, vek_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

[0 rows x 22 columns]

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vzdelani_cleneni, vek_cis, vek_kod, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, vek_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

[0 rows x 22 columns]

## 067. [C] Sčítání 2021 - Obyvatelstvo podle způsobu bydlení, velikostních skupin obcí a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydleni_cis, bydleni_kod, bydleni_cleneni, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydleni_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydleni_cis, bydleni_kod, bydleni_cleneni, velikostobce_cis, velikostobce_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydleni_txt, velikostobce_txt, pohlavi_txt, uzemi_txt]
Index: []

## 068. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí - rok 2021

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 069. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2020

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 070. [C] Statistická data pro územně analytické podklady - rok 2020

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

## 071. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí - rok 2020

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 072. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2019

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 073. [C] Statistická data pro územně analytické podklady - rok 2019

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

## 074. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí - rok 2019

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 075. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2018

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 076. [C] Statistická data pro územně analytické podklady - rok 2018

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk_id, rok, uzemi_cis, uzemi_kod, uzemi_txt, prislorp_kod, prislorp_txt, vuk_txt]
Index: []

## 077. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí - rok 2018

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 078. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2017

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 079. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí - rok 2017

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 080. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2016

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 081. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí - rok 2016

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 082. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2015

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 083. [C] Uchazeči o zaměstnání dosažitelní a podíl nezaměstnaných osob podle obcí - rok 2015

                        hodnota
polozka
target_years_present       None
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, obdobi, rok, mesic, uzemi_cis, uzemi_kod, uzemi_txt]
Index: []

## 084. [C] Pohyb obyvatel za ČR, kraje, okresy, SO ORP a obce - rok 2014

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, vuk, vuk_text, stapro_kod, vuzemi_cis, vuzemi_kod, rok, casref_od, casref_do, vuzemi_txt]
Index: []

## 085. [C] Obyvatelstvo a domy v obcích podle výsledků sčítání od roku 1869

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, stapro_kod, stapro_txt, rok, datum, vuzemi_cis, vuzemi_kod, vuzemi_txt, so_orp, so_orp_text, okres, okres_text, kraj, kraj_text]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, stapro_kod, stapro_txt, rok, datum, vuzemi_cis, vuzemi_kod, vuzemi_txt, so_orp, so_orp_text, okres, okres_text, kraj, kraj_text]
Index: []

## 086. [C] Ekonomické subjekty podle vybraných právních forem za správní obvody Prahy a obcí s rozšířenou působností

                         hodnota
polozka
target_years_present        None
has_primary_key             True
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, forma_cis, forma_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, forma_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, forma_cis, forma_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, forma_txt, vuzemi_txt]
Index: []

## 087. [C] Obyvatelstvo podle jednotek věku a pohlaví - rok 2024

                        hodnota
polozka
target_years_present       2024
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,obdobi,pohlavi_txt,vek_txt,uzemi_txt,uzemi_typ
0,1446328288,1397880,2406,NaN,NaN,NaN,NaN,100,3018,2024-12-31,NaN,NaN,Hlavní město Praha,kraj
1,1446020251,12083,2406,NaN,NaN,7700.0,4.000006e+14,100,3018,2024-12-31,NaN,0.0,Hlavní město Praha,kraj
2,1446058963,12716,2406,NaN,NaN,7700.0,4.000016e+14,100,3018,2024-12-31,NaN,1.0,Hlavní město Praha,kraj
3,1445962976,13675,2406,NaN,NaN,7700.0,4.000026e+14,100,3018,2024-12-31,NaN,2.0,Hlavní město Praha,kraj
4,1446063539,15577,2406,NaN,NaN,7700.0,4.000036e+14,100,3018,2024-12-31,NaN,3.0,Hlavní město Praha,kraj

**TAIL**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,obdobi,pohlavi_txt,vek_txt,uzemi_txt,uzemi_typ
43024,1446093575,2303,2406,102.0,2.0,7700.0,4.100966e+14,97,19,2024-12-31,žena,96.0,Česká republika,stát
43025,1446176020,1479,2406,102.0,2.0,7700.0,4.100976e+14,97,19,2024-12-31,žena,97.0,Česká republika,stát
43026,1446075580,1004,2406,102.0,2.0,7700.0,4.100986e+14,97,19,2024-12-31,žena,98.0,Česká republika,stát
43027,1446174708,655,2406,102.0,2.0,7700.0,4.100996e+14,97,19,2024-12-31,žena,99.0,Česká republika,stát
43028,1446093577,848,2406,102.0,2.0,7700.0,4.201008e+14,97,19,2024-12-31,žena,100.0,Česká republika,stát

## 088. [C] Obyvatelstvo podle jednotek věku a pohlaví - rok 2023

                        hodnota
polozka
target_years_present       2023
has_primary_key            True
primary_key_column    uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,obdobi,pohlavi_txt,vek_txt,uzemi_txt,uzemi_typ
0,1286408928,1384732,2406,NaN,NaN,NaN,NaN,100,3018,2023-12-31,NaN,NaN,Hlavní město Praha,kraj
1,1284319375,12586,2406,NaN,NaN,7700.0,4.000006e+14,100,3018,2023-12-31,NaN,0.0,Hlavní město Praha,kraj
2,1284269706,13722,2406,NaN,NaN,7700.0,4.000016e+14,100,3018,2023-12-31,NaN,1.0,Hlavní město Praha,kraj
3,1284358398,15702,2406,NaN,NaN,7700.0,4.000026e+14,100,3018,2023-12-31,NaN,2.0,Hlavní město Praha,kraj
4,1284259038,14172,2406,NaN,NaN,7700.0,4.000036e+14,100,3018,2023-12-31,NaN,3.0,Hlavní město Praha,kraj

**TAIL**

,idhod,hodnota,stapro_kod,pohlavi_cis,pohlavi_kod,vek_cis,vek_kod,uzemi_cis,uzemi_kod,obdobi,pohlavi_txt,vek_txt,uzemi_txt,uzemi_typ
43024,1284233115,2083,2406,102.0,2.0,7700.0,4.100966e+14,97,19,2023-12-31,žena,96.0,Česká republika,stát
43025,1284292696,1453,2406,102.0,2.0,7700.0,4.100976e+14,97,19,2023-12-31,žena,97.0,Česká republika,stát
43026,1284400520,970,2406,102.0,2.0,7700.0,4.100986e+14,97,19,2023-12-31,žena,98.0,Česká republika,stát
43027,1284384407,603,2406,102.0,2.0,7700.0,4.100996e+14,97,19,2023-12-31,žena,99.0,Česká republika,stát
43028,1284363602,794,2406,102.0,2.0,7700.0,4.201008e+14,97,19,2023-12-31,žena,100.0,Česká republika,stát

## 089. [D] Ekonomické subjekty podle odvětví převažující činnosti za správní obvody Prahy a obcí s rozšířenou působností

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, odvetvi_cis, odvetvi_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, odvetvi_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, aktivita_cis, aktivita_kod, odvetvi_cis, odvetvi_kod, vuzemi_cis, vuzemi_kod, casref, aktivita_txt, odvetvi_txt, vuzemi_txt]
Index: []

## 090. [D] Naděje dožití v okresech a správních obvodech ORP - časová řada

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 091. [D] Obyvatelstvo podle jednotek věku a pohlaví ve správních obvodech obcí s rozšířenou působností - rok 2021

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 092. [D] Sčítání 2021 - Byty podle obydlenosti

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obydlenost_cis, obydlenost_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obydlenost_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obydlenost_cis, obydlenost_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obydlenost_txt, uzemi_txt]
Index: []

## 093. [D] Sčítání 2021 - Byty podle obydlenosti a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obydlenost_cis, obydlenost_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obydlenost_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obydlenost_cis, obydlenost_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obydlenost_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

## 094. [D] Sčítání 2021 - Domy podle obydlenosti a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obydlen_cis, obydlen_kod, druh_cis, druh_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obydlen_txt, druh_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obydlen_cis, obydlen_kod, druh_cis, druh_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obydlen_txt, druh_txt, uzemi_txt, uzemi_typ]
Index: []

## 095. [D] Sčítání 2021 - Děti podle rodinného stavu, vzdělání a věku matky

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_zeny_cis, stav_zeny_kod, vzdelani_zeny_cis, vzdelani_zeny_kod, vek_zeny_cis, vek_zeny_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_zeny_txt, vzdelani_zeny_txt, vek_zeny_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_zeny_cis, stav_zeny_kod, vzdelani_zeny_cis, vzdelani_zeny_kod, vek_zeny_cis, vek_zeny_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_zeny_txt, vzdelani_zeny_txt, vek_zeny_txt, uzemi_txt]
Index: []

## 096. [D] Sčítání 2021 - Hospodařící domácnosti podle velikosti a typu domácnosti

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, clenu_cis, clenu_kod, typ_cis, typ_kod, typ_struktura, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, clenu_txt, typ_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, clenu_cis, clenu_kod, typ_cis, typ_kod, typ_struktura, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, clenu_txt, typ_txt, uzemi_txt, uzemi_typ]
Index: []

## 097. [D] Sčítání 2021 - Obydlené byty podle celkové plochy bytu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, plocha_cis, plocha_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, plocha_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, plocha_cis, plocha_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, plocha_txt, uzemi_txt]
Index: []

## 098. [D] Sčítání 2021 - Obydlené byty podle hlavního zdroje energie používaného k vytápění

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, energie_cis, energie_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, energie_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, energie_cis, energie_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, energie_txt, uzemi_txt, uzemi_typ]
Index: []

## 099. [D] Sčítání 2021 - Obydlené byty podle materiálu nosných zdí a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, material_cis, material_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, material_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, material_cis, material_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, material_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

## 100. [D] Sčítání 2021 - Obydlené byty podle období výstavby nebo rekonstrukce domu a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obdobi_cis, obdobi_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obdobi_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obdobi_cis, obdobi_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obdobi_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

## 101. [D] Sčítání 2021 - Obydlené byty podle polohy bytu v domě a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, poloha_cis, poloha_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, poloha_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, poloha_cis, poloha_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, poloha_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

## 102. [D] Sčítání 2021 - Obydlené byty podle počtu obytných místností

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, mistnosti_cis, mistnosti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, mistnosti_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, mistnosti_cis, mistnosti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, mistnosti_txt, uzemi_txt]
Index: []

## 103. [D] Sčítání 2021 - Obydlené byty podle počtu obytných místností včetně kuchyně

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, mistnosti_cis, mistnosti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, mistnosti_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, mistnosti_cis, mistnosti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, mistnosti_txt, uzemi_txt]
Index: []

## 104. [D] Sčítání 2021 - Obydlené byty podle počtu osob v bytě

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, osob_cis, osob_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, osob_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, osob_cis, osob_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, osob_txt, uzemi_txt]
Index: []

## 105. [D] Sčítání 2021 - Obydlené byty podle právního důvodu užívání bytu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, uzivani_cis, uzivani_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, uzivani_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, uzivani_cis, uzivani_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, uzivani_txt, uzemi_txt]
Index: []

## 106. [D] Sčítání 2021 - Obydlené byty podle připojení na plyn

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, plyn_cis, plyn_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, plyn_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, plyn_cis, plyn_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, plyn_txt, uzemi_txt, uzemi_typ]
Index: []

## 107. [D] Sčítání 2021 - Obydlené byty podle připojení na vodovod

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vodovod_cis, vodovod_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vodovod_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vodovod_cis, vodovod_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vodovod_txt, uzemi_txt, uzemi_typ]
Index: []

## 108. [D] Sčítání 2021 - Obydlené byty podle vlastníka a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vlastnik_cis, vlastnik_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vlastnik_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vlastnik_cis, vlastnik_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vlastnik_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

## 109. [D] Sčítání 2021 - Obydlené byty podle vybavení domu výtahem a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vytah_cis, vytah_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vytah_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vytah_cis, vytah_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vytah_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

## 110. [D] Sčítání 2021 - Obydlené byty podle vybavení kuchyní

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, kuchyne_cis, kuchyne_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, kuchyne_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, kuchyne_cis, kuchyne_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, kuchyne_txt, uzemi_txt]
Index: []

## 111. [D] Sčítání 2021 - Obydlené byty podle způsobu odvádění odpadních vod a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odpad_cis, odpad_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odpad_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odpad_cis, odpad_kod, druhdomu_cis, druhdomu_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odpad_txt, druhdomu_txt, uzemi_txt, uzemi_typ]
Index: []

## 112. [D] Sčítání 2021 - Obydlené domy podle materiálu nosných zdí a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, zdi_cis, zdi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, zdi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, zdi_cis, zdi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, zdi_txt, uzemi_txt, uzemi_typ]
Index: []

## 113. [D] Sčítání 2021 - Obydlené domy podle napojení na kanalizaci a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, odpad_cis, odpad_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, odpad_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, odpad_cis, odpad_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, odpad_txt, uzemi_txt, uzemi_typ]
Index: []

## 114. [D] Sčítání 2021 - Obydlené domy podle napojení na plyn a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, plyn_cis, plyn_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, plyn_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, plyn_cis, plyn_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, plyn_txt, uzemi_txt, uzemi_typ]
Index: []

## 115. [D] Sčítání 2021 - Obydlené domy podle napojení na vodovod a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vodovod_cis, vodovod_kod, vodovod_cleneni, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vodovod_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vodovod_cis, vodovod_kod, vodovod_cleneni, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vodovod_txt, uzemi_txt, uzemi_typ]
Index: []

## 116. [D] Sčítání 2021 - Obydlené domy podle období výstavby a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, obdobi_cis, obdobi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, obdobi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, obdobi_cis, obdobi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, obdobi_txt, uzemi_txt, uzemi_typ]
Index: []

## 117. [D] Sčítání 2021 - Obydlené domy podle počtu bytů v domě a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, byty_cis, byty_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, byty_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, byty_cis, byty_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, byty_txt, uzemi_txt, uzemi_typ]
Index: []

## 118. [D] Sčítání 2021 - Obydlené domy podle počtu nadzemních podlaží a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, podlazi_cis, podlazi_kod, druh_cis, druh_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, podlazi_txt, druh_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, podlazi_cis, podlazi_kod, druh_cis, druh_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, podlazi_txt, druh_txt, uzemi_txt, uzemi_typ]
Index: []

## 119. [D] Sčítání 2021 - Obydlené domy podle vlastnictví a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vlastnik_cis, vlastnik_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vlastnik_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vlastnik_cis, vlastnik_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vlastnik_txt, uzemi_txt, uzemi_typ]
Index: []

## 120. [D] Sčítání 2021 - Obydlené domy podle vybavení výtahem a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vytah_cis, vytah_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vytah_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vytah_cis, vytah_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vytah_txt, uzemi_txt, uzemi_typ]
Index: []

## 121. [D] Sčítání 2021 - Obydlené domy způsobu vytápění a druhu domu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vytapeni_cis, vytapeni_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vytapeni_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_cis, druh_kod, vytapeni_cis, vytapeni_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_txt, vytapeni_txt, uzemi_txt, uzemi_typ]
Index: []

## 122. [D] Sčítání 2021 - Obyvatelstvo podle bydliště matky v době narození a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydl_narozeni_cis, bydl_narozeni_kod, bydl_cleneni_typ, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydl_narozeni_txt, bydl_cleneni_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydl_narozeni_cis, bydl_narozeni_kod, bydl_cleneni_typ, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydl_narozeni_txt, bydl_cleneni_txt, pohlavi_txt, uzemi_txt]
Index: []

## 123. [D] Sčítání 2021 - Obyvatelstvo podle bydliště rok před sčítáním a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydl_1rok_cis, bydl_1rok_kod, bydl_cleneni_typ, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydl_1rok_txt, bydl_cleneni_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydl_1rok_cis, bydl_1rok_kod, bydl_cleneni_typ, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydl_1rok_txt, bydl_cleneni_txt, pohlavi_txt, uzemi_txt]
Index: []

## 124. [D] Sčítání 2021 - Obyvatelstvo podle desetiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 125. [D] Sčítání 2021 - Obyvatelstvo podle druhu registrovaného pobytu a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_regpobytu_cis, druh_regpobytu_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_regpobytu_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, druh_regpobytu_cis, druh_regpobytu_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, druh_regpobytu_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 126. [D] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, ekonaktiv_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, ekonaktiv_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 127. [D] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, desetiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 128. [D] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, jednoletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 129. [D] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, pětiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 130. [D] Sčítání 2021 - Obyvatelstvo podle ekonomické aktivity, základních věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, aktivita_struktura, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 131. [D] Sčítání 2021 - Obyvatelstvo podle jednotek věku a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 132. [D] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka (1 mateřský jazyk)

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, uzemi_txt]
Index: []

## 133. [D] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka (1 nebo 2 mateřské jazyky)

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, uzemi_txt]
Index: []

## 134. [D] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka a pohlaví (1 mateřský jazyk)

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, pohlavi_txt, uzemi_txt]
Index: []

## 135. [D] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka a pohlaví (1 nebo 2 mateřské jazyky)

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, pohlavi_txt, uzemi_txt]
Index: []

## 136. [D] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka, věku a pohlaví (1 mateřský jazyk)

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 137. [D] Sčítání 2021 - Obyvatelstvo podle mateřského jazyka, věku a pohlaví (1 nebo 2 mateřské jazyky)

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, jazyk_cis, jazyk_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, jazyk_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 138. [D] Sčítání 2021 - Obyvatelstvo podle místa registrovaného pobytu a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, misto_regpobytu_cis, misto_regpobytu_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, misto_regpobytu_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, misto_regpobytu_cis, misto_regpobytu_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, misto_regpobytu_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 139. [D] Sčítání 2021 - Obyvatelstvo podle náboženské víry

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vira_cis, vira_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vira_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vira_cis, vira_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vira_txt, uzemi_txt]
Index: []

## 140. [D] Sčítání 2021 - Obyvatelstvo podle náboženské víry a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vira_cis, vira_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vira_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vira_cis, vira_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vira_txt, pohlavi_txt, uzemi_txt]
Index: []

## 141. [D] Sčítání 2021 - Obyvatelstvo podle náboženské víry, věku a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vira_cis, vira_kod, vira_cleneni, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vira_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vira_cis, vira_kod, vira_cleneni, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vira_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 142. [D] Sčítání 2021 - Obyvatelstvo podle národnosti

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, narodnost_cis, narodnost_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, narodnost_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, narodnost_cis, narodnost_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, narodnost_txt, uzemi_txt]
Index: []

## 143. [D] Sčítání 2021 - Obyvatelstvo podle národnosti, věku a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, narodnost_cis, narodnost_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, narodnost_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, narodnost_cis, narodnost_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, narodnost_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 144. [D] Sčítání 2021 - Obyvatelstvo podle pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, uzemi_txt]
Index: []

## 145. [D] Sčítání 2021 - Obyvatelstvo podle pětiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 146. [D] Sčítání 2021 - Obyvatelstvo podle rodinného stavu

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, uzemi_txt]
Index: []

## 147. [D] Sčítání 2021 - Obyvatelstvo podle rodinného stavu a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, pohlavi_txt, uzemi_txt]
Index: []

## 148. [D] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, desetiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 149. [D] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, jednoletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 150. [D] Sčítání 2021 - Obyvatelstvo podle rodinného stavu, pětiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, stav_cis, stav_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, stav_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 151. [D] Sčítání 2021 - Obyvatelstvo podle státního občanství

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obcanstvi_cis, obcanstvi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obcanstvi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obcanstvi_cis, obcanstvi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obcanstvi_txt, uzemi_txt]
Index: []

## 152. [D] Sčítání 2021 - Obyvatelstvo podle státního občanství a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obcanstvi_cis, obcanstvi_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obcanstvi_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obcanstvi_cis, obcanstvi_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obcanstvi_txt, pohlavi_txt, uzemi_txt]
Index: []

## 153. [D] Sčítání 2021 - Obyvatelstvo podle státního občanství, věku a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obcan_cis, obcan_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obcan_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, obcan_cis, obcan_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, obcan_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 154. [D] Sčítání 2021 - Obyvatelstvo podle vzdělání

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, uzemi_txt]
Index: []

## 155. [D] Sčítání 2021 - Obyvatelstvo podle vzdělání a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vzdelani_cleneni, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vzdelani_cleneni, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, pohlavi_txt, uzemi_txt]
Index: []

## 156. [D] Sčítání 2021 - Obyvatelstvo podle vzdělání, věku a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 157. [D] Sčítání 2021 - Obyvatelstvo podle vzdělání, základních věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vzdelani_cis, vzdelani_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vzdelani_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 158. [D] Sčítání 2021 - Obyvatelstvo podle věkových skupin

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, uzemi_txt]
Index: []

## 159. [D] Sčítání 2021 - Obyvatelstvo podle věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 160. [D] Sčítání 2021 - Obyvatelstvo podle způsobu bydlení a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydleni_cis, bydleni_kod, bydleni_cleneni, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydleni_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydleni_cis, bydleni_kod, bydleni_cleneni, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydleni_txt, pohlavi_txt, uzemi_txt]
Index: []

## 161. [D] Sčítání 2021 - Obyvatelstvo podle způsobu bydlení, věku a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydleni_cis, bydleni_kod, bydleni_cleneni, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydleni_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, bydleni_cis, bydleni_kod, bydleni_cleneni, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, bydleni_txt, vek_txt, pohlavi_txt, uzemi_txt]
Index: []

## 162. [D] Sčítání 2021 - Obyvatelstvo s registrovaným pobytem podle pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 163. [D] Sčítání 2021 - Plodnost žen

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pocetdeti_cis, pocetdeti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pocetdeti_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pocetdeti_cis, pocetdeti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pocetdeti_txt, uzemi_txt]
Index: []

## 164. [D] Sčítání 2021 - Počet obyvatel a počet obydlených bytů za části obce, části obce - díl, ZSJ, ZDJ - díl,

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, uzemi_txt, uzemi_typ]
Index: []

## 165. [D] Sčítání 2021 - Počet členů hospodařících domácností podle velikosti a typu domácnosti

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, clenu_cis, clenu_kod, typ_cis, typ_kod, typ_struktura, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, clenu_txt, typ_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, clenu_cis, clenu_kod, typ_cis, typ_kod, typ_struktura, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, clenu_txt, typ_txt, uzemi_txt, uzemi_typ]
Index: []

## 166. [D] Sčítání 2021 - Průměrný věk obyvatel podle pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, uzemi_txt]
Index: []

## 167. [D] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle frekvence vyjížďky

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, frekvence_cis, frekvence_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, frekvence_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, frekvence_cis, frekvence_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, frekvence_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 168. [D] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle hlavního dopravního prostředku

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, prostredek_cis, prostredek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, prostredek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, prostredek_cis, prostredek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, prostredek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 169. [D] Sčítání 2021 - Vyjíždějící do zaměstnání podle frekvence vyjížďky

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, frekvence_cis, frekvence_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, frekvence_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, frekvence_cis, frekvence_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, frekvence_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 170. [D] Sčítání 2021 - Vyjíždějící do zaměstnání podle hlavního dopravního prostředku

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, prostredek_cis, prostredek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, prostredek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, prostredek_cis, prostredek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, prostredek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 171. [D] Sčítání 2021 - Vyjíždějící do školy podle frekvence vyjížďky

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, frekvence_cis, frekvence_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, frekvence_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, frekvence_cis, frekvence_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, frekvence_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 172. [D] Sčítání 2021 - Vyjíždějící do školy podle hlavního dopravního prostředku

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, prostredek_cis, prostredek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, prostredek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, prostredek_cis, prostredek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, prostredek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 173. [D] Sčítání 2021 - Zaměstnaní podle hlavních tříd zaměstnání a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, klasif_cis, klasif_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, klasif_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, klasif_cis, klasif_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, klasif_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 174. [D] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 175. [D] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti, desetiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 176. [D] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti, jednoletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 177. [D] Sčítání 2021 - Zaměstnaní podle odvětví ekonomické činnosti, pětiletých věkových skupin a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, odvetvi_cis, odvetvi_kod, vek_cis, vek_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, odvetvi_txt, vek_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 178. [D] Sčítání 2021 - Zaměstnaní podle postavení v zaměstnání a pohlaví

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, postaveni_cis, postaveni_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, postaveni_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, postaveni_cis, postaveni_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, postaveni_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 179. [D] Sčítání 2021 - Ženy ve věku 15 a více let podle rodinného stavu, vzdělání, věku a počtu dětí

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, stav_cis, stav_kod, vzdelani_cis, vzdelani_kod, vek_cis, vek_kod, pocet_deti_cis, pocet_deti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, stav_txt, vzdelani_txt, vek_txt, pocet_deti_txt, uzemi_txt]
Index: []

[0 rows x 24 columns]

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, pohlavi_cis, pohlavi_kod, stav_cis, stav_kod, vzdelani_cis, vzdelani_kod, vek_cis, vek_kod, pocet_deti_cis, pocet_deti_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, pohlavi_txt, stav_txt, vzdelani_txt, vek_txt, pocet_deti_txt, uzemi_txt]
Index: []

[0 rows x 24 columns]

## 180. [D] Obyvatelstvo podle jednotek věku a pohlaví ve správních obvodech obcí s rozšířenou působností - rok 2020

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 181. [D] Obyvatelstvo podle jednotek věku a pohlaví ve správních obvodech obcí s rozšířenou působností - rok 2019

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 182. [D] Obyvatelstvo podle jednotek věku a pohlaví ve správních obvodech obcí s rozšířenou působností - rok 2018

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_do, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 183. [D] Naděje dožití v okresech a správních obvodech ORP - rok 2017

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 184. [D] Naděje dožití v okresech a správních obvodech ORP - rok 2016

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 185. [D] Naděje dožití v okresech a správních obvodech ORP - rok 2015

                         hodnota
polozka
target_years_present        None
has_primary_key            False
primary_key_column    vuzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, vuzemi_cis, vuzemi_kod, casref_od, casref_do, stapro_txt, pohlavi_txt, vek_txt, vuzemi_txt]
Index: []

## 186. [D] Databáze KROK - data 2021

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 187. [D] Databáze MOS - data 2021

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 188. [D] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle cílového území a pohlaví

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, bydliste_cis, bydliste_kod, cil_dojizdky_cis, cil_dojizdky_kod, pohlavi_cis, pohlavi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, bydliste_txt, bydliste_typ, cil_dojizdky_txt, cil_dojizdky_typ, pohlavi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, bydliste_cis, bydliste_kod, cil_dojizdky_cis, cil_dojizdky_kod, pohlavi_cis, pohlavi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, bydliste_txt, bydliste_typ, cil_dojizdky_txt, cil_dojizdky_typ, pohlavi_txt]
Index: []

## 189. [D] Sčítání 2021 - Vyjíždějící do zaměstnání podle cílového území a pohlaví

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, bydliste_cis, bydliste_kod, cil_dojizdky_cis, cil_dojizdky_kod, pohlavi_cis, pohlavi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, bydliste_txt, bydliste_typ, cil_dojizdky_txt, cil_dojizdky_typ, pohlavi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, bydliste_cis, bydliste_kod, cil_dojizdky_cis, cil_dojizdky_kod, pohlavi_cis, pohlavi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, bydliste_txt, bydliste_typ, cil_dojizdky_txt, cil_dojizdky_typ, pohlavi_txt]
Index: []

## 190. [D] Sčítání 2021 - Vyjíždějící do školy podle cílového území a pohlaví

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, bydliste_cis, bydliste_kod, cil_dojizdky_cis, cil_dojizdky_kod, pohlavi_cis, pohlavi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, bydliste_txt, bydliste_typ, cil_dojizdky_txt, cil_dojizdky_typ, pohlavi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, bydliste_cis, bydliste_kod, cil_dojizdky_cis, cil_dojizdky_kod, pohlavi_cis, pohlavi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, bydliste_txt, bydliste_typ, cil_dojizdky_txt, cil_dojizdky_typ, pohlavi_txt]
Index: []

## 191. [D] Databáze KROK - data 2020

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 192. [D] Databáze MOS - data 2020

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 193. [D] Databáze KROK - data 2019

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 194. [D] Databáze MOS - data 2019

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 195. [D] Databáze KROK - data 2018

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 196. [D] Databáze MOS - data 2018

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 197. [D] Databáze KROK - data 2017

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 198. [D] Databáze MOS - data 2017

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 199. [D] Databáze KROK - data 2016

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 200. [D] Databáze MOS - data 2016

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 201. [D] Databáze KROK - data 2015

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 202. [D] Databáze MOS - data 2015

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 203. [D] Databáze KROK - data 2014

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 204. [D] Databáze MOS - data 2014

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 205. [D] Databáze KROK - data 2013

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 206. [D] Databáze MOS - data 2013

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 207. [D] Databáze KROK - data 2012

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 208. [D] Databáze MOS - data 2012

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 209. [D] Databáze KROK - data 2011

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 210. [D] Databáze MOS - data 2011

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 211. [D] Databáze KROK - data 2010

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 212. [D] Databáze MOS - data 2010

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 213. [D] Databáze KROK - data 2009

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 214. [D] Databáze MOS - data 2009

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 215. [D] Databáze KROK - data 2008

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 216. [D] Databáze MOS - data 2008

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 217. [D] Databáze KROK - data 2007

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 218. [D] Databáze MOS - data 2007

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 219. [D] Databáze KROK - data 2006

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 220. [D] Databáze MOS - data 2006

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 221. [D] Databáze KROK - data 2005

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 222. [D] Databáze MOS - data 2005

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 223. [D] Databáze KROK - data 2004

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 224. [D] Databáze MOS - data 2004

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 225. [D] Databáze KROK - data 2003

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 226. [D] Databáze MOS - data 2003

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 227. [D] Databáze KROK - data 2002

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 228. [D] Databáze MOS - data 2002

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 229. [D] Databáze KROK - data 2001

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 230. [D] Databáze MOS - data 2001

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 231. [D] Databáze KROK - data 2000

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 232. [D] Databáze MOS - data 2000

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

**TAIL**

Empty DataFrame
Columns: [rok, kodukaz, koduzemi, hodnota ]
Index: []

## 233. [D] Výběr údajů ze SLDB 2011 za domy a byty

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,typuz_naz,nazev,uzcis,uzkod,vse7111,vse7112,vse7113,vse7114,vse7121,vse7122,...,vse8183,vse8184,vse8191,vse8192,vse8193,vse8194,vse81101,vse81102,vse81103,vse81104
0,kraj,Hlavní město Praha,100,3018,99949.0,63610.0,32986.0,3353.0,92927.0,57354.0,...,116581.0,777.0,134535.0,16496.0,117572.0,467.0,61204.0,30322.0,30490.0,392.0
1,kraj,Středočeský kraj,100,3026,353037.0,327239.0,19892.0,5906.0,286780.0,262703.0,...,57181.0,1048.0,123515.0,73273.0,49481.0,761.0,134041.0,123550.0,9866.0,625.0
2,kraj,Jihočeský kraj,100,3034,163889.0,148153.0,12694.0,3042.0,123048.0,108358.0,...,34405.0,526.0,72151.0,34042.0,37604.0,505.0,58590.0,48512.0,9780.0,298.0
3,kraj,Plzeňský kraj,100,3042,131052.0,115381.0,12814.0,2857.0,105835.0,90894.0,...,36457.0,471.0,65350.0,29958.0,35071.0,321.0,48279.0,39797.0,8258.0,224.0
4,kraj,Karlovarský kraj,100,3051,44979.0,33753.0,9616.0,1610.0,39845.0,29092.0,...,29304.0,292.0,28258.0,8654.0,19388.0,216.0,19304.0,13765.0,5393.0,146.0

**TAIL**

,typuz_naz,nazev,uzcis,uzkod,vse7111,vse7112,vse7113,vse7114,vse7121,vse7122,...,vse8183,vse8184,vse8191,vse8192,vse8193,vse8194,vse81101,vse81102,vse81103,vse81104
6707,správní obvod Prahy,Praha 19,72,1119,2396.0,2077.0,280.0,39.0,2221.0,1909.0,...,811.0,12.0,1111.0,571.0,538.0,2.0,1185.0,1013.0,169.0,3.0
6708,správní obvod Prahy,Praha 20,72,1120,2633.0,2347.0,238.0,48.0,2395.0,2116.0,...,730.0,11.0,1772.0,629.0,1124.0,19.0,1329.0,1112.0,213.0,4.0
6709,správní obvod Prahy,Praha 21,72,1121,4358.0,4094.0,191.0,73.0,3940.0,3686.0,...,506.0,10.0,1348.0,850.0,487.0,11.0,2517.0,2279.0,228.0,10.0
6710,správní obvod Prahy,Praha 22,72,1122,3035.0,2752.0,238.0,45.0,2736.0,2459.0,...,642.0,20.0,979.0,534.0,434.0,11.0,1562.0,1431.0,122.0,9.0
6711,stát,Česká republika,97,19,2158119.0,1901126.0,214760.0,42233.0,1800075.0,1554794.0,...,669508.0,7657.0,1130229.0,481142.0,642967.0,6120.0,873631.0,728236.0,141149.0,4246.0

## 234. [D] Výběr údajů ze SLDB 2011 za domácnosti

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,typuz_naz,nazev,uzcis,uzkod,vse10111,vse10121,vse10131,vse10141,vse10151,vse10161,vse10171,vse10181,vse10191
0,kraj,Hlavní město Praha,100,3018,579509.0,300262.0,138255.0,85440.0,36987.0,39580.0,5034.0,225802.0,48411.0
1,kraj,Středočeský kraj,100,3026,523045.0,329829.0,150431.0,112184.0,32229.0,34985.0,10207.0,158918.0,24091.0
2,kraj,Jihočeský kraj,100,3034,262692.0,163840.0,76508.0,53696.0,15649.0,17987.0,4332.0,84195.0,10325.0
3,kraj,Plzeňský kraj,100,3042,242397.0,147651.0,71475.0,46581.0,14052.0,15543.0,3555.0,79334.0,11857.0
4,kraj,Karlovarský kraj,100,3051,128904.0,73917.0,34015.0,21078.0,8252.0,10572.0,1610.0,45345.0,8032.0

**TAIL**

,typuz_naz,nazev,uzcis,uzkod,vse10111,vse10121,vse10131,vse10141,vse10151,vse10161,vse10171,vse10181,vse10191
6707,správní obvod Prahy,Praha 19,72,1119,5380.0,3202.0,1355.0,1202.0,289.0,356.0,74.0,1774.0,330.0
6708,správní obvod Prahy,Praha 20,72,1120,6044.0,3864.0,1674.0,1343.0,373.0,474.0,109.0,1722.0,349.0
6709,správní obvod Prahy,Praha 21,72,1121,6565.0,4386.0,1865.0,1646.0,372.0,503.0,157.0,1702.0,320.0
6710,správní obvod Prahy,Praha 22,72,1122,5803.0,3591.0,1435.0,1431.0,300.0,425.0,85.0,1781.0,346.0
6711,stát,Česká republika,97,19,4375122.0,2667867.0,1236561.0,860470.0,271859.0,298977.0,69694.0,1422147.0,215414.0

## 235. [D] Výběr údajů ze SLDB 2011 za obyvatelstvo

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,typuz_naz,nazev,uzcis,uzkod,vse1111,vse1112,vse1113,vse1121,vse1122,vse1123,...,vse6193,vse61101,vse61102,vse61103,vse61111,vse61112,vse61113,vse61121,vse61122,vse61123
0,kraj,Hlavní město Praha,100,3018,1268796.0,613738.0,655058.0,535604.0,285543.0,250061.0,...,294698.0,231135.0,83326.0,147809.0,147461.0,73622.0,73839.0,123182.0,72214.0,50968.0
1,kraj,Středočeský kraj,100,3026,1289211.0,637252.0,651959.0,507375.0,280621.0,226754.0,...,334656.0,266140.0,102500.0,163640.0,174154.0,87125.0,87029.0,66595.0,40072.0,26523.0
2,kraj,Jihočeský kraj,100,3034,628336.0,308296.0,320040.0,245650.0,135702.0,109948.0,...,169649.0,142858.0,55375.0,87483.0,90905.0,45122.0,45783.0,26619.0,15605.0,11014.0
3,kraj,Plzeňský kraj,100,3042,570401.0,282137.0,288264.0,222189.0,124170.0,98019.0,...,149000.0,130064.0,51112.0,78952.0,74891.0,37205.0,37686.0,31752.0,19261.0,12491.0
4,kraj,Karlovarský kraj,100,3051,295595.0,145483.0,150112.0,121610.0,67238.0,54372.0,...,74334.0,62774.0,23914.0,38860.0,38270.0,19367.0,18903.0,24405.0,13850.0,10555.0

**TAIL**

,typuz_naz,nazev,uzcis,uzkod,vse1111,vse1112,vse1113,vse1121,vse1122,vse1123,...,vse6193,vse61101,vse61102,vse61103,vse61111,vse61112,vse61113,vse61121,vse61122,vse61123
6707,správní obvod Prahy,Praha 19,72,1119,13076.0,6544.0,6532.0,5515.0,2979.0,2536.0,...,3104.0,2022.0,757.0,1265.0,1593.0,801.0,792.0,1122.0,753.0,369.0
6708,správní obvod Prahy,Praha 20,72,1120,15262.0,7532.0,7730.0,6154.0,3321.0,2833.0,...,3577.0,2511.0,986.0,1525.0,2149.0,1111.0,1038.0,890.0,523.0,367.0
6709,správní obvod Prahy,Praha 21,72,1121,17921.0,9121.0,8800.0,7304.0,4093.0,3211.0,...,4304.0,2789.0,1078.0,1711.0,2548.0,1330.0,1218.0,1711.0,1088.0,623.0
6710,správní obvod Prahy,Praha 22,72,1122,14124.0,6966.0,7158.0,6308.0,3361.0,2947.0,...,3334.0,1778.0,648.0,1130.0,1854.0,912.0,942.0,921.0,562.0,359.0
6711,stát,Česká republika,97,19,10436560.0,5109766.0,5326794.0,4164427.0,2287597.0,1876830.0,...,2760108.0,2308294.0,882539.0,1425755.0,1446138.0,720731.0,725407.0,571064.0,334912.0,236152.0

## 236. [D] Výběr údajů ze SLDB 2011 za vyjížďku

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,typuz_naz,nazev,uzcis,uzkod,vse9111,vse9121,vse9131,vse9141,vse9151,vse9161,vse9171,vse9181,vse9191,vse91101
0,kraj,Hlavní město Praha,100,3018,363057.0,274568.0,250277.0,0.0,0.0,19615.0,4676.0,88489.0,82806.0,5683.0
1,kraj,Středočeský kraj,100,3026,367980.0,271378.0,57680.0,78688.0,25861.0,106645.0,2504.0,96602.0,26416.0,70186.0
2,kraj,Jihočeský kraj,100,3034,172169.0,122918.0,48181.0,48648.0,13561.0,8829.0,3699.0,49251.0,17074.0,32177.0
3,kraj,Plzeňský kraj,100,3042,157987.0,116786.0,47851.0,30368.0,27693.0,7691.0,3183.0,41201.0,17441.0,23760.0
4,kraj,Karlovarský kraj,100,3051,64822.0,47793.0,18276.0,18720.0,5490.0,3331.0,1976.0,17029.0,6191.0,10838.0

**TAIL**

,typuz_naz,nazev,uzcis,uzkod,vse9111,vse9121,vse9131,vse9141,vse9151,vse9161,vse9171,vse9181,vse9191,vse91101
6707,správní obvod Prahy,Praha 19,72,1119,4040.0,3133.0,2759.0,0.0,0.0,331.0,43.0,907.0,848.0,59.0
6708,správní obvod Prahy,Praha 20,72,1120,5522.0,4028.0,3588.0,0.0,0.0,399.0,41.0,1494.0,1401.0,93.0
6709,správní obvod Prahy,Praha 21,72,1121,5544.0,4012.0,3557.0,0.0,0.0,401.0,54.0,1532.0,1416.0,116.0
6710,správní obvod Prahy,Praha 22,72,1122,4528.0,3481.0,3054.0,0.0,0.0,382.0,45.0,1047.0,965.0,82.0
6711,stát,Česká republika,97,19,2846076.0,2062124.0,924948.0,596686.0,254617.0,248625.0,37248.0,783952.0,354218.0,429734.0

## 237. [D] Základní výsledky Sčítání lidu, domů a bytů 2011

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,typuz_naz,nazev,uzcis,uzkod,u01,u02,u03,u04,u05,u06,u07,u08,u09,u10,u11
0,kraj,Hlavní město Praha,100,3018,1268796.0,613738.0,655058.0,153622.0,908321.0,201029.0,644643.0,600730.0,92927.0,542168.0,579509.0
1,kraj,Středočeský kraj,100,3026,1289211.0,637252.0,651959.0,199300.0,895024.0,190911.0,639851.0,587539.0,286780.0,482860.0,523045.0
2,kraj,Jihočeský kraj,100,3034,628336.0,308296.0,320040.0,91119.0,435187.0,100000.0,307130.0,280844.0,123048.0,247608.0,262692.0
3,kraj,Plzeňský kraj,100,3042,570401.0,282137.0,288264.0,79469.0,396468.0,92734.0,278674.0,255278.0,105835.0,226298.0,242397.0
4,kraj,Karlovarský kraj,100,3051,295595.0,145483.0,150112.0,42159.0,207480.0,44538.0,139871.0,123100.0,39845.0,119403.0,128904.0

**TAIL**

,typuz_naz,nazev,uzcis,uzkod,u01,u02,u03,u04,u05,u06,u07,u08,u09,u10,u11
6707,správní obvod Prahy,Praha 19,72,1119,13076.0,6544.0,6532.0,2188.0,9213.0,1638.0,6582.0,6176.0,2221.0,4854.0,5380.0
6708,správní obvod Prahy,Praha 20,72,1120,15262.0,7532.0,7730.0,2239.0,11038.0,1943.0,8056.0,7503.0,2395.0,5440.0,6044.0
6709,správní obvod Prahy,Praha 21,72,1121,17921.0,9121.0,8800.0,3037.0,12627.0,2198.0,8607.0,8020.0,3940.0,5872.0,6565.0
6710,správní obvod Prahy,Praha 22,72,1122,14124.0,6966.0,7158.0,2599.0,10054.0,1408.0,7442.0,7030.0,2736.0,5342.0,5803.0
6711,stát,Česká republika,97,19,10436560.0,5109766.0,5326794.0,1488928.0,7267169.0,1644836.0,5080573.0,4580714.0,1800075.0,4104635.0,4375122.0

## 238. [D] Příjmy domácností zaměstnanců a důchodců

                        hodnota
polozka
target_years_present       2023
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

,idhod,hodnota,stapro_kod,ekakocd_cis,ekakocd_kod,pvdom_cis,pvdom_kod,rok,uzemi_cis,uzemi_kod,stapro_txt,ekakocd_txt,pvdom_txt
144,1441283496,278673,6010,NaN,NaN,NaN,NaN,2023,97,19,Průměrné čisté peněžní příjmy domácností,Domácnosti celkem,NaN
145,1441283497,154702,6010,NaN,NaN,213.0,14.0,2023,97,19,Průměrné čisté peněžní příjmy domácností,Domácnosti celkem,Příjmy ze závislé činnosti (hlavní zaměstnání)
146,1441283498,286954,6010,221.0,6.0,NaN,NaN,2023,97,19,Průměrné čisté peněžní příjmy domácností,Zaměstnanci,NaN
147,1441283499,235015,6010,221.0,6.0,213.0,14.0,2023,97,19,Průměrné čisté peněžní příjmy domácností,Zaměstnanci,Příjmy ze závislé činnosti (hlavní zaměstnání)
148,1441283528,310594,6010,221.0,5.0,NaN,NaN,2023,97,19,Průměrné čisté peněžní příjmy domácností,Samostatně činní,NaN

**TAIL**

,idhod,hodnota,stapro_kod,ekakocd_cis,ekakocd_kod,pvdom_cis,pvdom_kod,rok,uzemi_cis,uzemi_kod,stapro_txt,ekakocd_txt,pvdom_txt
1138,1441283193,282872,8620,221.0,6.0,NaN,NaN,2023,97,19,Průměrné disponibilní čisté příjmy domácností,Zaměstnanci,NaN
1139,1441283196,303691,8620,221.0,5.0,NaN,NaN,2023,97,19,Průměrné disponibilní čisté příjmy domácností,Samostatně činní,NaN
1140,1441283197,249566,8620,220.0,14.0,NaN,NaN,2023,97,19,Průměrné disponibilní čisté příjmy domácností,Důchodci,NaN
1141,1441283198,100525,8620,221.0,4.0,NaN,NaN,2023,97,19,Průměrné disponibilní čisté příjmy domácností,Nezaměstnaní,NaN
1142,1441283199,123707,8620,221.0,11.0,NaN,NaN,2023,97,19,Průměrné disponibilní čisté příjmy domácností,Ostatní domácnosti,NaN

## 239. [D] Obyvatelstvo podle jednotek věku a pohlaví - rok 2022

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, uzemi_cis, uzemi_kod, obdobi, pohlavi_txt, vek_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, stapro_kod, pohlavi_cis, pohlavi_kod, vek_cis, vek_kod, uzemi_cis, uzemi_kod, obdobi, pohlavi_txt, vek_txt, uzemi_txt, uzemi_typ]
Index: []

## 240. [D] Sčítání 2021 - Vyjíždějící do zaměstnání a školy podle kraje místa pracoviště/školy

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, kraj_dojizdky_cis, kraj_dojizdky_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, kraj_dojizdky_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, kraj_dojizdky_cis, kraj_dojizdky_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, kraj_dojizdky_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 241. [D] Sčítání 2021 - Vyjíždějící do zaměstnání podle kraje místa pracoviště

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, kraj_dojizdky_cis, kraj_dojizdky_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, kraj_dojizdky_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, kraj_dojizdky_cis, kraj_dojizdky_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, kraj_dojizdky_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 242. [D] Sčítání 2021 - Vyjíždějící do školy podle kraje místa školy

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, kraj_dojizdky_cis, kraj_dojizdky_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, kraj_dojizdky_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, ukaz_kod, aktivita_cis, aktivita_kod, kraj_dojizdky_cis, kraj_dojizdky_kod, pohlavi_cis, pohlavi_kod, uzemi_cis, uzemi_kod, sldb_rok, sldb_datum, ukaz_txt, aktivita_txt, kraj_dojizdky_txt, pohlavi_txt, uzemi_txt, uzemi_typ]
Index: []

## 243. [D] Produkce podnikových a komunálních odpadů podle krajů

                        hodnota
polozka
target_years_present       None
has_primary_key           False
primary_key_column    uzemi_cis

**HEAD**

Empty DataFrame
Columns: [idhod, hodnota, duvernost, stapro_kod, cznace_cis, cznace_kod, rok, uzemi_cis, uzemi_kod, stapro_txt, cznace_txt, uzemi_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [idhod, hodnota, duvernost, stapro_kod, cznace_cis, cznace_kod, rok, uzemi_cis, uzemi_kod, stapro_txt, cznace_txt, uzemi_txt]
Index: []

## 244. [D] Indexy spotřebitelských cen

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 245. [D] Indexy tržeb v odvětví dopravy, maloobchodu a služeb

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 246. [D] Konjunkturální průzkumy

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 247. [D] Průměrné spotřebitelské ceny pohonných hmot - týdenní šetření

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 248. [D] Regionální účty za regiony soudržnosti a kraje

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 249. [D] Vybavenost domácností informačními a komunikačními technologiemi

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 250. [D] Základní ukazatele národních účtů

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 251. [D] Úmrtnostní tabulky pro regiony soudržnosti

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 252. [D] Úmrtnostní tabulky pro správní obvody obcí s rozšířenou působností

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 253. [D] Bilance meziokresní vyjížďky do zaměstnání podle výsledků sčítání 2011

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [﻿"idhod", hodnota, stapro_kod, ekonaktiv_cis, ekonaktiv_kod, uzemiz_cis, uzemiz_kod, uzemido_cis, uzemido_kod, datum, uzemiz_txt, uzemido_txt]
Index: []

**TAIL**

Empty DataFrame
Columns: [﻿"idhod", hodnota, stapro_kod, ekonaktiv_cis, ekonaktiv_kod, uzemiz_cis, uzemiz_kod, uzemido_cis, uzemido_kod, datum, uzemiz_txt, uzemido_txt]
Index: []

## 254. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2004

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 255. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2005

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 256. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2006

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 257. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2007

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 258. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2008

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 259. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2009

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 260. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2010

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 261. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2011

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 262. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2012

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 263. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2013

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 264. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2014

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 265. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2015

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 266. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2016

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 267. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2017

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 268. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2018

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 269. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2019

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 270. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2020

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 271. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2021

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 272. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2022

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 273. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2023

                     hodnota
polozka
target_years_present    2023
has_primary_key         None
primary_key_column      None

## 274. [D] Cizinci podle státního občanství, věku a pohlaví - rok 2024

                     hodnota
polozka
target_years_present    2024
has_primary_key         None
primary_key_column      None

## 275. [D] Průměrné spotřebitelské ceny vybraných výrobků - potravinářské výrobky

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 276. [D] Hosté a přenocování v hotelích podle zemí

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 277. [D] Hosté a přenocování v hromadných ubytovacích zařízeních podle zemí

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 278. [D] Kapacity hromadných ubytovacích zařízení

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 279. [D] Návštěvnost hromadných ubytovacích zařízení

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 280. [D] Návštěvnost hromadných ubytovacích zařízení v oblastech destinačních managementů podle zemí

                         hodnota
polozka
target_years_present  2023, 2024
has_primary_key             None
primary_key_column          None

## 281. [D] Volby do Senátu Parlamentu ČR 2018 konané dne 5.10. - 6.10.2018 - číselníky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

**TAIL**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

## 283. [D] Volby do Senátu Parlamentu ČR 2022 - číselník obcí, městských částí, městských obvodů, katastrů a volebních okrsků

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

**TAIL**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

## 283. [D] Volby do Senátu Parlamentu ČR 2022 - číselník obcí, městských částí, městských obvodů, katastrů a volebních okrsků

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

**TAIL**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

## 285. [D] Volby do Senátu Parlamentu ČR 2024 - číselník obcí, městských částí, městských obvodů, katastrů a volebních okrsků

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

**TAIL**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

## 285. [D] Volby do Senátu Parlamentu ČR 2024 - číselník obcí, městských částí, městských obvodů, katastrů a volebních okrsků

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

**TAIL**

Empty DataFrame
Columns: [KRAJ, OKRES, CPOU, ORP, OBEC, NAZEVOBCE, OBVOD, MINOKRSEK1, MAXOKRSEK1, MINOKRSEK2, MAXOKRSEK2, MINOKRSEK3, MAXOKRSEK3, MINOKRSEK4, MAXOKRSEK4, MINOKRSEK5, MAXOKRSEK5, MINOKRSEK6, MAXOKRSEK6, MINOKRSEK7, MAXOKRSEK7, MINOKRSEK8, MAXOKRSEK8, MINOKRSEK9, MAXOKRSEK9, MINOKRSE10, MAXOKRSE10, OBEC_PREZ]
Index: []

[0 rows x 28 columns]

## 286. [D] Registry pro volby do zastupitelstev krajů 2016

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 287. [D] Volba prezidenta 2018 - číselníky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,OBEC,OKRSEK,KC1,NAZEVOKRSK,TYPURADU,KODZEME,ZKRZEME,NAZEVZEME,SVETADIL,ADRESA,CASPOSUN,NAZEVOKRSA,NAZEVZEMEA
0,999997,1,5,Tirana,vv,8,AL,Albánie,EV,Rruga Skenderbej 10; 1000 Tirana; Albania,0.0,Tirana,Albania
1,999997,2,6,Vídeō,vv,40,AT,Rakousko,EV,Penzingerstrasse 11-13; 1140 Wien; Republik Ös...,0.0,Vienna,Austria
2,999997,3,0,Brusel,vv,56,BE,Belgie,EV,"154, av. Adolphe Buyl; 1050 Bruxelles; Kingdom...",0.0,Brussels,Belgium
3,999997,4,1,Sarajevo,vv,70,BA,Bosna a Hercegovina,EV,Franjevačka 13; 71000 Sarajevo; Bosna i Herceg...,0.0,Sarajevo,Bosnia and Herzegovina
4,999997,5,2,Sofie,vv,100,BG,Bulharsko,EV,G.S. Rakovski 100; 1000 Sofia; Bulgaria,1.0,Sofia,Bulgaria

**TAIL**

,OBEC,OKRSEK,KC1,NAZEVOKRSK,TYPURADU,KODZEME,ZKRZEME,NAZEVZEME,SVETADIL,ADRESA,CASPOSUN,NAZEVOKRSA,NAZEVZEMEA
105,999997,106,5,Nairobi,vv,404,KE,Keōa,AF,"Embassy of the Czech Republik, P.O.Box 25639, ...",2.0,Nairobi,Kenya
106,999997,107,6,Lusaka,vv,894,ZM,Zambie,AF,"Embassy of the Czech Republic, 2A Twin Palm Ro...",1.0,Lusaka,Zambia
107,999997,108,0,Canberra,vv,36,AU,Austrálie,AO,"8 Culgoa Circuit, OīMalley; Canberra, ACT 2606...",10.0,Canberra,Australia
108,999997,109,1,Sydney,gk,36,AU,Austrálie,AO,"169 Military Road, Dover Heights; NSW 2030 Syd...",10.0,Sydney,Australia
109,999997,110,2,Tchaj-pej (Tchaj-wan),ek,156,CN,Čína,AS,"7F-Room B, No. 200, Keelung Road, Sec. 1, 110 ...",7.0,Taipei (Taiwan),China

## 288. [D] Volba prezidenta republiky 2018 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_15,HLASY_16,HLASY_17,HLASY_18,HLASY_19,HLASY_20,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,7204,500011,1,6,1,741,500,...,0,0,0,0,0,0,3148,5385,9,510798
1,1,0,0,7204,500011,2,0,1,429,275,...,0,0,0,0,0,0,1847,3099,9,506221
2,1,0,0,7204,500011,3,1,1,405,284,...,0,0,0,0,0,0,1717,2975,9,505975
3,1,0,0,7105,500020,1,2,1,263,159,...,0,0,0,0,0,0,1075,1816,9,503665
4,1,0,0,7105,500020,2,3,1,698,415,...,0,0,0,0,0,0,2718,4661,9,509357

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_15,HLASY_16,HLASY_17,HLASY_18,HLASY_19,HLASY_20,KC_3,KC_4,POSL_KAND,KC_SUM
29727,1,0,0,9999,999997,106,5,2,21,18,...,0,0,0,0,0,0,152,229,9,1000576
29728,1,0,0,9999,999997,107,6,2,24,12,...,0,0,0,0,0,0,104,166,9,1000452
29729,1,0,0,9999,999997,108,0,2,57,35,...,0,0,0,0,0,0,307,471,9,1001057
29730,1,0,0,9999,999997,109,1,2,557,328,...,0,0,0,0,0,0,2900,4443,9,1009003
29731,1,0,0,9999,999997,110,2,2,33,32,...,0,0,0,0,0,0,280,411,9,1000941

## 289. [D] Volba prezidenta republiky 2023 - výsledky pro zadaný kraj, jeho okresy i obce a pro zadané kolo volby

                     hodnota
polozka
target_years_present    2023
has_primary_key         None
primary_key_column      None

## 290. [D] Volba prezidenta republiky 2023 - výsledky za celou ČR

                     hodnota
polozka
target_years_present    2023
has_primary_key         None
primary_key_column      None

## 291. [D] Volba prezidenta republiky 2023 - výsledky za kraje a krajská města pro zadané kolo volby

                     hodnota
polozka
target_years_present    2023
has_primary_key         None
primary_key_column      None

## 292. [D] Volba prezidenta republiky 2023 - výsledky za zahraničí, kontinenty a státy pro zadané kolo volby

                     hodnota
polozka
target_years_present    2023
has_primary_key         None
primary_key_column      None

## 293. [D] Volba prezidenta republiky 2023 - výsledky za zpracované okrsky pro zadané číslo dávky a kolo volby

                     hodnota
polozka
target_years_present    2023
has_primary_key         None
primary_key_column      None

## 294. [D] Volba prezidenta republiky 2023 - zápisy za všechny okrsky po 1. kole

                     hodnota
polozka
target_years_present    2023
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_15,HLASY_16,HLASY_17,HLASY_18,HLASY_19,HLASY_20,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,7204,500011,1,6,1,723,520,...,0,0,0,0,0,0,2688,4967,9,509962
1,1,0,0,7204,500011,2,0,1,417,295,...,0,0,0,0,0,0,1497,2797,9,505617
2,1,0,0,7204,500011,3,1,1,393,297,...,0,0,0,0,0,0,1489,2772,9,505569
3,1,0,0,7105,500020,1,2,1,262,151,...,0,0,0,0,0,0,836,1552,9,503137
4,1,0,0,7105,500020,2,3,1,736,492,...,0,0,0,0,0,0,2703,4910,9,509855

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_15,HLASY_16,HLASY_17,HLASY_18,HLASY_19,HLASY_20,KC_3,KC_4,POSL_KAND,KC_SUM
29709,1,0,0,9999,999997,106,5,2,42,37,...,0,0,0,0,0,0,154,309,7,1000734
29710,1,0,0,9999,999997,107,6,2,32,18,...,0,0,0,0,0,0,81,169,7,1000456
29711,1,0,0,9999,999997,108,0,2,7,5,...,0,0,0,0,0,0,20,44,4,1000198
29712,1,0,0,9999,999997,109,1,2,88,46,...,0,0,0,0,0,0,199,427,7,1000969
29713,1,0,0,9999,999997,110,2,2,641,269,...,0,0,0,0,0,0,1159,2608,7,1005333

## 295. [D] Volby do Evropského parlamentu 2019 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,ESTRANA,POC_HLASU,...,HLASY_23,HLASY_24,HLASY_25,HLASY_26,HLASY_27,HLASY_28,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,2,0,0,7204,500011,1,6,3,3,...,0,0,0,0,0,0,12,18,6,507266
1,1,2,0,0,7204,500011,1,6,5,29,...,0,0,0,0,0,0,54,88,15,507415
2,1,2,0,0,7204,500011,1,6,6,4,...,0,0,0,0,0,0,0,10,0,507244
3,1,2,0,0,7204,500011,1,6,7,18,...,0,0,0,0,0,0,32,57,7,507345
4,1,2,0,0,7204,500011,1,6,9,10,...,0,0,0,0,0,0,23,42,20,507328

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,ESTRANA,POC_HLASU,...,HLASY_23,HLASY_24,HLASY_25,HLASY_26,HLASY_27,HLASY_28,KC_3,KC_4,POSL_KAND,KC_SUM
33108,14766,2,0,0,8104,599999,2,0,34,1,...,0,0,0,0,0,0,5,40,4,608191
33109,14766,2,0,0,8104,599999,2,0,36,5,...,0,0,0,0,0,0,37,78,15,608278
33110,14766,2,0,0,8104,599999,2,0,37,1,...,0,0,0,0,0,0,1,39,1,608186
33111,14766,2,0,0,8104,599999,2,0,39,39,...,2,0,0,0,0,3,229,307,28,608749
33112,14766,2,0,0,8104,599999,2,0,40,2,...,0,0,0,0,0,0,6,48,6,608209

## 296. [D] Volby do Evropského parlamentu 2019 - číselníky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,KRAJ,OKRES,CPOU,OBEC,OBEC_PREZ,NAZEVOBCE,ORP,MINOKRSEK1,MAXOKRSEK1
0,7200,7204,662,500011,500011,Želechovice nad Dřevnicí,7213,1,3
1,7100,7105,860,500020,500020,Petrov nad Desnou,7111,1,2
2,8100,8104,792,500046,500046,Libhošť,8115,1,1
3,1100,1100,1,500054,554782,Praha 1,1000,1001,1021
4,7200,7203,871,500062,500062,Krhová,7210,1,1

**TAIL**

,KRAJ,OKRES,CPOU,OBEC,OBEC_PREZ,NAZEVOBCE,ORP,MINOKRSEK1,MAXOKRSEK1
6383,8100,8104,792,599930,599930,Suchdol nad Odrou,8115,1,2
6384,8100,8104,791,599948,599948,Štramberk,8112,1,4
6385,8100,8104,789,599956,599956,Tichá,8105,1,1
6386,8100,8104,788,599964,599964,Tísek,8101,1,1
6387,8100,8104,789,599999,599999,Trojanovice,8105,1,2

## 297. [D] Volby do Evropského parlamentu 2024 - přílohy k zápisu s výsledky za okrsky

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,ESTRANA,POC_HLASU,...,HLASY_23,HLASY_24,HLASY_25,HLASY_26,HLASY_27,HLASY_28,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,2,0,0,7204,500011,1,6,1,1,...,0,0,0,0,0,0,0,2,0,507228
1,1,2,0,0,7204,500011,1,6,3,26,...,0,0,0,0,0,0,35,64,3,507355
2,1,2,0,0,7204,500011,1,6,4,1,...,0,0,0,0,0,0,0,5,0,507234
3,1,2,0,0,7204,500011,1,6,6,3,...,0,0,0,0,0,0,3,12,2,507250
4,1,2,0,0,7204,500011,1,6,9,26,...,0,0,0,0,0,0,25,60,4,507348

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,ESTRANA,POC_HLASU,...,HLASY_23,HLASY_24,HLASY_25,HLASY_26,HLASY_27,HLASY_28,KC_3,KC_4,POSL_KAND,KC_SUM
19392,14714,2,0,0,8104,599999,2,0,23,45,...,0,1,0,0,0,0,152,220,24,608571
19393,14714,2,0,0,8104,599999,2,0,24,1,...,0,0,0,0,0,0,0,25,0,608157
19394,14714,2,0,0,8104,599999,2,0,26,52,...,0,0,0,0,0,0,136,214,21,608556
19395,14714,2,0,0,8104,599999,2,0,27,1,...,0,0,0,0,0,0,0,28,0,608163
19396,14714,2,0,0,8104,599999,2,0,28,1,...,0,0,0,0,0,0,0,29,0,608165

## 299. [D] Volby do Evropského parlamentu 2024 - registr kandidátních listin

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ESTRANA,VSTRANA,NAZEVCELK,NAZEV_STRE,ZKRATKAE30,ZKRATKAE8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
0,1,40,Klub angažovaných nestraníků,Klub angažovaných nestraníků,Klub angažovaných nestraníků,KAN,1,040,0,A,NaN,0,Klub angažovaných nestraníků
1,2,1286,Liberální aliance nezávislých občanů,Liberální aliance nezávislých občanů,Liberální aliance nez. občanů,LANO,1,1286,0,A,NaN,0,Liberální aliance nezávislých občanů
2,3,1487,SPD a Trikolora,SPD a Trikolora,SPD a Trikolora,SPD+Trikolora,2,"1114,1227",0,A,NaN,1,SPD a Trikolora
3,4,1260,Mourek – politická strana,Mourek – politická strana,Mourek – politická strana,Mourek,1,1260,0,A,NaN,0,Mourek – politická strana
4,5,121,"LEPŠÍ ŽIVOT PRO LIDI-min.mzda 70.000 Kč,min.dů...",LEPŠÍ ŽIVOT PRO LIDI,LEPŠÍ ŽIVOT PRO LIDI,LŽPL,1,121,0,A,NaN,0,"LEPŠÍ ŽIVOT PRO LIDI - min. mzda 70.000 Kč, mi..."

**TAIL**

,ESTRANA,VSTRANA,NAZEVCELK,NAZEV_STRE,ZKRATKAE30,ZKRATKAE8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
25,26,1632,"STAČILO!, koalice KSČM, SD-SN, ČSNS","STAČILO!, koalice KSČM, SD-SN, ČSNS","STAČILO!, KSČM, SD-SN, ČSNS",ČSNS+KSČM+SD-SN,3,"002,047,143",0,A,NaN,2,"STAČILO!, koalice Komunistické strany Čech a M..."
26,27,715,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT,DSZ - ZA PRÁVA ZVÍŘAT,DSZ-ZA PR.ZVÍŘ.,1,715,0,A,NaN,0,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT
27,28,98,"Volte Pravý Blok-stranu za ODVOLAT.polit.,NÍZK...",Volte Pravý Blok www.cibulka.net,Volte Pr.Blok www.cibulka.net,PB,1,098,0,A,NaN,0,Volte Pravý Blok - stranu za snadnou a rychlou...
28,29,1240,SENIOŘI SOBĚ,SENIOŘI SOBĚ,SENIOŘI SOBĚ,SESO,1,1240,0,A,NaN,0,SENIOŘI SOBĚ
29,30,74,Levice,Levice,Levice,Levice,1,074,0,A,NaN,0,Levice

## 299. [D] Volby do Evropského parlamentu 2024 - registr kandidátních listin

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ESTRANA,VSTRANA,NAZEVCELK,NAZEV_STRE,ZKRATKAE30,ZKRATKAE8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
0,1,40,Klub angažovaných nestraníků,Klub angažovaných nestraníků,Klub angažovaných nestraníků,KAN,1,040,0,A,NaN,0,Klub angažovaných nestraníků
1,2,1286,Liberální aliance nezávislých občanů,Liberální aliance nezávislých občanů,Liberální aliance nez. občanů,LANO,1,1286,0,A,NaN,0,Liberální aliance nezávislých občanů
2,3,1487,SPD a Trikolora,SPD a Trikolora,SPD a Trikolora,SPD+Trikolora,2,"1114,1227",0,A,NaN,1,SPD a Trikolora
3,4,1260,Mourek – politická strana,Mourek – politická strana,Mourek – politická strana,Mourek,1,1260,0,A,NaN,0,Mourek – politická strana
4,5,121,"LEPŠÍ ŽIVOT PRO LIDI-min.mzda 70.000 Kč,min.dů...",LEPŠÍ ŽIVOT PRO LIDI,LEPŠÍ ŽIVOT PRO LIDI,LŽPL,1,121,0,A,NaN,0,"LEPŠÍ ŽIVOT PRO LIDI - min. mzda 70.000 Kč, mi..."

**TAIL**

,ESTRANA,VSTRANA,NAZEVCELK,NAZEV_STRE,ZKRATKAE30,ZKRATKAE8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
25,26,1632,"STAČILO!, koalice KSČM, SD-SN, ČSNS","STAČILO!, koalice KSČM, SD-SN, ČSNS","STAČILO!, KSČM, SD-SN, ČSNS",ČSNS+KSČM+SD-SN,3,"002,047,143",0,A,NaN,2,"STAČILO!, koalice Komunistické strany Čech a M..."
26,27,715,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT,DSZ - ZA PRÁVA ZVÍŘAT,DSZ-ZA PR.ZVÍŘ.,1,715,0,A,NaN,0,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT
27,28,98,"Volte Pravý Blok-stranu za ODVOLAT.polit.,NÍZK...",Volte Pravý Blok www.cibulka.net,Volte Pr.Blok www.cibulka.net,PB,1,098,0,A,NaN,0,Volte Pravý Blok - stranu za snadnou a rychlou...
28,29,1240,SENIOŘI SOBĚ,SENIOŘI SOBĚ,SENIOŘI SOBĚ,SESO,1,1240,0,A,NaN,0,SENIOŘI SOBĚ
29,30,74,Levice,Levice,Levice,Levice,1,074,0,A,NaN,0,Levice

## 301. [D] Volby do Evropského parlamentu 2024 - registr kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ESTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,STATOBCAN,POVOLANI,BYDLISTEN,BYDLISTEK,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,PORADIMAND,PORADINAHR
0,1,1,Stanislav,Pochman,NaN,NaN,60,CZ,výrobní dispečer,Oloví,560588,40,40,A,113,2.47,N,0,0
1,1,2,František,Laudát,Ing.,NaN,64,CZ,"manager staveb, předseda KAN",Praha,554782,40,40,A,210,4.60,N,0,0
2,1,3,Marie,Gottfriedová,Mgr.,NaN,49,CZ,ředitelka základní školy,Trmice,553697,99,40,A,195,4.27,N,0,0
3,1,4,Jiří,Schmidt,Mgr. et Mgr.,NaN,68,CZ,pedagog,Příbram,539911,99,40,A,73,1.60,N,0,0
4,1,5,Romana,Šimková,Ing.,NaN,36,CZ,Pricing & Merchandising Coordinator,Praha,554782,40,40,A,115,2.52,N,0,0

**TAIL**

,ESTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,STATOBCAN,POVOLANI,BYDLISTEN,BYDLISTEK,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,PORADIMAND,PORADINAHR
670,30,24,Jan,Široký,NaN,NaN,47,CZ,jednatel,Liberec,563889,74,74,A,5,0.21,N,0,0
671,30,25,Alexandr,Gluhov,NaN,NaN,21,CZ,student,Dobříš,540111,74,74,A,8,0.34,N,0,0
672,30,26,Martin,Biskup,Mgr.,NaN,50,CZ,právník,Nový Jičín,599191,74,74,A,22,0.95,N,0,0
673,30,27,Petr,Rohel,PhDr.,NaN,76,CZ,důchodce,Ostrava,554821,74,74,A,8,0.34,N,0,0
674,30,28,Vojtěch,Juřica,NaN,NaN,34,CZ,technik,Praha,554782,74,74,A,6,0.26,N,0,0

## 301. [D] Volby do Evropského parlamentu 2024 - registr kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ESTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,STATOBCAN,POVOLANI,BYDLISTEN,BYDLISTEK,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,PORADIMAND,PORADINAHR
0,1,1,Stanislav,Pochman,NaN,NaN,60,CZ,výrobní dispečer,Oloví,560588,40,40,A,113,2.47,N,0,0
1,1,2,František,Laudát,Ing.,NaN,64,CZ,"manager staveb, předseda KAN",Praha,554782,40,40,A,210,4.60,N,0,0
2,1,3,Marie,Gottfriedová,Mgr.,NaN,49,CZ,ředitelka základní školy,Trmice,553697,99,40,A,195,4.27,N,0,0
3,1,4,Jiří,Schmidt,Mgr. et Mgr.,NaN,68,CZ,pedagog,Příbram,539911,99,40,A,73,1.60,N,0,0
4,1,5,Romana,Šimková,Ing.,NaN,36,CZ,Pricing & Merchandising Coordinator,Praha,554782,40,40,A,115,2.52,N,0,0

**TAIL**

,ESTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,STATOBCAN,POVOLANI,BYDLISTEN,BYDLISTEK,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,PORADIMAND,PORADINAHR
670,30,24,Jan,Široký,NaN,NaN,47,CZ,jednatel,Liberec,563889,74,74,A,5,0.21,N,0,0
671,30,25,Alexandr,Gluhov,NaN,NaN,21,CZ,student,Dobříš,540111,74,74,A,8,0.34,N,0,0
672,30,26,Martin,Biskup,Mgr.,NaN,50,CZ,právník,Nový Jičín,599191,74,74,A,22,0.95,N,0,0
673,30,27,Petr,Rohel,PhDr.,NaN,76,CZ,důchodce,Ostrava,554821,74,74,A,8,0.34,N,0,0
674,30,28,Vojtěch,Juřica,NaN,NaN,34,CZ,technik,Praha,554782,74,74,A,6,0.26,N,0,0

## 303. [D] Volby do Evropského parlamentu 2024 - složení kandidátních listin

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   ESTRANA TYPSLOZENI  NSTRANA
0        1          P       40
1        2          P     1286
2        3          P     1114
3        3          P     1227
4        4          P     1260

**TAIL**

    ESTRANA TYPSLOZENI  NSTRANA
43       26          P        2
44       27          P      715
45       28          P       98
46       29          P     1240
47       30          P       74

## 303. [D] Volby do Evropského parlamentu 2024 - složení kandidátních listin

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   ESTRANA TYPSLOZENI  NSTRANA
0        1          P       40
1        2          P     1286
2        3          P     1114
3        3          P     1227
4        4          P     1260

**TAIL**

    ESTRANA TYPSLOZENI  NSTRANA
43       26          P        2
44       27          P      715
45       28          P       98
46       29          P     1240
47       30          P       74

## 305. [D] Volby do Evropského parlamentu 2024 - složení volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5

**TAIL**

      VSTRANA  NSTRANA
2795     1635     1272
2796     1636     1265
2797     1636     1269
2798     9995     9995
2799     9999     9999

## 305. [D] Volby do Evropského parlamentu 2024 - složení volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5

**TAIL**

      VSTRANA  NSTRANA
2795     1635     1272
2796     1636     1265
2797     1636     1269
2798     9995     9995
2799     9999     9999

## 306. [D] Volby do Evropského parlamentu 2024 - zápisy s výsledky za okrsky

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KC_2,ZAKRSTRANA,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK
0,1,1,0,0,7204,500011,1,6,1552,1011010010111110101110100110000000000000000000...,712,280,280,280
1,2,1,0,0,7204,500011,2,0,905,0110010010000110101110100110000000000000000000...,414,164,164,163
2,3,1,0,0,7204,500011,3,1,877,1010010010010110111110110100100000000000000000...,401,159,159,158
3,4,1,0,0,7105,500020,1,2,499,0010110010000100101110100100000000000000000000...,270,77,77,75
4,5,1,0,0,7105,500020,2,3,1417,0010110010011111101111100100000000000000000000...,739,228,228,222

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KC_2,ZAKRSTRANA,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK
14709,14710,1,0,0,8104,599948,4,6,1583,0110110010111110101110100100010000000000000000...,708,292,292,291
14710,14711,1,0,0,8104,599956,1,1,3184,0011110111111111111110110110000000000000000000...,1495,566,562,561
14711,14712,1,0,0,8104,599964,1,6,1675,1110110010011110111111110110000000000000000000...,763,305,305,302
14712,14713,1,0,0,8104,599999,1,6,1042,0010110010011101101110110110000000000000000000...,483,187,187,185
14713,14714,1,0,0,8104,599999,2,0,3451,0111010110010111111111110111000000000000000000...,1601,618,618,614

## 308. [D] Volby do Evropského parlamentu 2024 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,24,Konzervativní strana,Konzervativní strana,KONS

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
208,1286,Liberální aliance nezávislých občanů,Liberální aliance nez. občanů,LANO
209,1287,Osobnosti pro kraj,Osobnosti pro kraj,OK
210,1288,ANO LEPŠÍ EU S MIMOZEMŠŤANY (zast.drahotu a vá...,ANO LEPŠÍ EU S MIMOZEMŠŤANY,mimozemstani.eu
211,9995,Koalice,Koalice,Koalice
212,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 308. [D] Volby do Evropského parlamentu 2024 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,24,Konzervativní strana,Konzervativní strana,KONS

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
208,1286,Liberální aliance nezávislých občanů,Liberální aliance nez. občanů,LANO
209,1287,Osobnosti pro kraj,Osobnosti pro kraj,OK
210,1288,ANO LEPŠÍ EU S MIMOZEMŠŤANY (zast.drahotu a vá...,ANO LEPŠÍ EU S MIMOZEMŠŤANY,mimozemstani.eu
211,9995,Koalice,Koalice,Koalice
212,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 310. [D] Volby do Evropského parlamentu 2024 - číselník obcí

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   OBEC_PREZ                 NAZEVOBCE
0     500011  Želechovice nad Dřevnicí
1     500020         Petrov nad Desnou
2     500046                   Libhošť
3     500062                    Krhová
4     500071                   Poličná

**TAIL**

      OBEC_PREZ    NAZEVOBCE
6250     599948    Štramberk
6251     599956        Tichá
6252     599964        Tísek
6253     599999  Trojanovice
6254     999997    Zahraničí

## 310. [D] Volby do Evropského parlamentu 2024 - číselník obcí

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   OBEC_PREZ                 NAZEVOBCE
0     500011  Želechovice nad Dřevnicí
1     500020         Petrov nad Desnou
2     500046                   Libhošť
3     500062                    Krhová
4     500071                   Poličná

**TAIL**

      OBEC_PREZ    NAZEVOBCE
6250     599948    Štramberk
6251     599956        Tichá
6252     599964        Tísek
6253     599999  Trojanovice
6254     999997    Zahraničí

## 312. [D] Volby do Evropského parlamentu 2024 - číselník obcí, městských částí, městských obvodů a volebních okrsků

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,KRAJ,OKRES,CPOU,OBEC,OBEC_PREZ,NAZEVOBCE,ORP,MINOKRSEK1,MAXOKRSEK1
0,7200,7204,662,500011,500011,Želechovice nad Dřevnicí,7213,1,3
1,7100,7105,860,500020,500020,Petrov nad Desnou,7111,1,2
2,8100,8104,792,500046,500046,Libhošť,8115,1,1
3,1100,1100,1,500054,554782,Praha 1,1000,1001,1021
4,7200,7203,871,500062,500062,Krhová,7210,1,1

**TAIL**

,KRAJ,OKRES,CPOU,OBEC,OBEC_PREZ,NAZEVOBCE,ORP,MINOKRSEK1,MAXOKRSEK1
6383,8100,8104,792,599930,599930,Suchdol nad Odrou,8115,1,2
6384,8100,8104,791,599948,599948,Štramberk,8112,1,4
6385,8100,8104,789,599956,599956,Tichá,8105,1,1
6386,8100,8104,788,599964,599964,Tísek,8101,1,1
6387,8100,8104,789,599999,599999,Trojanovice,8105,1,2

## 312. [D] Volby do Evropského parlamentu 2024 - číselník obcí, městských částí, městských obvodů a volebních okrsků

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,KRAJ,OKRES,CPOU,OBEC,OBEC_PREZ,NAZEVOBCE,ORP,MINOKRSEK1,MAXOKRSEK1
0,7200,7204,662,500011,500011,Želechovice nad Dřevnicí,7213,1,3
1,7100,7105,860,500020,500020,Petrov nad Desnou,7111,1,2
2,8100,8104,792,500046,500046,Libhošť,8115,1,1
3,1100,1100,1,500054,554782,Praha 1,1000,1001,1021
4,7200,7203,871,500062,500062,Krhová,7210,1,1

**TAIL**

,KRAJ,OKRES,CPOU,OBEC,OBEC_PREZ,NAZEVOBCE,ORP,MINOKRSEK1,MAXOKRSEK1
6383,8100,8104,792,599930,599930,Suchdol nad Odrou,8115,1,2
6384,8100,8104,791,599948,599948,Štramberk,8112,1,4
6385,8100,8104,789,599956,599956,Tichá,8105,1,1
6386,8100,8104,788,599964,599964,Tísek,8101,1,1
6387,8100,8104,789,599999,599999,Trojanovice,8105,1,2

## 314. [D] Volby do Evropského parlamentu 2024 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS CHODNOTA
0        0      CZ     Česká republika     105       CZ
1     1000    CZ01               Praha     107     CZ01
2     1100   CZ010  Hlavní město Praha     108    CZ010
3     1199  CZ0100               Praha     109   CZ0100
4     2000    CZ02       Střední Čechy     107     CZ02

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS CHODNOTA
96      8103  CZ0803        Karviná     109   CZ0803
97      8104  CZ0804     Nový Jičín     109   CZ0804
98      8105  CZ0805          Opava     109   CZ0805
99      8106  CZ0806  Ostrava-město     109   CZ0806
100     9999     NaN      Zahraničí     109   CZZZZZ

## 314. [D] Volby do Evropského parlamentu 2024 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS CHODNOTA
0        0      CZ     Česká republika     105       CZ
1     1000    CZ01               Praha     107     CZ01
2     1100   CZ010  Hlavní město Praha     108    CZ010
3     1199  CZ0100               Praha     109   CZ0100
4     2000    CZ02       Střední Čechy     107     CZ02

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS CHODNOTA
96      8103  CZ0803        Karviná     109   CZ0803
97      8104  CZ0804     Nový Jičín     109   CZ0804
98      8105  CZ0805          Opava     109   CZ0805
99      8106  CZ0806  Ostrava-město     109   CZ0806
100     9999     NaN      Zahraničí     109   CZZZZZ

## 316. [D] Volby do Evropského parlamentu 2024 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,9,Nezávislá iniciativa (NEI),Nezávislá iniciativa (NEI),NEI

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
264,1285,Vize pro Karlovarský kraj,Vize pro Karlovarský kraj,Vize KVK
265,1286,Liberální aliance nezávislých občanů,Liberální aliance nez. občanů,LANO
266,1287,Osobnosti pro kraj,Osobnosti pro kraj,OK
267,1288,ANO LEPŠÍ EU S MIMOZEMŠŤANY (zast.drahotu a vá...,ANO LEPŠÍ EU S MIMOZEMŠŤANY,mimozemstani.eu
268,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 316. [D] Volby do Evropského parlamentu 2024 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,9,Nezávislá iniciativa (NEI),Nezávislá iniciativa (NEI),NEI

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
264,1285,Vize pro Karlovarský kraj,Vize pro Karlovarský kraj,Vize KVK
265,1286,Liberální aliance nezávislých občanů,Liberální aliance nez. občanů,LANO
266,1287,Osobnosti pro kraj,Osobnosti pro kraj,OK
267,1288,ANO LEPŠÍ EU S MIMOZEMŠŤANY (zast.drahotu a vá...,ANO LEPŠÍ EU S MIMOZEMŠŤANY,mimozemstani.eu
268,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 318. [D] Volby do Evropského parlamentu 2024 - číselník volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,3,Křesťanskodemokratická strana,Křesťanskodemokratická strana,Křesťanskodemokratická strana,KDS,1,003,KDS,S,NaN
3,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,LDS,S,NaN
4,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1361,1634,"Koalice ČSSD, DOMOV a Směr","Koalice ČSSD, DOMOV a Směr","Koalice ČSSD, DOMOV, Směr",ČSSD+DOMOV+Směr,3,"759,1221,1248",NaN,K,NaN
1362,1635,Koalice SEN 21 a Volt,Koalice SEN 21 a Volt,"Koalice SEN 21, Volt",SEN 21+Volt,2,"1187,1272",NaN,K,NaN
1363,1636,Koalice PRO 2022 a SV PRO ZS,Koalice PRO 2022 a SV PRO ZS,"Koalice PRO 2022, SV PRO ZS",PRO2022+SVPROZS,2,"1265,1269",NaN,K,NaN
1364,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1365,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 318. [D] Volby do Evropského parlamentu 2024 - číselník volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,3,Křesťanskodemokratická strana,Křesťanskodemokratická strana,Křesťanskodemokratická strana,KDS,1,003,KDS,S,NaN
3,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,LDS,S,NaN
4,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1361,1634,"Koalice ČSSD, DOMOV a Směr","Koalice ČSSD, DOMOV a Směr","Koalice ČSSD, DOMOV, Směr",ČSSD+DOMOV+Směr,3,"759,1221,1248",NaN,K,NaN
1362,1635,Koalice SEN 21 a Volt,Koalice SEN 21 a Volt,"Koalice SEN 21, Volt",SEN 21+Volt,2,"1187,1272",NaN,K,NaN
1363,1636,Koalice PRO 2022 a SV PRO ZS,Koalice PRO 2022 a SV PRO ZS,"Koalice PRO 2022, SV PRO ZS",PRO2022+SVPROZS,2,"1265,1269",NaN,K,NaN
1364,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1365,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 320. [D] Volby do Evropského parlamentu 2024 - číselník zemí

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ZKRATKA2,KODZEME,NAZZEMECZ,NAZZEMEEN,NAZZKRCZ,NAZZKREN,ZKRATKA3
0,AT,40,Rakouská republika,the Republic of Austria,Rakousko,Austria,AUT
1,BE,56,Belgické království,the Kingdom of Belgium,Belgie,Belgium,BEL
2,BG,100,Bulharská republika,the Republic of Bulgaria,Bulharsko,Bulgaria,BGR
3,CY,196,Kyperská republika,the Republic of Cyprus,Kypr,Cyprus,CYP
4,CZ,203,Česká republika,the Czech Republic,Česko,Czech Republic (the),CZE

**TAIL**

,ZKRATKA2,KODZEME,NAZZEMECZ,NAZZEMEEN,NAZZKRCZ,NAZZKREN,ZKRATKA3
22,PT,620,Portugalská republika,the Portuguese Republic,Portugalsko,Portugal,PRT
23,RO,642,Rumunsko,Romania,Rumunsko,Romania,ROU
24,SE,752,Švédské království,the Kingdom of Sweden,Švédsko,Sweden,SWE
25,SI,705,Slovinská republika,the Republic of Slovenia,Slovinsko,Slovenia,SVN
26,SK,703,Slovenská republika,the Slovak Republic,Slovensko,Slovakia,SVK

## 320. [D] Volby do Evropského parlamentu 2024 - číselník zemí

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ZKRATKA2,KODZEME,NAZZEMECZ,NAZZEMEEN,NAZZKRCZ,NAZZKREN,ZKRATKA3
0,AT,40,Rakouská republika,the Republic of Austria,Rakousko,Austria,AUT
1,BE,56,Belgické království,the Kingdom of Belgium,Belgie,Belgium,BEL
2,BG,100,Bulharská republika,the Republic of Bulgaria,Bulharsko,Bulgaria,BGR
3,CY,196,Kyperská republika,the Republic of Cyprus,Kypr,Cyprus,CYP
4,CZ,203,Česká republika,the Czech Republic,Česko,Czech Republic (the),CZE

**TAIL**

,ZKRATKA2,KODZEME,NAZZEMECZ,NAZZEMEEN,NAZZKRCZ,NAZZKREN,ZKRATKA3
22,PT,620,Portugalská republika,the Portuguese Republic,Portugalsko,Portugal,PRT
23,RO,642,Rumunsko,Romania,Rumunsko,Romania,ROU
24,SE,752,Švédské království,the Kingdom of Sweden,Švédsko,Sweden,SWE
25,SI,705,Slovinská republika,the Republic of Slovenia,Slovinsko,Slovenia,SVN
26,SK,703,Slovenská republika,the Slovak Republic,Slovensko,Slovakia,SVK

## 321. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - celkové výsledky za ČR a kraje

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 322. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - přednostní hlasy pro jednotlivé kandidáty

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 323. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - registry

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 324. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za kraje a krajská města

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 325. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Benešov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 326. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Beroun a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 327. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Blansko a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 328. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Brno-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 329. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Brno-venkov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 330. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Bruntál a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 331. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Břeclav a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 332. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Cheb a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 333. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Chomutov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 334. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Chrudim a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 335. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Domažlice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 336. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Děčín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 337. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Frýdek-Místek a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 338. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Havlíčkův Brod a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 339. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Hodonín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 340. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Hradec Králové a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 341. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Jablonec nad Nisou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 342. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Jeseník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 343. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Jihlava a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 344. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Jindřichův Hradec a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 345. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Jičín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 346. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Karlovy Vary a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 347. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Karviná a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 348. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Kladno a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 349. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Klatovy a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 350. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Kolín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 351. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Kroměříž a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 352. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Kutná Hora a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 353. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Liberec a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 354. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Litoměřice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 355. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Louny a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 356. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Mladá Boleslav a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 357. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Most a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 358. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Mělník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 359. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Nový Jičín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 360. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Nymburk a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 361. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Náchod a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 362. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Olomouc a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 363. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Opava a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 364. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Ostrava-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 365. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Pardubice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 366. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Pelhřimov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 367. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Plzeň-jih a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 368. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Plzeň-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 369. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Plzeň-sever a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 370. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Prachatice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 371. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Praha a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 372. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Praha-východ a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 373. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Praha-západ a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 374. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Prostějov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 375. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Písek a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 376. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Přerov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 377. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Příbram a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 378. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Rakovník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 379. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Rokycany a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 380. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Rychnov nad Kněžnou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 381. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Semily a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 382. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Sokolov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 383. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Strakonice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 384. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Svitavy a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 385. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Tachov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 386. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Teplice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 387. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Trutnov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 388. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Tábor a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 389. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Třebíč a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 390. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Uherské Hradiště a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 391. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Vsetín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 392. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Vyškov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 393. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Zlín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 394. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Znojmo a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 395. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Ústí nad Labem a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 396. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Ústí nad Orlicí a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 397. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Česká Lípa a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 398. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres České Budějovice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 399. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Český Krumlov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 400. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Šumperk a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 401. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okres Žďár nad Sázavou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 402. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za okrsky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_31,HLASY_32,HLASY_33,HLASY_34,HLASY_35,HLASY_36,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,2,0,0,2103,532088,1,0,1,21,...,1,0,0,0,0,0,238,260,31,534745
1,1,2,0,0,2103,532088,1,0,4,12,...,1,0,0,2,0,0,126,142,34,534512
2,1,2,0,0,2103,532088,1,0,7,13,...,0,0,0,0,0,0,130,150,22,534516
3,1,2,0,0,2103,532088,1,0,8,6,...,0,0,0,0,0,0,256,270,30,534764
4,1,2,0,0,2103,532088,1,0,9,3,...,1,0,0,0,0,0,120,132,31,534489

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_31,HLASY_32,HLASY_33,HLASY_34,HLASY_35,HLASY_36,KC_3,KC_4,POSL_KAND,KC_SUM
30302,14865,2,0,0,9999,999997,109,1,21,8,...,0,0,0,0,0,0,21,50,12,1010220
30303,14865,2,0,0,9999,999997,109,1,23,1,...,0,0,0,0,0,0,16,40,10,1010198
30304,14865,2,0,0,9999,999997,109,1,24,5,...,0,0,0,0,0,0,15,44,9,1010205
30305,14865,2,0,0,9999,999997,109,1,26,1,...,0,0,0,0,0,0,0,27,0,1010162
30306,14865,2,0,0,9999,999997,109,1,29,13,...,0,1,0,0,0,0,194,236,32,1010612

## 403. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - výsledky za zahraničí, kontinenty, státy

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 404. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2017 - číselníky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   VOLKRAJ    NAZVOLKRAJ  KRAJ  MAXKAND
0        1  Hl. m. Praha  1100       36
1        2   Středočeský  2100       34
2        3     Jihočeský  3100       22
3        4      Plzeňský  3200       20
4        5   Karlovarský  4100       14

**TAIL**

    VOLKRAJ       NAZVOLKRAJ  KRAJ  MAXKAND
9        10         Vysočina  6100       20
10       11     Jihomoravský  6200       34
11       12        Olomoucký  7100       23
12       13          Zlínský  7200       22
13       14  Moravskoslezský  8100       36

## 405. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - okrsková data, počty hlasů pro strany

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_31,HLASY_32,HLASY_33,HLASY_34,HLASY_35,HLASY_36,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,2,0,0,7204,500011,1,6,1,1,...,0,0,0,0,0,0,0,2,0,507228
1,1,2,0,0,7204,500011,1,6,2,1,...,0,0,0,0,0,0,0,3,0,507230
2,1,2,0,0,7204,500011,1,6,3,8,...,0,0,0,0,0,0,5,16,3,507259
3,1,2,0,0,7204,500011,1,6,4,67,...,0,0,0,0,0,0,226,297,22,507840
4,1,2,0,0,7204,500011,1,6,5,28,...,0,0,0,0,0,0,84,117,22,507480

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_31,HLASY_32,HLASY_33,HLASY_34,HLASY_35,HLASY_36,KC_3,KC_4,POSL_KAND,KC_SUM
42934,14886,2,0,0,9999,999997,111,3,15,1,...,0,0,0,0,0,0,0,16,0,1010144
42935,14886,2,0,0,9999,999997,111,3,17,103,...,0,0,0,0,0,0,1185,1305,26,1012748
42936,14886,2,0,0,9999,999997,111,3,18,2,...,0,0,0,0,0,0,90,110,19,1010351
42937,14886,2,0,0,9999,999997,111,3,20,5,...,0,0,0,0,0,0,75,100,26,1010338
42938,14886,2,0,0,9999,999997,111,3,21,1,...,0,0,0,0,0,0,0,22,0,1010156

## 406. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - okrsková data, počty voličů a hlasů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KC_2,ZAKRSTRANA,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK
0,1,1,0,0,7204,500011,1,6,2231,1111101101011011110111000000000000000000000000...,717,505,505,504
1,2,1,0,0,7204,500011,2,0,1295,1111101111011000110100000000000000000000000000...,435,288,288,284
2,3,1,0,0,7204,500011,3,1,1261,1011100110011011110110000000000000000000000000...,394,289,289,289
3,4,1,0,0,7105,500020,1,2,747,1111100101011000110101000000000000000000000000...,268,160,160,159
4,5,1,0,0,7105,500020,2,3,2091,1011101101011010110111000000000000000000000000...,729,455,455,452

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KC_2,ZAKRSTRANA,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK
14881,14882,1,0,0,9999,999997,107,6,104,1010000000001000100000000000000000000000000000...,32,24,24,24
14882,14883,1,0,0,9999,999997,108,0,247,0011100100011000100100000000000000000000000000...,72,59,59,57
14883,14884,1,0,0,9999,999997,109,1,100,0000100100011000100100000000000000000000000000...,25,25,25,25
14884,14885,1,0,0,9999,999997,110,2,144,1001100000001000100000000000000000000000000000...,69,25,25,25
14885,14886,1,0,0,9999,999997,111,3,1270,1111101100011010110110000000000000000000000000...,568,234,234,234

## 407. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - registr kandidátních listin

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,KSTRANA,VSTRANA,NAZEVCELK,NAZEV_STRK,ZKRATKAK30,ZKRATKAK8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
0,1,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,0,A,NaN,0,Strana zelených
1,2,752,Švýcarská demokracie (www.svycarska-demokracie...,Švýcarská demokracie (www.svycarska-demokracie...,Švýcarská demokracie,Švýcar. demokr.,1,752,0,A,NaN,0,Švýcarská demokracie (www.svycarska-demokracie...
2,3,759,VOLNÝ blok,VOLNÝ blok,VOLNÝ blok,Volný blok,1,759,0,A,NaN,0,VOLNÝ blok
3,4,1114,Svoboda a přímá demokracie (SPD),Svoboda a přímá demokracie (SPD),Svoboda a př. demokracie (SPD),SPD,1,1114,0,A,NaN,20,Svoboda a přímá demokracie (SPD)
4,5,7,Česká strana sociálně demokratická,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD,1,007,0,A,NaN,0,Česká strana sociálně demokratická

**TAIL**

,KSTRANA,VSTRANA,NAZEVCELK,NAZEV_STRK,ZKRATKAK30,ZKRATKAK8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
17,18,47,Komunistická strana Čech a Moravy,Komunistická strana Čech a Moravy,Komunistická str.Čech a Moravy,KSČM,1,047,0,A,NaN,0,Komunistická strana Čech a Moravy
18,19,1190,Moravské zemské hnutí,Moravské zemské hnutí,Moravské zemské hnutí,MZH,1,1190,22222222200022,A,NaN,0,Moravské zemské hnutí
19,20,768,ANO 2011,ANO 2011,ANO 2011,ANO,1,768,0,A,NaN,72,ANO 2011
20,21,1244,Otevřeme Česko normálnímu životu,Otevřeme Česko normálnímu životu,Otevřeme ČR normálnímu životu,OtČe,1,1244,0,A,NaN,0,Otevřeme Česko normálnímu životu
21,22,83,Moravané,Moravané,Moravané,Moravané,1,083,2022222000000,A,NaN,0,Moravané

## 408. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - registr kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,VOLKRAJ,KSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,BYDLISTEK,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,SKRUTINIUM,PORADIMAND,PORADINAHR
0,1,1,1,Eva,Kavková,Mgr.,NaN,45,"ředitelka vzdělávací a poradenské organizace, ...",Praha,1,5,5,A,716,11.81,N,0,0,0
1,1,1,2,Vít,Masare,Mgr.,NaN,34,"poradce pro udržitelnou politiku ve městech, t...",Praha,1,5,5,A,349,5.76,N,0,0,0
2,1,1,3,Jana,Jebavá,Mgr.,NaN,38,"grafička a editorka, členka Komise životního p...",Praha,1,5,5,A,593,9.78,N,0,0,0
3,1,1,4,Ondřej,Mirovský,Mgr.,M.EM,42,"radní Prahy 7 pro dopravu, bezpečnost a integr...",Praha,1,5,5,A,230,3.79,N,0,0,0
4,1,1,5,Petra,Urbanová,Mgr.,LL.M.,30,environmentální právnička,Praha,1,5,5,A,555,9.16,N,0,0,0

**TAIL**

,VOLKRAJ,KSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,BYDLISTEK,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,SKRUTINIUM,PORADIMAND,PORADINAHR
5257,14,22,32,Roman,Zvoníček,NaN,NaN,46.0,elektromechanik,Brumov-Bylnice,585114.0,99.0,83.0,A,9,0.31,N,0,0,0
5258,14,22,33,Tomáš,Kleibl,NaN,NaN,25.0,strojník,Uničov,505587.0,99.0,83.0,A,25,0.88,N,0,0,0
5259,14,22,34,Alois,Nezbeda,NaN,NaN,77.0,řezník,Loštice,540196.0,99.0,83.0,A,23,0.81,N,0,0,0
5260,14,22,35,Jiří,Žváček,NaN,NaN,58.0,strojník,Bílá Lhota,500623.0,99.0,83.0,A,14,0.49,N,0,0,0
5261,14,22,36,Petr,Srovnal,NaN,NaN,61.0,dělník,Senička,552267.0,99.0,83.0,A,20,0.70,N,0,0,0

## 409. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - registr zvláštních volebních okrsků – zahraničí

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,OBEC,OKRSEK,KC1,NAZEVOKRSK,TYPURADU,KODZEME,ZKRZEME,NAZEVZEME,SVETADIL,CASPOSUNLC,NAZEVOKRSA,NAZEVZEMEA,SUBKONTINENT
0,999997,1,5,Tirana,vv,8,AL,Albánie,EV,0.0,Tirana,Albania,EV
1,999997,2,6,Vídeň,vv,40,AT,Rakousko,EV,0.0,Vienna,Austria,EV
2,999997,3,0,Brusel,vv,56,BE,Belgie,EV,0.0,Brussels,Belgium,EV
3,999997,4,1,Sarajevo,vv,70,BA,Bosna a Hercegovina,EV,0.0,Sarajevo,Bosnia and Herzegovina,EV
4,999997,5,2,Sofie,vv,100,BG,Bulharsko,EV,1.0,Sofia,Bulgaria,EV

**TAIL**

,OBEC,OKRSEK,KC1,NAZEVOKRSK,TYPURADU,KODZEME,ZKRZEME,NAZEVZEME,SVETADIL,CASPOSUNLC,NAZEVOKRSA,NAZEVZEMEA,SUBKONTINENT
106,999997,107,6,Lusaka,vv,894,ZM,Zambie,AF,0.0,Lusaka,Zambia,AF
107,999997,108,0,Bamako,vv,466,ML,Mali,AF,-2.0,Bamako,Mali,AF
108,999997,109,1,Ménaka,kj,466,ML,Mali,AF,-2.0,Ménaka,Mali,AF
109,999997,110,2,Canberra,vv,36,AU,Austrálie,AO,9.0,Canberra,Australia,AO
110,999997,111,3,Sydney,gk,36,AU,Austrálie,AO,9.0,Sydney,Australia,AO

## 410. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - složení kandidátních listin

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   KSTRANA TYPSLOZENI  NSTRANA
0        1          P        5
1        2          P      752
2        3          P      759
3        4          P     1114
4        5          P        7

**TAIL**

    KSTRANA TYPSLOZENI  NSTRANA
20       18          P       47
21       19          P     1190
22       20          P      768
23       21          P     1244
24       22          P       83

## 411. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - složení volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        5        5
3        7        7
4        9        9

**TAIL**

      VSTRANA  NSTRANA
2279     1477      721
2280     1478     1012
2281     1478     1175
2282     9995     9995
2283     9999     9999

## 412. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD
4,9,Nezávislá iniciativa (NEI),Nezávislá iniciativa (NEI),NEI

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
243,1248,Trikolora - spojená pravice,Trikolora - spojená pravice,Triko
244,1249,Strana národní svobody,Strana národní svobody,SNS
245,1250,Urza.cz: Nechceme vaše hlasy,Urza.cz: Nechceme vaše hlasy,Nevolte Urza.cz
246,9995,Koalice,Koalice,Koalice
247,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 413. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - číselník obcí pro prezentaci

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   OBEC_PREZ                 NAZEVOBCE
0     500011  Želechovice nad Dřevnicí
1     500020         Petrov nad Desnou
2     500046                   Libhošť
3     500062                    Krhová
4     500071                   Poličná

**TAIL**

      OBEC_PREZ          NAZEVOBCE
6253     599930  Suchdol nad Odrou
6254     599948          Štramberk
6255     599956              Tichá
6256     599964              Tísek
6257     599999        Trojanovice

## 414. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - číselník obcí, městských částí, městských obvodů a volebních okrsků

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,VOLKRAJ,MINOKRSEK1,MAXOKRSEK1,OBEC_PREZ
0,7200,7204,662,7213,500011,Želechovice nad Dřevnicí,13,1,3,500011
1,7100,7105,860,7111,500020,Petrov nad Desnou,12,1,2,500020
2,8100,8104,792,8115,500046,Libhošť,14,1,1,500046
3,1100,1100,1,1000,500054,Praha 1,1,1000,1021,554782
4,7200,7203,871,7210,500062,Krhová,13,1,1,500062

**TAIL**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,VOLKRAJ,MINOKRSEK1,MAXOKRSEK1,OBEC_PREZ
6384,8100,8104,791,8112,599948,Štramberk,14,1,4,599948
6385,8100,8104,789,8105,599956,Tichá,14,1,1,599956
6386,8100,8104,788,8101,599964,Tísek,14,1,1,599964
6387,8100,8104,789,8105,599999,Trojanovice,14,1,2,599999
6388,9900,9999,999,9999,999997,Zahraničí,6,1,111,999997

## 415. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS  CHODNOTA
0        0     CZ0     Česká republika      97        19
1     1000    CZ01               Praha      99       213
2     1100   CZ010  Hlavní město Praha     100      3018
3     1199  CZ0100               Praha     101     40924
4     2000    CZ02       Střední Čechy      99       221

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS  CHODNOTA
96      8103  CZ0803        Karviná     101     40886
97      8104  CZ0804     Nový Jičín     101     40894
98      8105  CZ0805          Opava     101     40908
99      8106  CZ0806  Ostrava-město     101     40916
100     9999  CZZZZZ      Zahraničí     101     40002

## 416. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD
4,9,Nezávislá iniciativa (NEI),Nezávislá iniciativa (NEI),NEI

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
256,1247,Občanský Manifest - Pravá Svoboda a Prosperita,Občanský Manifest,Manifest.cz
257,1248,Trikolora - spojená pravice,Trikolora - spojená pravice,Triko
258,1249,Strana národní svobody,Strana národní svobody,SNS
259,1250,Urza.cz: Nechceme vaše hlasy,Urza.cz: Nechceme vaše hlasy,Nevolte Urza.cz
260,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 417. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - číselník volebních krajů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   VOLKRAJ    NAZVOLKRAJ  KRAJ  MAXKAND
0        1  Hl. m. Praha  1100       36
1        2   Středočeský  2100       34
2        3     Jihočeský  3100       22
3        4      Plzeňský  3200       20
4        5   Karlovarský  4100       14

**TAIL**

    VOLKRAJ       NAZVOLKRAJ  KRAJ  MAXKAND
9        10         Vysočina  6100       20
10       11     Jihomoravský  6200       34
11       12        Olomoucký  7100       23
12       13          Zlínský  7200       22
13       14  Moravskoslezský  8100       36

## 418. [D] Volby do Poslanecké sněmovny Parlamentu ČR 2021 - číselník volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S
2,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S
3,7,Česká strana sociálně demokratická,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD,1,007,ČSSD,S
4,9,Nezávislá iniciativa (NEI),Nezávislá iniciativa (NEI),Nezávislá iniciativa (NEI),NEI,1,009,NEI,S

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS
1129,1476,"Koalice STAN, Zelení a NEZ","Koalice STAN, Zelení a NEZ","Koalice STAN, Zelení, NEZ",STAN+Zelení+NEZ,3,"005,088,166",NaN,K
1130,1477,"Koalice ODS, TOP 09, KDU-ČSL a KAN","Koalice ODS, TOP 09, KDU-ČSL a KAN","Koalice ODS,TOP 09,KDU-ČSL,KAN",ODS+TOP+KDU+KAN,4,"001,040,053,721",NaN,K
1131,1478,Koalice UFO a ProMOST,Koalice UFO a ProMOST,"Koalice UFO, ProMOST",UFO+ProMOST,2,"1012,1175",NaN,K
1132,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S
1133,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S

## 419. [D] Volby do Senátu Parlamentu ČR - aktuální složení

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 420. [D] Volby do Senátu Parlamentu ČR 2016 konané dne 27.1. - 28.1.2017 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 421. [D] Volby do Senátu Parlamentu ČR 2016 konané dne 27.1. - 28.1.2017 - výsledky za jednotlivé senátní obvody

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 422. [D] Volby do Senátu Parlamentu ČR 2016 konané dne 7.10. - 8.10.2016 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 423. [D] Volby do Senátu Parlamentu ČR 2016 konané dne 7.10. - 8.10.2016 - výsledky za jednotlivé senátní obvody

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 424. [D] Volby do Senátu Parlamentu ČR 2018 konané dne 5.10. - 6.10.2018 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,511587,1,3,2,1,313,141,...,0,0,0,0,0,0,788,1521,9,514643
1,1,0,0,511587,1,3,2,2,313,57,...,0,0,0,0,0,0,268,754,6,513106
2,1,0,0,538337,1,4,2,1,562,258,...,0,0,0,0,0,0,1232,2561,9,543474
3,1,0,0,538337,1,4,2,2,563,110,...,0,0,0,0,0,0,520,1417,6,541183
4,1,0,0,538396,1,5,2,1,270,182,...,0,0,0,0,0,0,936,1739,9,541890

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
9240,1,0,0,592846,1,4,80,2,866,216,...,0,0,0,0,0,0,556,2151,3,597157
9241,1,0,0,592854,1,2,80,1,256,128,...,0,0,0,0,0,0,360,1071,7,595007
9242,1,0,0,592854,1,2,80,2,256,40,...,0,0,0,0,0,0,96,554,3,593969
9243,1,0,0,592871,1,3,80,1,133,110,...,0,0,0,0,0,0,253,762,6,594406
9244,1,0,0,592871,1,3,80,2,131,33,...,0,0,0,0,0,0,91,403,3,593685

## 425. [D] Volby do Senátu Parlamentu ČR 2018 konané dne 5.10. - 6.10.2018 - výsledky za jednotlivé senátní obvody

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 426. [D] Volby do Senátu Parlamentu ČR 2020 konané dne 2.10. - 3.10.2020 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,503916,1,1,3,1,454,152,...,0,0,0,0,0,0,773,1684,9,507296
1,1,0,0,503916,1,1,3,2,455,47,...,0,0,0,0,0,0,209,810,5,505544
2,1,0,0,538795,1,5,3,1,506,151,...,0,0,0,0,0,0,649,1604,9,542019
3,1,0,0,538795,1,5,3,2,508,62,...,0,0,0,0,0,0,277,975,5,540757
4,1,0,0,538817,1,3,3,1,160,53,...,0,0,0,0,0,0,208,521,9,539873

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
10163,1,0,0,592820,1,0,81,2,1201,188,...,0,0,0,0,0,0,533,2380,5,597587
10164,1,0,0,592820,2,1,81,1,1240,479,...,0,0,0,0,0,0,1417,4136,5,601101
10165,1,0,0,592820,2,1,81,2,1244,236,...,0,0,0,0,0,0,691,2726,5,598281
10166,1,0,0,592862,1,0,81,1,1334,518,...,0,0,0,0,0,0,1626,4557,5,601983
10167,1,0,0,592862,1,0,81,2,1336,294,...,0,0,0,0,0,0,942,3243,5,599355

## 427. [D] Volby do Senátu Parlamentu ČR 2020 konané dne 2.10. - 3.10.2020 - výsledky za jednotlivé senátní obvody

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 428. [D] Volby do Senátu Parlamentu ČR 2020 konané dne 2.10. - 3.10.2020 - číselníky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,OBVOD,MINOKRSEK1,MAXOKRSEK1,MINOKRSEK2,...,MAXOKRSEK6,MINOKRSEK7,MAXOKRSEK7,MINOKRSEK8,MAXOKRSEK8,MINOKRSEK9,MAXOKRSEK9,MINOKRSE10,MAXOKRSE10,OBEC_PREZ
0,7200,7204,662,7213,500011,Želechovice nad Dřevnicí,78,1,3,0,...,0,0,0,0,0,0,0,0,0,500011
1,1100,1100,1,1000,500054,Praha 1,27,1000,1021,0,...,0,0,0,0,0,0,0,0,0,500054
2,1100,1100,2,1000,500089,Praha 2,27,2032,2045,0,...,0,0,0,0,0,0,0,0,0,500089
3,1100,1100,11,1000,500143,Praha 5,21,5003,5081,5000,...,0,0,0,0,0,0,0,0,0,500143
4,1100,1100,11,1000,500143,Praha 5,27,5001,5002,0,...,0,0,0,0,0,0,0,0,0,500143

**TAIL**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,OBVOD,MINOKRSEK1,MAXOKRSEK1,MINOKRSEK2,...,MAXOKRSEK6,MINOKRSEK7,MAXOKRSEK7,MINOKRSEK8,MAXOKRSEK8,MINOKRSEK9,MAXOKRSEK9,MINOKRSE10,MAXOKRSE10,OBEC_PREZ
2223,2100,2111,197,2120,599751,Modřovice,18,1,1,0,...,0,0,0,0,0,0,0,0,0,599751
2224,2100,2112,206,2121,599760,Račice,6,1,1,0,...,0,0,0,0,0,0,0,0,0,599760
2225,8100,8104,793,8116,599867,Spálov,63,1,1,0,...,0,0,0,0,0,0,0,0,0,599867
2226,8100,8104,792,8115,599905,Starý Jičín,63,1,8,0,...,0,0,0,0,0,0,0,0,0,599905
2227,8100,8104,792,8115,599930,Suchdol nad Odrou,63,1,2,0,...,0,0,0,0,0,0,0,0,0,599930

## 429. [D] Volby do Senátu Parlamentu ČR 2022 - průběžná data za okrsky (dávky)

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 431. [D] Volby do Senátu Parlamentu ČR 2022 - registr kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
0,1,1,80,Pavel,Petričko,NaN,NaN,71,zdravotní potřeby,Ostrov,...,4.26,4.265741,0,0,0,0.00,0.000000,0,0,Nezávislý kandidát
1,1,2,1114,Eva,Chromcová,Ing.,NaN,45,operátor Zdravotnické záchranné služby - vedou...,Karlovy Vary,...,14.12,14.127166,2,0,2791,32.02,32.025244,0,0,Svoboda a přímá demokracie (SPD)
2,1,3,720,Bohdan,Vaněk,Ing.,M.A.,48,ekonomický analytik a projektový manažer,Karlovy Vary,...,5.69,5.697988,0,0,0,0.00,0.000000,0,0,Česká pirátská strana
3,1,4,1244,Bedřich,Šmudla,NaN,NaN,60,manažer,Sadov,...,1.62,1.624454,0,0,0,0.00,0.000000,0,0,Hnutí PES
4,1,5,768,Věra,Procházková,MUDr.,NaN,68,"bývalá poslankyně, lékařka Zdravotnické záchra...",Karlovy Vary,...,25.86,25.864154,2,0,5924,67.97,67.974756,1,0,ANO 2011

**TAIL**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
174,79,3,768,Ladislava,Brančíková,PhDr.,NaN,58,"ředitelka Centra služeb pro seniory Kyjov, p. o.",Vracov,...,27.70,27.706934,2,0,10919,48.38,48.386954,0,0,ANO 2011
175,79,4,47,Lenka,Ingrová,Mgr.,DiS.,44,"projektová manažerka, předsedkyně Okresního vý...",Hodonín,...,5.58,5.584044,0,0,0,0.00,0.000000,0,0,Komunistická strana Čech a Moravy
176,79,5,720,Ivo,Vašíček,PaedDr.,NaN,60,krajský zastupitel,Čejkovice,...,3.43,3.437557,0,0,0,0.00,0.000000,0,0,Česká pirátská strana
177,79,6,1114,Vítězslav,Krabička,JUDr.,NaN,63,"advokát, zastupitel města Hodonína",Hodonín,...,11.90,11.900980,0,0,0,0.00,0.000000,0,0,Svoboda a přímá demokracie (SPD)
178,79,7,1520,Zbyněk,Pastyřík,Ing.,MBA,41,starosta obce Dambořice,Dambořice,...,8.23,8.238791,0,0,0,0.00,0.000000,0,0,Koalice Moravského zemského hnutí a politické ...

## 431. [D] Volby do Senátu Parlamentu ČR 2022 - registr kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
0,1,1,80,Pavel,Petričko,NaN,NaN,71,zdravotní potřeby,Ostrov,...,4.26,4.265741,0,0,0,0.00,0.000000,0,0,Nezávislý kandidát
1,1,2,1114,Eva,Chromcová,Ing.,NaN,45,operátor Zdravotnické záchranné služby - vedou...,Karlovy Vary,...,14.12,14.127166,2,0,2791,32.02,32.025244,0,0,Svoboda a přímá demokracie (SPD)
2,1,3,720,Bohdan,Vaněk,Ing.,M.A.,48,ekonomický analytik a projektový manažer,Karlovy Vary,...,5.69,5.697988,0,0,0,0.00,0.000000,0,0,Česká pirátská strana
3,1,4,1244,Bedřich,Šmudla,NaN,NaN,60,manažer,Sadov,...,1.62,1.624454,0,0,0,0.00,0.000000,0,0,Hnutí PES
4,1,5,768,Věra,Procházková,MUDr.,NaN,68,"bývalá poslankyně, lékařka Zdravotnické záchra...",Karlovy Vary,...,25.86,25.864154,2,0,5924,67.97,67.974756,1,0,ANO 2011

**TAIL**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
174,79,3,768,Ladislava,Brančíková,PhDr.,NaN,58,"ředitelka Centra služeb pro seniory Kyjov, p. o.",Vracov,...,27.70,27.706934,2,0,10919,48.38,48.386954,0,0,ANO 2011
175,79,4,47,Lenka,Ingrová,Mgr.,DiS.,44,"projektová manažerka, předsedkyně Okresního vý...",Hodonín,...,5.58,5.584044,0,0,0,0.00,0.000000,0,0,Komunistická strana Čech a Moravy
176,79,5,720,Ivo,Vašíček,PaedDr.,NaN,60,krajský zastupitel,Čejkovice,...,3.43,3.437557,0,0,0,0.00,0.000000,0,0,Česká pirátská strana
177,79,6,1114,Vítězslav,Krabička,JUDr.,NaN,63,"advokát, zastupitel města Hodonína",Hodonín,...,11.90,11.900980,0,0,0,0.00,0.000000,0,0,Svoboda a přímá demokracie (SPD)
178,79,7,1520,Zbyněk,Pastyřík,Ing.,MBA,41,starosta obce Dambořice,Dambořice,...,8.23,8.238791,0,0,0,0.00,0.000000,0,0,Koalice Moravského zemského hnutí a politické ...

## 432. [D] Volby do Senátu Parlamentu ČR 2022 - složení volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        4        4
3        5        5
4        7        7

**TAIL**

      VSTRANA  NSTRANA
2848     1628     1114
2849     1628     1227
2850     1628     1244
2851     9995     9995
2852     9999     9999

## 433. [D] Volby do Senátu Parlamentu ČR 2022 - výsledky za jednotlivé senátní obvody

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 435. [D] Volby do Senátu Parlamentu ČR 2022 - výsledky za okrsky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,500101,1,1,1,1,170,71,...,0,0,0,0,0,0,401,784,11,501683
1,1,0,0,500101,1,1,1,2,170,11,...,0,0,0,0,0,0,46,252,5,500613
2,1,0,0,500127,1,5,1,1,130,57,...,0,0,0,0,0,0,306,608,11,501361
3,1,0,0,500127,1,5,1,2,130,23,...,0,0,0,0,0,0,94,296,5,500731
4,1,0,0,506486,1,6,1,1,198,127,...,0,0,0,0,0,0,1116,1697,11,509899

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
9339,1,0,0,586811,1,6,79,2,440,100,...,0,0,0,0,0,0,239,1058,3,588938
9340,1,0,0,586820,1,2,79,1,859,373,...,0,0,0,0,0,0,1133,3163,7,593157
9341,1,0,0,586820,1,2,79,2,861,165,...,0,0,0,0,0,0,436,1871,3,590569
9342,1,0,0,593354,1,3,79,1,258,109,...,0,0,0,0,0,0,400,1062,7,595490
9343,1,0,0,593354,1,3,79,2,258,38,...,0,0,0,0,0,0,107,559,3,594480

## 435. [D] Volby do Senátu Parlamentu ČR 2022 - výsledky za okrsky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,500101,1,1,1,1,170,71,...,0,0,0,0,0,0,401,784,11,501683
1,1,0,0,500101,1,1,1,2,170,11,...,0,0,0,0,0,0,46,252,5,500613
2,1,0,0,500127,1,5,1,1,130,57,...,0,0,0,0,0,0,306,608,11,501361
3,1,0,0,500127,1,5,1,2,130,23,...,0,0,0,0,0,0,94,296,5,500731
4,1,0,0,506486,1,6,1,1,198,127,...,0,0,0,0,0,0,1116,1697,11,509899

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
9339,1,0,0,586811,1,6,79,2,440,100,...,0,0,0,0,0,0,239,1058,3,588938
9340,1,0,0,586820,1,2,79,1,859,373,...,0,0,0,0,0,0,1133,3163,7,593157
9341,1,0,0,586820,1,2,79,2,861,165,...,0,0,0,0,0,0,436,1871,3,590569
9342,1,0,0,593354,1,3,79,1,258,109,...,0,0,0,0,0,0,400,1062,7,595490
9343,1,0,0,593354,1,3,79,2,258,38,...,0,0,0,0,0,0,107,559,3,594480

## 437. [D] Volby do Senátu Parlamentu ČR 2022 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
465,1278,Hnutí NEJ,Hnutí NEJ,NEJ
466,1279,HNUTÍ SPRÁVNÁ CESTA,HNUTÍ SPRÁVNÁ CESTA,SPRÁVNÁ CESTA
467,1280,Malá strana velkých cílů,Malá strana velkých cílů,MSVC
468,9995,Koalice,Koalice,Koalice
469,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 437. [D] Volby do Senátu Parlamentu ČR 2022 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
465,1278,Hnutí NEJ,Hnutí NEJ,NEJ
466,1279,HNUTÍ SPRÁVNÁ CESTA,HNUTÍ SPRÁVNÁ CESTA,SPRÁVNÁ CESTA
467,1280,Malá strana velkých cílů,Malá strana velkých cílů,MSVC
468,9995,Koalice,Koalice,Koalice
469,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 439. [D] Volby do Senátu Parlamentu ČR 2022 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS  CHODNOTA
0        0      CZ     Česká republika      97        19
1     1000    CZ01               Praha      99       213
2     1100   CZ010  Hlavní město Praha     100      3018
3     1199  CZ0100               Praha     101     40924
4     2000    CZ02       Střední Čechy      99       221

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS  CHODNOTA
96      8103  CZ0803        Karviná     101     40886
97      8104  CZ0804     Nový Jičín     101     40894
98      8105  CZ0805          Opava     101     40908
99      8106  CZ0806  Ostrava-město     101     40916
100     9999     NaN      Zahraničí     101     40002

## 439. [D] Volby do Senátu Parlamentu ČR 2022 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS  CHODNOTA
0        0      CZ     Česká republika      97        19
1     1000    CZ01               Praha      99       213
2     1100   CZ010  Hlavní město Praha     100      3018
3     1199  CZ0100               Praha     101     40924
4     2000    CZ02       Střední Čechy      99       221

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS  CHODNOTA
96      8103  CZ0803        Karviná     101     40886
97      8104  CZ0804     Nový Jičín     101     40894
98      8105  CZ0805          Opava     101     40908
99      8106  CZ0806  Ostrava-město     101     40916
100     9999     NaN      Zahraničí     101     40002

## 441. [D] Volby do Senátu Parlamentu ČR 2022 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
471,1277,Hnutí pro Žabiny,Hnutí pro Žabiny,HpŽ
472,1278,Hnutí NEJ,Hnutí NEJ,NEJ
473,1279,HNUTÍ SPRÁVNÁ CESTA,HNUTÍ SPRÁVNÁ CESTA,SPRÁVNÁ CESTA
474,1280,Malá strana velkých cílů,Malá strana velkých cílů,MSVC
475,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 441. [D] Volby do Senátu Parlamentu ČR 2022 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
471,1277,Hnutí pro Žabiny,Hnutí pro Žabiny,HpŽ
472,1278,Hnutí NEJ,Hnutí NEJ,NEJ
473,1279,HNUTÍ SPRÁVNÁ CESTA,HNUTÍ SPRÁVNÁ CESTA,SPRÁVNÁ CESTA
474,1280,Malá strana velkých cílů,Malá strana velkých cílů,MSVC
475,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 443. [D] Volby do Senátu Parlamentu ČR 2022 - číselník volebních obvodů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   OBVOD     NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
0      1  Karlovy Vary   4102         2        A
1      2       Sokolov   4103         4        A
2      3          Cheb   4101         6        A
3      4          Most   4205         2        A
4      5      Chomutov   4202         4        A

**TAIL**

    OBVOD         NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
76     77            Vsetín   7203         4        A
77     78              Zlín   7204         6        A
78     79           Hodonín   6205         2        A
79     80              Zlín   7204         4        A
80     81  Uherské Hradiště   7202         6        A

## 443. [D] Volby do Senátu Parlamentu ČR 2022 - číselník volebních obvodů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   OBVOD     NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
0      1  Karlovy Vary   4102         2        A
1      2       Sokolov   4103         4        A
2      3          Cheb   4101         6        A
3      4          Most   4205         2        A
4      5      Chomutov   4202         4        A

**TAIL**

    OBVOD         NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
76     77            Vsetín   7203         4        A
77     78              Zlín   7204         6        A
78     79           Hodonín   6205         2        A
79     80              Zlín   7204         4        A
80     81  Uherské Hradiště   7202         6        A

## 445. [D] Volby do Senátu Parlamentu ČR 2022 - číselník volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,NaN,S,NaN
3,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN
4,7,Česká strana sociálně demokratická,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD,1,007,ČSSD,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1367,1626,"Sdružení HpŽ, NK","Sdružení HpŽ, NK","Sdružení HpŽ, NK",HpŽ+NK,2,"080,1277",NaN,D,NaN
1368,1627,"Sdružení PRO 2022, NK","Sdružení PRO 2022, NK","Sdružení PRO 2022, NK",PRO 2022+NK,2,"080,1265",NaN,D,NaN
1369,1628,"Sdružení Svobodní, SPD, Trikolora, PES, NK","Sdružení Svobodní, SPD, Trikolora, PES, NK","Svobodní,SPD,Trikolora,PES,NK",SvoSPDTrikPESNK,5,"080,714,1114,1227,1244",NaN,D,NaN
1370,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1371,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 445. [D] Volby do Senátu Parlamentu ČR 2022 - číselník volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,NaN,S,NaN
3,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN
4,7,Česká strana sociálně demokratická,Česká strana sociálně demokratická,Česká str.sociálně demokrat.,ČSSD,1,007,ČSSD,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1367,1626,"Sdružení HpŽ, NK","Sdružení HpŽ, NK","Sdružení HpŽ, NK",HpŽ+NK,2,"080,1277",NaN,D,NaN
1368,1627,"Sdružení PRO 2022, NK","Sdružení PRO 2022, NK","Sdružení PRO 2022, NK",PRO 2022+NK,2,"080,1265",NaN,D,NaN
1369,1628,"Sdružení Svobodní, SPD, Trikolora, PES, NK","Sdružení Svobodní, SPD, Trikolora, PES, NK","Svobodní,SPD,Trikolora,PES,NK",SvoSPDTrikPESNK,5,"080,714,1114,1227,1244",NaN,D,NaN
1370,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1371,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 446. [D] Volby do Senátu Parlamentu ČR 2024 - průběžná data za okrsky (dávky)

                     hodnota
polozka
target_years_present    2024
has_primary_key         None
primary_key_column      None

## 448. [D] Volby do Senátu Parlamentu ČR 2024 - registr kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
0,2,1,1487,Josef,Vaněk,JUDr.,NaN,75,"právník, živnostník v oblasti cestovního ruchu...",Hazlov,...,5.20,5.208241,0,0,0,0.0,0.0,0,0,SPD a Trikolora
1,2,2,768,Jana,Mračková Vildumetzová,Mgr.,NaN,51,poslankyně Parlamentu ČR,Karlovy Vary,...,50.72,50.723737,1,0,0,0.0,0.0,0,0,ANO 2011
2,2,3,1270,Dana,Wittnerová,Mgr.,NaN,60,středoškolská učitelka,Sokolov,...,3.29,3.298997,0,0,0,0.0,0.0,0,0,SRDCEM PRO ...
3,2,4,112,Alexandr,Terek,NaN,NaN,44,starosta města,Horní Slavkov,...,3.69,3.698606,0,0,0,0.0,0.0,0,0,MÍSTNÍ HNUTÍ NEZÁVISLÝCH ZA HARMONICKÝ ROZVOJ ...
4,2,5,1118,Jan,Picka,Bc.,NaN,58,místostarosta města Sokolov,Sokolov,...,11.65,11.659711,0,0,0,0.0,0.0,0,0,Volba pro kraj

**TAIL**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
164,80,2,80,David,Rumpík,MUDr.,Ph.D.,54,"lékař, ředitel Kliniky reprodukční medicíny a ...",Luhačovice,...,14.71,14.715578,0,0,0,0.00,0.000000,0,0,Nezávislý kandidát
165,80,3,1,Patrik,Kunčar,Ing.,NaN,51,senátor,Uherský Brod,...,26.16,26.162587,2,0,8095,47.83,47.839962,0,0,KDU-ČSL
166,80,4,768,Oldřich,Hájek,doc. RNDr. PhDr.,"Ph.D., MBA",43,"ekonom a včelař, děkan Fakulty veřejnosprávníc...",Zlín,...,36.94,36.943256,2,0,8826,52.16,52.160038,1,0,ANO 2011
167,80,5,88,Jana,Juřenčáková,Ing.,NaN,61,daňový poradce a ekonomický expert,Rokytnice,...,10.31,10.310725,0,0,0,0.00,0.000000,0,0,NEZÁVISLÍ
168,80,6,166,Zbyněk Ziggy,Horváth,NaN,NaN,54,"lektor osvěty a primární prevence, písničkář",Spytihněv,...,5.45,5.456969,0,0,0,0.00,0.000000,0,0,STAROSTOVÉ A NEZÁVISLÍ

## 448. [D] Volby do Senátu Parlamentu ČR 2024 - registr kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
0,2,1,1487,Josef,Vaněk,JUDr.,NaN,75,"právník, živnostník v oblasti cestovního ruchu...",Hazlov,...,5.20,5.208241,0,0,0,0.0,0.0,0,0,SPD a Trikolora
1,2,2,768,Jana,Mračková Vildumetzová,Mgr.,NaN,51,poslankyně Parlamentu ČR,Karlovy Vary,...,50.72,50.723737,1,0,0,0.0,0.0,0,0,ANO 2011
2,2,3,1270,Dana,Wittnerová,Mgr.,NaN,60,středoškolská učitelka,Sokolov,...,3.29,3.298997,0,0,0,0.0,0.0,0,0,SRDCEM PRO ...
3,2,4,112,Alexandr,Terek,NaN,NaN,44,starosta města,Horní Slavkov,...,3.69,3.698606,0,0,0,0.0,0.0,0,0,MÍSTNÍ HNUTÍ NEZÁVISLÝCH ZA HARMONICKÝ ROZVOJ ...
4,2,5,1118,Jan,Picka,Bc.,NaN,58,místostarosta města Sokolov,Sokolov,...,11.65,11.659711,0,0,0,0.0,0.0,0,0,Volba pro kraj

**TAIL**

,OBVOD,CKAND,VSTRANA,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,...,PROC_K1,URIZ_PR_K1,ZVOLEN_K1,LOS_K1,HLASY_K2,PROC_K2,URIZ_PR_K2,ZVOLEN_K2,LOS_K2,NAZEV_VS
164,80,2,80,David,Rumpík,MUDr.,Ph.D.,54,"lékař, ředitel Kliniky reprodukční medicíny a ...",Luhačovice,...,14.71,14.715578,0,0,0,0.00,0.000000,0,0,Nezávislý kandidát
165,80,3,1,Patrik,Kunčar,Ing.,NaN,51,senátor,Uherský Brod,...,26.16,26.162587,2,0,8095,47.83,47.839962,0,0,KDU-ČSL
166,80,4,768,Oldřich,Hájek,doc. RNDr. PhDr.,"Ph.D., MBA",43,"ekonom a včelař, děkan Fakulty veřejnosprávníc...",Zlín,...,36.94,36.943256,2,0,8826,52.16,52.160038,1,0,ANO 2011
167,80,5,88,Jana,Juřenčáková,Ing.,NaN,61,daňový poradce a ekonomický expert,Rokytnice,...,10.31,10.310725,0,0,0,0.00,0.000000,0,0,NEZÁVISLÍ
168,80,6,166,Zbyněk Ziggy,Horváth,NaN,NaN,54,"lektor osvěty a primární prevence, písničkář",Spytihněv,...,5.45,5.456969,0,0,0,0.00,0.000000,0,0,STAROSTOVÉ A NEZÁVISLÍ

## 449. [D] Volby do Senátu Parlamentu ČR 2024 - složení volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5

**TAIL**

      VSTRANA  NSTRANA
3048     1679     1285
3049     1680      143
3050     1680     1228
3051     9995     9995
3052     9999     9999

## 450. [D] Volby do Senátu Parlamentu ČR 2024 - výsledky za jednotlivé senátní obvody

                     hodnota
polozka
target_years_present    2024
has_primary_key         None
primary_key_column      None

## 452. [D] Volby do Senátu Parlamentu ČR 2024 - výsledky za okrsky

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,511587,1,3,2,1,331,118,...,0,0,0,0,0,0,384,1071,6,513740
1,1,0,0,538337,1,4,2,1,596,191,...,0,0,0,0,0,0,665,1832,6,542013
2,1,0,0,538396,1,5,2,1,329,124,...,0,0,0,0,0,0,510,1213,6,540835
3,1,0,0,538434,1,6,2,1,1328,416,...,0,0,0,0,0,0,1394,3942,6,546332
4,1,0,0,538591,1,0,2,1,1060,361,...,0,0,0,0,0,0,1338,3482,6,545563

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
8867,1,0,0,592846,1,4,80,2,821,142,...,0,0,0,0,0,0,497,1824,4,596504
8868,1,0,0,592854,1,2,80,1,256,84,...,0,0,0,0,0,0,308,896,6,594656
8869,1,0,0,592854,1,2,80,2,256,41,...,0,0,0,0,0,0,145,606,4,594074
8870,1,0,0,592871,1,3,80,1,138,56,...,0,0,0,0,0,0,196,581,6,594044
8871,1,0,0,592871,1,3,80,2,138,33,...,0,0,0,0,0,0,124,443,4,593766

## 452. [D] Volby do Senátu Parlamentu ČR 2024 - výsledky za okrsky

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
0,1,0,0,511587,1,3,2,1,331,118,...,0,0,0,0,0,0,384,1071,6,513740
1,1,0,0,538337,1,4,2,1,596,191,...,0,0,0,0,0,0,665,1832,6,542013
2,1,0,0,538396,1,5,2,1,329,124,...,0,0,0,0,0,0,510,1213,6,540835
3,1,0,0,538434,1,6,2,1,1328,416,...,0,0,0,0,0,0,1394,3942,6,546332
4,1,0,0,538591,1,0,2,1,1060,361,...,0,0,0,0,0,0,1338,3482,6,545563

**TAIL**

,TYP_FORM,OPRAVA,CHYBA,OBEC,OKRSEK,KC_1,OBVOD,KOLO,VOL_SEZNAM,VYD_OBALKY,...,HLASY_17,HLASY_18,HLASY_19,HLASY_20,HLASY_21,HLASY_22,KC_3,KC_4,POSL_KAND,KC_SUM
8867,1,0,0,592846,1,4,80,2,821,142,...,0,0,0,0,0,0,497,1824,4,596504
8868,1,0,0,592854,1,2,80,1,256,84,...,0,0,0,0,0,0,308,896,6,594656
8869,1,0,0,592854,1,2,80,2,256,41,...,0,0,0,0,0,0,145,606,4,594074
8870,1,0,0,592871,1,3,80,1,138,56,...,0,0,0,0,0,0,196,581,6,594044
8871,1,0,0,592871,1,3,80,2,138,33,...,0,0,0,0,0,0,124,443,4,593766

## 454. [D] Volby do Senátu Parlamentu ČR 2024 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Sociální demokracie,Sociální demokracie,SOCDEM

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
479,1292,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČMS
480,1293,Nadační občansko-politické hnutí ReMeK,Nadační obč.-pol. hnutí ReMeK,ReMeK
481,1294,Nestraníci pro jižní Moravu-www.nestranici2024.cz,Nestraníci pro jižní Moravu,Nestranici2024
482,9995,Koalice,Koalice,Koalice
483,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 454. [D] Volby do Senátu Parlamentu ČR 2024 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Sociální demokracie,Sociální demokracie,SOCDEM

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
479,1292,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČMS
480,1293,Nadační občansko-politické hnutí ReMeK,Nadační obč.-pol. hnutí ReMeK,ReMeK
481,1294,Nestraníci pro jižní Moravu-www.nestranici2024.cz,Nestraníci pro jižní Moravu,Nestranici2024
482,9995,Koalice,Koalice,Koalice
483,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 456. [D] Volby do Senátu Parlamentu ČR 2024 - číselník obcí

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   OBEC_PREZ                 NAZEVOBCE
0     500011  Želechovice nad Dřevnicí
1     500020         Petrov nad Desnou
2     500046                   Libhošť
3     500054                   Praha 1
4     500062                    Krhová

**TAIL**

      OBEC_PREZ           NAZEVOBCE
6403     599964               Tísek
6404     599999         Trojanovice
6405     727181  Praha 2-Nové Město
6406     727598         Praha 4-Krč
6407     730106     Praha 6-Bubeneč

## 456. [D] Volby do Senátu Parlamentu ČR 2024 - číselník obcí

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   OBEC_PREZ                 NAZEVOBCE
0     500011  Želechovice nad Dřevnicí
1     500020         Petrov nad Desnou
2     500046                   Libhošť
3     500054                   Praha 1
4     500062                    Krhová

**TAIL**

      OBEC_PREZ           NAZEVOBCE
6403     599964               Tísek
6404     599999         Trojanovice
6405     727181  Praha 2-Nové Město
6406     727598         Praha 4-Krč
6407     730106     Praha 6-Bubeneč

## 458. [D] Volby do Senátu Parlamentu ČR 2024 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS CHODNOTA
0        0      CZ     Česká republika     105       CZ
1     1000    CZ01               Praha     107     CZ01
2     1100   CZ010  Hlavní město Praha     108    CZ010
3     1199  CZ0100               Praha     109   CZ0100
4     2000    CZ02       Střední Čechy     107     CZ02

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS CHODNOTA
96      8103  CZ0803        Karviná     109   CZ0803
97      8104  CZ0804     Nový Jičín     109   CZ0804
98      8105  CZ0805          Opava     109   CZ0805
99      8106  CZ0806  Ostrava-město     109   CZ0806
100     9999     NaN      Zahraničí     109   CZZZZZ

## 458. [D] Volby do Senátu Parlamentu ČR 2024 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS CHODNOTA
0        0      CZ     Česká republika     105       CZ
1     1000    CZ01               Praha     107     CZ01
2     1100   CZ010  Hlavní město Praha     108    CZ010
3     1199  CZ0100               Praha     109   CZ0100
4     2000    CZ02       Střední Čechy     107     CZ02

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS CHODNOTA
96      8103  CZ0803        Karviná     109   CZ0803
97      8104  CZ0804     Nový Jičín     109   CZ0804
98      8105  CZ0805          Opava     109   CZ0805
99      8106  CZ0806  Ostrava-město     109   CZ0806
100     9999     NaN      Zahraničí     109   CZZZZZ

## 460. [D] Volby do Senátu Parlamentu ČR 2024 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Sociální demokracie,Sociální demokracie,SOCDEM

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
485,1291,Hnutí Generace,Hnutí Generace,Generace
486,1292,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČMS
487,1293,Nadační občansko-politické hnutí ReMeK,Nadační obč.-pol. hnutí ReMeK,ReMeK
488,1294,Nestraníci pro jižní Moravu-www.nestranici2024.cz,Nestraníci pro jižní Moravu,Nestranici2024
489,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 460. [D] Volby do Senátu Parlamentu ČR 2024 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,4,Liberálně demokratická strana,Liberálně demokratická strana,LDS
3,5,Strana zelených,Strana zelených,Zelení
4,7,Sociální demokracie,Sociální demokracie,SOCDEM

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
485,1291,Hnutí Generace,Hnutí Generace,Generace
486,1292,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČMS
487,1293,Nadační občansko-politické hnutí ReMeK,Nadační obč.-pol. hnutí ReMeK,ReMeK
488,1294,Nestraníci pro jižní Moravu-www.nestranici2024.cz,Nestraníci pro jižní Moravu,Nestranici2024
489,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 462. [D] Volby do Senátu Parlamentu ČR 2024 - číselník volebních obvodů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   OBVOD     NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
0      1  Karlovy Vary   4102         2        A
1      2       Sokolov   4103         4        A
2      3          Cheb   4101         6        A
3      4          Most   4205         2        A
4      5      Chomutov   4202         4        A

**TAIL**

    OBVOD         NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
76     77            Vsetín   7203         4        A
77     78              Zlín   7204         6        A
78     79           Hodonín   6205         2        A
79     80              Zlín   7204         4        A
80     81  Uherské Hradiště   7202         6        A

## 462. [D] Volby do Senátu Parlamentu ČR 2024 - číselník volebních obvodů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   OBVOD     NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
0      1  Karlovy Vary   4102         2        A
1      2       Sokolov   4103         4        A
2      3          Cheb   4101         6        A
3      4          Most   4205         2        A
4      5      Chomutov   4202         4        A

**TAIL**

    OBVOD         NAZEV_OBV  OKRES  PRVNI_VO PLATNOST
76     77            Vsetín   7203         4        A
77     78              Zlín   7204         6        A
78     79           Hodonín   6205         2        A
79     80              Zlín   7204         4        A
80     81  Uherské Hradiště   7202         6        A

## 464. [D] Volby do Senátu Parlamentu ČR 2024 - číselník volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,3,Křesťanskodemokratická strana,Křesťanskodemokratická strana,Křesťanskodemokratická strana,KDS,1,003,KDS,S,NaN
3,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,LDS,S,NaN
4,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1464,1678,Koalice Piráti a MHS,Koalice Piráti a MHS,"Koalice Piráti, MHS",Piráti+MHS,2,"720,1194",NaN,K,NaN
1465,1679,"Sdružení Vize KVK, NK","Sdružení Vize KVK, NK","Sdružení Vize KVK, NK",Vize KVK+NK,2,"080,1285",NaN,D,NaN
1466,1680,Koalice SD-SN a SproK,Koalice SD-SN a SproK,"Koalice SD-SN, SproK",SD-SN+SproK,2,"143,1228",NaN,K,NaN
1467,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1468,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 464. [D] Volby do Senátu Parlamentu ČR 2024 - číselník volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,3,Křesťanskodemokratická strana,Křesťanskodemokratická strana,Křesťanskodemokratická strana,KDS,1,003,KDS,S,NaN
3,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,LDS,S,NaN
4,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1464,1678,Koalice Piráti a MHS,Koalice Piráti a MHS,"Koalice Piráti, MHS",Piráti+MHS,2,"720,1194",NaN,K,NaN
1465,1679,"Sdružení Vize KVK, NK","Sdružení Vize KVK, NK","Sdružení Vize KVK, NK",Vize KVK+NK,2,"080,1285",NaN,D,NaN
1466,1680,Koalice SD-SN a SproK,Koalice SD-SN a SproK,"Koalice SD-SN, SproK",SD-SN+SproK,2,"143,1228",NaN,K,NaN
1467,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1468,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 465. [D] Volby do zastupitelstev krajů 2016 - celkové výsledky za kraje a přehled za ČR

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 466. [D] Volby do zastupitelstev krajů 2016 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 467. [D] Volby do zastupitelstev krajů 2016 - přednostní hlasy pro jednotlivé kandidáty

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 468. [D] Volby do zastupitelstev krajů 2016 - výsledky za kraje a krajská města

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 469. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Benešov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 470. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Beroun a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 471. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Blansko a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 472. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Brno-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 473. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Brno-venkov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 474. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Bruntál a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 475. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Břeclav a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 476. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Cheb a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 477. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Chomutov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 478. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Chrudim a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 479. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Domažlice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 480. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Děčín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 481. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Frýdek-Místek a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 482. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Havlíčkův Brod a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 483. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Hodonín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 484. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Hradec Králové a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 485. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Jablonec nad Nisou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 486. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Jeseník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 487. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Jihlava a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 488. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Jindřichův Hradec a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 489. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Jičín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 490. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Karlovy Vary a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 491. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Karviná a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 492. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Kladno a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 493. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Klatovy a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 494. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Kolín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 495. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Kroměříž a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 496. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Kutná Hora a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 497. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Liberec a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 498. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Litoměřice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 499. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Louny a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 500. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Mladá Boleslav a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 501. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Most a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 502. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Mělník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 503. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Nový Jičín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 504. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Nymburk a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 505. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Náchod a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 506. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Olomouc a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 507. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Opava a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 508. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Ostrava-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 509. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Pardubice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 510. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Pelhřimov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 511. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Plzeň-jih a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 512. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Plzeň-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 513. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Plzeň-sever a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 514. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Prachatice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 515. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Praha-východ a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 516. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Praha-západ a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 517. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Prostějov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 518. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Písek a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 519. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Přerov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 520. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Příbram a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 521. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Rakovník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 522. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Rokycany a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 523. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Rychnov nad Kněžnou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 524. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Semily a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 525. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Sokolov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 526. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Strakonice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 527. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Svitavy a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 528. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Tachov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 529. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Teplice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 530. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Trutnov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 531. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Tábor a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 532. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Třebíč a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 533. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Uherské Hradiště a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 534. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Vsetín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 535. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Vyškov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 536. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Zlín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 537. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Znojmo a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 538. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Ústí nad Labem a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 539. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Ústí nad Orlicí a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 540. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Česká Lípa a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 541. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres České Budějovice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 542. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Český Krumlov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 543. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Šumperk a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 544. [D] Volby do zastupitelstev krajů 2016 - výsledky za okres Žďár nad Sázavou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 545. [D] Volby do zastupitelstev krajů 2016 - číselníky

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 546. [D] Volby do zastupitelstev krajů 2020 - celkové výsledky za kraje a přehled za ČR

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 547. [D] Volby do zastupitelstev krajů 2020 - okrsková data

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_66,HLASY_67,HLASY_68,HLASY_69,HLASY_70,KC_3,KC_4,KC_5,POSL_KAND,KC_SUM
0,1,2,0,0,7204,500011,1,6,5,1,...,0,0,0,0,0,0,0,6,0,507236
1,1,2,0,0,7204,500011,1,6,6,33,...,0,0,0,0,0,120,0,159,44,507586
2,1,2,0,0,7204,500011,1,6,7,39,...,0,0,0,0,0,173,199,418,50,508110
3,1,2,0,0,7204,500011,1,6,12,22,...,0,0,0,0,0,330,0,364,27,507979
4,1,2,0,0,7204,500011,1,6,16,24,...,0,0,0,0,0,110,0,150,44,507568

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_66,HLASY_67,HLASY_68,HLASY_69,HLASY_70,KC_3,KC_4,KC_5,POSL_KAND,KC_SUM
12723,13656,2,0,0,8104,599999,2,0,54,32,...,0,0,0,0,0,371,49,506,49,609168
12724,13656,2,0,0,8104,599999,2,0,63,24,...,0,0,0,0,0,102,55,244,55,608650
12725,13656,2,0,0,8104,599999,2,0,70,14,...,0,0,0,0,0,0,0,84,0,608275
12726,13656,2,0,0,8104,599999,2,0,79,3,...,0,0,0,0,0,9,0,91,9,608298
12727,13656,2,0,0,8104,599999,2,0,81,7,...,0,0,0,0,0,0,0,88,0,608283

## 548. [D] Volby do zastupitelstev krajů 2020 - přednostní hlasy pro jednotlivé kandidáty

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 549. [D] Volby do zastupitelstev krajů 2020 - registry

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 550. [D] Volby do zastupitelstev krajů 2020 - výsledky za kraje a krajská města

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 551. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Benešov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 552. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Beroun a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 553. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Blansko a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 554. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Brno-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 555. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Brno-venkov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 556. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Bruntál a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 557. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Břeclav a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 558. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Cheb a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 559. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Chomutov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 560. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Chrudim a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 561. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Domažlice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 562. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Děčín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 563. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Frýdek-Místek a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 564. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Havlíčkův Brod a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 565. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Hodonín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 566. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Hradec Králové a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 567. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Jablonec nad Nisou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 568. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Jeseník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 569. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Jihlava a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 570. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Jindřichův Hradec a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 571. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Jičín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 572. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Karlovy Vary a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 573. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Karviná a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 574. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Kladno a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 575. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Klatovy a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 576. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Kolín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 577. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Kroměříž a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 578. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Kutná Hora a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 579. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Liberec a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 580. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Litoměřice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 581. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Louny a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 582. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Mladá Boleslav a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 583. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Most a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 584. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Mělník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 585. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Nový Jičín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 586. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Nymburk a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 587. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Náchod a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 588. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Olomouc a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 589. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Opava a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 590. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Ostrava-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 591. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Pardubice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 592. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Pelhřimov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 593. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Plzeň-jih a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 594. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Plzeň-město a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 595. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Plzeň-sever a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 596. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Prachatice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 597. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Praha-východ a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 598. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Praha-západ a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 599. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Prostějov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 600. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Písek a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 601. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Přerov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 602. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Příbram a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 603. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Rakovník a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 604. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Rokycany a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 605. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Rychnov nad Kněžnou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 606. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Semily a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 607. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Sokolov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 608. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Strakonice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 609. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Svitavy a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 610. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Tachov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 611. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Teplice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 612. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Trutnov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 613. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Tábor a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 614. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Třebíč a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 615. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Uherské Hradiště a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 616. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Vsetín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 617. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Vyškov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 618. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Zlín a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 619. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Znojmo a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 620. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Ústí nad Labem a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 621. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Ústí nad Orlicí a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 622. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Česká Lípa a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 623. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres České Budějovice a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 624. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Český Krumlov a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 625. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Šumperk a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 626. [D] Volby do zastupitelstev krajů 2020 - výsledky za okres Žďár nad Sázavou a jeho obce

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 627. [D] Volby do zastupitelstev krajů 2020 - číselníky

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,KRZAST,MINOKRSEK1,MAXOKRSEK1,OBEC_PREZ
0,7200,7204,662,7213,500011,Želechovice nad Dřevnicí,12,1,3,500011
1,7100,7105,860,7111,500020,Petrov nad Desnou,11,1,2,500020
2,8100,8104,792,8115,500046,Libhošť,13,1,1,500046
3,7200,7203,871,7210,500062,Krhová,12,1,1,500062
4,7200,7203,871,7210,500071,Poličná,12,1,1,500071

**TAIL**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,KRZAST,MINOKRSEK1,MAXOKRSEK1,OBEC_PREZ
6326,8100,8104,792,8115,599930,Suchdol nad Odrou,13,1,2,599930
6327,8100,8104,791,8112,599948,Štramberk,13,1,4,599948
6328,8100,8104,789,8105,599956,Tichá,13,1,1,599956
6329,8100,8104,788,8101,599964,Tísek,13,1,1,599964
6330,8100,8104,789,8105,599999,Trojanovice,13,1,2,599999

## 628. [D] Volby do zastupitelstev krajů 2024 - Příloha č.1 k tiskopisu T/6 (strany, kandidáti)

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_66,HLASY_67,HLASY_68,HLASY_69,HLASY_70,KC_3,KC_4,KC_5,POSL_KAND,KC_SUM
0,1,2,0,0,7204,500011,1,6,15,3,...,0,0,0,0,0,0,0,18,0,507260
1,1,2,0,0,7204,500011,1,6,18,10,...,0,0,0,0,0,7,0,35,5,507299
2,1,2,0,0,7204,500011,1,6,21,7,...,0,0,0,0,0,58,0,86,24,507420
3,1,2,0,0,7204,500011,1,6,30,1,...,0,0,0,0,0,38,0,69,21,507383
4,1,2,0,0,7204,500011,1,6,39,98,...,0,0,0,0,0,841,237,1215,49,509703

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,KSTRANA,POC_HLASU,...,HLASY_66,HLASY_67,HLASY_68,HLASY_69,HLASY_70,KC_3,KC_4,KC_5,POSL_KAND,KC_SUM
37846,13591,2,0,0,8104,599999,2,0,70,2,...,0,0,0,0,0,0,0,72,0,608251
37847,13591,2,0,0,8104,599999,2,0,76,1,...,0,0,0,0,0,0,0,77,0,608261
37848,13591,2,0,0,8104,599999,2,0,77,26,...,0,0,0,0,0,51,0,154,36,608451
37849,13591,2,0,0,8104,599999,2,0,88,84,...,0,0,0,0,0,615,215,1002,57,610168
37850,13591,2,0,0,8104,599999,2,0,95,1,...,0,0,0,0,0,0,0,96,0,608299

## 629. [D] Volby do zastupitelstev krajů 2024 - registr kandidátních listin

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,KRZAST,KSTRANA,VSTRANA,NAZEVCELK,NAZEV_STRK,ZKRATKAK30,ZKRATKAK8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT
0,1,7,1639,"SPD, Trikolora a PRO","SPD, Trikolora a PRO","SPD, Trikolora a PRO",SPD+Trikol+PRO,3,"1114,1227,1265",0,A,NaN
1,1,14,1449,Zelení a SEN 21,Zelení a SEN 21,Zelení a SEN 21,Zelení+SEN 21,2,"005,1187",0,A,NaN
2,1,15,715,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT,Demokratická strana zelených - ZA PRÁVA ZVÍŘAT,DSZ - ZA PRÁVA ZVÍŘAT,DSZ-ZA PR.ZVÍŘ.,1,715,0,A,NaN
3,1,16,1245,PŘÍSAHA občanské hnutí,PŘÍSAHA občanské hnutí,PŘÍSAHA občanské hnutí,PŘÍSAHA,1,1245,0,A,NaN
4,1,21,720,Česká pirátská strana,Česká pirátská strana,Česká pirátská strana,Piráti,1,720,0,A,NaN

**TAIL**

,KRZAST,KSTRANA,VSTRANA,NAZEVCELK,NAZEV_STRK,ZKRATKAK30,ZKRATKAK8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT
179,13,70,7,Sociální demokracie,Sociální demokracie,Sociální demokracie,SOCDEM,1,007,0,A,NaN
180,13,76,752,Švýcarská demokracie (www.svycarska-demokracie...,Švýcarská demokracie (www.svycarska-demokracie...,Švýcarská demokracie,Švýcarská dem.,1,752,0,A,NaN
181,13,77,1642,"STAČILO!, koalice Komunistické strany Čech a M...","STAČILO!, koalice KSČM a ČSNS","STAČILO!, koalice KSČM a ČSNS",ČSNS+KSČM,2,"002,047",0,A,NaN
182,13,88,1327,SPOLU MSK,SPOLU MSK,SPOLU MSK,KDU+ODS+TOP 09,3,"001,053,721",0,A,NaN
183,13,95,1512,ČSSD A NEZÁVISLÉ OSOBNOSTI,ČSSD A NEZÁVISLÉ OSOBNOSTI,ČSSD A NEZÁVISLÉ OSOBNOSTI,ČSSD+DOMOV,2,"759,1221",0,A,NaN

## 630. [D] Volby do zastupitelstev krajů 2024 - registr kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,KRZAST,KSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,PORADIMAND,PORADINAHR
0,1,7,1,Jiří,Kobza,Mgr.,NaN,68,"poslanec, diplomat",Petrov,1114,1114,A,1807,9.56,A,1.0,NaN
1,1,7,2,Tomáš,Doležal,Ing. Mgr.,NaN,51,"ekonom, politolog, odborný mluvčí SPD pro obla...",Kamenice,1114,1114,A,1011,5.35,A,2.0,NaN
2,1,7,3,Oldřich,Černý,NaN,NaN,59,"poslanec, zastupitel města Kladno",Kladno,1114,1114,A,387,2.04,A,3.0,NaN
3,1,7,4,Jiří,Novotný,Mgr.,NaN,48,"bezpečnostní expert, zastupitel města Příbram",Příbram,1114,1114,A,466,2.46,A,4.0,NaN
4,1,7,5,Václav,Bošek,Mgr.,MBA,47,"živnostník, obchodní zástupce, zastupitel měst...",Kladno,1114,1114,A,240,1.27,N,NaN,1.0

**TAIL**

,KRZAST,KSTRANA,PORCISLO,JMENO,PRIJMENI,TITULPRED,TITULZA,VEK,POVOLANI,BYDLISTEN,PSTRANA,NSTRANA,PLATNOST,POCHLASU,POCPROC,MANDAT,PORADIMAND,PORADINAHR
8279,13,95,66,Robin,Król,NaN,DiS.,24,student VŠ,Rychvald,99,759,A,9,0.50,N,0.0,0.0
8280,13,95,67,Martina,Jarošová,NaN,NaN,31,operátor výroby,Nové Heřminovy,99,759,A,9,0.50,N,0.0,0.0
8281,13,95,68,Pavel,Jelínek,NaN,DiS.,39,OSVČ,Karviná,99,759,A,6,0.33,N,0.0,0.0
8282,13,95,69,Martin,Braš,NaN,NaN,26,elektrotechnik,Ostrava,99,759,A,6,0.33,N,0.0,0.0
8283,13,95,70,Miroslav,Demeter,NaN,NaN,57,"majitel agentury MARCO, organizátor akcí pro děti",Ostrava,759,759,A,6,0.33,N,0.0,0.0

## 631. [D] Volby do zastupitelstev krajů 2024 - složení registru kandidátních listin

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   KSTRANA TYPSLOZENI  NSTRANA
0        1          P      714
1        1          P      716
2        2          P      766
3        3          P       53
4        3          P      721

**TAIL**

     KSTRANA TYPSLOZENI  NSTRANA
189       93          P        1
190       93          P     1014
191       94          P      121
192       95          P      759
193       95          P     1221

## 632. [D] Volby do zastupitelstev krajů 2024 - složení číselníku volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5

**TAIL**

      VSTRANA  NSTRANA
2934     1679     1285
2935     1680      143
2936     1680     1228
2937     9995     9995
2938     9999     9999

## 633. [D] Volby do zastupitelstev krajů 2024 - souhrnný registr kandidátních listin (ČR)

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,KSTRANA,VSTRANA,NAZEVCELK,NAZEV_STRK,ZKRATKAK30,ZKRATKAK8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
0,1,1141,SPOLU PRO Liberecký kraj,SPOLU PRO Liberecký kraj,SPOLU PRO Liberecký kraj,Svobod+Soukrom,2,"714,716",2222202222222,A,NaN,0.0,SPOLU PRO Liberecký kraj
1,2,766,JIHOČEŠI 2012,JIHOČEŠI 2012,JIHOČEŠI 2012,JIH 12,1,766,2022222222222,A,NaN,0.0,JIHOČEŠI 2012
2,3,1637,Společně se Starosty pro občany,Společně se Starosty pro občany,Společně se Starosty p. občany,ODS+TOP 09+STO,3,"053,721,779",2222222202222,A,NaN,11.0,Společně se Starosty pro občany
3,4,1663,ČSSD – ČISTÝ KRAJ,ČSSD – ČISTÝ KRAJ,ČSSD – ČISTÝ KRAJ,ČSSD+ČiKR,2,"759,1021",2222022222222,A,NaN,0.0,ČSSD – ČISTÝ KRAJ
4,5,1669,HLAS samospráv – pro spravedlivý rozvoj Králov...,HLAS samospráv – pro spravedlivý rozvoj HK kraje,HLAS samospráv,SOCDEM+SproK+RH,3,"007,1228,1267",2222220222222,A,NaN,3.0,HLAS samospráv – pro spravedlivý rozvoj Králov...

**TAIL**

,KSTRANA,VSTRANA,NAZEVCELK,NAZEV_STRK,ZKRATKAK30,ZKRATKAK8,POCSTRVKO,SLOZENI,STAVREG,PLAT_STR,SLOZNEPLAT,POCMANDCR,NAZEVPLNY
90,91,1118,Volba pro kraj,Volba pro kraj,Volba pro kraj,VOK,1,1118,2220222222222,A,NaN,3.0,Volba pro kraj
91,92,1654,3PK - Pro prosperující Pardubický kraj,3PK - Pro prosperující Pardubický kraj,3PK-Pro prosperující Pard. kr.,SOCDEM+VČ+SproK,3,"007,770,1228",2222222022222,A,NaN,11.0,3PK - Pro prosperující Pardubický kraj
92,93,1661,PRO NÁŠ KRAJ – PRO PLZEŇ a KDU-ČSL s podporou ...,PRO NÁŠ KRAJ – PRO PLZEŇ a KDU-ČSL s podporou,"PRO NÁŠ KRAJ–PRO PLZEŇ,KDU-ČSL",KDUČSL+PROPLZEŇ,2,"001,1014",2202222222222,A,NaN,4.0,PRO NÁŠ KRAJ – PRO PLZEŇ a KDU-ČSL s podporou ...
93,94,121,"LEPŠÍ ŽIVOT PRO LIDI-min.mzda 70.000 Kč,min.dů...",LEPŠÍ ŽIVOT PRO LIDI,LEPŠÍ ŽIVOT PRO LIDI,LŽPL,1,121,202222222222,A,NaN,0.0,"LEPŠÍ ŽIVOT PRO LIDI - min. mzda 70.000 Kč, mi..."
94,95,1512,ČSSD A NEZÁVISLÉ OSOBNOSTI,ČSSD A NEZÁVISLÉ OSOBNOSTI,ČSSD A NEZÁVISLÉ OSOBNOSTI,ČSSD+DOMOV,2,"759,1221",2222222222220,A,NaN,0.0,ČSSD A NEZÁVISLÉ OSOBNOSTI

## 634. [D] Volby do zastupitelstev krajů 2024 - tiskopisy T/6 (okrsky)

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK,KC_2,ZAKRSTRANA
0,1,1,0,0,7204,500011,1,6,718,271,270,267,1526,0000000000000010010010000000010000000010000000...
1,2,1,0,0,7204,500011,2,0,415,143,143,143,844,0000000000000000010010000000010000000010000000...
2,3,1,0,0,7204,500011,3,1,407,125,125,125,782,0000000000000000010010000000101000000010000000...
3,4,1,0,0,7105,500020,1,2,272,83,83,79,517,0000000001000011000000000000000000000010000000...
4,5,1,0,0,7105,500020,2,3,742,196,196,193,1327,0000000001000011100000000000000000000010000000...

**TAIL**

,ID_OKRSKY,TYP_FORM,OPRAVA,CHYBA,OKRES,OBEC,OKRSEK,KC_1,VOL_SEZNAM,VYD_OBALKY,ODEVZ_OBAL,PL_HL_CELK,KC_2,ZAKRSTRANA
13586,13587,1,0,0,8104,599948,4,6,714,262,262,262,1500,0000001000000011000010100001000000000010000000...
13587,13588,1,0,0,8104,599956,1,1,1519,588,588,586,3281,0000001000000001000010000001000000000010000000...
13588,13589,1,0,0,8104,599964,1,6,763,271,271,271,1576,0000001000000001000010100001000000000010000000...
13589,13590,1,0,0,8104,599999,1,6,489,161,161,159,970,0000001000000011000010100001000000000010000000...
13590,13591,1,0,0,8104,599999,2,0,1620,553,553,548,3274,0000001000000011000010100001000000000010000000...

## 635. [D] Volby do zastupitelstev krajů 2024 - číselník obcí, městských částí, městských obvodů a volebních okrsků

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,KRZAST,MINOKRSEK1,MAXOKRSEK1,OBEC_PREZ
0,7200,7204,662,7213,500011,Želechovice nad Dřevnicí,12,1,3,500011
1,7100,7105,860,7111,500020,Petrov nad Desnou,11,1,2,500020
2,8100,8104,792,8115,500046,Libhošť,13,1,1,500046
3,7200,7203,871,7210,500062,Krhová,12,1,1,500062
4,7200,7203,871,7210,500071,Poličná,12,1,1,500071

**TAIL**

,KRAJ,OKRES,CPOU,ORP,OBEC,NAZEVOBCE,KRZAST,MINOKRSEK1,MAXOKRSEK1,OBEC_PREZ
6326,8100,8104,792,8115,599930,Suchdol nad Odrou,13,1,2,599930
6327,8100,8104,791,8112,599948,Štramberk,13,1,4,599948
6328,8100,8104,789,8105,599956,Tichá,13,1,1,599956
6329,8100,8104,788,8101,599964,Tísek,13,1,1,599964
6330,8100,8104,789,8105,599999,Trojanovice,13,1,2,599999

## 636. [D] Volby do zastupitelstev krajů 2024 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS CHODNOTA
0        0      CZ     Česká republika     105       CZ
1     1000    CZ01               Praha     107     CZ01
2     1100   CZ010  Hlavní město Praha     108    CZ010
3     1199  CZ0100               Praha     109   CZ0100
4     2000    CZ02       Střední Čechy     107     CZ02

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS CHODNOTA
96      8103  CZ0803        Karviná     109   CZ0803
97      8104  CZ0804     Nový Jičín     109   CZ0804
98      8105  CZ0805          Opava     109   CZ0805
99      8106  CZ0806  Ostrava-město     109   CZ0806
100     9999     NaN      Zahraničí     109   CZZZZZ

## 637. [D] Volby do zastupitelstev krajů 2024 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,9,Nezávislá iniciativa (NEI),Nezávislá iniciativa (NEI),NEI

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
268,1291,Hnutí Generace,Hnutí Generace,Generace
269,1292,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČECHY MORAVA SLEZSKO,MÁ VLAST ČMS
270,1293,Nadační občansko-politické hnutí ReMeK,Nadační obč.-pol. hnutí ReMeK,ReMeK
271,1294,Nestraníci pro jižní Moravu-www.nestranici2024.cz,Nestraníci pro jižní Moravu,Nestranici2024
272,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 638. [D] Volby do zastupitelstev krajů 2024 - číselník volebních stran

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,3,Křesťanskodemokratická strana,Křesťanskodemokratická strana,Křesťanskodemokratická strana,KDS,1,003,KDS,S,NaN
3,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,LDS,S,NaN
4,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1411,1678,Koalice Piráti a MHS,Koalice Piráti a MHS,"Koalice Piráti, MHS",Piráti+MHS,2,"720,1194",NaN,K,NaN
1412,1679,"Sdružení Vize KVK, NK","Sdružení Vize KVK, NK","Sdružení Vize KVK, NK",Vize KVK+NK,2,"080,1285",NaN,D,NaN
1413,1680,Koalice SD-SN a SproK,Koalice SD-SN a SproK,"Koalice SD-SN, SproK",SD-SN+SproK,2,"143,1228",NaN,K,NaN
1414,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1415,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 639. [D] Volby do zastupitelstev krajů 2024 - číselník zastupitelstev v krajích

                     hodnota
polozka
target_years_present    2024
has_primary_key        False
primary_key_column      None

**HEAD**

   KRZAST     NAZEVKRZ  MANDATYKRZ  KRAJ
0       1  Středočeský          65  2100
1       2    Jihočeský          55  3100
2       3     Plzeňský          55  3200
3       4  Karlovarský          45  4100
4       5      Ústecký          55  4200

**TAIL**

    KRZAST         NAZEVKRZ  MANDATYKRZ  KRAJ
8        9         Vysočina          45  6100
9       10     Jihomoravský          65  6200
10      11        Olomoucký          55  7100
11      12          Zlínský          45  7200
12      13  Moravskoslezský          65  8100

## 640. [D] Volby do zastupitelstev obcí 2022 - celkové výsledky za ČR

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 642. [D] Volby do zastupitelstev obcí 2022 - složení volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5

**TAIL**

      VSTRANA  NSTRANA
2957     1708     1708
2958     1709     1709
2959     1710     1710
2960     9995     9995
2961     9999     9999

## 642. [D] Volby do zastupitelstev obcí 2022 - složení volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   VSTRANA  NSTRANA
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5

**TAIL**

      VSTRANA  NSTRANA
2957     1708     1708
2958     1709     1709
2959     1710     1710
2960     9995     9995
2961     9999     9999

## 643. [D] Volby do zastupitelstev obcí 2022 - výsledky za obce vybraného okresu

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 644. [D] Volby do zastupitelstev obcí 2022 - výsledky za vybranou obec

                     hodnota
polozka
target_years_present    None
has_primary_key         None
primary_key_column      None

## 646. [D] Volby do zastupitelstev obcí 2022 - číselník druhu zastupitelstva obce

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   DRUHZASTUP                                         NAZDRUHZAS
0           1                                Zastupitelstvo obce
1           2                               Zastupitelstvo města
2           3                  Zastupitelstvo statutárního města
3           4                          Zastupitelstvo hl.m.Prahy
4           5  Zastupitelstvo městské části nebo městského ob...

**TAIL**

   DRUHZASTUP                                         NAZDRUHZAS
1           2                               Zastupitelstvo města
2           3                  Zastupitelstvo statutárního města
3           4                          Zastupitelstvo hl.m.Prahy
4           5  Zastupitelstvo městské části nebo městského ob...
5           6                             Zastupitelstvo městysu

## 646. [D] Volby do zastupitelstev obcí 2022 - číselník druhu zastupitelstva obce

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   DRUHZASTUP                                         NAZDRUHZAS
0           1                                Zastupitelstvo obce
1           2                               Zastupitelstvo města
2           3                  Zastupitelstvo statutárního města
3           4                          Zastupitelstvo hl.m.Prahy
4           5  Zastupitelstvo městské části nebo městského ob...

**TAIL**

   DRUHZASTUP                                         NAZDRUHZAS
1           2                               Zastupitelstvo města
2           3                  Zastupitelstvo statutárního města
3           4                          Zastupitelstvo hl.m.Prahy
4           5  Zastupitelstvo městské části nebo městského ob...
5           6                             Zastupitelstvo městysu

## 648. [D] Volby do zastupitelstev obcí 2022 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,24,Konzervativní strana,Konzervativní strana,KONS

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
214,1708,JSME,JSME,JSME
215,1709,Svěží Týniště,Svěží Týniště,ST
216,1710,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal za Lužánky,za Lužánky
217,9995,Koalice,Koalice,Koalice
218,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 648. [D] Volby do zastupitelstev obcí 2022 - číselník navrhujících stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,24,Konzervativní strana,Konzervativní strana,KONS

**TAIL**

,NSTRANA,NAZEV_STRN,ZKRATKAN30,ZKRATKAN8
214,1708,JSME,JSME,JSME
215,1709,Svěží Týniště,Svěží Týniště,ST
216,1710,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal za Lužánky,za Lužánky
217,9995,Koalice,Koalice,Koalice
218,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 650. [D] Volby do zastupitelstev obcí 2022 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS  CHODNOTA
0        0      CZ     Česká republika      97        19
1     1000    CZ01               Praha      99       213
2     1100   CZ010  Hlavní město Praha     100      3018
3     1199  CZ0100               Praha     101     40924
4     2000    CZ02       Střední Čechy      99       221

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS  CHODNOTA
96      8103  CZ0803        Karviná     101     40886
97      8104  CZ0804     Nový Jičín     101     40894
98      8105  CZ0805          Opava     101     40908
99      8106  CZ0806  Ostrava-město     101     40916
100     9999     NaN      Zahraničí     101     40002

## 650. [D] Volby do zastupitelstev obcí 2022 - číselník okresů, krajů a regionů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   NUMNUTS    NUTS           NAZEVNUTS  KODCIS  CHODNOTA
0        0      CZ     Česká republika      97        19
1     1000    CZ01               Praha      99       213
2     1100   CZ010  Hlavní město Praha     100      3018
3     1199  CZ0100               Praha     101     40924
4     2000    CZ02       Střední Čechy      99       221

**TAIL**

     NUMNUTS    NUTS      NAZEVNUTS  KODCIS  CHODNOTA
96      8103  CZ0803        Karviná     101     40886
97      8104  CZ0804     Nový Jičín     101     40894
98      8105  CZ0805          Opava     101     40908
99      8106  CZ0806  Ostrava-město     101     40916
100     9999     NaN      Zahraničí     101     40002

## 652. [D] Volby do zastupitelstev obcí 2022 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,24,Konzervativní strana,Konzervativní strana,KONS

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
238,1707,Hnutí Kruh,Hnutí Kruh,Kruh
239,1708,JSME,JSME,JSME
240,1709,Svěží Týniště,Svěží Týniště,ST
241,1710,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal za Lužánky,za Lužánky
242,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 652. [D] Volby do zastupitelstev obcí 2022 - číselník politické příslušnosti kandidátů

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL
1,2,Česká strana národně sociální,Česká strana národně sociální,ČSNS
2,5,Strana zelených,Strana zelených,Zelení
3,7,Sociální demokracie,Sociální demokracie,SOCDEM
4,24,Konzervativní strana,Konzervativní strana,KONS

**TAIL**

,PSTRANA,NAZEV_STRP,ZKRATKAP30,ZKRATKAP8
238,1707,Hnutí Kruh,Hnutí Kruh,Kruh
239,1708,JSME,JSME,JSME
240,1709,Svěží Týniště,Svěží Týniště,ST
241,1710,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal za Lužánky,za Lužánky
242,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV

## 654. [D] Volby do zastupitelstev obcí 2022 - číselník typu zastupitelstva obce

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   TYPZASTUP                                         NAZTYPUZAS
0          1  Zastupitelstvo obce,městysu,města,statutár.měs...
1          2  Zastupitelstvo městské části nebo městského ob...

**TAIL**

   TYPZASTUP                                         NAZTYPUZAS
0          1  Zastupitelstvo obce,městysu,města,statutár.měs...
1          2  Zastupitelstvo městské části nebo městského ob...

## 654. [D] Volby do zastupitelstev obcí 2022 - číselník typu zastupitelstva obce

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

   TYPZASTUP                                         NAZTYPUZAS
0          1  Zastupitelstvo obce,městysu,města,statutár.měs...
1          2  Zastupitelstvo městské části nebo městského ob...

**TAIL**

   TYPZASTUP                                         NAZTYPUZAS
0          1  Zastupitelstvo obce,městysu,města,statutár.měs...
1          2  Zastupitelstvo městské části nebo městského ob...

## 656. [D] Volby do zastupitelstev obcí 2022 - číselník volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,3,Křesťanskodemokratická strana,Křesťanskodemokratická strana,Křesťanskodemokratická strana,KDS,1,003,KDS,S,NaN
3,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,LDS,S,NaN
4,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1428,1708,JSME,JSME,JSME,JSME,1,1708,JSME,S,NaN
1429,1709,Svěží Týniště,Svěží Týniště,Svěží Týniště,ST,1,1709,ST,S,NaN
1430,1710,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal za Lužánky,za Lužánky,1,1710,za Lužánky,S,NaN
1431,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1432,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN

## 656. [D] Volby do zastupitelstev obcí 2022 - číselník volebních stran

                     hodnota
polozka
target_years_present    None
has_primary_key        False
primary_key_column      None

**HEAD**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
0,1,KDU-ČSL,KDU-ČSL,KDU-ČSL,KDU-ČSL,1,001,KDU-ČSL,S,NaN
1,2,Česká strana národně sociální,Česká strana národně sociální,Česká strana národně sociální,ČSNS,1,002,ČSNS,S,NaN
2,3,Křesťanskodemokratická strana,Křesťanskodemokratická strana,Křesťanskodemokratická strana,KDS,1,003,KDS,S,NaN
3,4,Liberálně demokratická strana,Liberálně demokratická strana,Liberálně demokratická strana,LDS,1,004,LDS,S,NaN
4,5,Strana zelených,Strana zelených,Strana zelených,Zelení,1,005,Zelení,S,NaN

**TAIL**

,VSTRANA,NAZEVCELK,NAZEV_STRV,ZKRATKAV30,ZKRATKAV8,POCSTR_SLO,SLOZENI,ZKRATKA_OF,TYPVS,PLNYNAZEV
1428,1708,JSME,JSME,JSME,JSME,1,1708,JSME,S,NaN
1429,1709,Svěží Týniště,Svěží Týniště,Svěží Týniště,ST,1,1709,ST,S,NaN
1430,1710,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal zpět za Lužánky,Zbrojovka a fotbal za Lužánky,za Lužánky,1,1710,za Lužánky,S,NaN
1431,9995,Koalice,Koalice,Koalice,Koalice,1,9995,koalice,S,NaN
1432,9999,Neregistrováno u MV,Neregistrováno u MV,Neregistrováno u MV,Neregistr. u MV,1,9999,Neregistrováno u MV,S,NaN


## Co vznikne ve výstupní složce

Ve `czso_ikz_a_to_z_output` najdeš hlavně:

- `ikz_a_to_z_manifest.csv`
- `ikz_a_to_z_manifest.xlsx`
- `selected_relevant_catalogue.csv`
- `datasets_by_category.csv`
- `datasets_by_pk_and_years.csv`
- `datasets_by_status.csv`
- `ikz_a_to_z_previews.md`
- `previews/` – samostatné `head.csv`, `tail.csv`, `meta.json`
- `_downloads/` – dočasná složka pro stažené soubory; při výchozím nastavení se po vytvoření preview průběžně čistí

Poznámka k previewům:
- pokud je detekován řádkový časový sloupec (`rok`, `datum`, `casref`, `obdobi` apod.), jsou `head` a `tail` vytvořené **už z odfiltrovaných target years**
- pokud je čas jen v hlavičkách nebo není detekce spolehlivá, preview zůstane nefiltrované a důvod je zapsaný v `meta.json` / `notes`